### ISSUE TITLE
Emotional health - input issue

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1010]
- [x] Remove the first "Provide final disposition" input
<img width="1164" alt="screen shot 2017-04-21 at 11 23 00 am" src="https://cloud.githubusercontent.com/assets/19935974/25284445/fc4fc62c-2684-11e7-9259-3e8c1174c60c.png">

- [x] Change final question text (in accordion) to "Do you have an additional instance where this matter was appealed to a higher court or administrative agency?"
<img width="1089" alt="screen shot 2017-04-21 at 11 24 38 am" src="https://cloud.githubusercontent.com/assets/19935974/25284514/33e3d74a-2685-11e7-82b2-fa629132ccae.png">

-
PDF form:
![screen shot 2017-04-21 at 11 25 28 am](https://cloud.githubusercontent.com/assets/19935974/25284521/3cee3e2a-2685-11e7-9ed8-d89750c86ff6.png)

**Comment by floresj** [comment]
Removed extra disposition field and added heading.
![selection_054](https://cloud.githubusercontent.com/assets/5938731/25490835/10b8fe38-2b3c-11e7-9ef8-a909783a4a71.png)

**Comment by Jay-Neighbours-I72** [comment]
This has come back
<img width="973" alt="screen shot 2017-05-02 at 10 51 58 am" src="https://cloud.githubusercontent.com/assets/19935974/25623698/8df226e4-2f25-11e7-8032-056d0358b00c.png">

**Comment by billy22g** [comment]
LGTM
