### ISSUE TITLE
Context around form questions about spouse or partner

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1012]
**What did you do?**
In filling out the marriage portion, for the spouse it asks "Provide current address, if different than your current address" and "Provide telephone number"

These are directly from the form, but without context it's confusing that it's asking about your spouse or partner, and not about you, since it doesn't say "Provide this person's telephone number" or something like that.
<img width="1189" alt="screen shot 2017-04-21 at 9 53 36 am" src="https://cloud.githubusercontent.com/assets/5091167/25285723/7a8c5a80-2678-11e7-999d-aabcae8811e5.png">

@Sheldon1013 @DBrenenborg @Jay-Neighbours-I72 @lauraponce @gabesnyder Thoughts on tracking things like this more explicitly when we think the form should read differently?

Also something to look out for during usability testing. Worth validating if I'm the only one who feels that way while filling it out. cc: @pjsumm

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Any ideas for text for this one?

**Comment by Jay-Neighbours-I72** [comment]
I agree 100% and think we should work in context like this throughout the form.

I think Billy's suggestion is perfect, adding "this person" or "their" works well to anchor it.

**Comment by billy22g** [comment]
Let's just make sure we track things like this Jay. This will definitely be
something I need to bring up with Donna when I'm there next month, and I
wanted to have an organized way to do that. Thanks y'all!

**Comment by bmallred** [comment]
See if sticky headings works and revisit if not.

**Comment by Jay-Neighbours-I72** [comment]
Test sticky accordion header with users and see if that solves this issue.

**Comment by pjsumm** [comment]
Waiting for usability test results before closing

**Comment by billy22g** [comment]
Where did we land here @Jay-Neighbours-I72?

**Comment by Jay-Neighbours-I72** [comment]
@billy22g 
Sticky headers have helped, user's haven't brought this up or been confused on the last few rounds of usability testing.

At the same time I still think it is worth rewording these to be more clear. IMO anytime we can speak more clearly to the users it is worth it.

If we are ok with that I can work in some of these text tweaks and track them.

**Comment by billy22g** [comment]
@lauraponce Thoughts? I agree with Jay that I think it's worth being clear in what we're asking. 

If we do decide to do that @Jay-Neighbours-I72, definitely will require tracking for each place so we can get the proper approvals.

**Comment by lauraponce** [comment]
I also agree with @Jay-Neighbours-I72, it would be great if we can clear up the ambiguity _even_ more through some text tweaks.

**Comment by Jay-Neighbours-I72** [comment]
Went through form and added context
PR #2227 #2235
Changed tracked in Proposed content update doc
