### ISSUE TITLE
Validate cohabitant entry against spouse

### ISSUE THREAD

**Issue by floresj** [truetandem/e-QIP-prototype#1014]

**Comment by floresj** [comment]
@billy22g Just to track updates for this specifically. After discussing with @Jay-Neighbours-I72 , the approach this first pass will be to compare a cohabitant entry against a current spouse after the `lastname` field is populated when a user is filling out the `Cohabitant` name.

**Comment by Jay-Neighbours-I72** [comment]
We also spoke briefly about using this same functionality in other places on the form.

Ex: Preventing someone from entering a relative in the "People who know you well" section.

**Comment by billy22g** [comment]
👏 I support that 100%

**Comment by billy22g** [comment]
My suggestion would be to get the flow right on this first one, get a go-ahead from Sheldon and Drew, and then look to reuse it elsewhere.

**Comment by floresj** [comment]
Here is a sample of a modal displaying a possible spouse match:

![selection_038](https://cloud.githubusercontent.com/assets/5938731/25340194/fddf85cc-28d2-11e7-8fd3-cef7eea1f951.png)

When the modal is presented and the person is a spouse, 
- the user can click the `Enter a different person` button to close the modal and clear the information. 
or
- Click `This is not my spouse` and nothing is cleared out.

**Comment by billy22g** [comment]
Great start, but not sure this quite nails it. They're not *necessarily* entering a different person, they're just confirming that the person they started to enter either is their spouse or is not. Maybe replace "Enter a different person" with "This is my spouse" with hint text under the button saying "clicking here will remove the entry you've started" or something along those lines. Just thinking out loud on how to make it more blatantly obvious what's happening. cc: @Jay-Neighbours-I72 @lauraponce

**Comment by Jay-Neighbours-I72** [comment]
If I understand the form correctly...

For this specific example the form wants the user to enter spouse in the first question about Marital status.

So when user enters the same spouse in the co-habitant section we would want to stop them.

We would want them to either not enter their spouse here or add another person that they live with right?

These may get a bit tricky because each location we are using this style will be specific to the shared information and what the form is looking for.

**Comment by billy22g** [comment]
Everything you said is correct, but **all** we're solving for here is that they don't enter their spouse in the cohab section if they've already entered them in the marital status section. Does my previous comment not make sense?

**Comment by Jay-Neighbours-I72** [comment]
It does, I think I read too much into it the first time.

I see what you are doing and it simplifies this scenario.

**Comment by floresj** [comment]
![selection_044](https://cloud.githubusercontent.com/assets/5938731/25394465/167a266c-29ac-11e7-95ce-024221f35bcc.png)
Modified text

**Comment by billy22g** [comment]
Thanks John!

@Jay-Neighbours-I72 @lauraponce Do you think this works, or do we need explanatory text letting them know that by clicking "This is my spouse" the entry they started will be cleared out? I'm not positive this will be clear enough as is.

**Comment by billy22g** [comment]
I'd like to hear from @lauraponce and @Jay-Neighbours-I72 if y'all think this solves it. I tend to think it should be more obvious what's going to happen when they click "This is my spouse." Now it clears out the fields, but that seems potentially abrupt and unexpected. Thoughts?
