### ISSUE TITLE
Your history > Where have you lived

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1016]
**What did you do?**

Entered my address in the 'where have you lived' block. However, I entered the address with a small error.

**What did you expect to see?**

When entering an address, if there is a validation error, and user is prompted that 'address is not found'.
As a user, I would expect to have the option to either correct my address, or use the address as entered.

**What did you see instead?**

A user is only given the option of using the address as entered. There is no option to 'correct this address'

**Additional Information**

If a user wants to correct their address, they must click 'use this address instead', then go back and edit/update their entry in the address fields, (even though it is 'green', indicating complete), then possibly go through the validation dialog again.

 - What browser and version are you using?
Chrome 56.0
 - What operating system?
macOS 10.12.4

![screen shot 2017-04-21 at 2 49 50 pm](https://cloud.githubusercontent.com/assets/26907482/25292253/52a84f62-26a3-11e7-931c-47fae6153b08.png)

**Comment by Jay-Neighbours-I72** [comment]
<img width="892" alt="screen shot 2017-04-27 at 2 39 41 pm" src="https://cloud.githubusercontent.com/assets/19935974/25498803/6024e890-2b57-11e7-8052-f079d3635d40.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72  and @gabesnyder, thanks!

## Preview

![dismiss-alt](https://cloud.githubusercontent.com/assets/697855/25500122/c770669c-2b5b-11e7-9d49-6d898b99c5f5.png)
