### ISSUE TITLE
Conditionally showing foreign born fields when born in US is selected

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1019]
**What did you do?**
On the marital section, if you select that they *were* born in the US, you are still shown the sections relating to being foreign born. It seems like those should be conditionally shown based on their answer to the question of whether they were born in the US.

<img width="1165" alt="screen shot 2017-04-21 at 1 37 56 pm" src="https://cloud.githubusercontent.com/assets/5091167/25293366/ce6ce268-2697-11e7-8c8b-061f16265250.png">

cc: @Jay-Neighbours-I72 @lauraponce @pjsumm

**Comment by bmallred** [comment]
I think that makes sense. Also, there appears to be some styling issues there as well.

**Comment by bmallred** [comment]
@floresj just toggling the display of the foreign documents. I didn't touch the styling just in case you are still working with them!

**Comment by floresj** [comment]
@bmallred  Sounds bueno! I'll update the validators to reflect the toggling.
