### ISSUE TITLE
Add use Current Address

### ISSUE THREAD

**Issue by floresj** [truetandem/e-QIP-prototype#1024]
Under the Marital/Relationships status section, there is an option to allow the user to `use my current address`. After a discussion with @Jay-Neighbours-I72 we have a few questions.

In the legacy application, the `History` information came first which would have allowed the user to specify their address before entering the `Marital` section. With the current proposed navigation, the marital section comes before the `Your History`. Therefore, if the user goes in order, we would not have any current address information at the moment they enter the Marital section. Should we change the order in which these sections are rendered?

Assuming a current address is available, should the `use my current address` option auto-populate the address field or should it just maintain some flag/designation that the current address is to be used?

cc: @billy22g @lauraponce

**Comment by Jay-Neighbours-I72** [comment]
Discussed via hangout
