### ISSUE TITLE
Country selection - allow Countries not on our list?

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1027]
When user is adding a country we see 2 ways to handle entering a Country that is not on our list:

1. Don't allow user to enter a country not on list, they would have to select from the typeahead list. This may be problematic for Countries that have changed their name.

2. Allow user to enter a Country not on the list (this would create an error style on input) then form would load an explanation box asking them to explain this Country that isn't on the list. Once explanation is written the error style on input would switch to green.

Thoughts or preferred direction? @billy22g 

<img width="647" alt="screen shot 2017-04-25 at 9 04 09 am" src="https://cloud.githubusercontent.com/assets/19935974/25389127/c0fddbba-299d-11e7-98f6-aba5105664bd.png">

**Comment by billy22g** [comment]
What data set are we using for countries? Does it include, e.g. Zaire and Czechoslovakia? If not, 1 is not an option. Is it possible to use an autocomplete library while also allowing a free text option?

In the screenshot, I don't see an "explain" box. Are you just saying one would be there?

**Comment by bmallred** [comment]
@billy22g it does not have Ziare or Czechoslovakia. It does have Czech Republic.

These values were pulled from the original schema given to us during sprint 0 I believe.

**Comment by Jay-Neighbours-I72** [comment]
@billy22g Yes, my suggestion for option 2 was to add an "explain box"

Then once user fills it out the Country input will switch to green.

**Comment by billy22g** [comment]
Yep, so unless the data set includes past countries, then I think Jay's suggestion is 👍

**Comment by bmallred** [comment]
So far this affects multiple components:

 - `BirthPlace`
 - `Address`
 - `Country`

@billy22g and @Jay-Neighbours-I72, good switching this from a **question** to a **bug/issue** now?

**Comment by billy22g** [comment]
Yep!

**Comment by bmallred** [comment]
From the decision in #1369 we need to update the help/error text to reflect.

**Comment by Jay-Neighbours-I72** [comment]
Error text has been updated in the Place of birth section. 
What is the best way to change this in all other locations?

We still need to load the add comment block after this error is shown
<img width="814" alt="screen shot 2017-08-01 at 9 29 28 am" src="https://user-images.githubusercontent.com/19935974/28827550-eed80f88-769b-11e7-9478-515789035f15.png">

**Comment by billy22g** [comment]
One last thing here. Should there be a help icon and corresponding text on these as well to indicate this construct so you don't have to be displayed an error to get to the right solution?

**Comment by Jay-Neighbours-I72** [comment]
I like this idea, checking with John and Bryan to see if help can be added to the Country label.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred Goal would be to have the help on the Country label.

Help text:
**Need help with your Country of birth?**
If you were born in a historic country indicate the country that currently governs the geographic location you are indicating. As necessary provide comments below to clarify.

^Open to tweaks on that text @billy22g

**Comment by billy22g** [comment]
We had a more plain language text in a separate issue: https://github.com/truetandem/e-QIP-prototype/issues/1666
