### ISSUE TITLE
Emotional health - need margin between accordion title and date

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1028]
**What did you expect to see?**

Psych section-- "Has a court or administrative agency ever issued an order declaring you mentally incompetent?" Accordion block has dynamic titles (institution name and date), but 

- [x] currently there is not enough spacing between the accordion title and date. 

This is appears to be a style issue across the entire section.

 - What browser and version are you using?
Chrome Version 56.0.2924.87 (64-bit)
 - What operating system?
macOS Sierra 10.12.4

![screen shot 2017-04-25 at 10 29 03 am](https://cloud.githubusercontent.com/assets/26907482/25390616/12448240-29a2-11e7-9e05-bbff99e1a0cf.png)

**Comment by floresj** [comment]
![selection_058](https://cloud.githubusercontent.com/assets/5938731/25498927/b91b05ba-2b57-11e7-968d-59db80e5cdc5.png)
