### ISSUE TITLE
Emotional health - Hospitalization - "No" scrolling issue

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1029]
- [x] Clicking No on question below scrolls user up to previous accordion:

![screen shot 2017-04-25 at 10 33 51 am](https://cloud.githubusercontent.com/assets/19935974/25390849/afd921fa-29a2-11e7-856f-fd1cb7e1352e.png)

**Comment by floresj** [comment]
I'm not able to reproduce this behavior. However, this may be due to updates to the accordion. This issue may have been resolved there.
