### ISSUE TITLE
Emotional health - review screen (and form wide)

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1030]
- [x] Load all accordions closed
- [x] Add dividing line and margins between sections

<img width="1111" alt="screen shot 2017-04-25 at 10 37 32 am" src="https://cloud.githubusercontent.com/assets/19935974/25391064/53206e54-29a3-11e7-916b-a6d5aa3a91e6.png">

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Any ballpark estimate as to how much margin you have between those?

**Comment by floresj** [comment]
Updated dividers 
![selection_048](https://cloud.githubusercontent.com/assets/5938731/25447493/69a5f9ba-2a83-11e7-90aa-5c9d0211da4d.png)

**Comment by Jay-Neighbours-I72** [comment]
That looks good to me @floresj
