### ISSUE TITLE
Emotional Health - closed accordion style and content tweaks

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1032]
- [x] Put numbers after “Order” on accordion items

- [x] Replace “description” with “Summary of orders”

![screen shot 2017-04-25 at 10 40 19 am](https://cloud.githubusercontent.com/assets/26907482/25391174/a31d134e-29a3-11e7-9a56-6d43558ea4b6.png)

**Comment by floresj** [comment]
Added descriptions and numbers to all accordions. See #1034 for screenshots.
