### ISSUE TITLE
Emotional health - Hospitalization - Need margin above headline “Agency…”

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1033]
- [x] Add margin above "Agency" headline

![screen shot 2017-04-25 at 10 42 50 am](https://cloud.githubusercontent.com/assets/19935974/25391296/f0f41680-29a3-11e7-861b-b43d109d3ca7.png)

**Comment by floresj** [comment]
Added margins to h2's. 
![selection_049](https://cloud.githubusercontent.com/assets/5938731/25450331/911fc602-2a8c-11e7-8712-815efdb7dbc9.png)
