### ISSUE TITLE
Emotional Health - Closed accordion sections title tweaks

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1034]
On all sections - use proper placeholder text:

- [x] Competence - “Provide your order details below”
- [x] Consultations - “Provide your order details below”
- [x] Hospitalization - “Provide your hospitalization details below”
- [x] Diagnoses - Provide your diagnoses details below”
- [x] Existing conditions - “Provide your condition details below”

![screen shot 2017-04-25 at 10 43 02 am](https://cloud.githubusercontent.com/assets/26907482/25391330/03f86772-29a4-11e7-8aba-27aeef1f9ae6.png)

**Comment by floresj** [comment]
Related ticket #1032

**Comment by floresj** [comment]
Updated summaries:

![selection_053](https://cloud.githubusercontent.com/assets/5938731/25488751/d8c66390-2b35-11e7-97b1-e5cfe2264bdb.png)
![selection_052](https://cloud.githubusercontent.com/assets/5938731/25488750/d8c4bc70-2b35-11e7-82fc-c9e99eee280d.png)
![selection_051](https://cloud.githubusercontent.com/assets/5938731/25488753/d8da3780-2b35-11e7-8212-217021206821.png)
![selection_050](https://cloud.githubusercontent.com/assets/5938731/25488752/d8cb347e-2b35-11e7-982b-46ab16373d86.png)
