### ISSUE TITLE
Emotional health - phone number blocks and extension character count

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1035]
- [x] Should we have more than 4 characters on extensions?
- [x] Toggling from “I Don’t know” and back validates empty inputs

![screen shot 2017-04-25 at 10 44 46 am](https://cloud.githubusercontent.com/assets/19935974/25391423/35d8de84-29a4-11e7-95e2-e57a4a30981a.png)

**Comment by floresj** [comment]
The toggling issue was resolved by #1068

**Comment by floresj** [comment]
Visibly shows 6 chars but allows for 10 to conserve space
![selection_061](https://cloud.githubusercontent.com/assets/5938731/25533270/17623fb6-2bfe-11e7-95f3-774cddc730d4.png)

Error
![selection_062](https://cloud.githubusercontent.com/assets/5938731/25533284/25d4c2c6-2bfe-11e7-84b1-ea6f158e4386.png)
