### ISSUE TITLE
Emotional health - Text button style

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1039]
- [x] Text button style - font should not be bold - parenthesis text should be smaller - 

note: This style already exists in prototype

![screen shot 2017-04-25 at 10 48 51 am](https://cloud.githubusercontent.com/assets/26907482/25391696/d3d83e68-29a4-11e7-8b04-1dfdce294535.png)

**Comment by floresj** [comment]
This issue was resolved in #1051. Removed (Provide Explanation) text and removed bold.
