### ISSUE TITLE
Emotional health - Diagnosed - text layout

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1040]
- [x] Match text layout from comp

PT:
![screen shot 2017-04-25 at 10 49 28 am](https://cloud.githubusercontent.com/assets/19935974/25391734/e39d507c-29a4-11e7-8c0e-a29b77cf1d14.png)

-
Comp:
![screen shot 2017-04-25 at 10 49 37 am](https://cloud.githubusercontent.com/assets/19935974/25391740/e829f974-29a4-11e7-97fb-9d079cae692a.png)

**Comment by floresj** [comment]
![selection_056](https://cloud.githubusercontent.com/assets/5938731/25491594/6e731f48-2b3e-11e7-9151-4c6577eec548.png)
