### ISSUE TITLE
Emotional health - Hospitalization - date error closes accordion

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1042]
- [x] Hospitalization - Bottom of accordion - triggering an error on “date section” closes the accordion item and doesn’t show the error box.

![screen shot 2017-04-25 at 10 51 00 am](https://cloud.githubusercontent.com/assets/26907482/25391820/20564262-29a5-11e7-889e-70a659a9112f.png)

**Comment by floresj** [comment]
This is under a different section (Military History). However, I tried to reproduce and wasn't able to. This may have been resolved with the latest batch of accordion updates.
