### ISSUE TITLE
Emotional health - Date range - No error for an impossible date range

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1043]
- [x] Date range - No error for an impossible date range 
(test input date range is backwards, throws no error)

![screen shot 2017-04-25 at 10 52 20 am](https://cloud.githubusercontent.com/assets/26907482/25391904/4f176018-29a5-11e7-875d-45960b5614ee.png)

**Comment by floresj** [comment]
Updated:
![selection_060](https://cloud.githubusercontent.com/assets/5938731/25532200/7db40974-2bfa-11e7-8932-0240a50efd39.png)

**Comment by billy22g** [comment]
This still isn't working quite right. There's no error message in the content portion, but the error icon pops up in the navigation.

<img width="650" alt="screen shot 2017-05-01 at 2 41 05 pm" src="https://cloud.githubusercontent.com/assets/5091167/25594052/61d52588-2e7c-11e7-94d5-7710d6fd6e7c.png">

<img width="261" alt="screen shot 2017-05-01 at 2 41 12 pm" src="https://cloud.githubusercontent.com/assets/5091167/25594061/68defc00-2e7c-11e7-9993-b42ffd30f60e.png">

In addition, the start date is in the future, and nothing indicates that either. cc: @floresj @gabesnyder

**Comment by floresj** [comment]
@billy22g Your screenshot appears to have an outdated version of the application (green checkboxes now show up for dropdowns). When did you access the site?

**Comment by bmallred** [comment]
Still needs the possibility for a minimum date to be applied (most likely the individuals birth date)

**Comment by billy22g** [comment]
@bmallred @floresj Calling this good, but other dates on the form relating to you also accept things before you were born (e.g. where you've lived and where you've worked). Thoughts on how to deal with this?

**Comment by bmallred** [comment]
@billy22g Maybe we can make another GH issue to identify those usages. Should be a rather quick application

**Comment by billy22g** [comment]
I agree. Would you mind making that issue and tagging me since you know the code base better? Thanks!

**Comment by bmallred** [comment]
Added issue #1193
