### ISSUE TITLE
Emotional health - Why we are asking - text duplicated

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1044]
"The U.S. government recognize..." paragraph appears twice.

- [x] remove duplicate paragraph

![screen shot 2017-04-25 at 1 35 53 pm](https://cloud.githubusercontent.com/assets/26907482/25399104/4ad87976-29bc-11e7-83ff-33d2f532a7da.png)

**Comment by floresj** [comment]
Updated.
![selection_046](https://cloud.githubusercontent.com/assets/5938731/25445075/53894d24-2a7b-11e7-9f83-2dd79634ac3b.png)
