### ISSUE TITLE
Your history - employment inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1048]
Looks like some of the inputs and branches at the end of Employment history are off/missing

This question is repeated (it shouldn't be):
"For this employment have any of the following happened to you in the last seven (7) years?"

Looks like reprimand branch is missing

Prototype:
<img width="1173" alt="screen shot 2017-04-25 at 2 08 25 pm" src="https://cloud.githubusercontent.com/assets/19935974/25400518/e1230e92-29c0-11e7-9329-01cde05bbb53.png">

-
PDF
![screen shot 2017-04-25 at 2 08 31 pm](https://cloud.githubusercontent.com/assets/19935974/25400524/e6c8eb3c-29c0-11e7-8018-d039abf8808e.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 reprimand branch shows up when either to start or end date of the employment is within 7 years from the current date. This appears to be working on my end.

![reprimand-branch](https://cloud.githubusercontent.com/assets/697855/25488166/5a8ee034-2b34-11e7-938a-68523d4bf8b6.png)
