### ISSUE TITLE
Comment style

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1050]
- [x] Keep consistent margin above the text when closed and open (Use the closed margin)
- [x] Keep the "Remove" text blue
- [x] Using existing blue text hover state color and add hover state

<img width="263" alt="screen shot 2017-04-25 at 2 23 30 pm" src="https://cloud.githubusercontent.com/assets/19935974/25401200/11df5d36-29c3-11e7-958f-d44485b49eb6.png">
<img width="221" alt="screen shot 2017-04-25 at 2 23 41 pm" src="https://cloud.githubusercontent.com/assets/19935974/25401203/1348a060-29c3-11e7-9b54-e7cb7ef4f0a1.png">

**Comment by bmallred** [comment]
Captured the full width of the window in these screen shots to hopefull demonstrate the left margins do not shift as well. @Jay-Neighbours-I72 and @lauraponce does the whitespace and colors look okay on these?

## Normal state

![add-text](https://cloud.githubusercontent.com/assets/697855/25487392/13646e2e-2b32-11e7-94a3-11b207c15690.png)

## Remove state

![remove-text](https://cloud.githubusercontent.com/assets/697855/25487389/0f0beb40-2b32-11e7-964b-c257e5ad6f8f.png)

## Remove + hover state

![remove-text-hover](https://cloud.githubusercontent.com/assets/697855/25487380/0b38158e-2b32-11e7-9c54-72ad555a8ceb.png)

**Comment by Jay-Neighbours-I72** [comment]
Looks good to me!
