### ISSUE TITLE
Emotional health - admission voluntary/involuntary

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1051]
Do we need (provide explanation) for voluntary and involuntary? Can’t it just pop up?

- [x] remove (Provide Explanation) from buttons

- [x] Make 'Provide explanation' field permanent (user must provide explanation no matter what)

![screen shot 2017-04-25 at 2 45 00 pm](https://cloud.githubusercontent.com/assets/26907482/25402225/135615a8-29c6-11e7-965b-da31f7960db7.png)

**Comment by floresj** [comment]
@gabesnyder @Jay-Neighbours-I72  The `(Provide Explanation)` text is part of the question in the SF-86 content guide. Just confirming if that is :+1:  to remove.

**Comment by floresj** [comment]
![selection_045](https://cloud.githubusercontent.com/assets/5938731/25444547/8b8d6608-2a79-11e7-898c-0585dd97e991.png)
Updated.

**Comment by Jay-Neighbours-I72** [comment]
It is ok to remove for now, I'll track this in the content update doc @floresj
