### ISSUE TITLE
Emotional health - diagnosis - healthcare professionals - phone box auto-checked

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1052]
Health care professional info - phone
"Both" box is auto-check.

- [x] do not set an initial check for any box

![screen shot 2017-04-25 at 2 47 55 pm](https://cloud.githubusercontent.com/assets/26907482/25402343/699d1ec0-29c6-11e7-86d2-1461d6d0f235.png)

**Comment by floresj** [comment]
@gabesnyder @Jay-Neighbours-I72 This is something that was added to be marked for all phone components. Just confirming if this is something we want unchecked for this particular section or site wide?

cc: @bmallred

**Comment by Jay-Neighbours-I72** [comment]
I like this feature, Laura did too. I think the default of "both" makes sense

You ok with keeping this as is @gabesnyder?

**Comment by floresj** [comment]
@Jay-Neighbours-I72 @gabesnyder  Any last objections to keeping this?
