### ISSUE TITLE
Font size and margin tweaks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1053]
Changes:

- [x] Title font size to 2.5rem
- [x] Title bottom margin to 2rem
- [x] H2 font size to 2.75em
- [x] Next/Previous button width to 30%
- [x] Next/Previous button top/bottom padding to 1.25rem
- [x] H3 font size to 1.8rem
- [x] H3 top margin to 1.5rem
- [x] H6 font size to 1.65rem
- [x] H6 line height to 1.65
- [x] "Address is" label on address block = remove bold, increase top padding to .6rem

Overall margin tweaks needed - may be best to walk through on a hangout after size tweaks are made

Desired look:
<img width="1564" alt="screen shot 2017-04-25 at 4 15 31 pm" src="https://cloud.githubusercontent.com/assets/19935974/25405794/7152b128-29d2-11e7-8b90-7d40ab7b20bd.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 @lauraponce 

We currently have breakpoints for a lot of these font sizes. How would you like us to handle them?

**Comment by Jay-Neighbours-I72** [comment]
Walked through via google hangout

**Comment by billy22g** [comment]
@lauraponce Would you mind taking a look at this one and moving to complete when you're 👍 ?
