### ISSUE TITLE
Emotional health - remove duplicate paragraph

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1064]
- [x] Remove duplicate paragraph

<img width="1290" alt="screen shot 2017-04-27 at 10 33 36 am" src="https://cloud.githubusercontent.com/assets/19935974/25488480/2131c1ca-2b35-11e7-9179-6dcc4f950a8e.png">

Note: I removed this from the en.js file, still showing up though.

**Comment by floresj** [comment]
@gabesnyder beat ya to it. I've already removed it as part of issue #1044
