### ISSUE TITLE
Emotional health - appealed to higher... text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1067]
- [ ] For the SECOND (and all following) instances where we ask the user if it was appealed to a higher court let's use the text from the PDF:
"Do you have an additional instance where this matter was appealed to a higher court or administrative agency?"

<img width="1027" alt="screen shot 2017-04-27 at 1 56 57 pm" src="https://cloud.githubusercontent.com/assets/19935974/25497196/c6158174-2b51-11e7-8fb2-5d0ab4ff8f6a.png">

**Comment by floresj** [comment]
This looks like it was already resolved
![selection_059](https://cloud.githubusercontent.com/assets/5938731/25504265/3db5e07a-2b6b-11e7-8b85-46b51f872af9.png)
