### ISSUE TITLE
Emotional health - diagnosis inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1082]
Note: This does NOT need to be complete before usability testing 5/3

Re-work the inputs below the initial question: 
"Identify the diagnosis or health condition"

New structure:
H3
Identify the diagnosis or health condition
-Text buttons-

- Psychotic disorder
- Schizophrenia
- Schizoaffective disorder
- Delusional disorder
- Bipolar mood disorder
- Borderline personality disorder
- Antisocial personality disorder

**Comment by billy22g** [comment]
LGTM
