### ISSUE TITLE
Sections complete size - tweak

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1084]
Let's make the sections complete a bit smaller to match the new font sizes:

- [x] .score-card: 5rem;
- [x] .score-card .score-card-text: 1.9rem;

<img width="486" alt="screen shot 2017-05-01 at 2 28 13 pm" src="https://cloud.githubusercontent.com/assets/19935974/25589461/b85688d6-2e7a-11e7-8461-4e6642425a47.png">

**Comment by floresj** [comment]
![selection_084](https://cloud.githubusercontent.com/assets/5938731/25817581/cc50b354-33f5-11e7-871c-0d13d0931b05.png)

**Comment by billy22g** [comment]
LGTM
