### ISSUE TITLE
Name block - suffix on 2 lines

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1088]
- [x] Can we reduce the width of the suffix label buttons to 7.5rem so they fit on 2 lines?

Prototype:
<img width="1085" alt="screen shot 2017-05-01 at 3 49 08 pm" src="https://cloud.githubusercontent.com/assets/19935974/25592201/e4a5c1d0-2e85-11e7-95b8-cd8ed1dc987c.png">

Desired:
<img width="1128" alt="screen shot 2017-05-01 at 3 48 39 pm" src="https://cloud.githubusercontent.com/assets/19935974/25592212/ea2f00e4-2e85-11e7-80c9-29b49f5ae8a9.png">

**Comment by bmallred** [comment]
## Preview
![suffix-in-accordion](https://cloud.githubusercontent.com/assets/697855/26014442/8e00f734-372a-11e7-9b0e-0216eab68a07.png)

Took this snapshot in an accordion to see it in a different scenario.

**Comment by lauraponce** [comment]
Looks great! Much cleaner fitting onto two lines.
