### ISSUE TITLE
Phone block - number type width

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1090]
- [x] Reduce number type buttons (.telephone .phonetype-option label) width to 8.7rem

desired
<img width="774" alt="screen shot 2017-05-01 at 3 55 10 pm" src="https://cloud.githubusercontent.com/assets/19935974/25592414/b72f2d8a-2e86-11e7-96f8-a9a4be5cf4b3.png">

**Comment by bmallred** [comment]
## Preview
![phone-number-type](https://cloud.githubusercontent.com/assets/697855/26014304/f696cff4-3729-11e7-943d-00b5d4343ba4.png)

**Comment by lauraponce** [comment]
Looks good to me!
