### ISSUE TITLE
Hair color & eye color width tweak

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1091]
- [x] Reduce width of hair and eye color blocks to 14rem (this will get us 4 buttons on 1 line)

Desired:
<img width="1153" alt="screen shot 2017-05-01 at 3 59 22 pm" src="https://cloud.githubusercontent.com/assets/19935974/25592648/8b785fc6-2e87-11e7-9cb4-61c7a78e7c7e.png">

**Comment by bmallred** [comment]
## Preview
![colors-hair-eye](https://cloud.githubusercontent.com/assets/697855/26014180/839adc66-3729-11e7-917e-65f86e389f75.png)

**Comment by lauraponce** [comment]
Looks great!
