### ISSUE TITLE
Your history - employment type - width

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1093]
- [x] Reduce width of employment activity buttons to 19rem

Desired:
<img width="1286" alt="screen shot 2017-05-01 at 4 16 24 pm" src="https://cloud.githubusercontent.com/assets/19935974/25593212/af70d230-2e89-11e7-808a-89e711718711.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 some of the text is cut-off when we reduce it down to `19rem`. We make them wrap and then adjust accordingly... does that sound alright? If you want we can look over options via hangout, too.

## Current
![current-employment-activity](https://cloud.githubusercontent.com/assets/697855/26014596/408471a6-372b-11e7-8838-0bf5f999d19a.png)


## Proposed
![after-employment-activity](https://cloud.githubusercontent.com/assets/697855/26014592/3c5c6688-372b-11e7-8b04-b6365e951dd3.png)

**Comment by bmallred** [comment]
ping: @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
How about wrap then a smaller line height and centering the ones on a single line...
<img width="894" alt="screen shot 2017-06-14 at 2 20 38 pm" src="https://user-images.githubusercontent.com/19935974/27147989-b4d44eaa-510c-11e7-8d17-d4fbf878b09a.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 we'll give it a shot!

**Comment by bmallred** [comment]
![activity-sm](https://user-images.githubusercontent.com/697855/27149001-24eb24ea-5110-11e7-9606-36e11c8f499f.png)

cc: @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
looks good!

**Comment by billy22g** [comment]
This is how it looks for me. Is that intended?

<img width="837" alt="screen shot 2017-06-18 at 10 17 16 am" src="https://user-images.githubusercontent.com/5091167/27262222-6236a3ae-540f-11e7-8149-b89b45c74264.png">

**Comment by bmallred** [comment]
@billy22g that is how it is suppose to look when 3 columns doesn't fit. @Jay-Neighbours-I72 should we look into modifying the width as well?

**Comment by Jay-Neighbours-I72** [comment]
Yeah I think so @bmallred, 3 columns is definitely preferred. 

Looks like reducing the width to 18rem instead of 19rem will do it.

**Comment by floresj** [comment]
@Jay-Neighbours-I72 @bmallred I'll reduce it.

**Comment by billy22g** [comment]
LGTM
