### ISSUE TITLE
Existing conditions - remove input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1098]
- [ ] Remove this input on existing conditions sections (it is not in the pdf):
"Was the counseling/treatment effective in managing your symptoms?"

<img width="802" alt="screen shot 2017-05-02 at 1 26 50 pm" src="https://cloud.githubusercontent.com/assets/19935974/25630534/81b4918a-2f3b-11e7-9513-81981150986a.png">

![screen shot 2017-05-02 at 1 30 37 pm](https://cloud.githubusercontent.com/assets/19935974/25630583/aed6bc6a-2f3b-11e7-926e-1cd383b66434.png)

**Comment by billy22g** [comment]
LGTM
