### ISSUE TITLE
Financial order - subsection order

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1099]
- [x] Per the PDF form put the Bankruptcy subsection first.

![screen shot 2017-05-02 at 1 43 26 pm](https://cloud.githubusercontent.com/assets/19935974/25631098/61b0110a-2f3d-11e7-959c-82bdfbd4b040.png)
![screen shot 2017-05-02 at 1 43 32 pm](https://cloud.githubusercontent.com/assets/19935974/25631101/629a2d8a-2f3d-11e7-9662-29e48c0d5b62.png)

**Comment by billy22g** [comment]
LGTM
