### ISSUE TITLE
Financial record - chapter 13 inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1101]
Bankruptcy subsection

- [ ] Reposition chapter 13 specific inputs to where they appear in the pdf:

![screen shot 2017-05-02 at 1 51 55 pm](https://cloud.githubusercontent.com/assets/19935974/25631453/84eb22a8-2f3e-11e7-9f08-3a9ea1d8113b.png)

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Everything looks like it's in the right order. The only thing I see missing is the 'Were you disharged off all debts claimed...". Is that what you were referring to?

**Comment by billy22g** [comment]
Don't think this solved it. 

1. The first chapter 13 specific question isn't the same as in the PDF.
2. The questions are not in the correct location, as in the PDF.
3. The address buttons are getting some goofy heights.

<img width="1248" alt="screen shot 2017-05-08 at 2 37 36 pm" src="https://cloud.githubusercontent.com/assets/5091167/25824318/29ffc246-33fc-11e7-9c60-e1ec42069547.png">

**Comment by bmallred** [comment]
@billy22g I'd keep this open for the moment. When merging `master` with the help icon PR #1165 I saw the same thing and corrected it.

**Comment by floresj** [comment]
@billy22g I just realized the PetitionType component had the trustee and address fields enclosed under the petition type buttons. I'll take these out so that they can be placed towards the end of the form like in the PDF.

**Comment by billy22g** [comment]
LGTM
