### ISSUE TITLE
Financial record - bankruptcy - missing input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1103]
We are missing the "Were you discharged of all debts claimed in the bankruptcy?" input

Looks like an explanation is required for both yes and no answers.

![screen shot 2017-05-02 at 1 53 12 pm](https://cloud.githubusercontent.com/assets/19935974/25631610/f1f53fe6-2f3e-11e7-9037-f93ac79e2768.png)

**Comment by billy22g** [comment]
LGTM
