### ISSUE TITLE
Financial record - gambling debt - repeat question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1104]
Add the repeat question below the accordion:

H3
Have you EVER experienced additional financial problems due to gambling?
P
If yes use the button below to add another financial problem.
-Add another financial problem button-

<img width="1488" alt="screen shot 2017-05-02 at 2 50 35 pm" src="https://cloud.githubusercontent.com/assets/19935974/25634057/4217383c-2f47-11e7-973b-45b2aa7bd30a.png">

**Comment by billy22g** [comment]
Typo fixed with #1163 

Otherwise, LGTM
