### ISSUE TITLE
Financial record - gambling section text tweaks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1105]
I'm thinking "Gambling debt" doesn't make sense for this section.

The inputs ask for "Financial problems" related to gambling. The monetary input says "Losses"

Let's try this:
- [x] Change subsection name to "Gambling"
- [x] Accordion title change "Gambling debt" with "Financial problem details"
- [x] Remove the first sentence in the accordion "Enter your gambling debt"
- [x] Change add another button text to "Add another financial problem"

**Comment by billy22g** [comment]
LGTM
