### ISSUE TITLE
Financial record - bankruptcy - repeat question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1107]
Add the repeat question below the accordion:

H3
In the last seven (7) years, have you filed any additional petitions under any chapter of the bankruptcy code?
P
If yes use the button below to add another bankruptcy petition.
-Add another bankruptcy petition button-

<img width="1488" alt="screen shot 2017-05-02 at 3 23 32 pm" src="https://cloud.githubusercontent.com/assets/19935974/25635204/54ea3ac8-2f4b-11e7-9190-96079d1e12c4.png">

**Comment by billy22g** [comment]
@floresj Should I be seeing this yet in staging?

**Comment by floresj** [comment]
@billy22g It should be showing up soon. Just merged it in a few minutes ago into master.

**Comment by billy22g** [comment]
LGTM! Thanks John!
