### ISSUE TITLE
Financial record - bankruptcy text tweak

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1108]
- [x] Change accordion item title from "Bankruptcy 1" to "Petition 1"
- [x] Change add another button text to "Add another petition"

**Comment by floresj** [comment]
![selection_081](https://cloud.githubusercontent.com/assets/5938731/25813214/af1f43f4-33e6-11e7-9968-37968a4bf248.png)

**Comment by billy22g** [comment]
LGTM
