### ISSUE TITLE
Gap styling not present

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1116]
The `Gap` styling (similar to an error message) is currently not applied.

![gap-styles-missing](https://cloud.githubusercontent.com/assets/697855/25708162/ae8fe74e-30b3-11e7-8a94-4b5466675883.png)

**Comment by bmallred** [comment]
## Preview

![gap-styles-reapplied](https://cloud.githubusercontent.com/assets/697855/25710028/01c0717c-30b9-11e7-9be7-e1d4fd537e51.png)

**Comment by billy22g** [comment]
Section: Your residence history.
What I did: Entered a residence. Clicked next and went to another section. Then I came back.

<img width="920" alt="screen shot 2017-05-05 at 12 20 11 pm" src="https://cloud.githubusercontent.com/assets/5091167/25758884/71737332-318d-11e7-975e-b9ae6877e4c7.png">

What happened:
1. The gap analysis didn't show.

2. The address that I had already entered was popped open instead of closed as I would expect.

**Comment by bmallred** [comment]
@billy22g was this on the **residence** individual view or the **review** section? The gaps only show on the **review**

**Comment by billy22g** [comment]
@bmallred Wait. I thought we're still providing gaps when they come back to each section, not just on the combined review. Is that not the case? cc: @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
My understanding was any time a user came back the gaps would show, like @billy22g said above.

We didn't want to track them immediately because it would be annoying to users, but show them once they return. On individual tracks and the final review screen.

**Comment by bmallred** [comment]
We removed this during the accordion revision (v3) due to user feedback stating they were losing track of things. The sorting of items and injection of gaps were moved to only be done on the review page.

We can definitely reintroduce this to each of the individual tracks, but we need to add all of the statement management and conditional logic of when it is appropriate to display certain pieces of information or not.

**Comment by Jay-Neighbours-I72** [comment]
@billy22g @bmallred @lauraponce Maybe we hop on a hangout and work through this?

Any times work well for you all?

**Comment by bmallred** [comment]
I'm available all day!

**Comment by lauraponce** [comment]
@Jay-Neighbours-I72 @bmallred @billy22g does tomorrow after standup work for walking through this?

**Comment by billy22g** [comment]
Works for me!

**Comment by Jay-Neighbours-I72** [comment]
Works for me too

**Comment by billy22g** [comment]
LGTM
