### ISSUE TITLE
Residence validation always returning as incomplete

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1118]
The validator for `Residence` always returns `false`

**Comment by bmallred** [comment]
Problem here was due to the way the `Accordion` handles updates to child items. It was referencing the item to update by **index**. This was fine in most use cases, however, the history section has two key differences:

 - the list items are sorted by date(s)
 - the list may have `Gap` components injected

Both of these use cases have the potential to alter the intended target index. To remedy this the use of the item's `uuid` is used instead.

**Comment by billy22g** [comment]
LGTM
