### ISSUE TITLE
ApplicantSSN server-side validation

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#112]
- [x] Social Security Number: length 9; all numeric
 - [x] Is Applicable - boolean

**Comment by floresj** [comment]
@bmallred Any preference on the structure for the ssn? Currently, the struct looks like,

```go
type SSNField struct {
   First string
   Middle string
   Last string
   Applicable bool
}
```
In the UI, it's separated into 3 blocks so I did the same. However, I was thinking of maybe just switching to

```go
type SSNField struct {
   SSN string
   Applicable bool
}
```

so that you can just send up  

```javascript
{ 
    ssn: '#########', 
    applicable: true 
}
```

rather than

```javascript
{ 
    first: '###', 
    middle: '##', 
    last: '####',
    applicable: true 
}
```

**Comment by bmallred** [comment]
I prefer the one string to rule them all approach personally. When being sent from the front end they can be concatenated and possibly strip out non-digits.

**Comment by floresj** [comment]
@bmallred Should the `SSNField` even have an applicable field? It's currently  

```go
type SSNField struct {
   SSN string
   Applicable bool
}
```

Or should I just change it to a plain string 
```go
type SSNField string
```
and we assume if it's blank then it's not applicable?

**Comment by bmallred** [comment]
Think we covered this in our talk this morning but I'd say leave it for the time being. The validation end point can ignore the `Applicable` property since if it is not applicable it probably won't need validation :)
