### ISSUE TITLE
Help text - open scroll down

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1122]
When opening help text off screen it scrolls the user down too far

Can we have it scroll the user down just enough to see the help text?

Currently is scrolls the inputs off screen....
<img width="2163" alt="screen shot 2017-05-04 at 10 35 27 am" src="https://cloud.githubusercontent.com/assets/19935974/25708803/8ee2fa06-30b5-11e7-89f1-53dd30d22756.png">
<img width="2159" alt="screen shot 2017-05-04 at 10 35 35 am" src="https://cloud.githubusercontent.com/assets/19935974/25708808/917762b6-30b5-11e7-96f5-0e9874feb9a5.png">

**Comment by billy22g** [comment]
Looks great!
