### ISSUE TITLE
Mental health - diagnosis - phone block auto tab

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1124]
- [x] Auto tab in the diagnosis section on Phone block isn't working.

<img width="826" alt="screen shot 2017-05-04 at 10 40 52 am" src="https://cloud.githubusercontent.com/assets/19935974/25709067/40bd0dac-30b6-11e7-9f7e-23f28b709317.png">

**Comment by billy22g** [comment]
LGTM
