### ISSUE TITLE
Mental health - diagnosis - in treatment inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1125]
- [ ] Name and phone number blocks are not getting green validation style

<img width="1404" alt="screen shot 2017-05-04 at 10 44 20 am" src="https://cloud.githubusercontent.com/assets/19935974/25709249/cd118ce2-30b6-11e7-911d-767f9d49fec4.png">

**Comment by billy22g** [comment]
LGTM
