### ISSUE TITLE
Review screen - last section bottom border

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1127]
Remove bottom border from last section on review screen, it is conflicting with the wider bottom grey line.

<img width="1476" alt="screen shot 2017-05-04 at 11 00 37 am" src="https://cloud.githubusercontent.com/assets/19935974/25710035/05f73690-30b9-11e7-9977-f6da5a323eb7.png">

**Comment by bmallred** [comment]
Appears to be a remnant of before existing conditions was conditional. Moving the horizontal rule within the conditional view.

**Comment by billy22g** [comment]
LGTM
