### ISSUE TITLE
Name fields - validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1128]
- [x] Section 1 name blocks are not getting green valid style

<img width="1262" alt="screen shot 2017-05-04 at 11 03 25 am" src="https://cloud.githubusercontent.com/assets/19935974/25710152/63d24534-30b9-11e7-9c39-f32c768aa136.png">

**Comment by bmallred** [comment]
Duplicate of #1125

**Comment by billy22g** [comment]
LGTM
