### ISSUE TITLE
Section 1 - POB margins

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1129]
Remove extra space between inputs

<img width="1201" alt="screen shot 2017-05-04 at 11 05 02 am" src="https://cloud.githubusercontent.com/assets/19935974/25710222/9b728be8-30b9-11e7-9373-b501a879771e.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 is this how you want it? We have gone back and forth multiple times on this and I want to make sure.

## Preview

![placeofbirth](https://cloud.githubusercontent.com/assets/697855/25717440/79ee774a-30d0-11e7-9238-32a34846f11f.png)

**Comment by Jay-Neighbours-I72** [comment]
@bmallred Yes that looks perfect

**Comment by billy22g** [comment]
LGTM
