### ISSUE TITLE
Section 1 - SSN validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1130]
SSN is not getting green valid style

<img width="1229" alt="screen shot 2017-05-04 at 11 05 52 am" src="https://cloud.githubusercontent.com/assets/19935974/25710251/b5da65f0-30b9-11e7-8dfe-cde9667f0ee5.png">

**Comment by bmallred** [comment]
Fixed with #1125

**Comment by billy22g** [comment]
LGTM
