### ISSUE TITLE
Date blocks - extra space around month

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1134]
When month is input only the number is shown but there is lots of space to the right. Maybe we keep the month name in parenthesis next to it?

<img width="595" alt="screen shot 2017-05-04 at 11 46 52 am" src="https://cloud.githubusercontent.com/assets/19935974/25712414/9c7031fc-30bf-11e7-91f6-e50ea7ebc9f1.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this is due to allowing the typeahead for the month names. Maybe aligning the month to the right would not be as much of an eye sore?

**Comment by Jay-Neighbours-I72** [comment]
Meaning keeping the name next to the number?

In this example it would read "1 (January)"

If so yeah I think that works @bmallred

**Comment by bmallred** [comment]
Moved this to [sprint 13](https://github.com/truetandem/e-QIP-prototype/milestone/14). We may have to go over this again with the suggestions mentioned by @lauraponce during the review.

**Comment by bmallred** [comment]
Should be resolved with #1206

**Comment by billy22g** [comment]
LGTM
