### ISSUE TITLE
ZIP Code - ignore trailing spaces

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1136]
- [x] ZIP Code inputs - ignore trailing spaces to avoid errors

<img width="784" alt="screen shot 2017-05-04 at 11 55 12 am" src="https://cloud.githubusercontent.com/assets/19935974/25712813/a3b5bb0c-30c0-11e7-8520-e6948a1987d3.png">

**Comment by billy22g** [comment]
LGTM
