### ISSUE TITLE
Financial record - Credit counseling question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1141]
The PDF form asks for the location of organization - City and State only

We are asking using the full address block in the prototype.

Should we use an abbreviated address block that only has City and State?
@billy22g Thoughts?

![screen shot 2017-05-04 at 3 22 02 pm](https://cloud.githubusercontent.com/assets/19935974/25721256/c296de4e-30dd-11e7-8ef6-e8f40e8d5536.png)
<img width="1056" alt="screen shot 2017-05-04 at 3 21 40 pm" src="https://cloud.githubusercontent.com/assets/19935974/25721260/c6dbd338-30dd-11e7-819a-0cde76ff268f.png">

**Comment by billy22g** [comment]
Yes, we should ask for an abbreviated, only city/state. Like place of birth.

**Comment by bmallred** [comment]
![credit-place](https://user-images.githubusercontent.com/697855/27144612-8a4f46c8-5100-11e7-9359-bcf89d4e30df.png)

cc: @Jay-Neighbours-I72 @lauraponce @billy22g

**Comment by billy22g** [comment]
@bmallred Still seeing the full address.

<img width="688" alt="screen shot 2017-06-14 at 1 07 50 pm" src="https://user-images.githubusercontent.com/5091167/27149923-83674714-5102-11e7-8423-3ee71aa1f413.png">

**Comment by floresj** [comment]
@billy22g I'm finishing up reviewing the PR where this issue lives. https://github.com/truetandem/e-QIP-prototype/pull/1426 It'll be up on staging soon.

**Comment by billy22g** [comment]
That's my bad @bmallred and @floresj. It wasn't in review/QA but I thought it was.

**Comment by billy22g** [comment]
LGTM. It's weird that they can't get credit counseling outside the US, but shruggie emoji?
