### ISSUE TITLE
Financial record - Delinquent payments - intro text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1142]
Reformat the intro text:

- [x] Make text in parenthesis paragraph text and remove ()

Current:
<img width="1309" alt="screen shot 2017-05-04 at 3 46 06 pm" src="https://cloud.githubusercontent.com/assets/19935974/25722176/270497ce-30e1-11e7-98da-df0a42db4cf0.png">

-

Desired:
<img width="1252" alt="screen shot 2017-05-04 at 3 47 10 pm" src="https://cloud.githubusercontent.com/assets/19935974/25722186/2da7b3d6-30e1-11e7-836a-9eda574edeb4.png">

**Comment by billy22g** [comment]
LGTM
