### ISSUE TITLE
Financial record - Delinquent payment

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1143]
Make (Check all that apply) text paragraph text.

Current:
<img width="2106" alt="screen shot 2017-05-04 at 4 03 50 pm" src="https://cloud.githubusercontent.com/assets/19935974/25722861/b8095906-30e3-11e7-847d-a589889afb81.png">

-

Desired:
<img width="2106" alt="screen shot 2017-05-04 at 4 06 07 pm" src="https://cloud.githubusercontent.com/assets/19935974/25722865/ba28de64-30e3-11e7-9f64-c0b4302076eb.png">

**Comment by Jay-Neighbours-I72** [comment]
Same change on Non-payment consequence:

<img width="2107" alt="screen shot 2017-05-04 at 4 13 06 pm" src="https://cloud.githubusercontent.com/assets/19935974/25723092/a0098e24-30e4-11e7-8fe6-23f1ea3484f5.png">

**Comment by billy22g** [comment]
Not getting the actual "Check all that apply" text.

<img width="1245" alt="screen shot 2017-05-08 at 2 43 02 pm" src="https://cloud.githubusercontent.com/assets/5091167/25824446/b85b2828-33fc-11e7-9308-3c8c29d2cf0a.png">

**Comment by billy22g** [comment]
LGTM
