### ISSUE TITLE
Lowercase on display, uppercase on input for addresses

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1149]
When you're typing in your address in the "Your History" section, when you start typing, it forces uppercase in the input field, but the display of the address is in lowercase. The display should mirror the input, or be Title case.

<img width="802" alt="screen shot 2017-05-05 at 11 59 44 am" src="https://cloud.githubusercontent.com/assets/5091167/25758079/5f3fc81c-318a-11e7-81c8-ebe9e8120fc4.png">

 - What browser and version are you using?
Latest Chrome
 - What operating system?
Mac OSX Yosemite

**Comment by bmallred** [comment]
Very good point. I think applying the CSS `text-transform: capitalize;` in both places is ideal

**Comment by billy22g** [comment]
Agreed 100%.

**Comment by billy22g** [comment]
LGTM
