### ISSUE TITLE
Form wide - not applicable top margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1161]
- [ ] Remove top margin on "not applicable" or text to push it up closer to input

<img width="1292" alt="screen shot 2017-05-08 at 10 56 27 am" src="https://cloud.githubusercontent.com/assets/19935974/25810118/1f9c8902-33dd-11e7-963b-414265f6bacc.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 without the `margin-top` this is how it would look in different use cases. Let us know what you think.

## With text
![or-text](https://cloud.githubusercontent.com/assets/697855/25812569/b81309f2-33e4-11e7-8a26-1089adf1d9da.png)



## With address
![or-address](https://cloud.githubusercontent.com/assets/697855/25812563/b39fdcce-33e4-11e7-9ecb-2a691b4244db.png)



## With date
![or-date](https://cloud.githubusercontent.com/assets/697855/25812558/aff69c5c-33e4-11e7-8a7f-19d061eda2a7.png)



## With name
![or-name](https://cloud.githubusercontent.com/assets/697855/25812555/abe5c264-33e4-11e7-8669-7a0e636dd478.png)

**Comment by Jay-Neighbours-I72** [comment]
Man, that estimated box ruins things.

Ideally we want a consistent space above "Or" everywhere, like in the "with name" example.

Any ideas on how to make this possible?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 besides finding a "middle ground" on the margin I would suggest something that handles the majority and then we apply tightly scoped styles to the areas that need them still.

**Comment by Jay-Neighbours-I72** [comment]
That makes sense. 

I'd say the middle ground is the change you have in your screenshots.

Then we fine tune the edge cases

**Comment by billy22g** [comment]
LGTM
