### ISSUE TITLE
Multiple country select not working properly

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1164]
**What did you do?**
On foreign contacts, countr(ies) of citizenship, I tried to add multiple countries, and it would not add more than one. Came upon this when reviewing user story #668 

To satisfy this:
1. Need to be able to add multiple countries.
2. Styling cuts off country name. Is this intentional? cc: @Jay-Neighbours-I72 

<img width="706" alt="screen shot 2017-05-08 at 10 41 42 am" src="https://cloud.githubusercontent.com/assets/5091167/25814551/27cd4280-33db-11e7-8529-4397716ebdc6.png">

**Comment by billy22g** [comment]
Hmmm...this is working now. Closing it unless it resurfaces.

**Comment by billy22g** [comment]
Only working on the second foreign contact addition, but the first one still having issues. Saudi is lowercase, I was not able to add "Equatorial Guinea" or another country after these four, but was able to when I deleted one. Definitely some issues here.

<img width="707" alt="screen shot 2017-05-08 at 10 53 18 am" src="https://cloud.githubusercontent.com/assets/5091167/25815015/b95adec8-33dc-11e7-891a-43b5444cfe83.png">

**Comment by bmallred** [comment]
Reference: https://github.com/truetandem/e-QIP-prototype/issues/1027

**Comment by Jay-Neighbours-I72** [comment]
@billy22g No that is not intentional, the country name should not be cut off.

**Comment by bmallred** [comment]
If you press enter when just "Saudi" is typed then it is entered verbatim. Selecting the option from the list places the entire country name below the input.

![blah](https://cloud.githubusercontent.com/assets/697855/25854651/bf49d574-349e-11e7-9103-410d5cd117e6.png)

**Comment by Jay-Neighbours-I72** [comment]
Ahhhh I see that, that makes sense because we have to allow inputs that are not on the list.

**Comment by billy22g** [comment]
We should test this with users next week if possible. I don't think it's clear at the moment that countries that aren't in the list are an option, and I would imagine most people this applies to will be confused.

**Comment by Jay-Neighbours-I72** [comment]
It is in the Relatives section so we can def test. @gabesnyder @lauraponce Maybe work it into the usability plan?

**Comment by bmallred** [comment]
From the decision made in #1369 I think we should handle this by

 1. Look up the first and best match and select that
 2. If no best or exact match was found do not add to the selected countries and leave in the input element

**maybe** in combination with option 2 provide some context being that a match was not found?

cc: @billy22g @Jay-Neighbours-I72 @lauraponce @floresj

**Comment by billy22g** [comment]
That all seems pretty directionally correct, not positive how the implementation will feel. @Jay-Neighbours-I72 can you work with @bmallred on this to ensure you're feeling good about how it works?

**Comment by Jay-Neighbours-I72** [comment]
In my head this works well, @bmallred loop me in whenever to walk through the implementation.

**Comment by billy22g** [comment]
LGTM
