### ISSUE TITLE
Form navigation - section number color

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1168]
- [x] Darken section number color to #6c7178 to pass WCAG AA 

<img width="510" alt="screen shot 2017-05-08 at 2 57 49 pm" src="https://cloud.githubusercontent.com/assets/19935974/25820276/b73a8c7a-33fe-11e7-83e8-0b7cfe2e8b3f.png">

**Comment by billy22g** [comment]
LGTM
