### ISSUE TITLE
Police record - type of charge inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1172]
- [x] Tighten up space between "Charge" and "Outcome" fields (so they feel more connected to the "Type of charge"

Current:
<img width="977" alt="screen shot 2017-05-08 at 3 58 19 pm" src="https://cloud.githubusercontent.com/assets/19935974/25822697/62325394-3407-11e7-95d0-2206fbb8130e.png">

-
Desired:
<img width="982" alt="screen shot 2017-05-08 at 4 00 30 pm" src="https://cloud.githubusercontent.com/assets/19935974/25822715/7a46c988-3407-11e7-9e83-eb567351e571.png">

**Comment by floresj** [comment]
Updated:
![selection_092](https://cloud.githubusercontent.com/assets/5938731/25951629/4083e466-362c-11e7-90b2-026f40697a71.png)

**Comment by lauraponce** [comment]
Looks great!
