### ISSUE TITLE
Form wide - selected color state

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1174]
- [x] Darken the selected green color of our selected style to #2b8746 (this will pass WCAG AA)

<img width="827" alt="screen shot 2017-05-08 at 4 32 27 pm" src="https://cloud.githubusercontent.com/assets/19935974/25824054/f5df2ff0-340b-11e7-81a6-e3b7ce7616ae.png">

**Comment by bmallred** [comment]
## Preview
![selected-darker](https://cloud.githubusercontent.com/assets/697855/26015076/5bf767b6-372d-11e7-8a97-81e09e30d361.png)

**Comment by lauraponce** [comment]
Looks good!
