### ISSUE TITLE
ApplicantName server-side validation

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#118]
- [x] Last name: length 100; Contains only letters, hyphens, periods, apostrophes, and spaces
 - [x] First name (Optional/Warning): length 100; Allow Initial Only
 - [x] Middle name: (Optional/Warning) length 100; Allow Initial Only
 - [x] Suffix: (Optional) length xx; Jr, Sr, I, II, III, IV, V, VI, VII, VIII, IX, X, Other

**Comment by bmallred** [comment]
Suffix with a value of **Other** should be a string with a maximum length of 100.

**Comment by floresj** [comment]
On the eqip site, the middle name field has an `Initial Only` and `No Middle Name` dropdown. However, since we're making that field optional,  I'm going to modify the middle name struct to

```golang
type MiddlenameField struct {
    Name NameField
    InitialOnly bool
}
```

I initially had a field `Type string` that would check if No Middle Name or Initial Only was selected.

**Comment by floresj** [comment]
@bmallred Ok, just posting proposed json based on what I have in structs:

```json
{
  "Firstname": {
    "Name": "",
    "InitialOnly": false
  },
  "Lastname": "",
  "Middlename": {
    "Name": "",
    "InitialOnly": false
  },
  "Suffix": {
    "Type": "",
    "Other": ""
  }
}
```

`POST`  with the following data
```json
{
  "Firstname": {
    "Name": "J*ohn",
    "InitialOnly": false
  },
  "Lastname": "",
  "Middlename": {
    "Name": "Winstonian the terrible!",
    "InitialOnly": false
  },
  "Suffix": {
    "Type": "Other",
    "Other": ""
  }
}
```

Errors Response

```json
{
  "Errors": [
    {
      "Fieldname": "Firstname",
      "Error": "contains invalid characters"
    },
    {
      "Fieldname": "Lastname",
      "Error": "field is required"
    },
    {
      "Fieldname": "Middlename",
      "Error": "contains invalid characters"
    },
    {
      "Fieldname": "Suffix",
      "Errors": [
        {
          "Fieldname": "Other",
          "Error": "Other is required when `Other` type is selected"
        }
      ]
    }
  ]
}
```
