### ISSUE TITLE
Relatives - Month error not showing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1182]
- [x] Error box for month error not showing

<img width="963" alt="screen shot 2017-05-09 at 3 09 55 pm" src="https://cloud.githubusercontent.com/assets/19935974/25868078/a5d43938-34c9-11e7-899b-4c5419319acb.png">

**Comment by bmallred** [comment]
Missing the `onValidate` method for this component.

**Comment by billy22g** [comment]
Still an issue for me in relatives section. I did cmd + shift + R to be sure I had latest. And the second validation of 54 in the day being ok seems wrong too.

<img width="419" alt="screen shot 2017-05-09 at 4 21 57 pm" src="https://cloud.githubusercontent.com/assets/5091167/25875257/b4658448-34d3-11e7-984e-e15ad82b64f3.png">

**Comment by bmallred** [comment]
The builds are not deploying to staging appropriately it appears. This is a new response so going to restart it at https://travis-ci.org/truetandem/e-QIP-prototype/builds/230523084

## Error
![travis-ci-1](https://cloud.githubusercontent.com/assets/697855/25896066/a5002a1c-3550-11e7-998a-fff0e4627d93.png)


cc: @adelevie

**Comment by bmallred** [comment]
Looks like it deployed!

**Comment by billy22g** [comment]
Values over 31 are still being accepted in the "Day" field.

**Comment by bmallred** [comment]
There is a bug which stemmed from the default handling of the `displayText()`. For example in `State` if you select **FL** it displays **FLORIDA**. This should still display **FL**

**Comment by billy22g** [comment]
LGTM
