### ISSUE TITLE
Accordion - close button

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1183]
- [x] Smaller hit box for accordion close links (current width is too wide, easy for users to accidentally click it)

<img width="1114" alt="screen shot 2017-05-09 at 3 13 28 pm" src="https://cloud.githubusercontent.com/assets/19935974/25868321/4f062fe8-34ca-11e7-9272-b4dea22743d9.png">

**Comment by lauraponce** [comment]
Looks good!
