### ISSUE TITLE
Financial record - next/previous buttons

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1185]
- [ ] Looks like re-ordering the sections didn't update the next/previous buttons

Bankruptcy, Gambling, and taxes are off
<img width="1873" alt="screen shot 2017-05-09 at 3 36 43 pm" src="https://cloud.githubusercontent.com/assets/19935974/25869160/579190be-34cd-11e7-8eda-48b7317e6984.png">
<img width="1958" alt="screen shot 2017-05-09 at 3 36 47 pm" src="https://cloud.githubusercontent.com/assets/19935974/25869161/57944232-34cd-11e7-95ec-514a4dd3fb31.png">
<img width="1951" alt="screen shot 2017-05-09 at 3 36 51 pm" src="https://cloud.githubusercontent.com/assets/19935974/25869162/57981a2e-34cd-11e7-97f2-1e116005c36d.png">

**Comment by bmallred** [comment]
This was closed in PR [1184](https://github.com/truetandem/e-QIP-prototype/pull/1184)

**Comment by billy22g** [comment]
Doesn't look like this is fixed.

<img width="1279" alt="screen shot 2017-05-09 at 4 28 03 pm" src="https://cloud.githubusercontent.com/assets/5091167/25875422/91e43102-34d4-11e7-9d0e-c2c5c6f13719.png">

**Comment by floresj** [comment]
I'll check to see what's going on with the deployment. That was also fixed with the last commit. I'm seeing it locally.

**Comment by billy22g** [comment]
Sounds good, thanks @floresj!

**Comment by bmallred** [comment]
Probably didn't deploy. Tracking it on [#1182](https://github.com/truetandem/e-QIP-prototype/issues/1182#issuecomment-300451675) as well.

**Comment by bmallred** [comment]
Looks like it deployed!

**Comment by billy22g** [comment]
LGTM
