### ISSUE TITLE
In addresses, STATE and ZIP CODE in all caps

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1188]
**What did you do?**
In all the address components, state and zip are all caps. They should be normal title case.

<img width="677" alt="screen shot 2017-05-09 at 3 36 09 pm" src="https://cloud.githubusercontent.com/assets/5091167/25873892/646db68c-34cd-11e7-9aff-6695d215e937.png">

**Comment by floresj** [comment]
This was resolved with our latest push to master https://github.com/truetandem/e-QIP-prototype/pull/1184/commits/0a25591fa8e1df75998e9d776f774d1c488b4be0. It should be up on staging soon.

**Comment by billy22g** [comment]
LGTM
