### ISSUE TITLE
Cleanup of verbiage on "Add another" buttons in Sprint 12 sections

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1194]
Many of the sections from Sprint 12 include "Add another interest" for the button text and "If yes, use the button below to add another interest" for the repeat question amplifying info.

These need to be reviewed so that they're referring to the thing that the applicant is actually adding another of.

<img width="807" alt="screen shot 2017-05-10 at 6 29 58 am" src="https://cloud.githubusercontent.com/assets/5091167/25898657/45ea4932-354a-11e7-9475-d41694c1ad32.png">

**Comment by bmallred** [comment]
I see five instances:

 - Foreign activities - Direct at [line 4873](https://github.com/truetandem/e-QIP-prototype/blob/master/src/config/locales/en.js#L4873)
 - Foreign activities - Indirect at [line 4985](https://github.com/truetandem/e-QIP-prototype/blob/master/src/config/locales/en.js#L4985)
 - Foreign activities - Real estate at [line 5111](https://github.com/truetandem/e-QIP-prototype/blob/master/src/config/locales/en.js#L5111)
 - Foreign business activities at [line 5754](https://github.com/truetandem/e-QIP-prototype/blob/master/src/config/locales/en.js#L5754)
 - Foreign business ventures at [line 5897](https://github.com/truetandem/e-QIP-prototype/blob/master/src/config/locales/en.js#L5897)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 how do the following changes sound?

## Direct

> If yes use the button below to add another direct interest.
> Add another direct interest

## Indirect

> If yes use the button below to add another indirect interest.
> Add another indirect interest

## Real estate

> If yes use the button below to add another real estate interest.
> Add another real estate interest

## Foreign business family advice/support

> If yes use the button below to add another instance of advice/support.
> Add another instance of advice/support

## Foreign business venture

> If yes use the button below to add another business venture.
> Add another business venture

**Comment by Jay-Neighbours-I72** [comment]
These look pretty good, I'd recommend changing this one so it aligns more closely with the left nav:

Real estate interest > Real estate purchase

@bmallred

**Comment by billy22g** [comment]
LGTM
