### ISSUE TITLE
Text on summaries bleed over and not accounted for in styling

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1195]
1. On summaries, the default text (and long names, etc.) bleed into the line below and mess up the spacing.

2. The default summary text is also Title Case, which reads very oddly.

Example from Foreign Business Family:
<img width="836" alt="screen shot 2017-05-10 at 6 32 58 am" src="https://cloud.githubusercontent.com/assets/5091167/25898807/c7cafcee-354a-11e7-85c0-7c9d3078314d.png">

cc: @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
Agreed on the title case, everything should be sentence case except for names, official titles, etc.

@bmallred I'm happy to talk through a solution for the multiple line issue

**Comment by bmallred** [comment]
This was modified in PR #1177 due to issue #1149. So should it be just title case for the following:

 - Address
 - Name

cc: @billy22g @Jay-Neighbours-I72 @lauraponce

**Comment by Jay-Neighbours-I72** [comment]
Name and address sounds good to me for Title case only

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 If you have not already done so, would you mind making a new issue to account for the placeholder text being truncated?

<img width="784" alt="screen shot 2017-05-30 at 8 31 03 am" src="https://cloud.githubusercontent.com/assets/5091167/26588363/5e0eb9d0-4512-11e7-9c51-4331eb0cad08.png">

Otherwise this LGTM
