### ISSUE TITLE
Storyboard Sticky navigation 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1198]
As an eApp user I want the navigation menu to stay on the left side of the screen as I scroll down the form so that I can access the menu if needed.

Note:  Multiple options/functionalities are possible to make this happen. Would need to figure out the most user friendly one. 

Acceptance Criteria
- [ ] Provide a solution to avoid users needing to scroll all the way back up to navigation.
- [ ] Review with stakeholders to approve design

**Comment by Jay-Neighbours-I72** [comment]
No comp for this.

Functionality discussed and shown to Laura/John/Bryan. Very similar to backend WordPress menu functionality:
Left nav will scroll along with content but stop scrolling when it reaches the last or first item.

Can demonstrate via google hangout for anyone interested.

**Comment by billy22g** [comment]
LGTM
