### ISSUE TITLE
Redundant “Add another” buttons

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1205]
On all accordions form wide:

- [x] Remove "If yes, use the button below to add another instance" line
- [x] Replace second "add another.." button with yes/no buttons

Clicking Yes will load a new accordion item
User will eventually need to click No to verify they have no more to add

Current:
<img width="1333" alt="screen shot 2017-05-10 at 2 53 41 pm" src="https://cloud.githubusercontent.com/assets/19935974/25915835/b6e6c034-3590-11e7-8f8c-f7c0f7f3c285.png">

**Comment by lauraponce** [comment]
It looks like the "Add another" button inside the accordion at the bottom was removed as well – was this the intent? @pjsumm @billy22g @Jay-Neighbours-I72 

![screen shot 2017-05-16 at 12 22 35 pm](https://cloud.githubusercontent.com/assets/21222704/26116788/5e08d852-3a32-11e7-88e4-33ca15d04386.png)

**Comment by billy22g** [comment]
@lauraponce Nope, that was not the intent. The "add another" inside the accordion should be preserved. cc: @pjsumm @bmallred

**Comment by lauraponce** [comment]
This looks good now!
