### ISSUE TITLE
Relatives - Mother branch - maiden name

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1209]
- [ ] Can we not display the "Maiden name?" question in the "Other names used" branch in this scenario:

Mother branch
"Provide mother's maiden name" -answer is "Same as listed"

Happy to walk through via hangout to clarify.

<img width="1144" alt="screen shot 2017-05-10 at 3 30 05 pm" src="https://cloud.githubusercontent.com/assets/19935974/25917444/122c8f50-3596-11e7-88cf-8490500315d5.png">
<img width="1131" alt="screen shot 2017-05-10 at 3 30 12 pm" src="https://cloud.githubusercontent.com/assets/19935974/25917448/130898b0-3596-11e7-8067-107570c71008.png">
<img width="1159" alt="screen shot 2017-05-10 at 3 30 18 pm" src="https://cloud.githubusercontent.com/assets/19935974/25917449/13f7e758-3596-11e7-832c-e9ae6e4d0290.png">

**Comment by billy22g** [comment]
LGTM
