### ISSUE TITLE
Relatives - relative type selection

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1210]
- [x] Allow for only single selection under relative type

This was a misunderstanding in the form, the (Multiple entries allowed) text refers to an entry per relative.

<img width="1153" alt="screen shot 2017-05-10 at 3 34 49 pm" src="https://cloud.githubusercontent.com/assets/19935974/25917525/606c471e-3596-11e7-99f8-2c5b2ee4d6f0.png">
![screen shot 2017-05-10 at 3 36 05 pm](https://cloud.githubusercontent.com/assets/19935974/25917530/64f7c222-3596-11e7-89b5-9b53d60a3132.png)

**Comment by lauraponce** [comment]
Looks good!
