### ISSUE TITLE
Police record - Sentenced branch

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1211]
- [x] In the sentenced branch - remove stray "or add date range" text

<img width="1167" alt="screen shot 2017-05-10 at 3 55 57 pm" src="https://cloud.githubusercontent.com/assets/19935974/25918407/4be751be-3599-11e7-910a-984979eb5543.png">

**Comment by floresj** [comment]
Updated:
![selection_093](https://cloud.githubusercontent.com/assets/5938731/25952027/7d6eeab4-362d-11e7-9add-151fd11e6c1a.png)

**Comment by lauraponce** [comment]
Looks good!
