### ISSUE TITLE
Police record - restructure section

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1212]
Would like to restructure this section and break it into 3 subsections (to avoid the extra long section and match c

Desired:

1. Police record
- Offenses
- Additional offenses
- Domestic violence

Content for Police record:
<img width="1108" alt="screen shot 2017-05-10 at 4 10 09 pm" src="https://cloud.githubusercontent.com/assets/19935974/25918955/26d38198-359b-11e7-85d0-7edfa7919b8d.png">

-

Content for Offenses:
<img width="1038" alt="screen shot 2017-05-10 at 4 10 52 pm" src="https://cloud.githubusercontent.com/assets/19935974/25918988/41fb3fe2-359b-11e7-9b96-5df28140ca31.png">

-

Content for Additional offenses:
<img width="1063" alt="screen shot 2017-05-10 at 4 11 12 pm" src="https://cloud.githubusercontent.com/assets/19935974/25918999/4d2a5042-359b-11e7-9bd9-492e169a9a35.png">

-

Content for Domestic violence:
<img width="768" alt="screen shot 2017-05-10 at 4 11 23 pm" src="https://cloud.githubusercontent.com/assets/19935974/25919005/53ec20ae-359b-11e7-992f-481b4125fbd1.png">

This question would become an H2

**Comment by floresj** [comment]
Intro
![selection_095](https://cloud.githubusercontent.com/assets/5938731/26006546/d54fa36c-370a-11e7-8863-ad923368b975.png)
Offenses
![selection_096](https://cloud.githubusercontent.com/assets/5938731/26006571/f21a0dca-370a-11e7-9334-b5a18ba1f838.png)
Other Offenses
![selection_097](https://cloud.githubusercontent.com/assets/5938731/26006581/f606205e-370a-11e7-88d7-90888f322979.png)
Domestic violence
![selection_098](https://cloud.githubusercontent.com/assets/5938731/26006587/f8e6911e-370a-11e7-97db-fd52d117f005.png)

**Comment by billy22g** [comment]
LGTM.

Though @Jay-Neighbours-I72, I still think the "Other than those offenses already listed" part isn't quite clear enough for folks.
