### ISSUE TITLE
Relatives - Other name used branch - maiden name input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1214]
Change the H4 for "Maiden name?" yes/no to "Was this their maiden name"

<img width="1053" alt="screen shot 2017-05-10 at 4 31 03 pm" src="https://cloud.githubusercontent.com/assets/19935974/25919946/43a0e948-359e-11e7-9f80-b03efec7b6d0.png">
 - 
to 
-
<img width="1006" alt="screen shot 2017-05-10 at 4 32 24 pm" src="https://cloud.githubusercontent.com/assets/19935974/25919957/4a0e5f04-359e-11e7-82ad-08269a5b026a.png">

**Comment by bmallred** [comment]
## Content guide

![other-names-used](https://cloud.githubusercontent.com/assets/697855/26002598/27e52050-36fe-11e7-8534-0636c1cc767c.png)

@Jay-Neighbours-I72 have we captured the change in the spreadsheet?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred No, talked this one through with Laura and we decided this didn't need to be tracked based on her and Billy's conversation with Donna a few weeks back about what needs to be tracked.

All good to go!

**Comment by lauraponce** [comment]
@bmallred @Jay-Neighbours-I72 would it be possible only ask the maiden name question if the relative is female or gender-neutral (e.g. mother, stepmother, foster parent, child, stepchild, sister, step-sister, half sister, mother-in-law, guardian) - this might avoid some confusing about people entering this info for their father, brother, etc. Thoughts on this?

**Comment by bmallred** [comment]
@lauraponce definitely possible to do that! Would like to see how others feel since it does deviate from the form a bit.

**Comment by Jay-Neighbours-I72** [comment]
Agree with Laura, that would be nice.

@lauraponce @billy22g These seems like something Donna would be ok with to me. Thoughts?

**Comment by billy22g** [comment]
Hmmm...I have heard of men changing their name to take their spouse's name. Is this making too big an assumption? Obviously your suggested approach would make it work in 99%+ of cases, but not sure if we should assume that universally.

**Comment by Jay-Neighbours-I72** [comment]
That is a good point that I hadn't considered.

**Comment by lauraponce** [comment]
Good point, and agreed - it's probably too big of an assumption since it isn't the case 100.0% of the time and it needs to be captured on the form.

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Would you mind tracking this? @lauraponce I must be misremembering, but I don't think this is something where Donna just gave us the 👍 to change without tracking, since it's actual form language. Do you?

Otherwise, this LGTM.
