### ISSUE TITLE
Placeholder text color

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1215]
- [x] Change placeholder color text to #5c5c5c to conform to WGAC AA

**Comment by floresj** [comment]
![selection_090](https://cloud.githubusercontent.com/assets/5938731/25949027/120f50e6-3624-11e7-9673-e891a119562c.png)
![selection_089](https://cloud.githubusercontent.com/assets/5938731/25949026/120e1bfe-3624-11e7-989a-8f8a6344c178.png)
![selection_088](https://cloud.githubusercontent.com/assets/5938731/25949025/120e0aec-3624-11e7-9561-828e6acc0af0.png)

**Comment by lauraponce** [comment]
Looks good to me!
