### ISSUE TITLE
Name block specific wording question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1221]
Since we are using the name block in multiple places throughout the form the personal wording in the help text doesn't always make sense.

This example is in the relatives section - asking about the mother's name
<img width="991" alt="screen shot 2017-05-12 at 9 51 36 am" src="https://cloud.githubusercontent.com/assets/19935974/26000927/a73a0f24-36f8-11e7-96ff-67e03243a0e7.png">

Thoughts of whether we should use different/specific name blocks

or

Be less specific in the help text

@lauraponce @billy22g

**Comment by bmallred** [comment]
The `Name` component takes a property called `prefix` which can also be used to drive it to different usages.

By default it does something like

```
name.label.first
name.placeholder.first
```

but, if we pass in a prefix of `section.subsection.name` it would be

```
section.subsection.name.label.first
section.subsection.name.placeholder.first
```

**Comment by Jay-Neighbours-I72** [comment]
Got it.

My preference would be to have specific help text for each one. I'm also thinking only the first 1 or 2 name fields need help. Users will have learned it by then.

Thoughts @billy22g @lauraponce

**Comment by Jay-Neighbours-I72** [comment]
For now I'm going to make these less specific and we can revisit later.

**Comment by lauraponce** [comment]
@Jay-Neighbours-I72 for being more specific, is it just a matter of replacing "your" with "your relative's"? That seems simple enough, and I agree – it would be helpful for people to know whose name they are entering again. (Sorry I missed this thread from a couple weeks ago!)

**Comment by billy22g** [comment]
Agree with Laura here, and also agree that evaluating the tradeoff of gain vs. burden to add/maintain is important.

**Comment by Jay-Neighbours-I72** [comment]
I like the idea of having them each specific like Laura mentioned.

Billy's point is a good one, I don't have an exact number but i'd guess it would be 10-20x more work that way because there are so many name inputs throughout the form. I do think it is worth it though.

For now I switched it from "Your" to "This" name specifically for testing Thursday.

**Comment by Jay-Neighbours-I72** [comment]
Next step:
Wider buckets:
Your name..
Your relative's name..
This name..

**Comment by Jay-Neighbours-I72** [comment]
@bmallred or @floresj can one of you create those^ buckets for the name fields?

**Comment by Jay-Neighbours-I72** [comment]
Flexibility to be more specific in the help text is there.

@billy22g @lauraponce 
I'm thinking the headline context tweaks will solve a lot of this issue of being more specific better than the help text tweaks.

How do we feel about running with those headline tweaks first?

**Comment by Jay-Neighbours-I72** [comment]
Headlines throughout form given more context #1012.
