### ISSUE TITLE
Relatives - US Citizenship Documentation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1223]
- [x] Remove the "Since you answered yes.." and arrow above this section (There isn't a yes/no that loads this branch)

- [x] Let's make "U.S. Citizenship Documentation" a H2 and all of it's following headlines H3s (This will allow it to register as a new subsection)

<img width="1107" alt="screen shot 2017-05-12 at 10 34 26 am" src="https://cloud.githubusercontent.com/assets/19935974/26002867/f6866bc6-36fe-11e7-8077-33047df324a1.png">

**Comment by billy22g** [comment]
LGTM
