### ISSUE TITLE
Relatives - Citizenship branch

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1224]
- [x] Looks like we are missing the Expiration date input from the Citizenship: US Address branch

<img width="1066" alt="screen shot 2017-05-12 at 11 06 16 am" src="https://cloud.githubusercontent.com/assets/19935974/26004272/3a6b236e-3703-11e7-9959-37259f35a0bc.png">

-

![screen shot 2017-05-12 at 11 05 57 am](https://cloud.githubusercontent.com/assets/19935974/26004295/4831dc7c-3703-11e7-99b8-97d0c8fbce62.png)

**Comment by billy22g** [comment]
LGTM
