### ISSUE TITLE
Relatives - affiliation with foreign govt buttons   

### ISSUE THREAD

**Issue by lauraponce** [truetandem/e-QIP-prototype#1238]
- [ ] Tighten up the space between the Yes/No button and the "I don't know" button so they feel like part of the same question

![screen shot 2017-05-16 at 12 08 03 pm](https://cloud.githubusercontent.com/assets/21222704/26116349/d785932a-3a30-11e7-8256-95425d83a25a.png)

**Comment by bmallred** [comment]
Related to #1161

**Comment by bmallred** [comment]
This should be resolved w/ PR #1286 

## Preview
![tighten-it-up](https://cloud.githubusercontent.com/assets/697855/26367416/8240d79e-3fbc-11e7-89c4-9dc7f1258d94.png)

**Comment by billy22g** [comment]
LGTM
