### ISSUE TITLE
Relatives - Current address input - stray link?

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1246]
When clicking in the space between "City" and "State" the form scrolls back up to the birth place input

<img width="1050" alt="screen shot 2017-05-18 at 9 46 17 am" src="https://cloud.githubusercontent.com/assets/19935974/26205223/1c998366-3baf-11e7-9aed-ba9a15a13c21.png">

**Comment by floresj** [comment]
This is a weird one. When I click on the State label for the full address, it puts the cursor on the state field for the relatives birthplace a few fields back. Same thing happens when the city label is clicked.

**Comment by floresj** [comment]
@bmallred Looks like city and state fields for birthplace and full address each have the same `id="city"` and `id="state"`. Wondering if we should do away with setting id of a component in generic to the value within `this.props.name` and instead use this.props.id when explicitly defined. Maybe even do away with using id's altogether.

**Comment by billy22g** [comment]
LGTM
