### ISSUE TITLE
Error needed for Initial only names

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1247]
On First, Middle, Last name inputs we need an error when user only inputs one character but doesn't check "Initial only"

Error text:
Title:
Looks like there is a problem with (name)

Message:
You only entered one letter, if your name is only one letter check the "Initial only" checkbox

<img width="993" alt="screen shot 2017-05-18 at 9 53 44 am" src="https://cloud.githubusercontent.com/assets/19935974/26206089/ce32435e-3bb1-11e7-9c3e-e129e2715e00.png">

**Comment by bmallred** [comment]
We had this originally but then conversation lead to individuals with names that actually are only one character. What do you think?

cc: @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
For people with a name that is actually one letter they will just need to check the "initial only" checkbox

So this error is only trigged if there is a single character and Initial only is NOT checked

that make sense? @bmallred

**Comment by bmallred** [comment]
Not really b/c someone with the middle name "Q" would receive an error because they didn't check the "initial only" box.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred chatted about this quickly.

@billy22g @pjsumm do you guys have time to talk this through after a stand up Monday or Tuesday.

**Comment by billy22g** [comment]
Tuesday could work. Monday I'm on a plane, so I won't be at standup.

**Comment by billy22g** [comment]
Sorry we didn't regroup on this, happy to chat about it tomorrow. I think (but not positive) I agree with what Jay is saying here. If a person proceeds after entering one letter and does not check "Initial only" we should show them an error that asks them to either enter their full name, or if it's just an initial, select "Initial only" or something like that. Did you arrive at a solution?

**Comment by pjsumm** [comment]
I went to school with someone who's first name was a letter, and it was not an initial.  As @bmallred said, and this was my recollection as well, the last time we talked about this with stakeholders they affirmed single letter names do occur on the form so we should not presume a single letter without "initial only" checked is an error condition.

**Comment by billy22g** [comment]
Great, thanks for that clarification!

**Comment by Jay-Neighbours-I72** [comment]
Looks like part of this has been implemented but the error message isn't showing.

Foreign national support section:
<img width="965" alt="screen shot 2017-06-09 at 2 02 44 pm" src="https://user-images.githubusercontent.com/19935974/26988316-df4fc630-4d1c-11e7-9ed8-58bd90e64eac.png">

**Comment by billy22g** [comment]
LGTM
