### ISSUE TITLE
Date block - 0 not showing in day input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1248]
- [x] On date blocks - 0s typed in day inputs are now showing - (first 0 only) - this makes the number not auto tab

<img width="696" alt="screen shot 2017-05-18 at 10 57 30 am" src="https://cloud.githubusercontent.com/assets/19935974/26208854/20141146-3bb9-11e7-8171-6c76a4fbbbb5.png">

**Comment by bmallred** [comment]
We were told to trim leading zeros. We can do away with that if we don't need it anymore.

**Comment by billy22g** [comment]
This looks like it works both ways now (trailing 0 and no trailing 0 for single digit numbers), which seems good to me. cc: @Jay-Neighbours-I72
