### ISSUE TITLE
Citizenship documentation - tighten up

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1250]
There was confusion around this question during testing, people thought a choice in each block was needed.

Tightening up the inputs will make it feel like one question.

- [ ] Remove bottom margins under the options and p labels.

Prototype:
<img width="1071" alt="screen shot 2017-05-18 at 11 11 07 am" src="https://cloud.githubusercontent.com/assets/19935974/26209654/653d5244-3bbb-11e7-8dac-0e25210c1568.png">

Desired:
<img width="791" alt="screen shot 2017-05-18 at 11 14 10 am" src="https://cloud.githubusercontent.com/assets/19935974/26209676/771c641e-3bbb-11e7-93df-75e18b053cd6.png">

**Comment by bmallred** [comment]
Can be done in tandem with #1278

**Comment by floresj** [comment]
Updated:
![selection_114](https://cloud.githubusercontent.com/assets/5938731/26360242/9f29af8c-3fa5-11e7-92d6-cd5687bd702e.png)

**Comment by Jay-Neighbours-I72** [comment]
Let's make the top 2 buttons (FS 240.... DS 1350) the same width as the other buttons below. This will help them all feel like part of the same family. @floresj

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Sounds good sir!

**Comment by billy22g** [comment]
LGTM
