### ISSUE TITLE
Relatives - US Citizenship branch - remove input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1251]
- [x] Remove the expiration date input - it is not in the PDF form

<img width="1095" alt="screen shot 2017-05-18 at 11 20 13 am" src="https://cloud.githubusercontent.com/assets/19935974/26209954/376354ee-3bbc-11e7-847d-9222d1d44760.png">

![screen shot 2017-05-18 at 11 20 17 am](https://cloud.githubusercontent.com/assets/19935974/26209993/556deabc-3bbc-11e7-81e9-ced249a8e6ef.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this was added per #1224. Still good to remove?

**Comment by Jay-Neighbours-I72** [comment]
Yea, sorry. It looks like I told you to add it to the wrong branch in #1224

**Comment by bmallred** [comment]
Not a problem :smile:

**Comment by billy22g** [comment]
LGTM
