### ISSUE TITLE
Relatives - Does not have US citizenship branch - date error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1252]
Expiration date shouldn't have the future error message - a lot of these will be future dates

<img width="970" alt="screen shot 2017-05-18 at 11 27 16 am" src="https://cloud.githubusercontent.com/assets/19935974/26210277/19cd09a6-3bbd-11e7-8e86-6e1fb3db4523.png">

**Comment by floresj** [comment]
Removed future date check.
![selection_115](https://cloud.githubusercontent.com/assets/5938731/26361574/6e97280a-3fa9-11e7-9751-56a3fef02188.png)

**Comment by billy22g** [comment]
LGTM
