### ISSUE TITLE
Police record - List item

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1254]
The last item on the repeat question (Are you currently on trial or awaiting a trial on criminal charges?) should also be a list item.

<img width="1005" alt="screen shot 2017-05-18 at 1 31 12 pm" src="https://cloud.githubusercontent.com/assets/19935974/26215468/6e646e58-3bce-11e7-93fa-bba97cff48cf.png">

**Comment by floresj** [comment]
![selection_112](https://cloud.githubusercontent.com/assets/5938731/26327809/b615dd20-3f0e-11e7-82ee-c6225c8bcae1.png)
