### ISSUE TITLE
Relatives - backspacing the country name hides the city and country field

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1255]
- [ ] Backspacing country name causes city and country field to disappear 
<img width="856" alt="screen shot 2017-05-18 at 2 01 23 pm" src="https://cloud.githubusercontent.com/assets/19935974/26216626/c1faddfa-3bd2-11e7-8e1c-571dfaf712cb.png">
<img width="848" alt="screen shot 2017-05-18 at 2 03 11 pm" src="https://cloud.githubusercontent.com/assets/19935974/26216627/c348f2dc-3bd2-11e7-86ea-36449d9a754d.png">

**Comment by floresj** [comment]
This is happening with the birthplace component in general. Will handle this in a separate PR.

**Comment by billy22g** [comment]
LGTM
