### ISSUE TITLE
Accordion - review screen - all accordion items

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1256]
- [ ] On review screen - all accordion items should load closed (Currently they are all open)

**Comment by billy22g** [comment]
Was this intended to apply also to the subsections? When I come back to "Where have you lived" for example with multiple entries, they're still loading open, and they should also be closed.

**Comment by floresj** [comment]
@billy22g This issue specifically addresses accordions on review screens. The case you're addressing will be covered in a separate issue.

**Comment by billy22g** [comment]
Great, LGTM then.
