### ISSUE TITLE
Police record - sentence branch

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1258]
- [x] Sentence branch is missing "Since you answered yes..." text and arrow when user answers yes.

<img width="997" alt="screen shot 2017-05-18 at 4 22 21 pm" src="https://cloud.githubusercontent.com/assets/19935974/26221995/61307b06-3be6-11e7-80ce-f379f7ebe2d1.png">
<img width="878" alt="screen shot 2017-05-18 at 4 22 25 pm" src="https://cloud.githubusercontent.com/assets/19935974/26222000/63226654-3be6-11e7-9929-bb5cd8de7446.png">

**Comment by floresj** [comment]
Offenses
![selection_110](https://cloud.githubusercontent.com/assets/5938731/26314467/0fe4fd1e-3edc-11e7-8dc1-82aae4020910.png)

Other offenses
![selection_111](https://cloud.githubusercontent.com/assets/5938731/26314477/148c9282-3edc-11e7-90da-dfa72ffaa3ae.png)
