### ISSUE TITLE
Financial record - credit counseling - address block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1259]
- [ ] Use abbreviated address block instead of full block
- [ ] Use city and state inputs only

![screen shot 2017-05-19 at 10 49 26 am](https://cloud.githubusercontent.com/assets/19935974/26253279/cf3327b2-3c80-11e7-8da4-77a4ea156545.png)

![screen shot 2017-05-19 at 10 49 26 am](https://cloud.githubusercontent.com/assets/19935974/26253286/d78d86d2-3c80-11e7-9c75-e990f243255a.png)

**Comment by bmallred** [comment]
Duplicate of #1141

**Comment by billy22g** [comment]
LGTM
