### ISSUE TITLE
Subquestion text incorrect for foreign business advice

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1273]
**What did you do?**
Here: https://eqip-prototype-staging.fr.cloud.gov/#/form/foreign/business/advice

The sub-title question is not correct:
<img width="663" alt="screen shot 2017-05-22 at 11 37 53 am" src="https://cloud.githubusercontent.com/assets/5091167/26321355/bd20720e-3ee3-11e7-8d45-85d98012b2fb.png">

It should be "Answer "No" if all your advice or support was authorized pursuant to official U.S. Government business."

**Comment by floresj** [comment]
@billy22g This was moved into the help block
![selection_116](https://cloud.githubusercontent.com/assets/5938731/26362553/4d50c25c-3fac-11e7-9efe-0b3bfcb01d17.png)

Is this not desirable? 
cc @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
Partially desirable.

Looks like we need to remove the "Provide a description of advice/support provided" line (paragraph text)

Then the help text should read:
(Title)Need help with this question?
(Message)Answer “No” if all your advice or support was authorized pursuant to official U.S. Government business.

@floresj @billy22g

**Comment by billy22g** [comment]
What Jay said, although I wonder if that shouldn't be outside of help in the same way it is below when it's asked again. Seems pretty pertinent.

**Comment by floresj** [comment]
@billy22g @Jay-Neighbours-I72 Sounds good. Here's how it looks with the help collapsed and expanded:

Collapsed:
![selection_117](https://cloud.githubusercontent.com/assets/5938731/26414674/e3be35cc-407d-11e7-9db1-58d3d49d0c7d.png)

Expanded:
![selection_118](https://cloud.githubusercontent.com/assets/5938731/26414687/ef0e7bc6-407d-11e7-8ed4-39c79b9234bf.png)

**Comment by floresj** [comment]
Updated with the following:
![selection_119](https://cloud.githubusercontent.com/assets/5938731/26415489/ab6efc94-4080-11e7-859b-40521ab1325b.png)

**Comment by Jay-Neighbours-I72** [comment]
I'd recommend removing the help text completely so we are not repeating the same message.

**Comment by billy22g** [comment]
Agree.

**Comment by billy22g** [comment]
LGTM
