### ISSUE TITLE
Last item should be bulleted

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1276]
Here: https://eqip-prototype-staging.fr.cloud.gov/#/form/legal/police/offenses

The last item should also be bulleted: "Are you currently on trial or awaiting a trial on criminal charges?"

<img width="674" alt="screen shot 2017-05-22 at 11 54 23 am" src="https://cloud.githubusercontent.com/assets/5091167/26322027/7b02f8c6-3ee6-11e7-928d-9d0b45a234dc.png">

**Comment by floresj** [comment]
Related to #1254.
