### ISSUE TITLE
Relatives - US Citizenship documentation - other input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1278]
- [x] The other input is opening the comment box instead of loading and explanation field:

<img width="666" alt="screen shot 2017-05-22 at 2 33 43 pm" src="https://cloud.githubusercontent.com/assets/19935974/26323166/cd6100bc-3efb-11e7-8a16-442f8b8cf9a9.png">
<img width="753" alt="screen shot 2017-05-22 at 2 33 49 pm" src="https://cloud.githubusercontent.com/assets/19935974/26323168/ce597436-3efb-11e7-9724-85dbcf9d1310.png">

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Should I add a label to the `Other` explanation? This is what it looks like when both the other textarea and comment box are expanded. What would you suggest I add labels to?
![selection_113](https://cloud.githubusercontent.com/assets/5938731/26329471/6f618832-3f15-11e7-8a28-00298f50a9de.png)

**Comment by bmallred** [comment]
@floresj probably just do away with the comment all together and add another `Field` with `Textarea`

**Comment by floresj** [comment]
:+1:

**Comment by bmallred** [comment]
I closed this? @floresj should this be closed or in review?

**Comment by floresj** [comment]
This should be in review. I'll move it over.

**Comment by billy22g** [comment]
LGTM
