### ISSUE TITLE
Do not truncate accordion summary if it is the default text

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1293]
When the default text is displaye (example: *Provide the <subject> details*) then truncation should not occur.

cc: @Jay-Neighbours-I72 @lauraponce @billy22g

**Comment by floresj** [comment]
Could this be as simple as just wrapping the default text in an element that contains a css class that overrides the text-overflow behavior? For instance, [Disciplinary.jsx](https://github.com/truetandem/e-QIP-prototype/blob/master/src/components/Section/Military/Disciplinary/Disciplinary.jsx) looks like the following (many others follow a similar pattern):
```jsx
  summary (item, index) {
    const itemProperties = (item || {}).Item || {}
    const service = itemProperties.Name && itemProperties.Name.value
          ? itemProperties.Name.value
          : i18n.t('military.disciplinary.collection.summary.unknown')
    const dates = itemProperties.Date && itemProperties.Date.date
          ? `${itemProperties.Date.month}/${itemProperties.Date.year}`
          : ''

    return (
      <span>
        <span className="index">{i18n.t('military.disciplinary.collection.summary.item')} {index + 1}:</span>
        <span><strong>{service}</strong></span>
        <span className="dates"><strong>{dates}</strong></span>
      </span>
    )
  }
```

Could we do something like 
```jsx
    const service = itemProperties.Name && itemProperties.Name.value
          ? <strong>itemProperties.Name.value</strong>
          : <strong  className="no-truncate">i18n.t('military.disciplinary.collection.summary.unknown')</strong>
```

or delegate to some component
```jsx

const service = (itemProperties || {}).Name || ''
<SummaryText value={service} default={i18n.t('military.disciplinary.collection.summary.unknown')} />
```
which would then render 
```jsx
<strong>{value}</strong>
``` 
or 
```jsx
<strong className="no-truncate">{default}</strong>
```

**Comment by bmallred** [comment]
The problem here is that if don't truncate then we get the same behavior we were trying to prevent where it pushed everything else to new lines.

**Comment by billy22g** [comment]
Yeah, this to me is two-fold.

1. Remove truncation for default text.
2. Ensure all of the default text items are short enough to work nicely (accounting for all screen sizes I assume).

**Comment by Jay-Neighbours-I72** [comment]
Can we make the default text italic too?

**Comment by Jay-Neighbours-I72** [comment]
Submitted a PR to change these to italic

**Comment by Jay-Neighbours-I72** [comment]
Can we increase the width of this placeholder text? 

Looks like it is cutting off sooner than needed (there won't ever be a date when the placeholder is there)

<img width="917" alt="screen shot 2017-07-11 at 2 38 19 pm" src="https://user-images.githubusercontent.com/19935974/28084486-bcc69678-6646-11e7-8271-12ee998e40a4.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 it was set to the length it is now due to the possibility of date ranges being to the right of that.

**Comment by Jay-Neighbours-I72** [comment]
There won't ever be a date when the placeholder is there correct? @bmallred

**Comment by bmallred** [comment]
Nope that is not correct. For that use case you see right now the odds of a date range coming first is very probable. As they fill in the date range then the dates are shown. The placeholder text is removed once the information on the left-hand side is available.

**Comment by Jay-Neighbours-I72** [comment]
Ahh I see.

Can we change it so as soon as the user enters any real data (date or other input) it replaces the placeholder text?

That could solve the width issue and open up the full width for placeholder text.

**Comment by bmallred** [comment]
What do we put on the left side? It would look something like (replace dots with spaces)

**Person 1: ** ................................................................................................ **1/2000 - 1/2001**

**Comment by Jay-Neighbours-I72** [comment]
Exactly that, blank space until real data is entered

**Comment by bmallred** [comment]
Yeah that is do-able

**Comment by Jay-Neighbours-I72** [comment]
Cool! That is my preference, sound ok to you @billy22g ?

**Comment by billy22g** [comment]
Seems fine to me, and we can adjust if necessary.

**Comment by bmallred** [comment]
## Maximum view size with `max-width: 53rem;`

![image](https://user-images.githubusercontent.com/697855/28272076-71624dc6-6ad8-11e7-9cd9-fce0e2fc8488.png)

## Width at breakpoints

### @media screen and (max-width: 1800px)
### @media screen and (max-width: 1800px)
### @media screen and (max-width: 1800px)

**Comment by bmallred** [comment]
## Maximum view size with `max-width: 53rem;`

![image](https://user-images.githubusercontent.com/697855/28272076-71624dc6-6ad8-11e7-9cd9-fce0e2fc8488.png)

## Width at breakpoints

### @media screen and (max-width: 1800px)
```css
max-width: 48rem;
```

### @media screen and (max-width: 1380px)
```css
max-width: 38rem;
```

### @media screen and (max-width: 1025px)
```css
max-width: 32rem;
```

### @media screen and (max-width: 640px)
```css
max-width: 28rem;
```

### @media screen and (max-width: 590px)
```css
max-width: 20rem;
```

**Comment by bmallred** [comment]
In reference to this [comment](https://github.com/truetandem/e-QIP-prototype/issues/1293#issuecomment-314534870) the "early truncation" was occurring due to the introduction of markdown to the summary text. This should be resolved once the PR is merged.

**Comment by billy22g** [comment]
LGTM
