### ISSUE TITLE
Adjust the breakpoint for the accordion button left-alignment

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1294]
When the view size shrinks to a certain point the **append** button is no longer left aligned as intended. Fix this.

cc: @Jay-Neighbours-I72 @billy22g

**Comment by floresj** [comment]
~765
![selection_129](https://cloud.githubusercontent.com/assets/5938731/26600575/93b2556e-454a-11e7-89f9-3b5ab107ff81.png)

~1178
![selection_128](https://cloud.githubusercontent.com/assets/5938731/26600532/6cc54a92-454a-11e7-95a8-9d75fdb2074f.png)

~1918
![selection_127](https://cloud.githubusercontent.com/assets/5938731/26600504/57b60894-454a-11e7-9bc6-77059f12e408.png)

**Comment by billy22g** [comment]
LGTM
