### ISSUE TITLE
Relative type grid confusion

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1298]
Address issue with the size of the relative type buttons

**Comment by floresj** [comment]
@Jay-Neighbours-I72 What were your thoughts on this?

**Comment by Jay-Neighbours-I72** [comment]
Decrease height to 6rem and center child vertically.

<img width="1293" alt="screen shot 2017-05-31 at 2 48 25 pm" src="https://cloud.githubusercontent.com/assets/19935974/26648357/40f3c558-4610-11e7-9da1-8061c6137156.png">


-
@billy22g What was the final decision on whether or not we could move the "Including adopted/foster" line under Child to help text?

If we can move that then 4 columns will work here:
<img width="1226" alt="screen shot 2017-05-31 at 2 53 43 pm" src="https://cloud.githubusercontent.com/assets/19935974/26648592/f956e26a-4610-11e7-9b63-41aa5d0245fe.png">

**Comment by billy22g** [comment]
At least for now, we can't do that. Let's see how it goes with option 1 and if we're still struggling we'll float that again. Thanks!

**Comment by bmallred** [comment]
## Preview
![relations-smaller](https://cloud.githubusercontent.com/assets/697855/26733833/10bd117a-478a-11e7-8a91-fcc150c6e300.png)

**Comment by billy22g** [comment]
LGTM
