### ISSUE TITLE
Adding multiple citizenships

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1299]
make it clear how the the multiple citizenship field works by adding hing/help

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 already has gone through and knocked out several of the help texts.

Went ahead and scoured the content guide for usages of the `Country` component allowing multiple entries. Several were found as well as several missing fields as well.

**Comment by billy22g** [comment]
LGTM
