### ISSUE TITLE
Fix navigation bar WCAG issues

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1300]
Using html code sniffer tool, address critical issues with the eApp navigation bar.

Acceptance Criteria
- 18f usability expert review of fixes

**Comment by billy22g** [comment]
@adelevie Would you mind checking this one and moving to the "Current Sprint Completed" column when 👍 ?

**Comment by colinpmacarthur** [comment]
@adelevie Did you have a chance to take a look at this one?

**Comment by adelevie** [comment]
No errors! Looks great. Sorry for the delay.
