### ISSUE TITLE
Verify Foreign Contacts

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1301]
Verify foreign contacts section (section 19 in SF-86 PDF) and the first part of foreign activities.  Equates to on page of the SF-86.

Include these sections in the verification:
  - [x] Do you have, or have you had, close and/or continuing contact with a foreign national within the last seven (7) years with whom you, or your spouse, or legally recognized civil union/domestic partner, or cohabitant are bound by affection, influence, common... 
  - [x] Have you, your spouse or legally recognized civil union/domestic partner, cohabitant, or dependent children EVER had any foreign financial interests...

Write/audit help text

Write/audit error text

Compare against validation matrix

**Comment by Jay-Neighbours-I72** [comment]
Help and error text PR submitted.

Validation issues added.

Content issues added.

Will review all when on staging.

**Comment by Jay-Neighbours-I72** [comment]
Direct control:
Help and error text PR submitted.

Validation issues added.

Will review all when on staging.

**Comment by billy22g** [comment]
LGTM
