### ISSUE TITLE
Foreign contacts - Nature of relationship - Personal subtext cut off

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1309]
Personal block - subtext is cut off. (These buttons for this specific answer will have to get taller)

<img width="1007" alt="screen shot 2017-05-25 at 1 22 56 pm" src="https://cloud.githubusercontent.com/assets/19935974/26462184/c1717a26-414d-11e7-9e18-d405ad18aa41.png">

![screen shot 2017-05-25 at 1 23 07 pm](https://cloud.githubusercontent.com/assets/19935974/26462207/d4b45f5e-414d-11e7-8b13-3b8bb552ddbf.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 should we try going two-column first?

**Comment by Jay-Neighbours-I72** [comment]
Yeah that is a good idea!

**Comment by floresj** [comment]
![selection_122](https://cloud.githubusercontent.com/assets/5938731/26596865/2bf947b8-453e-11e7-80b6-d499edbc8664.png)

**Comment by bmallred** [comment]
@floresj I think **Professional or business** needs to come down a bit and then **Personal** up

**Comment by floresj** [comment]
@bmallred Thank ya sir! Here's the updated one.
![selection_124](https://cloud.githubusercontent.com/assets/5938731/26598780/55a1eb28-4544-11e7-9544-566e775dbd5f.png)

**Comment by billy22g** [comment]
LGTM
