### ISSUE TITLE
Foreign contacts - Place of birth error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1310]
- [ ] Duplicate error in Place of birth - country field

<img width="1015" alt="screen shot 2017-05-25 at 2 42 38 pm" src="https://cloud.githubusercontent.com/assets/19935974/26465251/8af74f42-4158-11e7-9d3b-e83827a20655.png">

**Comment by floresj** [comment]
Once the validation refactor is in, we'll check to see if this is still an issue.

**Comment by bmallred** [comment]
## Preview
![fc-pob](https://cloud.githubusercontent.com/assets/697855/26632053/09ee348c-45dc-11e7-9449-2c4ed140f0f1.png)

**PR**: #1297

**Comment by lauraponce** [comment]
Looks great! (Not sure why @bmallred 's screenshot shows the 42 with the green checkmark, but I verified that it's not validating as green in the browser and correctly marks it red).

**Comment by bmallred** [comment]
@lauraponce thanks for checking that! No idea why that is green on the screenshot either
