### ISSUE TITLE
All question headlines - Period or no period

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1313]
Overall question.

Do we want to have periods after questions or not.

My preference is for no period, I don't think headlines require punctuation. 

Thoughts @lauraponce @billy22g 

<img width="1027" alt="screen shot 2017-05-26 at 9 07 53 am" src="https://cloud.githubusercontent.com/assets/19935974/26496897/5c0c0bb0-41f7-11e7-9b9c-444f9a5aa7ee.png">
<img width="792" alt="screen shot 2017-05-26 at 9 08 09 am" src="https://cloud.githubusercontent.com/assets/19935974/26496898/5c0db154-41f7-11e7-889a-81aadf61a433.png">

**Comment by billy22g** [comment]
Agreed. Some folks in OPM might push back on this, but it's a case we can make and I think they'll be receptive.

**Comment by lauraponce** [comment]
Agreed on not having punctuation for the headlines, but I can see it for the the additional instructional text such as in your screenshot for "Check all that apply" where it would have a period there. 

I think maybe it's the difference of font size/weight? For the large headlines, it looks fine and normal to ask without punctuation, but when it's the smaller font size, it looks strange to me without it (specifically I'm just looking at the 'Check all that apply' and think it needs a period after).

**Comment by billy22g** [comment]
+1

**Comment by bmallred** [comment]
No period
