### ISSUE TITLE
Foreign activities - Foreign real estate - address block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1328]
Provide the location/address of property:

Should only have:
- [x] Street
- [x] City
- [x] Country

<img width="922" alt="screen shot 2017-05-30 at 2 53 35 pm" src="https://cloud.githubusercontent.com/assets/19935974/26599943/45782786-4548-11e7-83c4-e4e55ef3b916.png">

![screen shot 2017-05-30 at 2 53 50 pm](https://cloud.githubusercontent.com/assets/19935974/26599987/69752f76-4548-11e7-8a2a-7d4614b672cd.png)

**Comment by bmallred** [comment]
This is probably repeated several times throughout the application since the original plan was to make everything the full address. Maybe we should make a sweep through the application while tackling this one.

**Comment by floresj** [comment]
Related #1259

**Comment by bmallred** [comment]
@floresj we can do the one in #1259 with the following:

```jsx
<BirthPlace branch={false} help="" hideCounty={true} domestic="Yes" cityPlaceholder="Please enter your city" />
```

The main difference on this on is the inclusion of **street** as well which is only present (currently) with a full address.

**Comment by floresj** [comment]
@bmallred cool beans. I can get going on this one then.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 will address validation be necessary?

**Comment by Jay-Neighbours-I72** [comment]
Good question @bmallred 

I'm assuming not, wouldn't USPS be confused by this anyway since it isn't a full address?

**Comment by bmallred** [comment]
I **think** @floresj verified and it is possible to submit for validation **without** the zip code. Obviously we'd only be validating those that had _United States_ as the country.

**Comment by billy22g** [comment]
Wait, isn't this specific to non-US countries, so it would never be in the US? The question says "real estate in a foreign country."

Also, the place of birth placeholder is in the country field.

<img width="635" alt="screen shot 2017-06-29 at 7 36 31 am" src="https://user-images.githubusercontent.com/5091167/27690172-ca7ab0cc-5c9d-11e7-94f6-deef6e9d1331.png">

**Comment by floresj** [comment]
@billy22g Good point about this address not being a US. I'm updating the placeholder in a PR. I will get that in the queue. THanks!

**Comment by colinpmacarthur** [comment]
Appears to be working correctly and all of the above issues have been addresssed
