### ISSUE TITLE
Go import paths

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#133]
# Concern

A very interesting question about the Go import paths arose the other day which made us think about possible alternatives, what is the best way forward at the moment and the future, and what others thought about the options. The main concerns come down to the following:

1. Possible code synchronization issues or breaking changes due to versioning
2. Hand-off

## Option 1: Rename the internal references to 18F repository

This involves just a few steps internally.

  1. We would change all paths from `github.com/truetandem/e-QIP-prototype` to `github.com/18F/e-QIP-prototype`.
  2. We can either...
    * leave the source code where it is and create a symlink to the 18F namespace
  ```
  mkdir -p $GOPATH/src/github.com/18F/
  cd $GOPATH/src/github.com/18F/
  ln -s $GOPATH/src/github.com/truetandem/e-QIP-prototype .
  ```
   * We can move the repository to the expected path
  ```
  mv $GOPATH/src/github.com/e-QIP-prototype $GOPATH/src/github.com/18F/
  ```

Either option always for minimal changes while still using the Go workspace. However, this does raise a question as to which is the authoritative source during the development lifecycle (i.e. if someone wanted to contribute which repository should they work against). Possible addition to the README and/or CONTRIBUTING:

```
1. Clone the repository `git clone <path/to/e-QIP-prototype> $GOPATH/src/<organization>`
2. Change in to the new directory `cd $GOPATH/src/<organization>/e-QIP-prototype`
3. Fork the code on Github
4. Add a `git remote` with `git remote add fork <URI to forked repository>`
5. Make changes and commit locally
6. Push to fork `git push fork`
7. Create pull request from forked repository to <18F/truetandem> repository
```

## Option 2: Allow for relative import paths

This would require moving the source code out of the Go workspace.

```
mv $GOPATH/src/truetandem/e-QIP-prototype ~/
```

then changing the import paths from `import "github.com/truetandem/e-QIP-prototype/middleware"` to `import "./middleware"` (or whatever the appropriate amount of dots are for the relative path).

This works and is typical during prototyping but I haven't personally seen this in practice a lot. Any feedback on this is welcomed.

## Option 3: Vendor internal packages to remove specific namespace

Move all internal packages in to a custom namespace under the `vendor/` directory.

```
cd <repository>/api
mkdir ./vendor/eapp
mv {middleware,cf,model,handlers} ./vendor/eapp
```

This allows our import paths to change from `import "github.com/truetandem/e-QIP-prototype/middleware"` to `import "eapp/middleware"`.

Downfalls to this is it separates the code base a bit. Not bad since most editors have fuzzy-finding, but when browsing the code base for the first time it may be odd. Also, it does place some additional TLC to the `vendor/` directory as to what is committed and what isn't during early development phases.

## Option 4: Leave as-is and change to 18F repository at hand off

Keep the import paths pointing to `github.com/truetandem/e-QIP-prototype` and before hand off change them to `github.com/18F/e-QIP-prototype`.

**Comment by jcscottiii** [comment]
FWIW, you should treat 18F as the org with the original source code. That means all import paths referenced in the code are `github.com/18F/e-QIP-prototype`.

Afterwards, you would do this part of option 1:

```
mv $GOPATH/src/github.com/truetandem/ $GOPATH/src/github.com/18F/
```
(instead of the symlink)

You'll also need to change references in your [glide.yaml](https://github.com/truetandem/e-QIP-prototype/blob/master/api/glide.yaml#L1) to point to 18F too. 


One word of caution, if you are running your CI tests from the `truetandem` org in travis / circleci, you'll need to do a manual move because it will place the code in `$GOPATH/src/github.com/truetandem`
