### ISSUE TITLE
Foreign activities - Real estate - Date block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1330]
Provide the date of purchase or to be acquired:

- [x] Year input is allowing too many characters and not throwing an error.
<img width="997" alt="screen shot 2017-05-30 at 3 39 04 pm" src="https://cloud.githubusercontent.com/assets/19935974/26601547/412e61ee-454e-11e7-9c80-23653739aa4a.png">

**Comment by bmallred** [comment]
This doesn't occur in more recent versions (not yet pushed to `staging`). When PR #1297 is merged it should be fixed.

**Comment by billy22g** [comment]
Few things here: 

1. So I think year should only accept four characters (right?). 
2. Typing 06 was working for month (evaluated to June) but is no longer working and showing up as an error.
3. Year error isn't showing properly.

<img width="660" alt="screen shot 2017-06-05 at 5 07 33 pm" src="https://cloud.githubusercontent.com/assets/5091167/26807094/80060d46-4a11-11e7-952c-7736f49432a6.png">

**Comment by billy22g** [comment]
LGTM
