### ISSUE TITLE
Military history - SSS input - can't type

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1343]
- [ ] Can't type any characters in the SSS number input

<img width="1109" alt="screen shot 2017-05-31 at 10 11 26 am" src="https://cloud.githubusercontent.com/assets/19935974/26636063/978442f2-45e9-11e7-9154-6efea188ee23.png">

**Comment by bmallred** [comment]
Resolved in #1297

**Comment by billy22g** [comment]
LGTM
