### ISSUE TITLE
Military history - Disciplinary procedures section 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1346]
Looks like this subsection is a within a branch on the PDF 

- [ ] If user answers "No" to having served in the U.S. Military they should not see this section.

<img width="2009" alt="screen shot 2017-05-31 at 10 23 08 am" src="https://cloud.githubusercontent.com/assets/19935974/26636734/a83a4f9a-45eb-11e7-9278-417ff371c575.png">
![screen shot 2017-05-31 at 10 26 55 am](https://cloud.githubusercontent.com/assets/19935974/26636749/b0499222-45eb-11e7-8637-0d2dfd8a757a.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 so are we moving this to somewhere else?

The current tracking on sections looks to be:

```
Military History
 - U.S. military
 - Disciplinary procedures
 - Foreign military
```

Which also doesn't include the **Selective service record**.

**Comment by Jay-Neighbours-I72** [comment]
After rethinking this my suggestion is unnecessary. 

I was thinking of treating it like the mental health section but looking again I don't think we need to do that.

Closing this @bmallred

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 lol, you sure? i just implemented it haha

**Comment by Jay-Neighbours-I72** [comment]
Ugh, you are right, this still makes sense. My brain isn't working.

**Comment by billy22g** [comment]
LGTM
