### ISSUE TITLE
Military history - Foreign military - name of country

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1347]
Provide name of country:

- [x] Can we use the country typeahead for this block?

<img width="1092" alt="screen shot 2017-05-31 at 10 39 19 am" src="https://cloud.githubusercontent.com/assets/19935974/26637543/bd310ee6-45ed-11e7-8aa4-b42731207467.png">

**Comment by billy22g** [comment]
LGTM
