### ISSUE TITLE
Military history review - and all sections

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1349]
- [x] All review screens app wide should have dividing lines and padding/margin between subsections (Emotional health can be used as a correct example)

- [x] All subsections headlines should be the same size they are on the individual subsections (Ex. Disciplinary procedures is smaller on review)

<img width="1432" alt="screen shot 2017-05-31 at 11 05 34 am" src="https://cloud.githubusercontent.com/assets/19935974/26638937/74a11d02-45f1-11e7-9403-2f96e1d3058d.png">
<img width="1338" alt="screen shot 2017-05-31 at 11 08 30 am" src="https://cloud.githubusercontent.com/assets/19935974/26638948/8015612a-45f1-11e7-9d77-9ea5ad31f5db.png">

**Comment by bmallred** [comment]
The title for disciplinary procedures is an `h2` in both instances.
 - review: https://github.com/truetandem/e-QIP-prototype/blob/master/src/components/Section/Military/Military.jsx#L83
 - individual: https://github.com/truetandem/e-QIP-prototype/blob/master/src/components/Section/Military/Military.jsx#L138

cc: @Jay-Neighbours-I72

**Comment by billy22g** [comment]
Leaving this for @Jay-Neighbours-I72 because context is helpful here.

**Comment by Jay-Neighbours-I72** [comment]
Looks good
