### ISSUE TITLE
People who know you well - Zip code error lingering

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1350]
- [ ] The ZIP Code error is lingering instead of closing right after it is fixed and clicked out of.

<img width="861" alt="screen shot 2017-05-31 at 1 41 48 pm" src="https://cloud.githubusercontent.com/assets/19935974/26645700/0872cbc4-4607-11e7-8a8a-0c5bd6d851a1.png">

**Comment by lauraponce** [comment]
This looks good now!
