### ISSUE TITLE
People who know you well - Other explanation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1353]
Provide relationship to you:
Other:
Explanation label is missing

<img width="1026" alt="screen shot 2017-05-31 at 2 19 46 pm" src="https://cloud.githubusercontent.com/assets/19935974/26647132/4f32a674-460c-11e7-91bc-b4199554addb.png">

**Comment by bmallred** [comment]
## Preview
![explanation-label](https://cloud.githubusercontent.com/assets/697855/26792325/0caa928c-49e8-11e7-8cdf-f922c65e81d9.png)

**Comment by billy22g** [comment]
LGTM
