### ISSUE TITLE
People who know you well - Person counter

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1354]
When does the person added counter change?

- [ ] This example has 3 people added, all fields complete and no selected at the bottom but only 2 people on the counter.

-
<img width="1633" alt="screen shot 2017-05-31 at 2 24 36 pm" src="https://cloud.githubusercontent.com/assets/19935974/26647345/133a5f76-460d-11e7-8ffa-1695c83b6806.png">

**Comment by bmallred** [comment]
This may have been resolved. As long as the person is valid it will be counted.

On another note I went ahead and aligned the accordion summary to be more like other usages:
![persons-3-for-3](https://cloud.githubusercontent.com/assets/697855/26792168/87eb253e-49e7-11e7-8e88-4d4b5de9de81.png)

**Comment by billy22g** [comment]
LGTM
