### ISSUE TITLE
People who know you well - Gap and incomplete messaging

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1355]
- [x] This section should have the same gap messaging and incomplete messaging as the Your history section.

**Comment by bmallred** [comment]
## Preview
![people-gaps](https://cloud.githubusercontent.com/assets/697855/26795441/a77efce8-49f3-11e7-9d51-061cb7ae4330.png)

**Comment by billy22g** [comment]
I'm not seeing the gap show up when I come back.

Also, I'm seeing the subsection as complete (the green dot) when it's not.

<img width="1210" alt="screen shot 2017-06-06 at 1 25 33 pm" src="https://user-images.githubusercontent.com/5091167/26847887-cd48e7e0-4abb-11e7-829d-8c129c0e0572.png">

**Comment by bmallred** [comment]
Ah, think I only set it up for review. I'll fix that.

**Comment by Jay-Neighbours-I72** [comment]
Looks good

**Comment by Jay-Neighbours-I72** [comment]
Re-opening, not seeing the "incomplete message" yet

**Comment by bmallred** [comment]
Didn't know we wanted that. We can add it in though.

**Comment by Jay-Neighbours-I72** [comment]
Crap, my fault, I should have been more specific about what I meant by Incomplete message when adding this.

**Comment by bmallred** [comment]
Are all accordions going to have this "incomplete" type message? Or is it still just specific ones?

**Comment by Jay-Neighbours-I72** [comment]
I was thinking all will have it on he review screen, when we are showing red on all missing inputs - (related to the validation issues)

Was originally thinking that only the gap tracking accordions would have them in real time but maybe it makes sense for them all to have it?

Thoughts?

**Comment by bmallred** [comment]
Either way it justifies reworking the `Accordion` since injecting in custom messages like that at the moment is on a per section basis. I have no opinion on when it shows up but I think how it works in "Your History" works well.

While I'm in here for "People who know you well" I'll take off the requirement for the people to be valid in order to be counted towards the counter.

**Comment by Jay-Neighbours-I72** [comment]
What about a generic message to be used on all accordions?

"This information is incomplete"

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 definitely will do that and allow it to be overridden as well just in case!

**Comment by billy22g** [comment]
That sounds like a great approach!

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Gonna leave this one for you. I looks good to me, but the accordions are all still open when you leave and come back, which is not what we want. I thought there was already an issue for that, but if not, would you add it please?

**Comment by bmallred** [comment]
@billy22g and @Jay-Neighbours-I72  that issue is being tracked over on #1321.

**Comment by billy22g** [comment]
Then LGTM
