### ISSUE TITLE
Change focus when navigating between sections and subsections

### ISSUE THREAD

**Issue by adelevie** [truetandem/e-QIP-prototype#1358]
When keyboard navigating with the left nav bar, the focus should move from the nav bar to the form content. This accessibility issue was identified by @nickbristow from some quick manual testing.

Without this fix, folks keyboard navigating (e.g. w/ a screenreader) need to move focus all the way through the nav bar before arriving on form content.

**Comment by bmallred** [comment]
@adelevie @nickbristow

So maybe `up` and `down` would keep the focus in the navigation section and `right` and `left` moves between navigation and content?

**Comment by nickbristow** [comment]
The issue is, after selecting a nav link on the left, focus doesn't move to the new content or the top like a normal page would.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
