### ISSUE TITLE
Create form routing by section and subsections

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#136]
The goal is to route based on something like the following:

```
/form
/form/:section
/form/:section/:subsection
```

**Comment by bmallred** [comment]
Based on what I could find on [react-routing](https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteMatching.md) there are two options:

```jsx
<Route path="/form" component={Form}>
  <Route path=":section" component={Form}>
    <Route path=":subsection" component={Form} />
  </Route>
</Route>
```

or the condensed version

```jsx
<Route path="/form(/:section(/:subsection))" component={Form} />
```

They both allow for optional route variables to be accessed via `this.props.params` in the referenced component (`Form` in this example).

**Comment by floresj** [comment]
Awesome. Did not know about the condensed version. That's pretty interesting.

**Comment by bmallred** [comment]
Yeah, took a bit more digging. Honestly surprised it was more upfront in the documentation.
