### ISSUE TITLE
Military history - accordion title

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1371]
Accordion titles are missing spaces between words

<img width="1265" alt="screen shot 2017-06-05 at 1 34 42 pm" src="https://cloud.githubusercontent.com/assets/19935974/26795487/d54e22e8-49f3-11e7-9626-22b4b2787d56.png">

<img width="1310" alt="screen shot 2017-06-05 at 2 03 26 pm" src="https://cloud.githubusercontent.com/assets/19935974/26796547/de894d02-49f7-11e7-9efb-2c204802cbe8.png">

**Comment by billy22g** [comment]
LGTM
