### ISSUE TITLE
Foreign activities - Direct control - date input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1375]
Provide the date control or ownership was relinquished:

- [x] Error style on inputs not showing.

<img width="1110" alt="screen shot 2017-06-05 at 3 47 48 pm" src="https://cloud.githubusercontent.com/assets/19935974/26800297/ca6e60fa-4a06-11e7-8b86-e8ecf539fafb.png">

**Comment by billy22g** [comment]
LGTM
