### ISSUE TITLE
Add comment for "Sex" not working

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1379]
When you try to click "Add comment" under Sex, it seems to be in the hit area of the "Female" button. 

<img width="799" alt="screen shot 2017-06-06 at 1 02 35 pm" src="https://user-images.githubusercontent.com/5091167/26846919-77d1b858-4ab8-11e7-8a93-1c3da1281c8f.png">

**Comment by lauraponce** [comment]
I think this was updated from the initial issue @billy22g pointed out and that seems to be resolved, but now the hit area for add a comment seems to extend pretty far to the right, can you bring this is so it's a closer to the text itself and immediate surrounding area?

![screen shot 2017-06-16 at 3 07 03 pm](https://user-images.githubusercontent.com/21222704/27241163-a28db7f0-52a5-11e7-94c4-1cefda34752b.png)

**Comment by bmallred** [comment]
Should be up on staging soon.

**Comment by billy22g** [comment]
LGTM
