### ISSUE TITLE
"Your Identifying Information" always incomplete

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1380]
When going through Section 1, the final subsection, "Your identifying information" is never showing up as complete despite all the fields being completed.

<img width="287" alt="screen shot 2017-06-06 at 1 04 30 pm" src="https://user-images.githubusercontent.com/5091167/26847031-d90a74e8-4ab8-11e7-93d1-279760cc576c.png">

**Comment by billy22g** [comment]
It appears "Domestic violence" also has this issue. I selected "No" and it didn't show up as complete.

<img width="279" alt="screen shot 2017-06-06 at 1 07 44 pm" src="https://user-images.githubusercontent.com/5091167/26847148-3ae0e36e-4ab9-11e7-97f5-e9a5da81204b.png">

**Comment by bmallred** [comment]
@billy22g what values are you using? I was able to get the green dot using using

 - Height: 6' 1"
 - Weight: 190
 - Bald
 - Green
 - Male

**Comment by bmallred** [comment]
Domestic violence does have an issue. Will look in to that.

**Comment by billy22g** [comment]
Looks like "unspecified," "grey", "blonde", and "red or auburn" are the culprits? That seems suuuuper brittle though. Shouldn't there be no difference between the values in terms of the completion?

**Comment by bmallred** [comment]
Sniffed around and looks like in the validation logic it's using the descriptive text and not the underlying value.

example:

```'Gray' !== 'Gray or Partially Gray'```

**Comment by billy22g** [comment]
Makes sense, thanks! LGTM
