### ISSUE TITLE
Previous & Next Button hit areas not quite complete

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1388]
The top and bottom of the buttons have the hover state, but the hit area doesn't extend to the edge of the buttons.

<img width="332" alt="screen shot 2017-06-07 at 7 29 48 am" src="https://user-images.githubusercontent.com/5091167/26880908-225e4a8a-4b53-11e7-8334-0b6398952446.png">

**Comment by bmallred** [comment]
This appears to highlight a more widespread issue as well. Apparently sometimes the buttons have padding and sometimes they do not. Tracking this down in the styling.

## Example without padding (in identification)

![button-hit-area1](https://user-images.githubusercontent.com/697855/27192772-926a5d00-51ca-11e7-8b2b-56cdc0221427.png)


## Example has padding (in substance use)

![button-hit-area](https://user-images.githubusercontent.com/697855/27192475-835ae6a0-51c9-11e7-8b98-dd573058ec47.png)

**Comment by billy22g** [comment]
LGTM
