### ISSUE TITLE
Mobile navigation refinements

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1390]
Discuss and make changes to mobile navigation.

**Comment by Jay-Neighbours-I72** [comment]
Changes:

- Nav icon larger, moved to left, removed "navigation" spelled out. (Removed this because it was consuming valuable real estate, causing us to have to use the nav icon on the right, cluttering header. We think users will know how to open it without the text, plan is to test it with users and see)
- Centered seal and form name
- Logout link moved to upper right
- Reduced size of sections complete to push navigation up
- Added arrow open/close indicators on nav items - this will be alongside new functionality, sections with children will toggle open and close to reveal/hide them
- Third level items indented further to be more clear 


![e-qip-small-screen-nav-v2-1](https://user-images.githubusercontent.com/19935974/27096599-92b91ec2-503f-11e7-89e5-9eb9fc7a3468.jpg)
![e-qip-small-screen-nav-v2-2](https://user-images.githubusercontent.com/19935974/27096600-92bb113c-503f-11e7-8997-642556a4e0b3.jpg)

**Comment by billy22g** [comment]
To be clear, this is just storyboarded, not implemented, correct? I'm assuming so, so I'm going to close and move to complete, but just wanted to check @Jay-Neighbours-I72.

**Comment by bmallred** [comment]
@billy22g that is correct
