### ISSUE TITLE
Consider re-enabling zoom on mobile devices

### ISSUE THREAD

**Issue by toolness** [truetandem/e-QIP-prototype#1392]
It looks like mobile zooming was disabled in #1387, but I think this poses accessibility issues, as I mentioned in my review of it:

> What's the rationale for restricting zooming here?  [WCAG AA's Zoom/Magnification guidelines](https://www.w3.org/TR/mobile-accessibility-mapping/#zoom-magnification) recommend against this, and practical reasons for it are given in Adrian Roselli's [Don't Disable Zoom](http://adrianroselli.com/2015/10/dont-disable-zoom.html) post.

So, if possible it'd be nice to re-enable zooming. If not, it'd be good to document the rationale here or somewhere else in the code.

**Comment by billy22g** [comment]
LGTM
