### ISSUE TITLE
Date range "present" button toggling off should register a date or blank the values

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1398]
1. When you click **Present** initially the current date is populated.
 2. Click **Present** again the values appear to still be there but actually are not persisted in the background

![daterange-present](https://user-images.githubusercontent.com/697855/26944885-fd2ad782-4c57-11e7-9b5c-16b0ee0967e7.png)

**Comment by bmallred** [comment]
Resolved in #1424

**Comment by billy22g** [comment]
LGTM
