### ISSUE TITLE
Email address error 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1407]
- [x] Error being shown on number based urls

<img width="1056" alt="screen shot 2017-06-13 at 10 20 56 am" src="https://user-images.githubusercontent.com/19935974/27088172-f3d262b0-5024-11e7-934c-bc26d1a01a5d.png">
<img width="1055" alt="screen shot 2017-06-13 at 10 29 02 am" src="https://user-images.githubusercontent.com/19935974/27088171-f3cf1ef2-5024-11e7-9ae1-ba447dd9a81f.png">

-
- [x] Error not being thrown when spaces in domain
<img width="973" alt="screen shot 2017-06-13 at 1 39 31 pm" src="https://user-images.githubusercontent.com/19935974/27096075-dbdba2c0-503d-11e7-88e2-001ec7477c25.png">

**Comment by billy22g** [comment]
LGTM
