### ISSUE TITLE
Phone number - validate blank entry - all zeros

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1410]
User inputs number
Then user clicks "I don't know"
User deselects "I don't know"
Number is cleared but green checks are still there.

- [x] Can we clear the valid green checks too? 

<img width="528" alt="screen shot 2017-06-13 at 1 46 41 pm" src="https://user-images.githubusercontent.com/19935974/27096450-12966a56-503f-11e7-951c-785924b86c9c.png">
<img width="524" alt="screen shot 2017-06-13 at 1 46 46 pm" src="https://user-images.githubusercontent.com/19935974/27096451-129a0724-503f-11e7-8c7a-c5c7b4fdc442.png">
<img width="516" alt="screen shot 2017-06-13 at 1 46 49 pm" src="https://user-images.githubusercontent.com/19935974/27096449-12955e4a-503f-11e7-9e26-389c2857c337.png">
<img width="714" alt="screen shot 2017-06-13 at 1 47 25 pm" src="https://user-images.githubusercontent.com/19935974/27096452-129a7948-503f-11e7-9a59-b56d5e0a494e.png">

-
Can we throw errors when all zeros are entered?
<img width="724" alt="screen shot 2017-06-13 at 2 02 04 pm" src="https://user-images.githubusercontent.com/19935974/27097035-f908e1ac-5040-11e7-92c8-96a86b4077e8.png">
<img width="545" alt="screen shot 2017-06-13 at 2 01 57 pm" src="https://user-images.githubusercontent.com/19935974/27097034-f908e29c-5040-11e7-8f9b-d7ce5e7954df.png">

**Comment by billy22g** [comment]
When I click "I don't know" and then click it again to deselect, the inputs are still greyed out and I can't enter any numbers.

<img width="766" alt="screen shot 2017-06-14 at 1 22 07 pm" src="https://user-images.githubusercontent.com/5091167/27150461-9b19fdf0-5104-11e7-86bf-e2808a64189e.png">

**Comment by bmallred** [comment]
@billy22g I definitely see the same behavior in the staging behavior as you described. However, using the version that is suppose to be up there in local development it is working as intended. Might be related to PR #1435 with the new node version (**v8.1.1**) causing compilation issues.

I'll try again once a new build is up and if it is still happening will move this back to **in progress** for further investigation.

**Comment by bmallred** [comment]
@floresj moved this back to **in progress**. For some reason this is not working on staging but does on local.

**Comment by floresj** [comment]
@bmallred After performing an arch update, my nodejs and npm were updated which gave me some weird errors when I attempted to build. So I cleared out the `node_modules/ ` dir and reran `npm install` and was able to reproduce locally. I think I have a fix now. Just verifying.

**Comment by bmallred** [comment]
@floresj ah, so it may have been something where our dependencies were a bit behind.

**Comment by bmallred** [comment]
Just tried it and worked on staging so moved this back in to QA!

**Comment by billy22g** [comment]
LGTM!

@Jay-Neighbours-I72 @lauraponce What do you think about if a user clicks back into any of the inputs, it also deselects the "I don't know" and allows them to begin typing in the input? I'm on the fence here, but that's definitely a behavior I would expect, but it might be confusing for others and introduces the possibility of accidental clicks doing something unexpected.
