### ISSUE TITLE
Contact info - email - error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1412]
- [x] Email error thrown, input deleted, error message remains.

<img width="1033" alt="screen shot 2017-06-13 at 2 30 07 pm" src="https://user-images.githubusercontent.com/19935974/27098257-f08c18ce-5044-11e7-8ad6-68f26642c6ca.png">

**Comment by bmallred** [comment]
This should be resolved in PR #1424

**Comment by billy22g** [comment]
LGTM
