### ISSUE TITLE
People who know you well - editing a stack of accordions

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1414]
1. Add several people who know you well.
2. open one of the accordions to edit a detail.
3. hit the close link at the bottom of that accordion.
4. accordion closes, but doesnt move you back up the screen. You either see a random form area, or a huge white screen (if last accordion)

![screen shot 2017-06-13 at 2 36 31 pm](https://user-images.githubusercontent.com/26907482/27098529-e31e2c76-5045-11e7-82f9-b4c0b26fdcac.png)
![screen shot 2017-06-13 at 2 37 01 pm](https://user-images.githubusercontent.com/26907482/27098532-e589100c-5045-11e7-99d1-364830819526.png)
![screen shot 2017-06-13 at 2 37 07 pm](https://user-images.githubusercontent.com/26907482/27098534-e71311fc-5045-11e7-8514-d3f3cf6ce6e7.png)

**Comment by bmallred** [comment]
@gabesnyder @Jay-Neighbours-I72 so what is the desired results? Should we target the same item and scroll to that with a similar buffer to what we use when adding a new item?

**Comment by Jay-Neighbours-I72** [comment]
Might need to do a hangout for this one, I'm not able to reproduce it

**Comment by bmallred** [comment]
TODO:

 - [ ] On close scroll to the item similar to when adding a new item to the accordion. Include the same buffer on top.
 - [ ] On remove apply animation similar to close prior to removing it from the accordion.

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Is this still relevant? Thoughts?

**Comment by Jay-Neighbours-I72** [comment]
This looks to have been fixed to me, screen is scrolling back up properly
