### ISSUE TITLE
Military history - 'US military' not getting a green dot when completed.

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1417]
1. filled out complete US military subsection.
2. moved on to next section.
3. green progress dot did not appear.
![screen shot 2017-06-13 at 2 49 15 pm](https://user-images.githubusercontent.com/26907482/27099111-da271072-5047-11e7-9c27-f0f9a45f31ce.png)

**Comment by bmallred** [comment]
Closing since it has been recorded twice (#1397 and #1374) already and is part of PR #1425
