### ISSUE TITLE
People who know you well - Spell check is running on 'email' fields

### ISSUE THREAD

**Issue by gabesnyder** [truetandem/e-QIP-prototype#1418]
1. type a strange but valid email
2. Spell check suggests that email is spelled wrong.
3. clicking out of field causes spell check to resolve.
![screen shot 2017-06-13 at 2 53 58 pm](https://user-images.githubusercontent.com/26907482/27099280-70635352-5048-11e7-84f8-59e5813d751e.png)

**Comment by lauraponce** [comment]
Looks good!
