### ISSUE TITLE
Address block - yellow style?

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1419]
- [x] When using the browser suggestion for an input in address block it gets a yellow bg style

<img width="815" alt="screen shot 2017-06-13 at 3 15 58 pm" src="https://user-images.githubusercontent.com/19935974/27100219-4a39d7b6-504b-11e7-833d-579f54d88391.png">

**Comment by billy22g** [comment]
I'm unclear on this @Jay-Neighbours-I72. Are we allowing it to use the default yellow style if it's a browser filled input, or removing that? I'll let you close this one when you're good.

**Comment by Jay-Neighbours-I72** [comment]
The goal is to remove the default yellow style completely. IMO it doesn't serve any purpose

@billy22g

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Roger. You mind checking that it's complete then and moving columns? Thanks!
