### ISSUE TITLE
Foreign business - Employment - Accept offer

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1421]
Looks like the PDF wants an explanation for both Yes and No answers

<img width="1038" alt="screen shot 2017-06-13 at 4 09 39 pm" src="https://user-images.githubusercontent.com/19935974/27102369-f526fbfc-5052-11e7-8f67-f5b50c32193c.png">
![screen shot 2017-06-13 at 4 09 47 pm](https://user-images.githubusercontent.com/19935974/27102371-f6e322ae-5052-11e7-9356-9820c6eb8f91.png)

**Comment by billy22g** [comment]
LGTM
