### ISSUE TITLE
Update build pack to use Go 1.8.x

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1430]

**Comment by floresj** [comment]
@bmallred Is this as easy is changing https://github.com/truetandem/e-QIP-prototype/blob/master/manifest-api.yml#L15 to `GOVERSION: go1.7.6` ?

**Comment by bmallred** [comment]
Each of the API manifests and possibly the API dockerfile as well. The dockerfile you may just have to rebuild to get the most current version.

This isn't an urgent item. I saw the new buidpack was available and wanted to put a task in so we didn't forget!

**Comment by bmallred** [comment]
New buildpack for `v1.8.5` at https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.8.5
