### ISSUE TITLE
Placeholder text for address field needs adjusting

### ISSUE THREAD

**Issue by lauraponce** [truetandem/e-QIP-prototype#1448]
The placeholder text in the address input field is "Enter mailing address" but there are certain cases, where the question is asking for the location of the organization, which could potentially be different than it's mailing address. 

What's the best way to handle this? Some options are to make it more generic or change it to "Enter street address" 

@bmallred brought up the concern that if we said to enter the street address people may think they can enter only one. Our address block only has one form element for it an using "mailing address" may have been an attempt to state you can have more than one.

This issue was originally brought up in #946 cc @billy22g @bmallred 

![screen shot 2017-06-16 at 10 55 28 am](https://user-images.githubusercontent.com/21222704/27231946-54a5a1a6-5282-11e7-968e-185edaee366f.png)

**Comment by billy22g** [comment]
My thinking is that "Enter street address" is general enough that if people are confused about the single line in that, they'd also be confused about the single line with "Enter mailing address" as the placeholder. It's more accurate for what we're asking, and if we see it come up in usability testing, we can add a second address line.

**Comment by floresj** [comment]
@billy22g @lauraponce So leave as is with `Enter street address?`

**Comment by billy22g** [comment]
That's my preference. Over to you @lauraponce.

**Comment by lauraponce** [comment]
I agree, I think "Enter street address" makes sense there.

**Comment by billy22g** [comment]
For APO/FPO and International, this is still "Enter mailing address." I think for international it should also be "Enter street address," and for APO/FPO it should just be "Enter address." Thoughts?

**Comment by lauraponce** [comment]
I agree with that @billy22g

**Comment by bmallred** [comment]
So I think we have a conflict in GH issues:

 - This issue has changes to placeholder text
 - Issue #1204 has us removing it

Which way do we want to proceed?

cc: @floresj @lauraponce @billy22g @Jay-Neighbours-I72 @pjsumm

**Comment by Jay-Neighbours-I72** [comment]
I think we can do both:

First line placeholder text = "Enter mailing address."
Second line = no placeholder text

**Comment by floresj** [comment]
So to confirm, is this good?

![selection_257](https://user-images.githubusercontent.com/5938731/27558061-e1ba53a2-5a89-11e7-9fbc-c0bad18d1834.png)

**Comment by Jay-Neighbours-I72** [comment]
That looks good to me!

**Comment by billy22g** [comment]
LGTM
