### ISSUE TITLE
Substance use - Date range

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1457]
Error style is highlighting all fields when year is wrong.

@bmallred I'm open to this is there is a solid reason why this is better than the original style.

My preference is to highlight each individual field like we were doing previously because:
- [ ] Easier for user to quickly identify where the problem area is (when all three are showing error style they will have to figure out which is the problem)

- [ ] It is misleading, the day and month could still be correct but they will be highlighted red, could cause confusion with users

- [ ] The error text is written to highlight the specific error area (Ex. There is a problem with the "year". To make sense with all 3 being highlighted we would want to re-write it more generic - There is a problem with the "date"

- [ ] All users have been good with the old style (highlighting issue input only)

Opening this to discussion with @bmallred @billy22g @lauraponce 
Thoughts?

<img width="913" alt="screen shot 2017-06-19 at 11 25 50 am" src="https://user-images.githubusercontent.com/19935974/27293670-18586fa2-54e5-11e7-855b-4283b4f040b0.png">
<img width="789" alt="screen shot 2017-06-19 at 11 27 56 am" src="https://user-images.githubusercontent.com/19935974/27293669-18573880-54e5-11e7-8c2a-a40539e13315.png">

Preferred:
<img width="802" alt="screen shot 2017-06-19 at 11 46 09 am" src="https://user-images.githubusercontent.com/19935974/27293690-237feca2-54e5-11e7-949f-12297978e256.png">

**Comment by billy22g** [comment]
I agree 100%. The error should be based on the individual field unless there's a compelling reason to do otherwise.

**Comment by lauraponce** [comment]
Agreed! I think this makes much more sense and gives users a clear indication about what they did wrong and what needs fixing.

**Comment by Jay-Neighbours-I72** [comment]
Next steps:
Highlight full date with error message when it is necessary.

**Comment by bmallred** [comment]
Note to self... partially implemented composite component error for #919 and need to do the same to `DateRange`

**Comment by colinpmacarthur** [comment]
This appears to be implemented and working well!
