### ISSUE TITLE
Substance use - Review screen - second line

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1458]
Can we remove the second line on the review screen?

<img width="1435" alt="screen shot 2017-06-19 at 1 40 10 pm" src="https://user-images.githubusercontent.com/19935974/27297982-f485e3ce-54f4-11e7-915b-9b6a31759417.png">
<img width="1431" alt="screen shot 2017-06-19 at 1 41 33 pm" src="https://user-images.githubusercontent.com/19935974/27298005-080cd074-54f5-11e7-8248-f096a2caf973.png">

**Comment by floresj** [comment]
@Jay-Neighbours-I72 will do!

**Comment by lauraponce** [comment]
Looks good! The extra line is no more
