### ISSUE TITLE
Substance use - Left nav - Green circles

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1459]
- [x] Can we have the top level subsection get a green dot too when all of it's children are complete?

This will be especially important when we work in the collapsing nav menu

<img width="459" alt="screen shot 2017-06-19 at 1 44 35 pm" src="https://user-images.githubusercontent.com/19935974/27298825-2a831a5c-54f8-11e7-9417-694d3a0f725b.png">

**Comment by billy22g** [comment]
LGTM
