### ISSUE TITLE
Changing section answer from Yes to No wipes out data

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1464]
As an eApp user I want to see a warning message if I have a section I answered "Yes" to, entered data, then selected "No" so that I understand changing Yes to No will remove the data I've entered so far

Acceptance Criteria
- [x] Prompt user that changing from Yes to No will clear out data that has been entered in that section
- [x] Only show user the message if data has been entered in the corresponding section

**Comment by colinpmacarthur** [comment]
Good idea!

If I:
1. Select "Yes" on one of these form sections
2. Enter text in the subsequent fields
3. Then delete it all
4. Then select "No"
5. I still receive the warning.

Is that the intended functionality? I think it would be a bit better if the warning didn't trigger if all  the fields were empty, but I'm open to other thoughts.

**Comment by bmallred** [comment]
We don't have that capability at the moment but will be built in. When an accordion is rendered it fills the first **X** amount of items with their default properties. There is discussion on tracking this but unsure of implementation yet.

**Comment by bmallred** [comment]
Related conversation at https://github.com/truetandem/e-QIP-prototype/issues/1314#issuecomment-314437232

**Comment by billy22g** [comment]
Calling this complete and entered #1605. cc: @bmallred and @colinpmacarthur
