### ISSUE TITLE
Remove Add Another button from top-level accordion

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1465]
As an eApp user I do not want to see the extra "add another..." button at the bottom of a top level accordion so that I have one clear way to add another section to the accordion.

Acceptance Criteria 
- [x] For top-level accordions remove the "add another" button
- [x] for accordions within an accordion, need to keep the "add another" button

**Comment by lauraponce** [comment]
Looks good! Accordions within accordions (such as your history) still have the add another and the top level accordions (such as criminal history) no longer have the add another.
