### ISSUE TITLE
Add save button on form

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1466]
As an eApp applicant I want to have a save button available to me even though there is an auto-save occurring, so that if I am ready to leave the form before auto-save has executed I can save my progress. 

Acceptance Criteria
- [x] Follow storyboard in #1306 
- [x] When user clicks save, save action is executed

**Comment by colinpmacarthur** [comment]
Seems like this functionality has been squared implemented, but there's some new ongoing work about the design in https://github.com/truetandem/e-QIP-prototype/issues/1535. Should we leave this one open for until those modifications are made? Or close it and open a separate issue for the modifications? @billy22g

**Comment by billy22g** [comment]
I'm good with closing this, and as you noted there are already separate issues for the enhancements.
