### ISSUE TITLE
Storyboard link back to the form information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1467]
As an eApp applicant I would like to see a link on the eApp web form to go back to the form information section so that I can reference information in that section after I've logged in. 

Acceptance Criteria
- [x] Create a storyboard showing where the link will be located
- [ ] Approval of storyboard by stakeholders

**Comment by Jay-Neighbours-I72** [comment]
I'm thinking we keep this simple and place it next to Logout. 

It won't interfere or take space away from main navigation but will be easy to access at the same time.

![e-app-instructions-link](https://user-images.githubusercontent.com/19935974/27706781-d7fb1a82-5ce0-11e7-8fe8-118a0fdd00f8.jpg)
