### ISSUE TITLE
Storyboard Physical Traits

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#147]
As an eApp designer I want to derive a design concept that illustrates the selection style concepts for physical traits: height, weight, hair color, eye color, and sex to promote ease of use for users entering the data on the form and so that the programmers can build a prototype that represents the design concept, and users can test the prototype to validate, or challenge, the design decisions.

Acceptance Criteria
- Create a Storyboard utilizing the current design standards representing the physical trait form fields 
- Provide selection design concepts for height, weight, eye color, hair color, and sex
- Review the storyboard/comp with the Product Owner
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-sections-6-v4-1](https://cloud.githubusercontent.com/assets/19935974/21620252/73421c94-d1c1-11e6-9171-e77e3717b51e.jpg)
![e-qip-comp-sections-6-v4-2](https://cloud.githubusercontent.com/assets/19935974/21620253/73484114-d1c1-11e6-8189-4f0ffe5ac81d.jpg)
![e-qip-comp-sections-6-v4-3](https://cloud.githubusercontent.com/assets/19935974/21620254/73493060-d1c1-11e6-8bea-b4a7786514cc.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-sections-6.pdf](https://github.com/truetandem/e-QIP-prototype/files/683058/e-QIP-comp-sections-6.pdf)

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-section-6-v5-1](https://cloud.githubusercontent.com/assets/19935974/21655925/efe7be8e-d289-11e6-967f-0290cd446606.jpg)
![e-qip-comp-section-6-v5-2](https://cloud.githubusercontent.com/assets/19935974/21655927/efef56a8-d289-11e6-8335-28945e3dfee0.jpg)
![e-qip-comp-section-6-v5-3](https://cloud.githubusercontent.com/assets/19935974/21655926/efee7f4e-d289-11e6-807a-1db6de80c35d.jpg)
[e-QIP-comp-section-6-V5.pdf](https://github.com/truetandem/e-QIP-prototype/files/685656/e-QIP-comp-section-6-V5.pdf)
