### ISSUE TITLE
Menu and section discrepancy

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1484]
I noticed there is a discrepancy in the menu under Your History:  "Where have you lived"  and the corresponding section header "Where you have lived".  I believe the latter is what should use for both.

![image](https://user-images.githubusercontent.com/12962390/27517172-e5741f22-5995-11e7-91a9-682e9fffc988.png)

**Comment by bmallred** [comment]
Just to clarify b/c I had to re-read this multiple times and still didn't see it: **The navigation item has "have" and "you" in the wrong order**

**Comment by lauraponce** [comment]
Looks good!
