### ISSUE TITLE
Need CSS classes to identify Where you have lived form elements

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1485]
In the "Where you have lived" section, if you have an address that is within 3 years of the current date, additional fields appear for contact information of a neighbor who knows you at this address.  

While writing feature specs for this section, the additional address fields and date of last contact fields collide with the date and address of the residence.  Currently there is no way to use a CSS selector to differentiate between the fields, which makes writing a feature spec test very difficult and fragile.

Requesting CSS classes to identify the following field groups in "Where you have lived":
- Provide date of last contact  
- Provide street address for this person (including apartment number).

**Comment by billy22g** [comment]
@pjsumm I'm going to let you have the final 👍 on this one, since it was very specific to the specs you were working on.

**Comment by pjsumm** [comment]
This was completed the next day (6/26).  The Where you have lived feature spec is completed because this is fixed.
