### ISSUE TITLE
Storyboard Navigation Responsiveness

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#149]
As an eApp designer I want to prepare design concepts for eApp form navigation responsiveness so that I can derive a comprehensive design that is scalable/optimized at all device levels: Desktop, Tablet, and Mobile. 

Acceptance Criteria
- Adheres to web design standards and conforms to the overall eApp style
- Reviewed by the Product Owner
- Accepted by the Product Owner

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-small-screen-nav-1](https://cloud.githubusercontent.com/assets/19935974/21620213/4b9df618-d1c1-11e6-9cc4-71a863fa402d.jpg)
![e-qip-small-screen-nav-2](https://cloud.githubusercontent.com/assets/19935974/21620214/4ba40512-d1c1-11e6-9c33-990c6fb91d86.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-small-screen-nav.pdf](https://github.com/truetandem/e-QIP-prototype/files/683055/e-QIP-small-screen-nav.pdf)

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-small-screen-nav-v2-1](https://cloud.githubusercontent.com/assets/19935974/21655895/d2a3839e-d289-11e6-9ca7-9c185817edba.jpg)
![e-qip-small-screen-nav-v2-2](https://cloud.githubusercontent.com/assets/19935974/21655894/d2a31eea-d289-11e6-8efd-d9736d0b56ff.jpg)
[e-QIP-small-screen-nav-V2.pdf](https://github.com/truetandem/e-QIP-prototype/files/685652/e-QIP-small-screen-nav-V2.pdf)
