### ISSUE TITLE
Replace Address references with Location component

### ISSUE THREAD

**Issue by floresj** [truetandem/e-QIP-prototype#1491]
Reference discussion:
- [x] Replace Address references with Location component (https://github.com/truetandem/e-QIP-prototype/pull/1477#discussion_r124070259)
- ~~Remove dead code (https://github.com/18F/e-QIP-prototype/pull/75/files/0d3193486a38ff0e55a9ce7a9e5b828eda538a92#diff-489b44d2b1a7219c3893b39868436163R96)~~
- [x] Replace `AddressValidator` references with `LocationValidator`

**Comment by bmallred** [comment]
Don't forget to remove this dead code: https://github.com/18F/e-QIP-prototype/pull/75/files/0d3193486a38ff0e55a9ce7a9e5b828eda538a92#diff-489b44d2b1a7219c3893b39868436163R96

**Comment by floresj** [comment]
Which also reminds me, change `AddressValidator` references to `LocationValidator`.
