### ISSUE TITLE
Form information on login throwing off feature spec tests

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1493]
The form information modal now pops up on login, so when a feature spec test has a successful login, all test fail downstream because the modal is blocking until the user answers. 

![image](https://user-images.githubusercontent.com/12962390/27585441-49ed53ae-5b0a-11e7-8c66-21ee58dc90df.png)

**Comment by bmallred** [comment]
This is as designed, we just need to add a piece on the login part to click **Yes**

**Comment by billy22g** [comment]
LGTM
