### ISSUE TITLE
Help icon placement

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1504]
Multiple usability test users have had issues telling which question the help icon was associated with.

Is it possible to use the original style? 
![e-qip-comp-sections-1-4-v4-5](https://user-images.githubusercontent.com/19935974/27691600-787b1ba8-5cb2-11e7-9619-c37949412f82.jpg)

Positioned to right, immediately after the input and including the subtle left line

cc @lauraponce @bmallred @billy22g @floresj @gabesnyder

**Comment by Jay-Neighbours-I72** [comment]
@colinpmacarthur

**Comment by bmallred** [comment]
So, from memory, I believe we talked about two (2) different adjustments:

 1. Leave the help icon on the right side but move it up to the line with the question instead of the content below the question.
 2. Move the help icon to the left side of the question and offset it so as to not interfere with current alignment(s).

The original design comp which @Jay-Neighbours-I72 posted above had the help icon to the **immediate** right of the content found under the question. After several iterations to achieve this it was found to be unreliable, and thus inconsistent, due to the amount of deviations between complex components as well as rendering for multiple form factors.

**Comment by Jay-Neighbours-I72** [comment]
@lauraponce @colinpmacarthur thoughts?

Should we use the left side style instead?

**Comment by Jay-Neighbours-I72** [comment]
The alternate idea here would be to shift the icon to the left of the inputs.

![screen shot 2017-07-07 at 8 11 13 am](https://user-images.githubusercontent.com/19935974/27957303-eb3e87ee-62eb-11e7-819b-8eeb9bbc0a4e.png)

Since the original idea isn't possible I'm thinking we run with this style @bmallred @floresj

**Comment by colinpmacarthur** [comment]
Thanks for mocking this up, Jay. Do you think that the left-aligned icon is _too_ prominent? Willing to try this in testing, but wonder if Bryan's option number 2 would be better.

**Comment by Jay-Neighbours-I72** [comment]
@colinpmacarthur It does feel a bit heavier on the left side, that was the original reason we decided it was better on the right.

Can you clarify what you mean by Bryan's option number 2?

![screen shot 2017-07-07 at 3 03 42 pm](https://user-images.githubusercontent.com/19935974/27972760-7d726124-6325-11e7-9218-256b50e97cad.png)

^Option 2 there, which I took as moving the help icon to the left of the input which is shown in the screenshot above your comment.

@bmallred Does that screenshot reflect your option 2 or did I misunderstand it?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 yup that was what thinking when i mentioned it

**Comment by Jay-Neighbours-I72** [comment]
@colinpmacarthur are you ok with the help on the left or do you prefer on the far right as it currently is in the prototype?

**Comment by colinpmacarthur** [comment]
Ugh, sorry for confusing things further here. I think I meant to say @bmallred option 1. :( That said, let's test this and see whether the left-hand positioning is distracting.

**Comment by bmallred** [comment]
I'll mock this up real quick (left-side)

**Comment by Jay-Neighbours-I72** [comment]
I'm thinking this one is done.

**Comment by bmallred** [comment]
There is a pending issues for some style alignment at https://github.com/truetandem/e-QIP-prototype/issues/1626

**Comment by colinpmacarthur** [comment]
@bmallred Are you OK calling this one done? (The other issue can be the placeholder for outstanding bug fixes.)

**Comment by lauraponce** [comment]
It seems like the help text area will be getting more attention on https://github.com/truetandem/e-QIP-prototype/issues/1871, and also what have https://github.com/truetandem/e-QIP-prototype/issues/1626 for tracking style changes – I'm going to move this one over to done!
