### ISSUE TITLE
Save icon stretching

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1505]
Looks like as the text under the help icon changes it stretches the icon.

Need to find a solution that keeps this icon consistently the same size and proportions 
<img width="185" alt="screen shot 2017-06-29 at 1 07 19 pm" src="https://user-images.githubusercontent.com/19935974/27700574-07632af4-5ccc-11e7-8e37-2eb6218a5470.png">

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 I'll leave this one for you to drag to complete. I never saw it initially so not 100% sure if I know how to reliably reproduce.

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 bump.

**Comment by colinpmacarthur** [comment]
I did see this problem before and can verify it's been fixed. I'll move to done.
