### ISSUE TITLE
Citizenship - Naturalized address block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1506]
- [x] Let's use the new address block style (2 street address lines) everywhere we are asking for a full address.

- [x] Address validation is not triggered when user enters a state (manually, not selecting one from typeahead). This example I used Md - is there a way to trigger this or to change a user entered state to the same state from the typeahead list?

<img width="1009" alt="screen shot 2017-06-29 at 1 12 36 pm" src="https://user-images.githubusercontent.com/19935974/27700904-2bf40a40-5ccd-11e7-9b47-f974785b149a.png">

Also should address on stand alone typeahead :
<img width="975" alt="screen shot 2017-06-29 at 1 27 26 pm" src="https://user-images.githubusercontent.com/19935974/27701424-c9d60c80-5cce-11e7-8f70-4c8c12567ff9.png">

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 You mind checking this one and dragging to complete when 👍 ?

**Comment by Jay-Neighbours-I72** [comment]
looks good to me
