### ISSUE TITLE
Citizenship - Accordion items open on review screen

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1507]
- [x] Passport foreign travel accordion is open on review screen

<img width="1372" alt="screen shot 2017-06-29 at 1 18 12 pm" src="https://user-images.githubusercontent.com/19935974/27701031-93b916b6-5ccd-11e7-9762-fb5c9bee0730.png">
<img width="1349" alt="screen shot 2017-06-29 at 1 18 20 pm" src="https://user-images.githubusercontent.com/19935974/27701030-93b5ace2-5ccd-11e7-87f3-0f46b07c0e99.png">

**Comment by billy22g** [comment]
LGTM
