### ISSUE TITLE
Write spec for "People who know you well"

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1512]
Write the feature specification for the "Relationships" subsection "People who know you well"

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/28134155-1b9bff8e-6710-11e7-8729-07b93021dfe5.gif)

**Comment by colinpmacarthur** [comment]
Read through the spec and it makes sense to me!
