### ISSUE TITLE
Write spec for "Relatives"

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1513]
Write the feature specification for the "Relationships" subsection "Relatives"

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/28136706-aee21bf4-6718-11e7-8cc4-6705aed23b6e.gif)

**Comment by colinpmacarthur** [comment]
Read through the spec and it makes sense to me!
