### ISSUE TITLE
Citizenship - Foreign passports - expiration date

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1514]
- [ ] Need to allow for dates in the future for passport expiration dates

<img width="788" alt="screen shot 2017-06-29 at 2 26 25 pm" src="https://user-images.githubusercontent.com/19935974/27703977-0605c1e8-5cd7-11e7-934a-61d0fcff4f38.png">

**Comment by floresj** [comment]
![selection_348](https://user-images.githubusercontent.com/5938731/28546739-d12a1b6e-7099-11e7-8cf9-5fd15a941ae5.png)

**Comment by billy22g** [comment]
LGTM
