### ISSUE TITLE
Substance use - tabbing skips "No" buttons

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1515]
- [x] Tabbing through form skips the "No" buttons

<img width="1011" alt="screen shot 2017-06-29 at 2 31 58 pm" src="https://user-images.githubusercontent.com/19935974/27704254-ed6c1aa0-5cd7-11e7-969c-3707943c081f.png">
<img width="969" alt="screen shot 2017-06-29 at 2 32 06 pm" src="https://user-images.githubusercontent.com/19935974/27704255-ed6d014a-5cd7-11e7-9ea3-a7d297164aca.png">

**Comment by bmallred** [comment]
This is because they are radio buttons in a group.

**Comment by colinpmacarthur** [comment]
Looks fixed to me!
