### ISSUE TITLE
Implement Sticky Navigation

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1520]
As an eApp user I want the navigation menu to stay on the left side of the screen as I scroll down the form so that I can access the menu if needed.

Acceptance Criteria
- Provide a solution to avoid users needing to scroll all the way back up to navigation.
- Review with stakeholders to approve design
- follow design in #1198

**Comment by billy22g** [comment]
This feels quite jumpy to me, not sure we're there yet. Thoughts @colinpmacarthur, @Jay-Neighbours-I72, and others?

**Comment by Jay-Neighbours-I72** [comment]
I am seeing the jumpy/flashing too, showed Bryan on my screen via hangout just now.

**Comment by bmallred** [comment]
Moving it back to **in progress**. This is what I see on all of my machines: https://youtu.be/iTSqAgJWfIw

**Comment by colinpmacarthur** [comment]
I too am feeling the jumpyness in Chrome on MacOS.

**Comment by bmallred** [comment]
New demo: https://youtu.be/WkOdOUma0sY

**Comment by billy22g** [comment]
@colinpmacarthur @Jay-Neighbours-I72 How are the two of you feeling here? I think this might just be some iterating over time. It feels pretty good to me at the moment, but sometimes frustrating.

**Comment by colinpmacarthur** [comment]
Yesterday's tests were promising; I didn't see as much struggle as I expected. Let's move this to done and revisit it after the testing results come in.

Colin

**Comment by billy22g** [comment]
Great!

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 did capture some of the weird behavior mentioned here in #1627
