### ISSUE TITLE
Validate dates across the form

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1522]
As an eApp applicant I want the SF-86 form to prevent me from entering dates that are not possible given my date of birth so that I do not accidentally put a date that is not possible into the form.

Acceptance Criteria
- work with stakeholders to derive instances where this is needed

**Comment by bmallred** [comment]
Not pointing since these are broken out in to separate tasks and will be ongoing.

**Comment by billy22g** [comment]
Jay is doing these on an ongoing basis. One thing Sheldon brought up is geographic mismatch between where you worked during a certain time compared with where you lived at a certain time.

**Comment by pjsumm** [comment]
Closing issues, as these date validations are already being identified and verified as part of our content verification process.
