### ISSUE TITLE
Storyboard save button refinements

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1524]
As an SF86 user on a phone I want to know where to save the form and when it was last saved so that I feel comfortable my answers are being saved.

As the eAPP designer I want to comp up the save button with the sticky headers so that we can see if this produces any visual problems, too busy, confusing, etc.

_
_
**These stories are specific to a clickable save icon:**
As an SF86 user I want to clearly understand that the save button is clickable and be given feedback so I know to click it and when it has finished saving.

As an SF86 user whose entires are not being saved quickly I want to know when the form is actively saving so that it is clear the form has saved and/or when it is done saving.

_
_
**Acceptance criteria:**
- [x] Mobile comp showing save button location
- [x] Comp to show sticky headers and save button
- [x] Comps to explore "more welcoming" save button and feedback

**Comment by Jay-Neighbours-I72** [comment]
Broke out the question #1535

**Comment by Jay-Neighbours-I72** [comment]
Mobile idea:
<img width="401" alt="e-app-save-v2-mobile" src="https://user-images.githubusercontent.com/19935974/27914608-b9277564-6231-11e7-8de9-8ceb8b170d29.png">

**Comment by Jay-Neighbours-I72** [comment]
**Save button refinements idea 1**:
Much bolder and obvious hover state.
On hover text changes to "Save now" implying the user can click to save.
While saving stroke around circle switches to spinner while saving and text changes to "Saving"

![e-app-save-v2-option-1-0](https://user-images.githubusercontent.com/19935974/27918710-c4e46b26-623d-11e7-9ced-4b9bb7477b69.jpg)
![e-app-save-v2-option-1-1](https://user-images.githubusercontent.com/19935974/27918711-c4e79882-623d-11e7-826f-419f4f2222ce.jpg)
![e-app-save-v2-option-1-2](https://user-images.githubusercontent.com/19935974/27918712-c4e95d8e-623d-11e7-9a88-6b3bd2d427c5.jpg)
![e-app-save-v2-option-1-3](https://user-images.githubusercontent.com/19935974/27918709-c4e32234-623d-11e7-9b12-18635c13bda4.jpg)

**Comment by Jay-Neighbours-I72** [comment]
**Save button refinements idea 1**:
More subtle changes on hover, stronger drop shadow, size increase of blue circle, same text changes as above.
Similar saving animation spinner during save.
 
![e-app-save-v2-option-2-0](https://user-images.githubusercontent.com/19935974/27918846-2c7c2418-623e-11e7-89f9-c90537dacdbd.jpg)
![e-app-save-v2-option-2-1](https://user-images.githubusercontent.com/19935974/27918845-2c6a9c3e-623e-11e7-963b-e19ed20417da.jpg)
![e-app-save-v2-option-2-2](https://user-images.githubusercontent.com/19935974/27918844-2c65c7ae-623e-11e7-9c5e-b3497180afe1.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Both options show the save button in addition to the sticky headers and nav

**Comment by billy22g** [comment]
I *think* I like option 2, but don't feel strongly.

**Comment by billy22g** [comment]
cc: @colinpmacarthur

**Comment by colinpmacarthur** [comment]
I am also a fan of option 2. (Think we talked about this one in other channels, right @Jay-Neighbours-I72?)

**Comment by Jay-Neighbours-I72** [comment]
Yep we did @colinpmacarthur 
2 votes for option 2

**Comment by colinpmacarthur** [comment]
Any objection to me moving this into the done pile, @Jay-Neighbours-I72 ?

**Comment by billy22g** [comment]
Think this is good to move to complete.

**Comment by Jay-Neighbours-I72** [comment]
Would like to hear @adelevie thoughts on this, a lot of the feedback around this was from him.

**Comment by adelevie** [comment]
Sorry to be late to the party here, but I concur with everyone on option #2.

**Comment by Jay-Neighbours-I72** [comment]
Thanks! all good for 2
