### ISSUE TITLE
Save button - clickable?

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1535]
As the eAPP team we want to decide whether or not a clickable save button is necessary so that the form is optimized for users.

**Acceptance criteria:**
- [ ] Button will be clickable
- [ ] Button will not be clickable

We touched on this during review, thoughts one way or the other @billy22g @bmallred @floresj @colinpmacarthur

I am not married to one or the other, I lean towards having it clickable to user's piece of mind and I don't see any negatives.

**Comment by billy22g** [comment]
I'm fine with having it clickable (it currently is today, correct?), but I don't think we need to do any additional callouts there.

The more important piece to me is that we effectively manage the slow saving scenario, whether the save is triggered automatically or manual.

**Comment by Jay-Neighbours-I72** [comment]
Correct, it is currently clickable.

**Comment by bmallred** [comment]
From several previous usability sessions people consistently wanted the "clickable" button. Even though they acknowledged they knew it was automatically saving it was *comforting* to know they can manually trigger the process as well.

**Comment by colinpmacarthur** [comment]
So, @Jay-Neighbours-I72, I've seen your mockups on this one and they look fine to me. Does that mean that this story is done?

**Comment by Jay-Neighbours-I72** [comment]
Sounds like it if we are all good with it remaining clickable.
