### ISSUE TITLE
Foreign activities - Event participation - Yes/No button not working

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1539]
- [x] Yes/No buttons are not working. Clicking doesn't turn them on/off

![screen shot 2017-07-07 at 11 02 45 am](https://user-images.githubusercontent.com/19935974/27963801-16089876-6304-11e7-9f23-c4582b0319ec.png)

**Comment by floresj** [comment]
![selection_349](https://user-images.githubusercontent.com/5938731/28547025-f24063c0-709a-11e7-8f6d-ef09c622ff52.png)

**Comment by bmallred** [comment]
Already was resolved in PR #1613
