### ISSUE TITLE
Navigation Rework Specific Sections

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1551]
As an eAPP user I want intuitively interact with the form navigation so that I can easily locate and go to specific sections.

**Acceptance criteria:**
- [x] Sections with open/close arrows will be content buckets only (not pages)
- [x] Clicking on one of these sections will only open it's sub-sections

**Comment by pjsumm** [comment]
**Reference**
Parent issue: #1500
Individual issues for each section:
#1534 #1533 #1532 #1531 #1530 #1529 #1528 #1527 #1527 #1526 #1525

See related issues for check-in/PR associations

**Comment by colinpmacarthur** [comment]
Working well for all sections!
