### ISSUE TITLE
Foreign business > Foreign national sponsorship > Place of birth

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1553]
Missing State and ZIP Code inputs

![screen shot 2017-07-12 at 8 41 00 am](https://user-images.githubusercontent.com/19935974/28118239-48cb1724-66de-11e7-9e68-3fb59dc58e83.png)
![screen shot 2017-07-12 at 8 41 19 am](https://user-images.githubusercontent.com/19935974/28118244-4bc72abc-66de-11e7-9d09-e680afe56bb9.png)

Thinking something similar to User Place of Birth would work here:

H3 - Provide the place of birth for the sponsored foreign national.
P - This foreign national was born:
Button 1= Outside the United States   Button 2 = In the United States

Button 1 Fields
City
Country

Button 2 Fields
State
ZIP Code

Thoughts? I'm open to other options

**Comment by floresj** [comment]
I think since a person is a foreign national, it's assumed that they were not born in the United States.

**Comment by bmallred** [comment]
Definition from [Wikipedia](https://en.wikipedia.org/wiki/Foreign_national)

> A foreign national is a person who is not a citizen of the host country in which he or she is residing or temporarily sojourning. For example, a foreign national in Canada is someone who is neither a Canadian citizen nor a permanent resident of Canada.

With that said I guess

 1. you may be born in country
 2. renounce your citizenship and become a citizen in another country
 3. try to come back to your birth country?

**Comment by floresj** [comment]
Ahhh yes that case would definitely negate my previous comment. Good call. :+1:

**Comment by floresj** [comment]
Switched the layout used in the Location component to match form.

### Nothing selected
![selection_345](https://user-images.githubusercontent.com/5938731/28546350-597bad68-7098-11e7-8b73-d13391392a00.png)

### US location
![selection_346](https://user-images.githubusercontent.com/5938731/28546352-5bed2720-7098-11e7-8674-008859158025.png)

### International location
![selection_347](https://user-images.githubusercontent.com/5938731/28546353-5f194636-7098-11e7-9a70-a20ef7a0b351.png)

**Comment by colinpmacarthur** [comment]
LGTM!
