### ISSUE TITLE
Accordion help icons duplicating

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1555]
- [x] Help icons from previous accordion items are still visible when new items are open.

![screen shot 2017-07-12 at 9 05 00 am](https://user-images.githubusercontent.com/19935974/28119146-c8523db2-66e1-11e7-85d1-08eb8ab13514.png)

**Comment by bmallred** [comment]
**/me** *shakes fist*

**Comment by floresj** [comment]
You can never have enough help. :sos:

**Comment by billy22g** [comment]
LGTM
