### ISSUE TITLE
Foreign business >Foreign national support > date error text not showing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1557]
- [x] Error text not showing

![screen shot 2017-07-12 at 10 16 29 am](https://user-images.githubusercontent.com/19935974/28122215-88f31eca-66eb-11e7-9adc-501086f3a1bb.png)

![screen shot 2017-07-12 at 10 19 50 am](https://user-images.githubusercontent.com/19935974/28122258-af066220-66eb-11e7-824d-bd7dcb533550.png)

**Comment by floresj** [comment]
Updated:

![selection_344](https://user-images.githubusercontent.com/5938731/28545348-ad432042-7094-11e7-9001-1d4556f058df.png)

**Comment by floresj** [comment]
The address error not showing was resolved with PR #1608.

**Comment by colinpmacarthur** [comment]
Verified the problem's been fixed.
