### ISSUE TITLE
Save button animations

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1560]
Reference #1524

## Mobile

<img width="401" alt="e-app-save-v2-mobile" src="https://user-images.githubusercontent.com/19935974/27914608-b9277564-6231-11e7-8de9-8ceb8b170d29.png">

## Refinements

> More subtle changes on hover, stronger drop shadow, size increase of blue circle, same text changes as above. Similar saving animation spinner during save.
 
### Default
![e-app-save-v2-option-1-0](https://user-images.githubusercontent.com/19935974/27918870-39978656-623e-11e7-9c9d-f235d12f4a2c.jpg)

---
![e-app-save-v2-option-2-0](https://user-images.githubusercontent.com/19935974/27918846-2c7c2418-623e-11e7-89f9-c90537dacdbd.jpg)

### On hover change text to "Save now"
![e-app-save-v2-option-2-1](https://user-images.githubusercontent.com/19935974/27918845-2c6a9c3e-623e-11e7-963b-e19ed20417da.jpg)

### Animation
![e-app-save-v2-option-2-2](https://user-images.githubusercontent.com/19935974/27918844-2c65c7ae-623e-11e7-9c5e-b3497180afe1.jpg)

**Comment by bmallred** [comment]
TODO:

 - [ ] Blue text on hover
 - [ ] Blue text on action
 - [ ] Larger box shadow when active/hover

**Comment by Jay-Neighbours-I72** [comment]
Looks like we are missing the slight increase in size of the blue circle behind the save icon.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 let me know when you have a few to go over this. That wasn't on my list from our last walkthrough.

**Comment by billy22g** [comment]
LGTM
