### ISSUE TITLE
Information about you - phone inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1564]
Your contact info:
- [x] Phone inputs shouldn't have "I don't know" options

![screen shot 2017-07-12 at 1 05 26 pm](https://user-images.githubusercontent.com/19935974/28129915-313e403e-6703-11e7-9d3e-f7725408e460.png)
![screen shot 2017-07-12 at 1 05 53 pm](https://user-images.githubusercontent.com/19935974/28129914-313a08f2-6703-11e7-97e3-1c4aa8af8e2f.png)

**Comment by bmallred** [comment]
So this was built off of this design comp:

![image](https://user-images.githubusercontent.com/697855/28133641-a9e8b716-670e-11e7-8b4b-fe5e643d41e2.png)

Are we saying we need the ability to toggle the visibility of the **I don't know** button?

**Comment by Jay-Neighbours-I72** [comment]
Yes, need the ability to toggle on and off I don't know button.

Some sections do now have the "I don't know" option.

**Comment by bmallred** [comment]
Cool, default is to be **visible** as well (per discussion)

**Comment by bmallred** [comment]
## Without "IDK"

![image](https://user-images.githubusercontent.com/697855/29273337-e8f206b0-80d1-11e7-9bd1-1058fa13bc50.png)

## With "IDK"

![image](https://user-images.githubusercontent.com/697855/29273348-f2b946cc-80d1-11e7-80ca-9c30104aae3b.png)

**Comment by billy22g** [comment]
This makes a lot of sense to me @Jay-Neighbours-I72 why we wouldn't have them on this section. Let's make sure we're thoughtful about which have them and don't, and don't just blindly follow the form. I think you're doing that, just want to reiterate that we should recommend departure from the form if it makes sense to do so.

**Comment by billy22g** [comment]
LGTM
