### ISSUE TITLE
Navigation - top level sections not getting icons

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1565]
- [x] Top level nav items are not getting full icons, only getting the small dots.

![screen shot 2017-07-12 at 1 13 10 pm](https://user-images.githubusercontent.com/19935974/28130438-982608b2-6704-11e7-96f7-0cfbba910226.png)
![screen shot 2017-07-12 at 1 16 34 pm](https://user-images.githubusercontent.com/19935974/28130436-98147656-6704-11e7-81c7-d7b13552ac13.png)

**Comment by bmallred** [comment]
![image](https://user-images.githubusercontent.com/697855/28134360-bee427a2-6710-11e7-8918-689f6d8de659.png)

**Comment by billy22g** [comment]
LGTM
