### ISSUE TITLE
Accordion second line cut off

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1571]
- [x] On accordion items that get a second line, the second person is cutting cut off (the bottom of the text)

**Question...** is this still necessary? The accordion has evolved a lot since it was put in. We lost the ability to link straight to that second item.

I'm questioning it's usefulness.

<img width="1264" alt="screen shot 2017-07-13 at 3 20 59 pm" src="https://user-images.githubusercontent.com/19935974/28183892-3acab4a2-67df-11e7-87f3-09c7a98802c3.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 does this still have a pulse?

**Comment by bmallred** [comment]
![image](https://user-images.githubusercontent.com/697855/29578134-30635574-873c-11e7-8f9e-d42a12ec1513.png)

**Comment by Jay-Neighbours-I72** [comment]
looks good!

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 What did you decide here about the usefulness?

**Comment by Jay-Neighbours-I72** [comment]
@billy22g Bryan and I chatted a bit about it.

I don't think it is extremely useful for the Where you have lived - person who knows you.

I do think it is useful in the School - Diploma and Where you have worked - additional period of work. Those two I'm thinking will be useful for people to at a glance see that they entered a diploma or another work period. 

I'm also thinking we should test this full section again at some point to see how user's react to it.

Thoughts?

**Comment by colinpmacarthur** [comment]
(My 2 cents: I agree with Jay, although it's a little weird to have 2 line accordion headers in some places and not others. Definitely want to test with users.)

**Comment by billy22g** [comment]
Concur about testing. How are you tracking what you intend to test with @myukna72? If you're good to go, so am I and please close and drag to complete.

**Comment by myukna72** [comment]
@billy22g I'd like to catch up with @colinpmacarthur on this today.

**Comment by lauraponce** [comment]
I'm just getting caught up on this thread, @myukna72 is this something you had a chance to go over with @colinpmacarthur at this point yet, or would you like to sync up about it today?

**Comment by myukna72** [comment]
@lauraponce not yet. Lets discuss today. I've been following the thread as well, and was going to bring up in our meeting about whats due for the next round of testing.

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 @lauraponce Bumping. Did we make a decision on whether this is necessary or not?

**Comment by Jay-Neighbours-I72** [comment]
@billy22g @lauraponce We are planning another full test of the history section at some point. Maybe next round.

How do we feel about closing this issue and re-opening depending on that sessions finding?

**Comment by billy22g** [comment]
As long as we don’t lose the memory, I’m totally cool with that.

**Comment by Jay-Neighbours-I72** [comment]
I'm confident we won't. Closing now.
