### ISSUE TITLE
Write spec for "Dual/Multiple Citizenship"

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1581]
Write the feature specification for the "Citizenship" subsection "Dual/Multiple Citizenship"

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/28546588-3cc87f1a-7099-11e7-9ffd-880ebca43ff3.gif)

**Comment by billy22g** [comment]
LGTM
