### ISSUE TITLE
Place of Birth - error message not showing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1584]
Error message not showing for place of birth

<img width="1212" alt="screen shot 2017-07-18 at 1 22 43 pm" src="https://user-images.githubusercontent.com/19935974/28330645-557717ec-6bbc-11e7-9cf8-6d3312473ed7.png">

Update: Looks like this is form wide

**Comment by billy22g** [comment]
LGTM
