### ISSUE TITLE
Help icons pushing inputs in

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1585]
Around 1380px breakpoint the help icons are shifting to the right and pushing inputs around/overlapping items

<img width="808" alt="screen shot 2017-07-18 at 2 45 27 pm" src="https://user-images.githubusercontent.com/19935974/28334153-3dbfaaf4-6bc8-11e7-92df-05824182d739.png">
<img width="765" alt="screen shot 2017-07-18 at 2 45 42 pm" src="https://user-images.githubusercontent.com/19935974/28334154-3dc882be-6bc8-11e7-857c-1ef515a273fc.png">

**Comment by billy22g** [comment]
LGTM
