### ISSUE TITLE
Marital status - one document type - headline to label 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1586]
Change the following to labels instead of headlines:

- [x] Born Abroad to U.S. Parents: (remove :)
- [x] Naturalized: (remove :)
- [x] Derived
- [x] Not a U.S. Citizen
- [x] Other

<img width="777" alt="screen shot 2017-07-18 at 2 53 09 pm" src="https://user-images.githubusercontent.com/19935974/28334401-02fe48e8-6bc9-11e7-8c2f-8f7ac1617bc5.png">

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Here's what the updates look like:

![selection_342](https://user-images.githubusercontent.com/5938731/28538669-0973903a-707d-11e7-9219-7075da8932c6.png)

Cool?

**Comment by Jay-Neighbours-I72** [comment]
Ultra cool

**Comment by billy22g** [comment]
LGTM
