### ISSUE TITLE
Verify dual/multiple citizenship and foreign passport information

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1595]
Verify the dual/multiple citizenship and foreign passport information portion of the eApp form (section 10 in SF-86 PDF). Equates to 1/4 of a page in the SF-86.

Include these sections in the verification:
- [x] Do you now or have you EVER held dual/multiple citizenships?
- [x] Have you EVER been issued a passport (or identity card for travel) by a country other than the U.S.?

**Comment by Jay-Neighbours-I72** [comment]
Dual/Multi citizenship:
Content issues #1641 #1642 #1643 
No help text needed
No error text needed #1644

**Comment by Jay-Neighbours-I72** [comment]
Foreign passport:
No content issues
PR submitted for help text
No error text needed
Validation issue #1654

**Comment by Jay-Neighbours-I72** [comment]
Will review when changes are live

**Comment by billy22g** [comment]
LGTM
