### ISSUE TITLE
Estimated date clarification

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1598]
As a user I want to understand how to use the "Estimated" check box on date fields work so that I can accurately input my dates/date range.

To do:
- [x] Do not validate day on dates with an estimated check box.

**Comment by bmallred** [comment]
## TODO:

 - [ ] Don't change value if one is present

**Comment by colinpmacarthur** [comment]
Looks great! 

An interesting question: What should happen with the validation when you click "Estimated" and haven't entered a date? Right now, an empty day box gets green checkbox, which seems a bit weird. Should we not do the instant validation until the Month or Year are entered?

**Comment by bmallred** [comment]
Every element is individually validated as well as validated as a whole when necessary. That is why when you go to DOB and just click "Estimated" you have the day populated with a green validation mark while month and year are still in a neutral state.

![image](https://user-images.githubusercontent.com/697855/29298802-69f19954-8138-11e7-8be2-ee9a65cbabc2.png)

@colinpmacarthur is this not what you see?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 @colinpmacarthur What needs to be changed for this to go back in to review?

**Comment by colinpmacarthur** [comment]
Ack, sorry! This one fell off my radar. Let's move this one into done for now. We'll see whether usability testing picks up problems with it.

**Comment by bmallred** [comment]
Cool, thanks for the quick follow up!
