### ISSUE TITLE
Marital - Margin missing after place of birth input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1601]
- [ ] Need space after place of birth

<img width="875" alt="screen shot 2017-07-19 at 3 50 41 pm" src="https://user-images.githubusercontent.com/19935974/28386686-51c87d82-6c9a-11e7-9aa1-b00ff29ee3f5.png">
<img width="884" alt="screen shot 2017-07-19 at 3 50 46 pm" src="https://user-images.githubusercontent.com/19935974/28386687-51cefd2e-6c9a-11e7-84ab-02b8e9e2f8a5.png">

**Comment by billy22g** [comment]
LGTM
