### ISSUE TITLE
Marital - Significant other - other names used - add "n/a" button

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1602]
Marital - Married - Other names uses:
- [ ] Add missing "Not Applicable" button other other names used input

<img width="1014" alt="screen shot 2017-07-19 at 4 05 32 pm" src="https://user-images.githubusercontent.com/19935974/28387227-44150780-6c9c-11e7-8851-def63b0d6571.png">
![screen shot 2017-07-19 at 4 06 39 pm](https://user-images.githubusercontent.com/19935974/28387228-45371e1e-6c9c-11e7-836a-eedf0cb3b713.png)

**Comment by Jay-Neighbours-I72** [comment]
ahhhhh i see.

i think we can resolve this by shifting some headline sizes. want to walk through via hangout?

**Comment by floresj** [comment]
Making this use the branch collection like you proposed in #1587 I think resolves this issue because the user will be able to click no if OtherName information is NA.

**Comment by Jay-Neighbours-I72** [comment]
ahhhhhh i see.. that could work

try that and we can revisit

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Leaving this one for you.

**Comment by Jay-Neighbours-I72** [comment]
@floresj point was good, it did resolve this for me
