### ISSUE TITLE
Left alignment is off in content area

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1606]
This seems like it may have to do with screen size too.

<img width="559" alt="screen shot 2017-07-21 at 10 52 39 am" src="https://user-images.githubusercontent.com/5091167/28473653-d317eb20-6e02-11e7-8793-42e965613a94.png">

**Comment by Jay-Neighbours-I72** [comment]
Duplicate of #1585

I believe it will be resolved once that one is closed.

**Comment by billy22g** [comment]
LGTM
