### ISSUE TITLE
School Name help text

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1610]
School name help text not rendering in "Where you went to school"

<img width="693" alt="screen shot 2017-07-24 at 9 19 51 am" src="https://user-images.githubusercontent.com/5091167/28530511-543995fa-7051-11e7-94f4-02327d981cab.png">

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/28682098-b55b7950-72c9-11e7-9348-575cea026f44.png)

**Comment by billy22g** [comment]
@DBrenenborg What did you say the help text *should* be here?

**Comment by bmallred** [comment]
![image](https://user-images.githubusercontent.com/697855/28724429-f65ba8da-7387-11e7-8eb2-43c465064693.png)

It appears the help text was for the **school address**. Should we leave the **school name** help text as is and update the **school address**?

cc: @billy22g  @Jay-Neighbours-I72 @DBrenenborg @colinpmacarthur

**Comment by Jay-Neighbours-I72** [comment]
I'd say the school name doesn't need any help text.

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Sounds ok to me, but a bit ambivalent because this was something Drew raised specifically. Would you mind bringing that up directly with Drew and seeing if that makes sense to him?
