### ISSUE TITLE
Financial record - bankruptcy - error message not showing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1623]
- [x] Discharge date error message not showing

<img width="1150" alt="screen shot 2017-07-26 at 8 57 10 am" src="https://user-images.githubusercontent.com/19935974/28621902-7e7d7594-71e0-11e7-9888-355ec0a9f193.png">

**Comment by floresj** [comment]
This was resolved in PR #1614 which affected components enclosed in a `NotApplicable` component.

![selection_357](https://user-images.githubusercontent.com/5938731/28622209-b669743e-71e1-11e7-854d-af2eb32177d8.png)
