### ISSUE TITLE
Input selected - can't type over

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1624]
- [x] When input text is selected it can't be typed over. It adds the text to the end or the next field

This should function like regular text, ex highlighting it and typing will replace the text

<img width="1150" alt="screen shot 2017-07-26 at 8 57 10 am" src="https://user-images.githubusercontent.com/19935974/28622325-26a67b48-71e2-11e7-8f5f-a68d1aafb3c0.png">

**Comment by bmallred** [comment]
This is caused by the autotabbing capabilities. Need to check a few special properties testing if a selection is present:

```js
const hasSelection = input.selectionEnd - input.selectionStart !== 0
```

If the `hasSelection` is `true` then we need to let the natural flow fall through.

**Comment by colinpmacarthur** [comment]
Verified fixed!
