### ISSUE TITLE
Address block - APO carries over into city

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1625]
User switches to APO/FPO address
User clicks APO
User switches back to in US or outside US and "APO" text is input in the city field

<img width="847" alt="screen shot 2017-07-26 at 9 10 46 am" src="https://user-images.githubusercontent.com/19935974/28622403-606672e8-71e2-11e7-8775-a87a583c250c.png">
<img width="893" alt="screen shot 2017-07-26 at 9 10 50 am" src="https://user-images.githubusercontent.com/19935974/28622401-603c19bc-71e2-11e7-8223-9c8f6fdd89d7.png">
<img width="839" alt="screen shot 2017-07-26 at 9 10 53 am" src="https://user-images.githubusercontent.com/19935974/28622400-60356630-71e2-11e7-8c70-c47562cca83b.png">

**Comment by bmallred** [comment]
This is only going to clear the `city` value when both coming **from** APO/FPO and going **to** something else. Setting the city name in the United States address block will carry over to the International address block.

cc: @Jay-Neighbours-I72

**Comment by billy22g** [comment]
LGTM
