### ISSUE TITLE
Help icons off center

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1626]
1380px and below - help icons are off center

- [ ] Keep them vertically centered

<img width="1380" alt="screen shot 2017-07-26 at 9 23 50 am" src="https://user-images.githubusercontent.com/19935974/28623498-2952541e-71e4-11e7-8046-b186c047a9fd.png">

**Comment by bmallred** [comment]
Closing this issue since help icons have been moved again.
