### ISSUE TITLE
Discharged yes/no - too much margin below

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1628]
Reduce the margin above the "Provide details"

Current
<img width="937" alt="screen shot 2017-07-26 at 9 32 30 am" src="https://user-images.githubusercontent.com/19935974/28624086-f55c0766-71e5-11e7-9ce5-0de8066b0db2.png">

Desired
<img width="781" alt="screen shot 2017-07-26 at 9 40 30 am" src="https://user-images.githubusercontent.com/19935974/28624222-79fc8dba-71e6-11e7-9cf6-3436978639a7.png">

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/28684975-5699c308-72d4-11e7-8dce-8799aa014149.png)

**Comment by billy22g** [comment]
LGTM
