### ISSUE TITLE
Location blocks - city then state

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1629]
- [x] On all location blocks City should come before state

<img width="1332" alt="screen shot 2017-07-26 at 9 56 08 am" src="https://user-images.githubusercontent.com/19935974/28624925-bc9f9d72-71e8-11e7-9121-1eb2e1e3d41f.png">

**Comment by colinpmacarthur** [comment]
LGTM!
