### ISSUE TITLE
Marital - need option for "married"

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1630]
Action item:
- [x] Add an button - Currently in a civil marriage"

Currently there is no option for "Married"

@billy22g do you have more direction on this? 
Are we adding another choice to the form? Reworking one of the existing choices?

<img width="884" alt="screen shot 2017-07-26 at 9 59 17 am" src="https://user-images.githubusercontent.com/19935974/28625058-21b3960a-71e9-11e7-9bd2-8f8a84a3b7fb.png">

![screen shot 2017-07-26 at 9 59 40 am](https://user-images.githubusercontent.com/19935974/28625181-6bc02592-71e9-11e7-8a01-aaf968f2fcc2.png)

**Comment by billy22g** [comment]
Yes. Per an email from Drew a few months back, there should be an additional option, "Currently in a civil marriage" and we should track it in the content tracking doc as a departure/recommended change to the content guide. @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
Tracked in the doc, will update with screenshot once it is in the prototype

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 are we appending this to the text of the top-left button or is this a new button altogether?

If it is a new button, what behavior should it have for the branching?

**Comment by billy22g** [comment]
@bmallred The branching should correspond to the PDF branch portion, which *is* actually correct. The "Branch, If in a Marriage, civil union..."

This is a new button.

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/28679936-b98e1e58-72c2-11e7-974e-afd35823f020.png)

**Comment by colinpmacarthur** [comment]
Great!
