### ISSUE TITLE
Typeahead - hover/select on first item in list when typing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1632]
- [x] Type ahead inputs should auto select/complete with the first item in the list

This way when user hits enter their desired input will be used. Currently the input is chopped early and the desired selection isn't made.

<img width="958" alt="screen shot 2017-07-26 at 10 09 44 am" src="https://user-images.githubusercontent.com/19935974/28625550-9b265792-71ea-11e7-807f-42059b2216f5.png">

<img width="485" alt="screen shot 2017-07-26 at 10 10 22 am" src="https://user-images.githubusercontent.com/19935974/28625568-aa26af1c-71ea-11e7-8e63-6a62cba855e1.png">

**Comment by lauraponce** [comment]
This appears to be working now and hitting enter autofills the field with the first entry.
