### ISSUE TITLE
Address block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1633]
Weird issues with the USPS validation:

Asks for more specific info
User put in "B" for apt number
Still asked for more info and didn't suggest adding "Apt"
Manually added "Apt" and it verified

Any thoughts here? Can we control any of this?

<img width="889" alt="screen shot 2017-07-26 at 10 13 31 am" src="https://user-images.githubusercontent.com/19935974/28625819-58ef7bb4-71eb-11e7-844f-d3232223cd27.png">
<img width="948" alt="screen shot 2017-07-26 at 10 13 44 am" src="https://user-images.githubusercontent.com/19935974/28625818-58ee54aa-71eb-11e7-860e-0f79f1ff0062.png">
<img width="838" alt="screen shot 2017-07-26 at 10 13 48 am" src="https://user-images.githubusercontent.com/19935974/28625816-58e79390-71eb-11e7-9c9b-a0f1690e1a17.png">
<img width="901" alt="screen shot 2017-07-26 at 10 14 02 am" src="https://user-images.githubusercontent.com/19935974/28625817-58ee9834-71eb-11e7-9e78-d2f30eef176c.png">

**Comment by pjsumm** [comment]
This is how the USPS web service works unfortunately.  Closing
