### ISSUE TITLE
Placeholder text confusing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1634]
Users were confused with specific placeholder text.

No specific examples should be given. ex. "$1000" . Users thought this was already entered.

- [x] For dollar figures let's use "0"
- [x] Dates lets use "0000"
- [x] Placeholder text should disappear when user clicks into the input (any time input is active/focus there should be no placeholder text visible)

<img width="792" alt="screen shot 2017-07-26 at 10 16 09 am" src="https://user-images.githubusercontent.com/19935974/28625951-b6b66c30-71eb-11e7-8e52-3be8ab6175d8.png">
<img width="814" alt="screen shot 2017-07-26 at 10 16 22 am" src="https://user-images.githubusercontent.com/19935974/28625952-b6b7447a-71eb-11e7-83c7-040bd05ccd01.png">
<img width="758" alt="screen shot 2017-07-26 at 10 16 45 am" src="https://user-images.githubusercontent.com/19935974/28625953-b6b8c96c-71eb-11e7-9442-4b5f5040a509.png">

**Comment by billy22g** [comment]
Hmm...I tend to think "0" for the dollar placeholder text is also a bit confusing.

**Comment by colinpmacarthur** [comment]
LGTM!
