### ISSUE TITLE
People who know you well - counter incorrect

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1635]
Counter shows 1/3 people added upon arriving at the page and not yet having entered anyone.

<img width="763" alt="screen shot 2017-07-26 at 10 24 16 am" src="https://user-images.githubusercontent.com/5091167/28632114-b10a7366-71ec-11e7-9619-d24371f18192.png">

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Should we only add to the people counter once all the information for a particular row item is valid?

**Comment by Jay-Neighbours-I72** [comment]
I'd say after the full accordion item is complete

**Comment by billy22g** [comment]
I second Jay's recommendation. We should also be consistent in terms of how we treat counters. @Jay-Neighbours-I72 Would you mind taking a look at them at your convenience to ensure anytime we're counting up (for coverage period, number of degrees/diplomas, number of people you know, etc.) it's a consistent and intuitive experience?

**Comment by Jay-Neighbours-I72** [comment]
Residence and Work history are also counting after year is input only.
School counter wasn't working: #2160

@floresj 
- [ ] Goal is to have all counters only update after accordion item is complete

**Comment by lauraponce** [comment]
This is working as expected now, the counter goes to 1 as soon as the last input for the accordion element (address) is added.
