### ISSUE TITLE
Accordions should be closed upon coming back to same screen

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1639]
**What did you do?**
Entered multiple accordion items
Left the page
Came back to the page
Saw all of the accordions open

They should be closed when you leave and come back (e.g. Where you've lived, employment, where you went to school, etc.)

**Comment by floresj** [comment]
Issue #1321 is still opened describing this behavior. We'll need to take a closer look to see how persistence and other conditions affect the way accordions behave. We just haven't tackled it yet.
