### ISSUE TITLE
Dual/multi citizenship - missing headline

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1641]
- [ ] Put in missing headline after country of citizenship - "During what period of time did you hold citizenship with this country?" - will be an H2

current
<img width="1212" alt="screen shot 2017-07-26 at 2 25 12 pm" src="https://user-images.githubusercontent.com/19935974/28637196-b28b4932-720e-11e7-84d2-1bb13ba8f60a.png">

![screen shot 2017-07-26 at 2 25 18 pm](https://user-images.githubusercontent.com/19935974/28637198-b3dc53a8-720e-11e7-9156-1144a7c5cdaf.png)

with new headline
<img width="1225" alt="screen shot 2017-07-26 at 2 27 32 pm" src="https://user-images.githubusercontent.com/19935974/28637204-b6cd9cac-720e-11e7-85e9-442edc828da9.png">

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/28682565-740e2e6e-72cb-11e7-9b3e-205e5b591d09.png)

**Comment by colinpmacarthur** [comment]
LGTM!
