### ISSUE TITLE
Dual/Multi citizenship - Present Current branch

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1642]
This question:
Do you currently hold citizenship with this country?

Looks like it should only be visible when the date range is present/current.

<img width="1219" alt="screen shot 2017-07-26 at 2 31 59 pm" src="https://user-images.githubusercontent.com/19935974/28637403-68842466-720f-11e7-8f89-65c0e56c4cfc.png">

![screen shot 2017-07-26 at 2 33 43 pm](https://user-images.githubusercontent.com/19935974/28637417-706b0d2a-720f-11e7-9689-d8e7a14ac64a.png)

**Comment by Jay-Neighbours-I72** [comment]
@billy22g Both Bryan and I took this to mean the branch is only visible when "Present" is selected for the to date.

Does that seem right to you?

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Yes, that's correct. Still a very strange question, should be implied that you still hold it if the end date is present, but c'est la vie.

**Comment by colinpmacarthur** [comment]
@billy22g: Could you take a look? I think this has been fixed, but I'm worried I'm not looking for the right thing.

**Comment by billy22g** [comment]
LGTM. This still seems like a silly question. If they've answered that they held the citizenship through "Present," it makes no sense to ask them whether they currently hold it. Moving to complete and emailing @Sheldon1013 and @DBrenenborg to find out whether they'd like to suggest removing this question.

**Comment by billy22g** [comment]
Per @DBrenenborg via email:

> This question cannot be removed.  The content guide has an error.  It should be if NOT present/current.

So the change in behavior is that if they have *NOT* selected present, we ask them whether they currently hold this citizenship and to explain.

cc: @bmallred @colinpmacarthur @Jay-Neighbours-I72
