### ISSUE TITLE
Dual/Multi citizenship - last 2 questions - explanations

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1643]
Looks like both of the last 2 questions in the accordion should have "Provide explanation" inputs for both yes and no answers.

<img width="917" alt="screen shot 2017-07-26 at 2 34 43 pm" src="https://user-images.githubusercontent.com/19935974/28637480-b03829ba-720f-11e7-92e2-fc7e82c5f7b1.png">

![screen shot 2017-07-26 at 2 35 48 pm](https://user-images.githubusercontent.com/19935974/28637495-bb102676-720f-11e7-8383-48fb8857cb72.png)

**Comment by bmallred** [comment]
I'll make the change, but I could've sworn we made this behave this way on purpose.

**Comment by bmallred** [comment]
Checked with @Jay-Neighbours-I72 and verified both explanation fields are required.

**Comment by colinpmacarthur** [comment]
LGTM!
