### ISSUE TITLE
Buttons - can't deselect

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1656]
On my Chrome and Safari buttons can't be deselected.

Clicking them again doesn't remove the selection.

<img width="960" alt="screen shot 2017-07-28 at 2 15 28 pm" src="https://user-images.githubusercontent.com/19935974/28730752-4f181622-739f-11e7-8c01-280726819838.png">

**Comment by Jay-Neighbours-I72** [comment]
suffix and phone number time are working now.

- [ ] can't deselect relationship type
![screen shot 2017-12-20 at 1 47 44 pm](https://user-images.githubusercontent.com/19935974/34223197-6efdad80-e58c-11e7-88f2-d865f416d298.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I'm able to deselect these on the **dev** environment. May need to get with you to try and reproduce!

**Comment by Jay-Neighbours-I72** [comment]
Working for me now!
