### ISSUE TITLE
Citizenship status - basis of naturalization - other explanation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1657]
- [x] Can we have the explanation box load a "Provide explanation label and multi line input instead of the comment style?

<img width="809" alt="screen shot 2017-07-28 at 3 46 39 pm" src="https://user-images.githubusercontent.com/19935974/28733850-033268fe-73ac-11e7-8195-05fd93bc119d.png">
<img width="916" alt="screen shot 2017-07-28 at 3 46 42 pm" src="https://user-images.githubusercontent.com/19935974/28733851-03434dae-73ac-11e7-8975-d7c0d4a15a68.png">

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/28794292-d5e6cbec-7603-11e7-9d86-0e8f5fd039cd.png)

**Comment by colinpmacarthur** [comment]
LGTM!
