### ISSUE TITLE
Citizenship status - Derived track - certificate date

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1658]
Change "Provide the date the certificate was issued" to "Provide the date the document was issued" to match the PDF

<img width="1019" alt="screen shot 2017-07-28 at 3 53 09 pm" src="https://user-images.githubusercontent.com/19935974/28734034-f3fd9aec-73ac-11e7-8deb-0ee1afcf9ef4.png">
![screen shot 2017-07-28 at 3 53 16 pm](https://user-images.githubusercontent.com/19935974/28734035-f4042dbc-73ac-11e7-827a-c8b42107ed66.png)

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/28793150-14db894a-7600-11e7-866d-57c0110c8867.png)

**Comment by colinpmacarthur** [comment]
Done!
