### ISSUE TITLE
Citizenship status - Not a US citizen track - country and entry fields

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1659]
- [x] Provide your country(ies) of citizenship should come first
- [x] Change "Provide the location of entry into the U.S." to "Provide your place of entry in the U.S."
- [x] Address fields should be City and State only

<img width="836" alt="screen shot 2017-07-28 at 3 57 08 pm" src="https://user-images.githubusercontent.com/19935974/28734146-8606b338-73ad-11e7-9f7b-484ab541abe4.png">

![screen shot 2017-07-28 at 3 58 18 pm](https://user-images.githubusercontent.com/19935974/28734156-957b2948-73ad-11e7-8db8-093860bf9de1.png)

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/28792911-4327857a-75ff-11e7-828c-5a2bfc5b5952.png)

**Comment by colinpmacarthur** [comment]
LGTM!
