### ISSUE TITLE
"Contacts" navigation button

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#1660]
On "Full Name" under section 1, the navigation button says "Contacts." I would recommend it say instead, "Your contact info" or "Contact Information." To the greatest extent possible, we should try to maintain consistency between the navigation titles and the text of the button.

<img width="339" alt="screen shot 2017-07-31 at 9 24 28 am" src="https://user-images.githubusercontent.com/5091167/28785074-8435e232-75d2-11e7-9fda-a53698c82758.png">

**Comment by bmallred** [comment]
Updates...

 - Birth date **=>** Date of birth
 - Birth place **=>** Place of birth
 - Contacts **=>** Your contact information

and removed some old text

## Preview

![image](https://user-images.githubusercontent.com/697855/28791655-24ebacd4-75fb-11e7-8c37-0aeff3c6d729.png)

**Comment by billy22g** [comment]
LGTM. Any issues with it being too much text on the button for mobile?

**Comment by billy22g** [comment]
@bmallred I actually don't see this on staging yet.

**Comment by colinpmacarthur** [comment]
I am seeing this on staging, but wonder whether we should say "Social security number" instead of "SSN" in the navigation hierarchy (so it matches the button). Alternatively, we could retitle the button to "SSN."

**Comment by bmallred** [comment]
Verified it is on staging.

@colinpmacarthur we can do either. The navigation title was taking from the GDoc a long time ago (not sure how up to date it is now). Which is preferred?

**Comment by colinpmacarthur** [comment]
Let's go for `social security number`

**Comment by billy22g** [comment]
💥 Nice! LGTM
