### ISSUE TITLE
Verify substance use alcohol

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1673]
Verify the Use of Alcohol portion of the eApp form (section 24 in SF-86 PDF). Equates to 3/4 of a page in the legacy SF-86.

Include these sections in the verification:
- [x] Negative impact
- [x] Mandatory counseling or treatment
- [x] Voluntary counseling or treatment
- [x] Additional instances

**Comment by Jay-Neighbours-I72** [comment]
Negative impact:
Content issue #1693 
No help/error txt updates needed
Validation #1694

**Comment by Jay-Neighbours-I72** [comment]
Mandatory counseling or treatment:
Content issue #1695
No help/error text updates needed
Validation #1696

**Comment by Jay-Neighbours-I72** [comment]
Voluntary counseling or treatment:
Content issue #1701
Help text tweak #1700
No error text updates needed
Validation #1702

**Comment by Jay-Neighbours-I72** [comment]
Additional instances:
No content issues  |  Bug #1703
Help text tweaks added to #1700
No error text updates needed
Validation #1704
