### ISSUE TITLE
Substance use - usage margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1677]
Too much margin under the Usage question headline.

- [x] Match same margin used elsewhere on the form

Too much margin:
<img width="903" alt="screen shot 2017-08-02 at 2 57 51 pm" src="https://user-images.githubusercontent.com/19935974/28889797-3269ae26-7793-11e7-94fa-83736a318f41.png">

Correct margin:
<img width="791" alt="screen shot 2017-08-02 at 2 57 58 pm" src="https://user-images.githubusercontent.com/19935974/28889803-36f21a82-7793-11e7-9785-32cf3cb6fb80.png">

**Comment by colinpmacarthur** [comment]
✔️
