### ISSUE TITLE
Substance use - Purchase - future use question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1682]
- [x] Let's use the label style for "Provide explanation" on the last question.

<img width="1954" alt="screen shot 2017-08-03 at 9 54 08 am" src="https://user-images.githubusercontent.com/19935974/28925094-d96187aa-7831-11e7-9e09-567b98e8a076.png">

**Comment by bmallred** [comment]
After speaking with @Jay-Neighbours-I72 we are going to apply this application wide as well.

**Comment by colinpmacarthur** [comment]
✔️
