### ISSUE TITLE
Substance use - Mandatory counseling or treatment - provide explanation text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1688]
- [x] Change "Provide explanation" to label style - 2 total locations on this subsection 

<img width="1311" alt="screen shot 2017-08-03 at 2 40 05 pm" src="https://user-images.githubusercontent.com/19935974/28937743-d8ee9a38-7859-11e7-8a90-d347b2bf3cd9.png">
<img width="1298" alt="screen shot 2017-08-03 at 2 40 19 pm" src="https://user-images.githubusercontent.com/19935974/28937744-d8f0323a-7859-11e7-92a1-5a12d5dbfe5d.png">

**Comment by colinpmacarthur** [comment]
✔️
