### ISSUE TITLE
Substance use - Mandatory counseling or treatment - Phone block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1689]
- [x] Looks like we don't need the phone number type here

- [x] Also applies all phone blocks in substance and alcohol use.

<img width="1369" alt="screen shot 2017-08-03 at 2 44 03 pm" src="https://user-images.githubusercontent.com/19935974/28937853-3551d416-785a-11e7-9a1f-896ae654e341.png">

![screen shot 2017-08-03 at 2 43 19 pm](https://user-images.githubusercontent.com/19935974/28937856-366182de-785a-11e7-876f-1251c4db6635.png)

**Comment by colinpmacarthur** [comment]
LGTM!
