### ISSUE TITLE
Substance use - Voluntary counseling or treatment - Provide explanation text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1691]
- [x] Change "Provide explanation" to label style 

<img width="1214" alt="screen shot 2017-08-03 at 2 55 26 pm" src="https://user-images.githubusercontent.com/19935974/28938391-ecd44974-785b-11e7-96b5-126dc2b3d782.png">

**Comment by colinpmacarthur** [comment]
✔️
