### ISSUE TITLE
Use of alcohol - Mandatory counseling or treatment - Provide explanation text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1695]
- [x] Change "Provide explanation" text to label style

<img width="1243" alt="screen shot 2017-08-04 at 11 03 51 am" src="https://user-images.githubusercontent.com/19935974/28974548-c01932ce-7904-11e7-836d-0dd45ced9a88.png">

**Comment by colinpmacarthur** [comment]
✔️
