### ISSUE TITLE
Auto-scroll to prev/next buttons

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1698]
As an eApp applicant, I want clear feedback from the form after selecting “No” at the end of a form section indicating I have no more information to add to that section so that I know what action to take next.

Acceptance Criteria
- [ ]  Suggestion from usability testing:  auto-scroll down to the “Next/Previous” buttons portion of the form after selecting "no"

**Comment by floresj** [comment]
@bmallred I'm thinking of updating `Accordion.jsx` to allow a prop called `onAddendumUpdate(yesNoValue)` to be passed in that gets executed when the bottom yes/no branch is clicked. 

I then noticed that we could leverage `SubsectionElement` to contain a `scrollToSectionButtons()` that scrolls the user down to the bottom section navigation buttons. That way, with the accordions, we can do something like

```jsx
export default class Bankruptcies extends SubsectionElement {

  .. other stuff

  render () {
    return (
      <Accordion
         onAddendumUpdate={this.scrollToSectionButtons}
         ...>
      <Blah />
     </Accordion>
   )
  }
}

Just wanted to get your thoughts.

**Comment by bmallred** [comment]
So this would mean `Accordion.updateAddendum()` would have two callbacks to execute, both `this.props.onUpdate` and `this.props.onAddendumUpdate`?

I'm okay with that I guess or just passing in a CSS selector for scrolling top the bottom similar to how we do it for scrolling up.

**Comment by floresj** [comment]
Ah gotcha :+1: . So inside of accordion, when the no option on addendum is triggered, scroll to passed in css selector.

**Comment by bmallred** [comment]
Well, right now the `scrollTo` is for scrolling **up** to a specific point. If you wanted to pass another selector for scrolling down on selection of **No** in the addendum probably need a name change to `scrollToTop` and/or `scrollToBottom`.

/shrugs

The callback is fine, too.

**Comment by billy22g** [comment]
LGTM!
