### ISSUE TITLE
Use of alcohol - Voluntary counseling or treatment - Provide explanation text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1701]
- [x] Use label style for "Provide explanation" text

<img width="1230" alt="screen shot 2017-08-04 at 1 44 19 pm" src="https://user-images.githubusercontent.com/19935974/28980233-09ae965c-791b-11e7-823e-efe7039b601f.png">

**Comment by colinpmacarthur** [comment]
✔️
