### ISSUE TITLE
Use of alcohol -  Additional instances - "Present" checkbox

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1703]
- [x] Use the "or Present" style from all other date range blocks

<img width="1205" alt="screen shot 2017-08-04 at 2 21 05 pm" src="https://user-images.githubusercontent.com/19935974/28981626-7ad563f6-7920-11e7-817c-e16e4f959fa6.png">

Correct style:
<img width="1255" alt="screen shot 2017-08-04 at 2 21 15 pm" src="https://user-images.githubusercontent.com/19935974/28981634-808bb3a4-7920-11e7-9839-403ca2c4938d.png">

**Comment by colinpmacarthur** [comment]
✔️
