### ISSUE TITLE
Intro - 

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1706]
Is this a yes/no answer to a question or understanding?

Persons completing this form should begin after carefully reading the preceding instructions
I have read the instructions and I understand that if I withhold, misrepresent, or falsify information on this form, I am subject to the penalties for inaccurate or false statement (per U. S. Criminal Code, Title 18, section 1001), denial or revocation of a security clearance, and/or removal and debarment from Federal Service.

Yes Button-No Button

**Comment by Jay-Neighbours-I72** [comment]
Good question.

The PDF form has it as a Yes/No:
![screen shot 2017-09-29 at 1 27 18 pm](https://user-images.githubusercontent.com/19935974/31027900-f9afa4e6-a519-11e7-8d2b-9800e48a90fe.png)

Changing it to "I agree" or "I disagree" or something similar and more clear makes sense to me.

Thoughts @billy22g @pjsumm ?

**Comment by pjsumm** [comment]
I agree.  We should pose the question to Donna for approval.

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 I second Paul's suggestion (with me, Drew, Sheldon, and Paul) on that if it has not already been posed. Apologies for the delay.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 any updates on this one?

**Comment by Jay-Neighbours-I72** [comment]
Forgot to include this in the content tracking doc. Adding now.

**Comment by Jay-Neighbours-I72** [comment]
Tracked in update doc. Per Sheldon leaving this one a Yes/No as is for now.
