### ISSUE TITLE
Section 1 - Full Name - Validation

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1709]
Chrome-Win7
First Name allows continuous spaces + leading space-
Middle Name allows apostrophe for an initial-
(First Middle Last) are interchangeable in regards to issue listed.

Other is selected and contains an Null value with no error or warning.

![image](https://user-images.githubusercontent.com/30842622/29134628-4568f8f2-7d05-11e7-8e94-3eb3ba7dae2b.png)

**Comment by Jay-Neighbours-I72** [comment]
Leading spaces will be removed automatically when form stores in the database.

Blank "Other" input will be flagged on the review screen.
