### ISSUE TITLE
Section 1 - Contact Information - US Phone Number

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1715]
I don't know button selected for primary number with no other number provided. No warning or error given.

**Comment by Jay-Neighbours-I72** [comment]
That I don't know button was there by mistake. It has been removed.

<img width="1181" alt="screen shot 2017-09-29 at 2 51 55 pm" src="https://user-images.githubusercontent.com/19935974/31031130-cde3a9be-a525-11e7-89b8-1a2a2a1c1a83.png">
