### ISSUE TITLE
Section 1 - Contact Information - US Number

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1716]
Once selecting I don't know I was unable to change my mind and enter a contact number.

![image](https://user-images.githubusercontent.com/30842622/29136302-cd9736b2-7d0a-11e7-8595-9e6d450b02bf.png)

**Comment by Jay-Neighbours-I72** [comment]
I am also seeing this on the phone number blocks

 
<img width="1287" alt="screen shot 2017-09-29 at 1 52 55 pm" src="https://user-images.githubusercontent.com/19935974/31028946-e0cc8e72-a51d-11e7-9e37-7056f567da37.png">

**Comment by pjsumm** [comment]
this has been addressed.
