### ISSUE TITLE
Foreign activities - direct control

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1718]
This question "Provide the current value (in U.S. dollars) or the value at the time control or ownership was sold, lost or otherwise disposed of" seems like it should have a "Not applicable" button associated with it. User's may still own the property or interest

On the PDF form it does not.

Thoughts? @colinpmacarthur @billy22g 

<img width="1201" alt="screen shot 2017-08-09 at 2 57 34 pm" src="https://user-images.githubusercontent.com/19935974/29138952-2baa559c-7d13-11e7-9677-a8bd3a6df22b.png">

![screen shot 2017-08-09 at 2 57 27 pm](https://user-images.githubusercontent.com/19935974/29138953-2c6b8a3c-7d13-11e7-83b0-350e708d2958.png)

This field (screenshot below) looks like it should only appear when a date is input above.
<img width="840" alt="screen shot 2017-08-09 at 3 01 26 pm" src="https://user-images.githubusercontent.com/19935974/29139061-a04eb30c-7d13-11e7-8b1c-400be9872809.png">

**Comment by colinpmacarthur** [comment]
I agree with you, Jay. How have we handled this type of issue in the past? Do we run it by Drew?

**Comment by billy22g** [comment]
Yes, we run it by Drew. Jay, feel free to send an email with that to Drew,
and add it to the content changes doc.

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 Did we run this by Drew/Sheldon and add to the content changes? I'm not sure this needs to be in the Icebox, should be a fairly quick resolution.

**Comment by Jay-Neighbours-I72** [comment]
@billy22g 

 We didn't run it by them yet, it fell off my radar.

I think we can wrap this into the meeting we are planning to have with Drew/Sheldon to go through these "Question" tagged issues.

**Comment by billy22g** [comment]
Sounds like a plan @Jay-Neighbours-I72, thanks.

**Comment by bmallred** [comment]
https://user-images.githubusercontent.com/19935974/29139061-a04eb30c-7d13-11e7-8b1c-400be9872809.png

When **not applicable** then do not display the explanation question. May need to capture this change.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred good call, I dropped it into the content tracking doc.

**Comment by bmallred** [comment]
Found a similar case in **indirect control**:

![image](https://user-images.githubusercontent.com/697855/37480563-efc38e1a-2855-11e8-8314-d82dc0421768.png)

**Comment by Jay-Neighbours-I72** [comment]
^That one also tracked in content tracking doc

**Comment by Jay-Neighbours-I72** [comment]
@bmallred can we go through this at some point? I have a couple of questions

**Comment by bpdesigns** [comment]
LGTM
