### ISSUE TITLE
Using the up and down arrows on keyboard switch the yes/no button answers

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1719]
Using the up and arrow buttons on the keyboard toggle the yes/no buttons

Example: a user is using up and down button to scroll and instead of scrolling it switches their answer.

<img width="1106" alt="screen shot 2017-08-09 at 3 41 12 pm" src="https://user-images.githubusercontent.com/19935974/29140777-a6a67ff4-7d19-11e7-8746-f3871afe989b.png">

**Comment by colinpmacarthur** [comment]
LGTM!
