### ISSUE TITLE
Foreign activities - US Passport information - Expiration date

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1725]
- [x] Passport expiration date should allow future dates

<img width="1115" alt="screen shot 2017-08-10 at 1 13 12 pm" src="https://user-images.githubusercontent.com/19935974/29182688-d6fc5732-7dcd-11e7-9759-a1c7f50a1796.png">

**Comment by myukna72** [comment]
Found the same error. Anything past 2016 will through the same error.

**Comment by billy22g** [comment]
LGTM
