### ISSUE TITLE
Section 1 - DOB

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1739]
While the DOB is valid below. The aka section uses date pre DOB.

![image](https://user-images.githubusercontent.com/30842622/29280860-d61ab442-80ea-11e7-9553-26e578f5f018.png)

**Comment by Jay-Neighbours-I72** [comment]
these are working now and will be flagged on the review screen

![screen shot 2018-01-04 at 10 52 50 am](https://user-images.githubusercontent.com/19935974/34571788-76e1a1a2-f13d-11e7-9897-11a2a8f3a548.png)
