### ISSUE TITLE
Section 1 - POB

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1740]
Only supplied State.
No error or warning given that other fields were required.

![image](https://user-images.githubusercontent.com/30842622/29280961-28297b06-80eb-11e7-90ca-fb32a2030d9e.png)

**Comment by Jay-Neighbours-I72** [comment]
Flagged on review screen.

<img width="1145" alt="screen shot 2017-09-29 at 2 42 35 pm" src="https://user-images.githubusercontent.com/19935974/31030740-7571e062-a524-11e7-89d2-61d02708d205.png">
