### ISSUE TITLE
Section 1 - SSN

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1741]
999 99 9999
Is not a valid SSN or allowed to be used.

![image](https://user-images.githubusercontent.com/30842622/29281252-42313a88-80ec-11e7-8c7e-f1ffd9c6f4d7.png)

**Comment by billy22g** [comment]
@Sheldon1013 said he would send the standards for a valid SSN.

**Comment by bmallred** [comment]
## Prior to June 25, 2011

 - Areas: https://www.ssa.gov/employer/stateweb.htm
 - Structure: https://www.ssa.gov/history/ssn/geocard.html

## As of June 25, 2011

  - Randomization: https://www.ssa.gov/employer/randomization.html

**Comment by billy22g** [comment]
LGTM
