### ISSUE TITLE
Verify investigations and clearance record

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1764]
Verify the **Investigation and Clearance Record** portion of the eApp form (section 25 in SF-86 PDF). Equates to 1/2 of a page in the legacy SF-86.

Include these sections in the verification:
- [x] Ever been investigated
- [x] Denied
- [x] Debarment

**Comment by Jay-Neighbours-I72** [comment]
Ever been investigated:
No content issues Bug #1800
Help text tweaked
No error text needed
Validation #1801

**Comment by Jay-Neighbours-I72** [comment]
Denied:
Small spelling error fixed
Help text tweaked
No error text needed
Validation #1811

**Comment by Jay-Neighbours-I72** [comment]
Debarment:
No content issues
Help text tweaked
No error text needed
Validation #1821
