### ISSUE TITLE
Verify Use of IT Systems

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1765]
Verify the Use of Information Technology Systems portion of the eApp form (section 27 in SF-86 PDF). Equates to 1/2 of a page in the legacy SF-86.

Include these sections in the verification:
- [x] Unauthorized access
- [x] manipulating access
- [x] unlawful use

**Comment by Jay-Neighbours-I72** [comment]
Unauthorized access:
No content tweaks needed
Help text tweaked
No error text changed needed
Validation #1859

**Comment by Jay-Neighbours-I72** [comment]
Manipulating access:
No content tweaks needed
Help text tweaked
No error text changed needed
Validation #1860

**Comment by Jay-Neighbours-I72** [comment]
Unlawful use:
No content tweaks needed
Help text tweaked
No error text changed needed
Validation #1861

**Comment by Jay-Neighbours-I72** [comment]
PR #1862

**Comment by billy22g** [comment]
LGTM
