### ISSUE TITLE
Verify non-criminal court actions

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1766]
Verify the Involvement in Non-Criminal Court Actions portion of the eApp form (section 28 in SF-86 PDF). Equates to 1/4 of a page in the legacy SF-86.

Include these sections in the verification:
- [x]  main section

**Comment by Jay-Neighbours-I72** [comment]
No content errors
Help text tweaked
No error text needed
Validation #1822
