### ISSUE TITLE
Foreign activities - Add help text for Usability test session 10

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1768]
As a SF86 user I want to clearly understand questions and specific words/terms used in them so that I can answer the questions accurately.

**Words/terms that need help text clarification:**
- [x] Foreign National
- [x] Direct control
- [x] Indirect control

**Comment by Jay-Neighbours-I72** [comment]
PR submitted last week. All 3 in prototype now

<img width="1089" alt="screen shot 2017-08-22 at 9 32 12 am" src="https://user-images.githubusercontent.com/19935974/29567950-ca6dc714-871c-11e7-8562-492e6aac77a3.png">
<img width="874" alt="screen shot 2017-08-22 at 9 29 16 am" src="https://user-images.githubusercontent.com/19935974/29567951-cc003e18-871c-11e7-950e-de72382005cc.png">
<img width="951" alt="screen shot 2017-08-22 at 9 29 22 am" src="https://user-images.githubusercontent.com/19935974/29567952-cc07f900-871c-11e7-9a8c-1dafc582c067.png">

**Comment by colinpmacarthur** [comment]
LGTM!
