### ISSUE TITLE
Section 2 - Global

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1770]
Fields that are required are not being flagged as not completed when leaving page.
(No error or warning)

**Comment by Jay-Neighbours-I72** [comment]
All required fields left blank are flagged on review screen now:

<img width="1336" alt="screen shot 2017-09-29 at 2 44 29 pm" src="https://user-images.githubusercontent.com/19935974/31030956-2e8ff91c-a525-11e7-983f-c0ce99237f1d.png">
