### ISSUE TITLE
Global All Sections - Date Range Comparisons

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1776]
Any date that is supplied in the from field can be more recent than the to date which should not be allowed.

**Comment by Jay-Neighbours-I72** [comment]
Looks good to me, have been checking along with other validation QA

![screen shot 2018-01-04 at 10 43 41 am](https://user-images.githubusercontent.com/19935974/34571338-37c4f7e0-f13c-11e7-8d22-5eb39d19df3d.png)
![screen shot 2018-01-04 at 10 43 23 am](https://user-images.githubusercontent.com/19935974/34571339-37cee610-f13c-11e7-8122-d787c3abeac8.png)
