### ISSUE TITLE
Global - Date Focus Issue

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1779]
When selecting month field initially type 1.
Click January.
Focus automatically goes to day field.

Issue is that the month field remains without a green success mark.

**Comment by Jay-Neighbours-I72** [comment]
Typeahead and auto tabbing on date block was removed after feedback from usability test sessions. 

New style:
<img width="543" alt="screen shot 2017-09-12 at 2 13 56 pm" src="https://user-images.githubusercontent.com/19935974/30341662-dbcb8876-97c4-11e7-893b-dbfb5c949cbb.png">
