### ISSUE TITLE
Storyboard Where You Have Lived

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#178]
As an eApp designer I want to create a design concept to capture eApp application places of residence by providing address lookup/validation and a timeline of occupation so that users can easily enter correct addresses and review the times in which they occupied those spaces. 

Acceptance Criteria 
- Create a Storyboard utilizing the current design standards representing the physical attribute form fields
- Provide data entry for the following fields: Dates of residence (mo/yr, estimate/present); ownership/rent/military/other; Explanation; Street Address; Optional Comment; Summary of residences; Additional Comments
- Provide manner of looking up addresses/verifying addresses that were manually entered
- Review the storyboard/comp with the Product Owner
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-section-11-1](https://cloud.githubusercontent.com/assets/19935974/21935584/148ecdec-d97c-11e6-8e34-871686651881.jpg)
![e-qip-comp-section-11-2](https://cloud.githubusercontent.com/assets/19935974/21935586/1490fc66-d97c-11e6-865f-ebe709fa8db1.jpg)
![e-qip-comp-section-11-3](https://cloud.githubusercontent.com/assets/19935974/21935581/14894b24-d97c-11e6-9160-69d39fdbfb7d.jpg)
![e-qip-comp-section-11-4](https://cloud.githubusercontent.com/assets/19935974/21935583/148abb30-d97c-11e6-9454-99908f2948e6.jpg)
![e-qip-comp-section-11-5](https://cloud.githubusercontent.com/assets/19935974/21935585/148fab22-d97c-11e6-9f87-627f92dbcc0d.jpg)
![e-qip-comp-section-11-6](https://cloud.githubusercontent.com/assets/19935974/21935582/148953e4-d97c-11e6-97fc-1fd1e9a55dc1.jpg)
![e-qip-comp-section-11-7](https://cloud.githubusercontent.com/assets/19935974/21935587/14912f92-d97c-11e6-9c9d-720d947ded1a.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-section-11.pdf](https://github.com/truetandem/e-QIP-prototype/files/704690/e-QIP-comp-section-11.pdf)

**Comment by Jay-Neighbours-I72** [comment]
Version 2 starts here:

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-section-11-1](https://cloud.githubusercontent.com/assets/19935974/22039741/789e79fe-dcce-11e6-8d3b-5c5b739d8f9d.jpg)
![e-qip-comp-section-11-2](https://cloud.githubusercontent.com/assets/19935974/22039742/78a21064-dcce-11e6-8cbb-0e0ef54abf67.jpg)
![e-qip-comp-section-11-3](https://cloud.githubusercontent.com/assets/19935974/22039747/78a92750-dcce-11e6-8a67-173578b31201.jpg)
![e-qip-comp-section-11-4](https://cloud.githubusercontent.com/assets/19935974/22039743/78a6177c-dcce-11e6-9d03-980523df579f.jpg)
![e-qip-comp-section-11-5](https://cloud.githubusercontent.com/assets/19935974/22039744/78a62cd0-dcce-11e6-8be6-332cfb9f3f10.jpg)
![e-qip-comp-section-11-6](https://cloud.githubusercontent.com/assets/19935974/22039746/78a78a80-dcce-11e6-8654-4be76e670e89.jpg)
![e-qip-comp-section-11-7](https://cloud.githubusercontent.com/assets/19935974/22039745/78a635ae-dcce-11e6-936b-8754190c2d75.jpg)
![e-qip-comp-section-11-8](https://cloud.githubusercontent.com/assets/19935974/22039748/78acb154-dcce-11e6-982c-e15dc9bfb19d.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-section-11-where-you-have-lived.pdf](https://github.com/truetandem/e-QIP-prototype/files/712318/e-QIP-comp-section-11-where-you-have-lived.pdf)
