### ISSUE TITLE
Section 3 - Where you have lived - Time Calculation

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1780]
I presented my residence as follows.
1940-1980
1960-Present
1999-Present

States gap in residence as well as negative history.

![image](https://user-images.githubusercontent.com/30842622/29417514-6b357190-8337-11e7-8eba-d80eff276516.png)

**Comment by Jay-Neighbours-I72** [comment]
Residence gap and negative history have been resolved.

<img width="1302" alt="screen shot 2017-09-29 at 3 03 54 pm" src="https://user-images.githubusercontent.com/19935974/31031736-7d6fb1a6-a527-11e7-9e42-0575de2d03bf.png">

@bmallred Should we track multiple "Present" answers and show an error?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 is this still open?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred I guess the question up there^ "Should we track multiple "Present" answers and show an error?" is more for Sheldon/Drew/Billy
