### ISSUE TITLE
Section 3 - Employment Activities - Missing Question

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1784]
![image](https://user-images.githubusercontent.com/30842622/29465578-c47d54f4-8407-11e7-8faa-f9c133aa302d.png)

**Comment by Jay-Neighbours-I72** [comment]
Missing from these branches:
If Employment Type is Other Federal employment, State Government, Federal Contractor, Non-government employment, or Other

![screen shot 2017-09-12 at 1 58 31 pm](https://user-images.githubusercontent.com/19935974/30341015-87bc627a-97c2-11e7-9c17-4e6635d90c7d.png)

**Comment by billy22g** [comment]
LGTM
