### ISSUE TITLE
Section 3 - Where you have lived - Zip Code

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1786]
Error message states 5 or 9 digits with no mention that a hyphen must be included. Maybe a format example or a change in message.

![image](https://user-images.githubusercontent.com/30842622/29529267-0048f77e-866d-11e7-931b-b3fcde7be3c7.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm 
9 digit zip codes are now accepted
