### ISSUE TITLE
Section 3 - Where you have lived - Outside U.S.

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1788]
Once I selected outside U.S. and filled in the appropriate section I am still given an error. Not sure if I need to go back and delete the zip in the previous button.

![image](https://user-images.githubusercontent.com/30842622/29529526-061fcea6-866e-11e7-8165-94a08dc62f87.png)

**Comment by Jay-Neighbours-I72** [comment]
This was fixed. Re-open if you are still seeing it.

**Comment by bmallred** [comment]
Love the address!
