### ISSUE TITLE
Storyboard Where You Went to School

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#179]
As an eApp designer I want to derive a design concept to help eApp applicants enter information regarding the schools they attended in the last 10 years by providing autocomplete to assist users in entering school names and finding school addresses so that data entry mistakes are avoided.   

Acceptance Criteria 
- Create a Storyboard utilizing the current design standards representing the education fields
- Provide data entry for dates of attendance; type of school: high school, College/University, Vocational, Correspondence; School address (street/city/state/zip, country)
- Provide autocomplete/lookup where possible, but still allow manually data entry
- Provide a comments section
- Review the storyboard/comp with the Product Owner
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
Version 2 starts here:

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-section-12-1](https://cloud.githubusercontent.com/assets/19935974/22039792/b5b1fd98-dcce-11e6-9aac-ba7bc7ea51a1.jpg)
![e-qip-comp-section-12-2](https://cloud.githubusercontent.com/assets/19935974/22039795/b5bc6df0-dcce-11e6-8dea-632e5490a84f.jpg)
![e-qip-comp-section-12-3](https://cloud.githubusercontent.com/assets/19935974/22039796/b5bc6b3e-dcce-11e6-83a1-f7b6ca30ba17.jpg)
![e-qip-comp-section-12-4](https://cloud.githubusercontent.com/assets/19935974/22039793/b5b798e8-dcce-11e6-885f-3e443362b101.jpg)
![e-qip-comp-section-12-5](https://cloud.githubusercontent.com/assets/19935974/22039794/b5b9413e-dcce-11e6-8d8f-acaeb00a7f0b.jpg)
![e-qip-comp-section-12-6](https://cloud.githubusercontent.com/assets/19935974/22039799/b5c2f1e8-dcce-11e6-85aa-5a7ce0b08449.jpg)
![e-qip-comp-section-12-7](https://cloud.githubusercontent.com/assets/19935974/22039797/b5bced20-dcce-11e6-8481-0b0e0923282e.jpg)
![e-qip-comp-section-12-8](https://cloud.githubusercontent.com/assets/19935974/22039798/b5c1375e-dcce-11e6-9a0a-aabd159834ff.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-section-12-school.pdf](https://github.com/truetandem/e-QIP-prototype/files/712320/e-QIP-comp-section-12-school.pdf)
