### ISSUE TITLE
Foreign activities - Date block - Month not being validated

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1793]
Form wide bug

- [x] When selecting a Month from the typeahead suggestions the green validated style isn't being applied.

<img width="640" alt="screen shot 2017-08-22 at 10 31 13 am" src="https://user-images.githubusercontent.com/19935974/29570729-4edb91ae-8725-11e7-91fc-09b49f6672bd.png">
<img width="601" alt="screen shot 2017-08-22 at 10 31 25 am" src="https://user-images.githubusercontent.com/19935974/29570730-4edceb9e-8725-11e7-93fc-254dd094ff9c.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this is what I see:

![image](https://user-images.githubusercontent.com/697855/29571372-0418a88a-8727-11e7-85a1-62683f1ac883.png)

**Comment by floresj** [comment]
![selection_410](https://user-images.githubusercontent.com/5938731/29572751-31cd9dfe-872b-11e7-9d3c-b18f79f762fe.png)

**Comment by bmallred** [comment]
Note: We were able to reproduce this in development

**Comment by colinpmacarthur** [comment]
LGTM!
