### ISSUE TITLE
Foreign Activities - Foreign Contacts - Other - Provide explanation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1794]
For all "Other" button choices:
- [x] Close margin above "Provide explanation"
- [x] Use label text style for "Provide explanation"

<img width="787" alt="screen shot 2017-08-22 at 10 36 59 am" src="https://user-images.githubusercontent.com/19935974/29571306-daa60bfa-8726-11e7-8aad-9b93e89332a3.png">
<img width="814" alt="screen shot 2017-08-22 at 10 44 23 am" src="https://user-images.githubusercontent.com/19935974/29571322-e3d57a1c-8726-11e7-8a92-e8968a00d542.png">
<img width="777" alt="screen shot 2017-08-22 at 10 44 28 am" src="https://user-images.githubusercontent.com/19935974/29571321-e3cdfbfc-8726-11e7-832c-2bd6efb2a125.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 closing the margin again? :) If you have time this would be nice to do over screenshare

**Comment by colinpmacarthur** [comment]
I'm seeing a different header style for "Explanation" in the "Provide methods of contact question" than others:

<img width="618" alt="screen shot 2017-08-27 at 6 09 04 pm" src="https://user-images.githubusercontent.com/2092076/29754440-eff2658c-8b52-11e7-8fc7-46b43a43da26.png">

<img width="601" alt="screen shot 2017-08-27 at 6 09 11 pm" src="https://user-images.githubusercontent.com/2092076/29754441-f190c564-8b52-11e7-9bfa-fbe523946c0b.png">

**Comment by bmallred** [comment]
@colinpmacarthur can you check again? I think the deployments didn't go through as expected... I'm seeing the changes on staging now.
