### ISSUE TITLE
Section 3 - Where you have lived - Zipcode

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1795]
After correcting the zipcode error still is present.

![image](https://user-images.githubusercontent.com/30842622/29573214-6aac144c-872c-11e7-9378-24dea9806601.png)

**Comment by Jay-Neighbours-I72** [comment]
Looks like this was fixed.

<img width="1041" alt="screen shot 2017-09-29 at 3 05 53 pm" src="https://user-images.githubusercontent.com/19935974/31031801-c2f8f7d2-a527-11e7-9d7e-3b382e23b1e3.png">
<img width="1073" alt="screen shot 2017-09-29 at 3 05 59 pm" src="https://user-images.githubusercontent.com/19935974/31031802-c3029526-a527-11e7-9d4e-735cdf4ae0d3.png">
