### ISSUE TITLE
Section 3 - Where you have lived - Residence Gap

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1796]
The second address is listed from 1/2013 to present.
I am given this error which I should not and states to add address not residence.

![image](https://user-images.githubusercontent.com/30842622/29573414-e95c48a2-872c-11e7-9581-e5d6bc543dc8.png)

**Comment by Jay-Neighbours-I72** [comment]
This has been fixed.

<img width="1284" alt="screen shot 2017-09-29 at 2 56 35 pm" src="https://user-images.githubusercontent.com/19935974/31031400-6a9c6458-a526-11e7-9226-8221f1be8cb0.png">
