### ISSUE TITLE
Ever been investigated - Agency blocks - I don't know

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1800]
Currently selecting "I don't know" doesn't clear the selected agency and user can switch agency through the white overlay

- [x] Clear current selection if "I don't know" is selected
- [x] Disable buttons behind white overlay

Also seeing on the Level of clearance block.

<img width="931" alt="screen shot 2017-08-22 at 2 49 55 pm" src="https://user-images.githubusercontent.com/19935974/29582113-801c03f6-8749-11e7-9d3b-92053560ff06.png">
<img width="961" alt="screen shot 2017-08-22 at 2 49 59 pm" src="https://user-images.githubusercontent.com/19935974/29582114-8024b938-8749-11e7-8794-7bb40be97946.png">

<img width="989" alt="screen shot 2017-08-22 at 2 59 44 pm" src="https://user-images.githubusercontent.com/19935974/29582411-9cf0fcba-874a-11e7-9823-40ff570ba8e1.png">
<img width="870" alt="screen shot 2017-08-22 at 2 59 40 pm" src="https://user-images.githubusercontent.com/19935974/29582412-9cf203f8-874a-11e7-8d99-720d1a997e49.png">

**Comment by lauraponce** [comment]
This doesn't appear to be resolved on dev or staging, is it still in progress @bmallred or should I be seeing it up now?

**Comment by bmallred** [comment]
@lauraponce this looks like it has changed... going to send it back to **In Progress** so @floresj or I can take a look at it.

Several things immediately come to attention:
 - The opacity of the elements does not trigger when toggling **I don't know**
 - When **I don't know** is selected you can still select on of the options (and then **I don't know** remains selected)

**Comment by billy22g** [comment]
Seems like there's also an issue with the dates still being there even when "I don't know is selected" (same section). Wonder if this is pervasive in other parts of the form too?

<img width="483" alt="screen shot 2017-11-08 at 6 47 08 am" src="https://user-images.githubusercontent.com/5091167/32552300-b75b7a42-c450-11e7-8c49-f36fb1e15c11.png">

<img width="631" alt="screen shot 2017-11-08 at 6 47 21 am" src="https://user-images.githubusercontent.com/5091167/32552305-bbc85974-c450-11e7-8fbf-3c235059db86.png">

**Comment by floresj** [comment]
The latest updates have resolved this issue. We had to make some updates to default values when persisting components that are wrapped in `NotApplicable`.

**Comment by billy22g** [comment]
Still seeing the same things. Maybe it's the distinction between "Not Applicable" and "I don't know" @floresj?

<img width="1277" alt="screen shot 2017-11-17 at 9 10 07 am" src="https://user-images.githubusercontent.com/5091167/32956819-2fe865b0-cb77-11e7-8b8a-3f0358983757.png">

**Comment by Jay-Neighbours-I72** [comment]
lgtm now:
![screen shot 2017-12-19 at 4 08 13 pm](https://user-images.githubusercontent.com/19935974/34178904-da28416c-e4d6-11e7-80ac-a618b7a7112d.jpg)
![screen shot 2017-12-19 at 4 08 16 pm](https://user-images.githubusercontent.com/19935974/34178905-da34d51c-e4d6-11e7-9005-7925351359f5.jpg)

**Comment by billy22g** [comment]
LGTM
