### ISSUE TITLE
Section 3 - School - Error  Grammer

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1802]
Error for user would not be informative.

![image](https://user-images.githubusercontent.com/30842622/29582476-dd457ad4-874a-11e7-86a7-fb7eede8b0d8.png)

**Comment by Jay-Neighbours-I72** [comment]
Fixed in #1726

<img width="958" alt="screen shot 2017-09-12 at 1 36 19 pm" src="https://user-images.githubusercontent.com/19935974/30340125-7a6550f8-97bf-11e7-8ad3-cd9fb9c39440.png">
