### ISSUE TITLE
Section 3 - School - Relationship

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1803]
This question is not in the 2017 form.

![image](https://user-images.githubusercontent.com/30842622/29582664-8f303e5a-874b-11e7-94e8-9127e9e64fbc.png)

![image](https://user-images.githubusercontent.com/30842622/29582692-aca591d8-874b-11e7-99e8-d326314b6ad0.png)

**Comment by Jay-Neighbours-I72** [comment]
Covered in #1895
