### ISSUE TITLE
Section 3 - School - Person Who Knew You

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1804]
I dont believe the APO/FPO addressing is available.

![image](https://user-images.githubusercontent.com/30842622/29582824-25685204-874c-11e7-8af5-7961c3c03a4e.png)

See below these choices/branching is not listed.

**Comment by Jay-Neighbours-I72** [comment]
Hide APO/FPO option here

![screen shot 2017-09-12 at 1 33 46 pm](https://user-images.githubusercontent.com/19935974/30340019-0e86d122-97bf-11e7-8703-874e7dc241f1.png)

**Comment by pjsumm** [comment]
This is operating as designed.  APO/FPO is possible here.

**Comment by Jay-Neighbours-I72** [comment]
Note:

this branch is missing currently

![screen shot 2017-11-30 at 11 18 58 am](https://user-images.githubusercontent.com/19935974/33441274-4bf55bb6-d5c0-11e7-97b3-4462c67382db.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 which branch is missing here? Isn't this the portion where you have to enter a name first before the other fields are displayed? Also, clicking on "Yes" for receiving a diploma or degree starts a branch collection.

**Comment by bmallred** [comment]
Here is how you can reproduce. Enter a date with "Present" selected and see the branch be displayed. Then enter a past value in the **from** portion of the date range and the branch will disappear.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred you are right, this was my mistake. Closing now.
