### ISSUE TITLE
Storyboard Field Comments

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#181]
As an eApp designer I want to create a storyboard to reflect how users can add comments to a field/field grouping in a form, so that we have a consistent design representation to implement across all cases of field comments

Acceptance Criteria
- Create a Storyboard utilizing the current design standards representing the field comments field
- Provide manner of opening/closing, or adding/removing comments to a given field/field group
- Review the storyboard/comp with the Product Owner
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-comment-style-1](https://cloud.githubusercontent.com/assets/19935974/21862846/f6159b8a-d808-11e6-8cd6-1e74659a4875.jpg)
![e-qip-comp-comment-style-2](https://cloud.githubusercontent.com/assets/19935974/21862845/f614e6ea-d808-11e6-84e9-64218dbb20ad.jpg)

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-comment-style-1](https://cloud.githubusercontent.com/assets/19935974/21935877/27252a40-d97d-11e6-8d0e-be5b9a3eaad9.jpg)
![e-qip-comp-comment-style-2](https://cloud.githubusercontent.com/assets/19935974/21935878/272b6a68-d97d-11e6-8d77-7dfe4dba2194.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-comment-style.pdf](https://github.com/truetandem/e-QIP-prototype/files/704699/e-QIP-comp-comment-style.pdf)

**Comment by Jay-Neighbours-I72** [comment]
![e-qip-comp-comment-style-1](https://cloud.githubusercontent.com/assets/19935974/22028888/bd5df5f6-dca6-11e6-9e3f-58df586ac287.jpg)
![e-qip-comp-comment-style-2](https://cloud.githubusercontent.com/assets/19935974/22028889/bd5e9916-dca6-11e6-8c15-761a78b06bb5.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-QIP-comp-comment-style.pdf](https://github.com/truetandem/e-QIP-prototype/files/711638/e-QIP-comp-comment-style.pdf)
