### ISSUE TITLE
Accordion Item Validation

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1825]
As an eApp applicant I want verification to my input on accordion controls to be clear and easy to understand so that I am notified of issues and can quickly find and correct them. 

Related Stories:
#1806 
#1807 
#1808 
#1809 
#1810 
#1816 
#1817 
#1818 
#1819 
#1820

**Comment by lauraponce** [comment]
LGTM! @billy22g and I both spot checked these accordion validations
