### ISSUE TITLE
Section 5 - Citizenship Status - Place of entry - error message

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1826]
Error message for user could cause confusion.

**Comment by TravisAJackson** [comment]
![image](https://user-images.githubusercontent.com/30842622/29669882-e81d2524-88b2-11e7-96a1-bc04e783e75b.png)

**Comment by Jay-Neighbours-I72** [comment]
State message also missing:

<img width="839" alt="screen shot 2017-09-12 at 1 26 45 pm" src="https://user-images.githubusercontent.com/19935974/30339757-0e74ffde-97be-11e7-8be0-ff2944dcf342.png">

**Comment by bmallred** [comment]
This may be fixed already.
