### ISSUE TITLE
Section 5 - Dual Citizenship - Styling

### ISSUE THREAD

**Issue by TravisAJackson** [truetandem/e-QIP-prototype#1828]
Page styling is not displaying correctly.

**Comment by TravisAJackson** [comment]
![image](https://user-images.githubusercontent.com/30842622/29674044-0373100c-88bf-11e7-8d0e-5f517dba00d0.png)

**Comment by Jay-Neighbours-I72** [comment]
This looks to be resolved. 

<img width="1448" alt="screen shot 2017-09-29 at 3 01 42 pm" src="https://user-images.githubusercontent.com/19935974/31031631-217f5b44-a527-11e7-86c6-9e3d7d76e30b.png">
