### ISSUE TITLE
Write spec for "Foreign Business - Family Support"

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1840]
Write the feature specification for the "Foreign Business" subsection "Family Support"

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/29792786-8c46c056-8c0f-11e7-8f6b-61c64c2cc0f4.gif)

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/29792994-4af33c6e-8c10-11e7-95c5-76d1769e9bb0.gif)

**Comment by lauraponce** [comment]
Looks good!
