### ISSUE TITLE
Write spec for "Foreign Business - Other business ventures"

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1842]
Write the feature specification for the "Foreign Business" subsection "Other business ventures"

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/29794687-0c0771bc-8c17-11e7-850e-4d58bf3e9a0c.gif)

**Comment by lauraponce** [comment]
Looks good!
