### ISSUE TITLE
Write spec for "Foreign Business - Conferences"

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1843]
Write the feature specification for the "Foreign Business" subsection "conferences"

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/29820962-45459332-8c94-11e7-8fbe-5cabb509701b.gif)

**Comment by lauraponce** [comment]
@pjsumm It looks like this test isn't clicking the last yes/no question in the section before jumping out to the yes/no question outside of the section. Is that something that should be covered in this test? (I'm still learning what to look for with these feature specs, so let me know if I'm off-base here!)

**Comment by pjsumm** [comment]
@lauraponce I skipped over that re-prompt because the CSS is identical between the "do you have another subsequent..." messages so there is currently no clear way using solely CSS selectors to differentiate between the two.   Since answering "No" doesn't impact the flow of the form I thought it would be OK to move past and answer the next question.  If you disagree, I can work with John to figure out a way to make each of the "do you have another subsequent..." re-prompts unique so they can be differentiated through CSS selectors during tests.  I believe I have done this in other tests, too.

**Comment by pjsumm** [comment]
@lauraponce thinking about this some more,  I'm wondering whether leaving that field unanswered should result in a validation error when the user clicks's next?  If the current passive behavior is OK, which allows the user to move on without confirming they have nothing else to add, then leaving the test as-is is arguably OK.  However, if the desired behavior is to make them answer the question before moving on, then the test case and the validation/confirmation should be fixed.  I think this is worth clarifying with the team in case this is currently behaving as requested.  @Jay-Neighbours-I72 and @bmallred should it be OK to leave the section without confirming they have nothing more to add, or have we not asked this question before?

**Comment by billy22g** [comment]
Bumping @pjsumm's question above. @Jay-Neighbours-I72 @bmallred @lauraponce This *might* be a question in our collection of them for Sheldon.

We do force them to complete it later on in the review, so I think it's actually ok. I think I'm 👍 on the current implementation.

<img width="1280" alt="screen shot 2017-11-03 at 8 52 19 am" src="https://user-images.githubusercontent.com/5091167/32379907-636654d2-c074-11e7-8f66-c84977cbdc98.png">

**Comment by billy22g** [comment]
Actually @pjsumm as I think about it, the feature specs should be testing that all the fields are clickable too. So I think there's value from the happy path perspective of checking "No" there. Thoughts?

**Comment by billy22g** [comment]
@pjsumm and @bmallred Would you mind loading another gif of this one too, since I assume it's the same issue as the other one?

**Comment by pjsumm** [comment]
Updated the selector to select the second instance of the question so we can say no the second time.

![testresult](https://user-images.githubusercontent.com/12962390/34850077-90e9d0b4-f6f2-11e7-8e53-41d392053b3f.gif)

**Comment by billy22g** [comment]
LGTM
