### ISSUE TITLE
Foreign activities - Foreign contacts - margins and text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1847]
- [ ] Method of contact - make "Explanation" label style
<img width="853" alt="screen shot 2017-08-25 at 10 31 30 am" src="https://user-images.githubusercontent.com/19935974/29718677-8ebc60ec-8981-11e7-84a1-62617201780e.png">

...

- [ ] Nature of relationship - Close margin above "Explanation"
<img width="822" alt="screen shot 2017-08-25 at 10 39 47 am" src="https://user-images.githubusercontent.com/19935974/29718756-c712d67e-8981-11e7-9ace-b087835e7c74.png">

**Comment by bmallred** [comment]
Closing this one in favor of the one already in queue: https://github.com/truetandem/e-QIP-prototype/issues/1794
