### ISSUE TITLE
Association record - Membership - violence or force $

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1849]
- [x] Add the $ before this input - "Provide all contributions (in U.S. dollars) made to the organization, if any"

<img width="905" alt="screen shot 2017-08-25 at 2 58 29 pm" src="https://user-images.githubusercontent.com/19935974/29728478-0f1a6b02-89a6-11e7-9160-ea0103bfc8f2.png">

**Comment by Jay-Neighbours-I72** [comment]
I'm not seeing the change on this one...

![screen shot 2017-11-02 at 2 43 05 pm](https://user-images.githubusercontent.com/19935974/32344140-31408560-bfdc-11e7-865c-a0c76b2c6b94.png)

**Comment by bmallred** [comment]
Looks like there was a bad merge: https://github.com/truetandem/e-QIP-prototype/commit/445ab9bf8dcc7f0ae782f3c1a04c421a6cb59012

**Comment by billy22g** [comment]
LGTM
