### ISSUE TITLE
Valdiation

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#1853]
**What did you do?**
Entered an initial for First Name w/o putting a check in the Initial Only box. Left Middle Name blank w/o putting a check in Middle Name box. Entered an initial for Last Name w/o putting a check in the Initial Only box.  Chose "Other" for Suffix and left the Other field blank. No validation error. 
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
Validation error for First Name, Middle Name, Last Name, and Suffix. 
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.* To provide the applicant validation errors when they enter an initial and don't check the Initial Only box.  Provide the applicant a validation error when they don't provide a middle name and don't check the No Middle Name box. Provide the applicant a validation error when the choose "other" Suffix and leave the Other field blank. 

**What did you see instead?**
No validation errors
*Include a high-level description of the feature or error here*
 See above.
**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
 - What browser and version are you using?
Google Chrome 
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
Will be fixed with this bug #1738
