### ISSUE TITLE
Verify where you have lived

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1865]
Verify the Where you have lived portion of the eApp form (section 11 in SF-86 PDF). Equates to 3/4 of a page in the legacy SF-86.

Include these sections in the verification:
- [x] locations
- [x] people who know you at the locations

**Comment by Jay-Neighbours-I72** [comment]
Bug #1911 #1912

**Comment by Jay-Neighbours-I72** [comment]
Bug  #1968

**Comment by billy22g** [comment]
LGTM
