### ISSUE TITLE
Verify employment activities former federal service

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1868]
Verify the Employment Activities – Former Federal Service portion of the eApp form (section 13b in SF-86 PDF). Equates to 1/4 of a page in the legacy SF-86.

Include these sections in the verification:
- [x] Do you have former federal civilian employment, excluding military service, NOT indicated previously, to report?

**Comment by Jay-Neighbours-I72** [comment]
Content issue #1891
Bugs #1888 #1889
Help text tweaked
No error text changed needed
Validation #1892

Will review when bugs and PR pushed
