### ISSUE TITLE
Verify employment record

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1869]
Verify the Employment Record portion of the eApp form (section 13c in SF-86 PDF). Equates to < 1/4 of a page in the legacy SF-86.

Include these sections in the verification:
- [ ] Have any of the following happened to you in the last seven (7) years at employment activities...

**Comment by Jay-Neighbours-I72** [comment]
Content issue: #1874
Can't review this section until that issue is complete.

**Comment by Jay-Neighbours-I72** [comment]
Content verified 
Bug #1977 #1978
Help text tweaked 
Changes and help text in this PR #1979

**Comment by billy22g** [comment]
LGTM
