### ISSUE TITLE
Address block - add dividing lines between addresses 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1870]
- [x] Add grey horizontal dividing line between addresses in address suggestion block

comp:
<img width="1134" alt="screen shot 2017-08-30 at 9 10 19 am" src="https://user-images.githubusercontent.com/19935974/29873987-48da7b32-8d63-11e7-8441-253755eacc1d.png">

dev:
<img width="1000" alt="screen shot 2017-08-30 at 9 11 53 am" src="https://user-images.githubusercontent.com/19935974/29873997-4d3c5e34-8d63-11e7-9c01-b1d519602d59.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 is this for the suggestions which come back from USPS as well?

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/30216663-bfc273ba-9481-11e7-84e1-b95a7a11760b.png)

**Comment by lauraponce** [comment]
LGTM!
