### ISSUE TITLE
Employment Record Section - Add content to Employment Activities

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1874]
Add the content from Employment Record section at the bottom of the Employment Activities accordion.

**Content:**
Have any of the following happened to you in the last seven (7) years at employment activities that you have not previously listed?

- Fired from a job? 
- Quit a job after being told you would be fired?  
- Have you left a job by mutual agreement following charges or allegations of misconduct?  
- Left a job by mutual agreement following notice of unsatisfactory performance?  
- Received a written warning, been officially reprimanded, suspended, or disciplined for misconduct in the workplace, such as violation of a security policy?

Yes/No button
(Yes will add another accordion item)

On review screen add this question where it would naturally fall (put a white bg on it if it is within the grey accordion)

<img width="1313" alt="screen shot 2017-09-05 at 11 16 56 am" src="https://user-images.githubusercontent.com/19935974/30068406-bed0561e-922b-11e7-8eed-6a1b79714e03.png">

![screen shot 2017-09-05 at 11 17 07 am](https://user-images.githubusercontent.com/19935974/30068415-c3801da2-922b-11e7-84fc-dbe4568e8576.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 how does this look?

## In the employment section

![image](https://user-images.githubusercontent.com/697855/30218020-dd12c7fe-9485-11e7-89ae-b9654c815769.png)


## In review

![image](https://user-images.githubusercontent.com/697855/30217980-c52e5504-9485-11e7-95eb-40756f72e764.png)

**Comment by Jay-Neighbours-I72** [comment]
Sorry @bmallred I missed that tag.

We need to add one more piece here. Need to add the second question from 13a directly after the accordion.

**Text:**
Do you have an additional employment activity to enter?
Yes/No button (will add another accordion item)

Desired:
<img width="1961" alt="screen shot 2017-09-25 at 9 57 38 am" src="https://user-images.githubusercontent.com/19935974/30812151-035de222-a1d8-11e7-90d1-830a6e081c1d.png">

**Comment by Jay-Neighbours-I72** [comment]
Duplicate of #1903

**Comment by Jay-Neighbours-I72** [comment]
lgtm
