### ISSUE TITLE
Where you went to school - incomplete error bug

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1887]
- [ ] "Information incomplete" message is being thrown when all required fields are complete.

<img width="1977" alt="screen shot 2017-09-07 at 2 08 30 pm" src="https://user-images.githubusercontent.com/19935974/30178219-32454022-93d6-11e7-801e-2d783fc9f77b.png">

**Comment by floresj** [comment]
This will be resolved with the history accordion item validation. I think I had to also update some validator logic for this one.

**Comment by lauraponce** [comment]
LGTM!
