### ISSUE TITLE
Former federal service - review screen error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1888]
- [ ] "Problem error" being thrown in review screen when all required fields are complete

<img width="1383" alt="screen shot 2017-09-07 at 2 11 10 pm" src="https://user-images.githubusercontent.com/19935974/30178326-81b0c26c-93d6-11e7-94f8-279c7728c33f.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 This is a work in progress at the moment with the refactoring @floresj has been pushing up.

@floresj can you track this to make sure it is covered in one of your PR's?

**Comment by floresj** [comment]
Just note to myself. This will be in the history accordion review PR.

**Comment by floresj** [comment]
Looks resolved.
![selection_472](https://user-images.githubusercontent.com/5938731/31080687-6d71e008-a757-11e7-83b2-898384c5d4fd.png)
