### ISSUE TITLE
Month By Name Entry 

### ISSUE THREAD

**Issue by myukna72** [truetandem/e-QIP-prototype#1890]
Shorten Entry Field Width - Limit the width provided in the Auto Populate for the number of the month. 
<img width="714" alt="screen shot 2017-09-07 at 2 15 32 pm" src="https://user-images.githubusercontent.com/30809116/30178487-19026cec-93d7-11e7-8565-7ecc63dd00bf.png">

**Comment by Jay-Neighbours-I72** [comment]
Note: We are losing the typeahead completely.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 can do!

**Comment by lauraponce** [comment]
LGTM!
