### ISSUE TITLE
Former federal service - Headlines question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1891]
"Provide all former federal service" headline - I don't remember when/why we added this, do you @bmallred 

<img width="1547" alt="screen shot 2017-09-07 at 2 44 40 pm" src="https://user-images.githubusercontent.com/19935974/30179642-188dbdb2-93db-11e7-80ae-136c70605c86.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I do not. I don't see a comp for it, but it definitely is not present on the content guide. Want to remove it and bump the branch question up a level?

**Comment by billy22g** [comment]
LGTM
