### ISSUE TITLE
Where you went to school - headline size

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1894]
- [x] Change "Have you attended any schools in the last 10 years?" to H3

<img width="1181" alt="screen shot 2017-09-07 at 4 06 43 pm" src="https://user-images.githubusercontent.com/19935974/30182956-a46726ba-93e6-11e7-8586-fecd55e63ccc.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 `h3` for the other question as well if you answer **No**?

![image](https://user-images.githubusercontent.com/697855/30225095-4138e132-949f-11e7-9502-037713889094.png)
