### ISSUE TITLE
Date range block - arrow missing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1899]
- [x] Arrow is missing from date range blocks

I'm seeing it form wide
<img width="805" alt="screen shot 2017-09-08 at 10 15 35 am" src="https://user-images.githubusercontent.com/19935974/30216005-a7b7de74-947f-11e7-805b-d7e8ff663b83.png">

**Comment by bmallred** [comment]
## Before

![image](https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fi.makeagif.com%2Fmedia%2F12-05-2013%2F2rYo5g.gif&f=1)

## After

![image](https://user-images.githubusercontent.com/697855/30223445-dfe53a26-9498-11e7-8305-01c714e3f2ee.png)

**Comment by lauraponce** [comment]
LGTM!
