### ISSUE TITLE
Where you went to school - Previous address block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1901]
- [ ] Use previous address book is now showing in the accordion

This image is the second address I am inputting:
<img width="881" alt="screen shot 2017-09-08 at 10 41 23 am" src="https://user-images.githubusercontent.com/19935974/30216843-4f433100-9482-11e7-9e1f-94d37e753ed3.png">

**Comment by lauraponce** [comment]
I'm still not seeing the choose a previously used address in the where you went to school section. Should that be showing up now?
