### ISSUE TITLE
Where you went to school - Can't navigate back to section

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1902]
After inputting 2 schools accordion functionality stopped working. Went to another page and couldn't get back to school/diplomas.

Clicking on Where you went to school would change to the correct header but wrong content:
<img width="1975" alt="screen shot 2017-09-08 at 10 43 36 am" src="https://user-images.githubusercontent.com/19935974/30216991-ce85c554-9482-11e7-8bb6-7bb14ff57752.png">

Note: Cleared cache and hard reload to test again. Same issue, froze only after when finishing the second school entry.

**Comment by floresj** [comment]
Looks resolved. Was probably a buggy with section links.

**Comment by Jay-Neighbours-I72** [comment]
I'm still seeing this, accordion stops working after adding 2 schools.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 you may have to show us this tomorrow. I just tried it out with five schools and not having an issue.

cc: @floresj

**Comment by bmallred** [comment]
Caused due to #2160

**Comment by Jay-Neighbours-I72** [comment]
Has this fix been pushed? I am still seeing it happening on dev. @bmallred
