### ISSUE TITLE
Where you have lived - add person who knows you branch

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1911]
The "Person who knew you" branch only shows when the From date year is 3 years old or newer.
This means if the To date is 2017 but from is older than 3 years the branch doesn't load.

Should we switch the 3 year criteria to the To date to avoid this?

In this example the branch wasn't there:
<img width="1128" alt="screen shot 2017-09-11 at 2 27 56 pm" src="https://user-images.githubusercontent.com/19935974/30290823-d0c13cda-96fe-11e7-9ee6-52c59638e5a7.png">

**Comment by bmallred** [comment]
This may be a bug. According to the logic it should account for either of those dates being within 3 years.

Code for [ResidenceItem.jsx @ lines 6 - 10](https://github.com/truetandem/e-QIP-prototype/blob/master/src/components/Section/History/Residence/ResidenceItem.jsx#L6-L10)

```jsx
// We need to determine how far back 3 years ago was
const threeYearsAgo = daysAgo(today, 365 * 3)
const withinThreeYears = (from, to) => {
  return (from && from.date >= threeYearsAgo) || (to && to.date >= threeYearsAgo)
}
```

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 just tested on my local instance (since the cloud environments are having issues) and this may already be solved.

**Comment by Jay-Neighbours-I72** [comment]
working for me now too.

**Comment by billy22g** [comment]
LGTM
