### ISSUE TITLE
Where you have lived - add person who knows you - add comment

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1912]
- [x] Clicking on "Add comment" under relationship selects "Business associate"
- [x] Can't open comment

<img width="740" alt="screen shot 2017-09-11 at 3 04 10 pm" src="https://user-images.githubusercontent.com/19935974/30292061-b273e558-9702-11e7-9cc2-d9ab47d21765.png">
<img width="754" alt="screen shot 2017-09-11 at 3 04 05 pm" src="https://user-images.githubusercontent.com/19935974/30292062-b27844ea-9702-11e7-87b0-085aa0c0f76c.png">

**Comment by lauraponce** [comment]
LGTM!
