### ISSUE TITLE
Where you have lived - Progress bar not updating

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1913]
Progress bar didn't update after adding an address. Address was "Present" address.

<img width="1278" alt="screen shot 2017-09-11 at 3 09 47 pm" src="https://user-images.githubusercontent.com/19935974/30292205-539c2620-9703-11e7-924c-137ffe861065.png">

**Comment by Jay-Neighbours-I72** [comment]
Cross reference #1782

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this is what I am seeing

![image](https://user-images.githubusercontent.com/697855/30452721-9f1c475c-9964-11e7-89a4-9b783f96e64f.png)


I did notice on your screenshot the **to** date was **NA** which would suggest a reason why it was not reflected in the progress bar possibly.

**Comment by Jay-Neighbours-I72** [comment]
I am seeing it working on dev, seems like the "Present" button wasn't updating the date on staging
