### ISSUE TITLE
Optional comment width

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1918]
Optional comment link width is too wide. Easy for user to accidentally click and open comment.

- [x] Reduce width to fit text and icon

<img width="1140" alt="screen shot 2017-09-12 at 1 40 30 pm" src="https://user-images.githubusercontent.com/19935974/30340316-1aba2de4-97c0-11e7-874a-8c905a69691a.png">

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/30486525-d549a80c-99fe-11e7-8df6-b57f0cc50acf.png)

**Comment by lauraponce** [comment]
LGTM!
