### ISSUE TITLE
Input field editing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1923]
When editing a previous word in an input:
Any key after the previous word shifts the cursor to the end of the input

<img width="779" alt="screen shot 2017-09-13 at 2 57 48 pm" src="https://user-images.githubusercontent.com/19935974/30395399-fdb2ba0c-9893-11e7-86f7-20163490ce78.png">
<img width="775" alt="screen shot 2017-09-13 at 2 58 30 pm" src="https://user-images.githubusercontent.com/19935974/30395403-05d2266e-9894-11e7-8245-6216f73e36a2.png">

**Comment by bmallred** [comment]
Whoa, when did this start happening!

**Comment by bmallred** [comment]
Appears to be only happening within the **Your History** section. May be due to the fact these components are still managing their local state.

**Comment by lauraponce** [comment]
Appears to be fixed now!
