### ISSUE TITLE
Address block - previously used address

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1925]
Previously used address blocks are not showing on Marital Relations (sharing across accordion items)

<img width="1481" alt="screen shot 2017-09-13 at 3 13 40 pm" src="https://user-images.githubusercontent.com/19935974/30396121-91cedb4c-9896-11e7-81f5-d0a5ad8e2bbd.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 we can at it in there. According to the R&D it was suppose to be in these sections of `Relationships`:

> **Relationships > Marital & relationship status** 
> Suggest from Where you have lived for Separated, Annulled, Divorced/dissolved, and Widowed

> **Relationships > Relatives**
> Suggest from Where you have lived for all relative types
