### ISSUE TITLE
Implement help icon relocation

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#1928]
Storyboard: #1871

 - [x] Relocate the help icon to be inline with the heading
 - [x] Relocate the help message to be directly beneath the heading

**Comment by bmallred** [comment]
## inline with a label

![image](https://user-images.githubusercontent.com/697855/30447135-1bae39a8-9959-11e7-942c-b51ca6f9158c.png)

## branch with top header + paragraph + question

**Comment by lauraponce** [comment]
LGTM!
