### ISSUE TITLE
Address block - more info needed

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1929]
Issues with adding an Apt

If the Apt # is put into the second address line it requires more info:
<img width="801" alt="screen shot 2017-09-14 at 2 15 59 pm" src="https://user-images.githubusercontent.com/19935974/30447399-02dca74c-995a-11e7-9a16-eeeec9a34bf9.png">
<img width="740" alt="screen shot 2017-09-14 at 2 34 50 pm" src="https://user-images.githubusercontent.com/19935974/30447398-02dad714-995a-11e7-977e-6564291dcad1.png">

If Apt # is put into the first line it works:
<img width="738" alt="screen shot 2017-09-14 at 2 35 15 pm" src="https://user-images.githubusercontent.com/19935974/30447411-0d6fe3a4-995a-11e7-8524-6c4a073a4d36.png">

Suite works on second line:
<img width="793" alt="screen shot 2017-09-14 at 2 36 49 pm" src="https://user-images.githubusercontent.com/19935974/30447452-302ec978-995a-11e7-86de-7814f2a9acb7.png">

Is this address specific or something USPS?

**Comment by bmallred** [comment]
In the second line for apartments I see these attempts from above:
 - Apt: A
 - A

What I found works is
 - Apt A

Checking on how we send it across... I **think** we concatenate the two address lines

**Comment by bmallred** [comment]
Scratch that they are sent separately: [/api/geo/usps.go @ line 251](https://github.com/truetandem/e-QIP-prototype/blob/master/api/geo/usps.go#L251)
