### ISSUE TITLE
Uses of information technology systems - all subsections multi line inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1930]
- [ ] Both multi line inputs in each of the 3 subsections are not getting the green verified style

<img width="600" alt="screen shot 2017-09-14 at 3 02 41 pm" src="https://user-images.githubusercontent.com/19935974/30449877-559523e8-995e-11e7-8378-09d5a5bfea75.png">

<img width="1891" alt="screen shot 2017-09-14 at 3 02 46 pm" src="https://user-images.githubusercontent.com/19935974/30449871-53328f46-995e-11e7-9a78-73bc2b2c85ad.png">

Edit: looks like this is form wide:
<img width="1190" alt="screen shot 2017-09-14 at 3 26 06 pm" src="https://user-images.githubusercontent.com/19935974/30451265-1435b14e-9961-11e7-9132-f5c3d8cf1a0c.png">

<img width="1167" alt="screen shot 2017-09-14 at 3 26 54 pm" src="https://user-images.githubusercontent.com/19935974/30451289-279579a4-9961-11e7-8752-8fc010663e0c.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this is what I see on each subsection:

![image](https://user-images.githubusercontent.com/697855/30452501-de3ecb22-9963-11e7-9a1e-14de0f617984.png)

**Comment by Jay-Neighbours-I72** [comment]
I'm still seeing this on dev
<img width="1893" alt="screen shot 2017-09-15 at 9 07 52 am" src="https://user-images.githubusercontent.com/19935974/30483588-639ae08a-99f5-11e7-9e4e-4075adb21b44.png">

I'll wait till the next release and check again

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 i see it on dev as well, but on local it is working. for one they aren't in sync (not much of our deployments are working at the moment) but i'll look at the differences and see what is going on.

**Comment by Jay-Neighbours-I72** [comment]
this is working for me now

**Comment by lauraponce** [comment]
LGTM!
