### ISSUE TITLE
Investigations and clearance record - Denied

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1931]
Let's change the accordion headline and item titles to:
Summary of Denials
Denial 1

To be more consistent with the subsection title

![screen shot 2017-09-14 at 3 29 05 pm](https://user-images.githubusercontent.com/19935974/30451582-c64ffa4c-9961-11e7-94c5-9e8a1d1d57a4.png)

**Comment by bmallred** [comment]
## Word count (not including accordion obviously)

 - **Denied**: 2
 - **Suspended**: 2
 - **Revoked**: 3 (includes revocation)
 - **Downgrade**: 1
 - **Termination**: 1

Just saying :-P
