### ISSUE TITLE
Accordion closed when coming back to a section

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1933]
- [x] Let's load all accordions closed when returning to a section. 

This way when users come back to a section with a lot of accordion items it is easier to find what they are looking for.

**Comment by bmallred** [comment]
Duplicate of #1321 

This is the end goal, but currently not capable of doing so since there wasn't a way to tell if based on the state of the data. I think when @floresj has pushed up all the changes for the **incomplete** messages we will have a better chance of implementing this.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
