### ISSUE TITLE
Create server validation for applicant passport number

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#194]
Add server validation for passport numbers and see if there are any regular expressions.

**Comment by floresj** [comment]
Some findings:

- United States Citizenship and Immigration Services (USCIS) [E-verify Help Page](https://e-verify.uscis.gov/esp/help/EvHelpPassportandPassportCardNbr.htm)
  - *The number must be between six and nine alphanumeric characters (letters and numbers). You may not enter any special characters.*
  - *A U.S. Passport number, circled below, usually contains nine numeric characters. There are a few versions of the U.S. Passport still in circulation that vary from the version shown. In some cases, a U.S. Passport number contains eight characters—one letter followed by seven numeric characters.*
- Another [USCIS info page](https://www.uscis.gov/e-verify/about-program/e-verify-enhancements/us-passport-and-visa-number-entry)
  - *U.S. Passport numbers must be between six and nine alphanumeric characters (letters and numbers).*
  - *The “C” that precedes a U.S. Passport Card number is no longer case sensitive.*

**Questions**
- There seems to be a distinction between a `Passport` and `Passport Card` Passport Cards start with the letter C followed by 8 numbers. Should we add a field for passport cards?
