### ISSUE TITLE
Create front-end component for applicant passport number

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#195]
Labels

 - [x] "Do you possess a U.S. passport (current or expired)?"
 - [x] "Provide the following information for the most recent U.S. passport you currently possess."
 - [x] "Provide your U.S. passport number:"
 - [x] "Click HERE for U.S. State Department passport help"
 - [x] "Add Optional Comment"
 - [x] "Note: If you need to provide any additional comments about this information, enter them below."

Fields

  - [x] The do you have a passport field is a Y/N choice, required 
  - [x] Passport Number field is free text - letters and numbers, unlimited, required 
  - [x] There is inline help text and a link for information regarding Passport number that goes to: 
https://travel.state.gov/content/travel/en.html
  - [x] The comments field is free text
  - [x] Validation rules are enforced on the client side as the user leaves the field
  - [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
Legacy
![selection_214](https://cloud.githubusercontent.com/assets/5938731/21929139/de6c1acc-d95c-11e6-9d34-f20391b92105.png)
