### ISSUE TITLE
Validation on Full Name

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#1953]
**What did you do?**
Completed Full Name

*Including steps for recreating it, if applicable.*

**What did you expect to see?**
1. Validation Errors when incorrect data is provided: First and Last Names are initials, but validation accepted the initials when the Initial Only blocks are not checked.

2. Validation on Suffix: When "Other" is chosen, but the field is left blank. Should trigger a validation error asking for a response for "other" .
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![validation full name](https://user-images.githubusercontent.com/31284016/30608339-00517486-9d46-11e7-9a1a-e466df2d8ae8.PNG)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
Will be fixed with this bug #1738
