### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#1954]
**What did you do?**
Entered an invalid email address
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
A validation error stating an incorrect format.
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
A validation error providing a true statement.
**What did you see instead?**
An incorrect statement. 
*Include a high-level description of the feature or error here*
The validation error states _This email isn't valid Check for any spelling mistakes in your email address._ 
The application is not checking for spelling mistakes, it's checking for format. 

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/30641440-077f0a18-9dd5-11e7-9057-fa3448fbce97.png)

 - What browser and version are you using?
 - What operating system?

**Comment by Jay-Neighbours-I72** [comment]
Maybe change to "Check for any mistakes and/or the format"?

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/31298090-7eff18ba-aab6-11e7-8b58-f69a8499a29e.png)

**Comment by lauraponce** [comment]
LGTM!
