### ISSUE TITLE
Telephone Number Error Messages

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#1955]
**What did you do?**
Entered invalid telephone number
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
Error message. 
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
Change the verbiage in the error message. From "should be X numbers long" to Must be X digits. Also, when an error has been corrected by the applicant, then the error message should not include the corrected issue. 
**What did you see instead?**
A correct area code, but the error message says there is a problem with is. 
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

![telephone number error messages](https://user-images.githubusercontent.com/31284016/30644502-8f91f464-9de0-11e7-8e2a-e5682482829b.PNG)

 - What browser and version are you using?
 - What operating system?

**Comment by Jay-Neighbours-I72** [comment]
Looks like this is caused by the errors not clearing when the field is cleared (after user switches between US # and DSN

<img width="1270" alt="screen shot 2017-09-29 at 3 56 17 pm" src="https://user-images.githubusercontent.com/19935974/31033712-2234fa50-a52f-11e7-8fa1-086873a3584d.png">

**Comment by floresj** [comment]
This looks like it was indirectly resolved.

![selection_714](https://user-images.githubusercontent.com/5938731/36034514-5233f90c-0d82-11e8-8935-db8ad4dc4719.png)

![selection_715](https://user-images.githubusercontent.com/5938731/36034523-58ab1d42-0d82-11e8-8f26-b38784344903.png)
