### ISSUE TITLE
Employment activities - Present button

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1959]
When using the "Present" option in the date range: (note: when selecting "Present" first)

- [x] To date in accordion header says NA and years are not tracked in the progress bar

<img width="1161" alt="screen shot 2017-09-20 at 11 06 17 am" src="https://user-images.githubusercontent.com/19935974/30651487-de643026-9df3-11e7-832f-123c323494e4.png">
<img width="1242" alt="screen shot 2017-09-20 at 11 06 30 am" src="https://user-images.githubusercontent.com/19935974/30651488-de658066-9df3-11e7-876d-f607075d18e0.png">

**Comment by bmallred** [comment]
Resolved from another issue

**Comment by Jay-Neighbours-I72** [comment]
lgtm
