### ISSUE TITLE
Log in page - Missing elements

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1960]
Missing:
- [x] Show password link
- [ ] ~~Agreement blurb and link to full agreement~~

Storyboard issue with comp - #248

**Comment by Jay-Neighbours-I72** [comment]
@Jay-Neighbours-I72 to add comp

**Comment by bmallred** [comment]
Per discussion on daily stand-up we are going to scrap the paragraph text since the full agreement is presented when logging in to the system each time.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
