### ISSUE TITLE
Summary of Phone Numbers

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#1961]
**What did you do?**
Entered 5 phone numbers. 3 were invalid
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
The phone numbers displayed exactly the way thew were entered.
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
To display the invalid phone numbers exactly the way they were entered
**What did you see instead?**
Invalid telephone numbers were auto corrected in order to complete/correct the invalid fields.
*Include a high-level description of the feature or error here*

**Additional Information**
The applicant is certifying everything is correct that was entered on the form. Auto populating fields is not  accurate action. 
*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

![summary of phone numbers](https://user-images.githubusercontent.com/31284016/30696993-79e48232-9eab-11e7-935d-53d1850971b3.PNG)

![summary of phone numbers expanded](https://user-images.githubusercontent.com/31284016/30697010-868fd34c-9eab-11e7-8075-351ad6857e81.PNG)

 - What browser and version are you using?
 - What operating system?

**Comment by bmallred** [comment]
This appears to have been resolved.

## Current

![image](https://user-images.githubusercontent.com/697855/33611183-77bf6bf4-d99b-11e7-86eb-fe0dfca2c87f.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
