### ISSUE TITLE
Dates, Date Range, and Validation Error Messages

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#1964]
**What did you do?**
Entered invalid months and days. Also entered year 1000 in the "To and From" fields.
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
Validation to not allow those dates. I did receive validation messages for the invalid months and days, but they were not specific. 

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

![dates](https://user-images.githubusercontent.com/31284016/30701703-e4981bc2-9eb8-11e7-81da-790ded5db4c3.PNG)

 - What browser and version are you using?
 - What operating system?

**Comment by Jay-Neighbours-I72** [comment]
I'm not seeing this in Chrome on Staging...

<img width="1328" alt="screen shot 2017-10-06 at 9 48 38 am" src="https://user-images.githubusercontent.com/19935974/31280819-9df3ade8-aa7b-11e7-9d8f-8a1e0186e9cd.png">

**Comment by Jay-Neighbours-I72** [comment]
I was wrong, it was happening for me too, was fixed in this bug #2049
