### ISSUE TITLE
Your identifying  information - comment in wrong location

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1969]
- [ ] Comment in the wrong location

<img width="1022" alt="screen shot 2017-09-25 at 10 31 21 am" src="https://user-images.githubusercontent.com/19935974/30814418-1c800bc6-a1de-11e7-8b18-057bc3cb0b8b.png">

**Comment by floresj** [comment]
Looks like it was resolved:

![selection_808](https://user-images.githubusercontent.com/5938731/37467538-e9306858-2836-11e8-948e-9534a72137fb.png)
