### ISSUE TITLE
Form wide - Add comment style

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1970]
- [x] Grey line to the left of add comment is too close to the inputs

PT:
<img width="865" alt="screen shot 2017-09-25 at 10 31 26 am" src="https://user-images.githubusercontent.com/19935974/30815958-ac539f34-a1e2-11e7-9094-a7664caa2323.png">

Comp:
<img width="870" alt="screen shot 2017-09-25 at 11 16 09 am" src="https://user-images.githubusercontent.com/19935974/30816089-f30e8916-a1e2-11e7-9aea-f2024117354e.png">

**Comment by lauraponce** [comment]
LGTM!
