### ISSUE TITLE
Where you have lived - Address block error message

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1974]
APO/FPO block - when error is in state - validation window is missing text:
<img width="858" alt="screen shot 2017-09-25 at 4 17 53 pm" src="https://user-images.githubusercontent.com/19935974/30828916-42077a3a-a20d-11e7-820e-e96ece3b0597.png">

**Comment by bmallred** [comment]
Note to self:

 - The validation should not be fired off due to the error in the **state** dropdown being present.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
