### ISSUE TITLE
Employment record - Self Employment - Person who knows you blocks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1978]
Too many blocks for the person who knows you.

Remove:
- [x] Provide date of last contact
- [x] Relationship
- [x] Their contact information headline and text
- [x] Email address

 
<img width="1865" alt="screen shot 2017-09-26 at 1 34 05 pm" src="https://user-images.githubusercontent.com/19935974/30875484-b0a28cc8-a2c1-11e7-8965-cd9f17625a1e.png">

![screen shot 2017-09-26 at 1 50 52 pm](https://user-images.githubusercontent.com/19935974/30875496-baf9e46e-a2c1-11e7-9685-b146df002ea2.png)

**Comment by bmallred** [comment]
So here is an example where we had used the same component, in this case `Reference`, in two different sections but the fields do not align.

Suggested options:
 1. Remove the `Reference` component and do handle it inline
 2. Allow fields to be **toggled** through properties

**Comment by Jay-Neighbours-I72** [comment]
lgtm
