### ISSUE TITLE
Add comments to sections

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1982]
As an eApp applicant I want to potentially add comments to each section so that I can supplement my answer on the form with additional information.

Acceptance  Critieria
- [x] Utilize the design from #1872 
- [x] Add to each form section ~~/subsection~~

**Comment by bmallred** [comment]
@pjsumm does this remove the need for #1876?

**Comment by billy22g** [comment]
This isn't quite plain language. We're asking them if they would like to add a comment, to which the answer is either "Yes" or "No," not the comment itself. @Jay-Neighbours-I72 @lauraponce I think we should change the verbiage here to be more explicit in terms of what we'd like them to do, but I'll defer to you on how to do that.

<img width="734" alt="screen shot 2017-11-02 at 7 54 46 am" src="https://user-images.githubusercontent.com/5091167/32329643-3ce3f66a-bfa3-11e7-9b94-f346a0495488.png">

**Comment by lauraponce** [comment]
Good catch on the yes/no phrasing. How about something along the lines of, "Add a comment to clarify any of your responses in the Relationships section _(optional)_. And then replace Relationships with the name of whichever section this is in. Thoughts @Jay-Neighbours-I72?

**Comment by Jay-Neighbours-I72** [comment]
Ah good point @billy22g !

That text sounds great @lauraponce . 

One question Bryan and I went back and forth on was keeping or losing the "(optional)" text since we switched to marking required fields with the *. We settled on removing it and seeing if users struggled with it. 

Thoughts on that? Would we prefer to keep the "optional" text?

**Comment by billy22g** [comment]
I think I'd prefer to keep the (optional) for clarity as long as the language is somewhat directive. "Add a comment to clarify any of your responses in the section" seems like, "huh, do I have to? I probably don't have anything but maybe I should?" Just my :two-cents:

**Comment by lauraponce** [comment]
+1 to @billy22g's note about people second guessing if they should put something there. Having the optional text would help emphasize the fact that it's optional (along with no *) which would hopefully result in people who really have something to say adding text there and those who don't won't have to think twice about it.

**Comment by Jay-Neighbours-I72** [comment]
Sounds good to me. 

Issue here #2163

**Comment by bmallred** [comment]
New build being deployed with the changes from https://github.com/truetandem/e-QIP-prototype/pull/2165

**Comment by billy22g** [comment]
I don't see Laura's suggested text from above: "Add a comment to clarify..." here yet. It's still a Yes/No question ("Would you like to add...?) with an input field.

**Comment by billy22g** [comment]
@bmallred Bumping the above.

**Comment by bmallred** [comment]
@billyg ah didn't see the text change. Will update that shortly!

**Comment by billy22g** [comment]
LGTM. Let's test this @Jay-Neighbours-I72 and @lauraponce and make sure people really understand the purpose of it from the verbiage.
