### ISSUE TITLE
Verify People Who Know You Well

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#1987]
Confirm People Who Know You Well portion of the eApp form (sections 16 in SF-86 PDF). Equates to 1/4 page in the legacy SF-86.

Include these sections in the verification:
- [x] Provide three people who know you well and who preferably live in the U.S.

**Comment by Jay-Neighbours-I72** [comment]
Content verified
Bug #1998 #1999

**Comment by billy22g** [comment]
LGTM
