### ISSUE TITLE
Unlawful use - question - add help text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1993]
Clarify this question in help text
<img width="1164" alt="screen shot 2017-09-28 at 11 46 06 am" src="https://user-images.githubusercontent.com/19935974/30976375-9ff1b868-a442-11e7-84eb-67e9344e12c6.png">

**Comment by Jay-Neighbours-I72** [comment]
Having difficulty working up help text to explain this question.

Idea:

"We are asking if you have changed anything in an IT System without approval or unlawfully.
Example: Installed installing a program without approval."

Thoughts @billy22g @lauraponce ?

**Comment by billy22g** [comment]
Hmmm...I honestly don't have any great ideas here. Your example seems a bit limiting.

"We are asking if you have used or changed an IT system when it was not allowed."

But that's maybe a different question and a bit precarious. @lauraponce Thoughts? Regardless of what we do here, we should at the very least run it by @Sheldon1013 and @DBrenenborg, and likely Donna.

**Comment by Jay-Neighbours-I72** [comment]
leave alone for now per Sheldon
