### ISSUE TITLE
People who know you well - Relationship options

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#1999]
Change relationship options to:
- [x] Neighbor
- [x] Friend
- [x] Work associate
- [x] Schoolmate
- [x] Other

<img width="1354" alt="screen shot 2017-09-28 at 3 22 30 pm" src="https://user-images.githubusercontent.com/19935974/30986411-5624cf9e-a461-11e7-9b8e-66f99bb42692.png">

![screen shot 2017-09-28 at 3 22 25 pm](https://user-images.githubusercontent.com/19935974/30986415-592e4742-a461-11e7-8cc8-933459a6f622.png)

**Comment by lauraponce** [comment]
LGTM!
