### ISSUE TITLE
401 Unauthorized when I enter the 2fa code

### ISSUE THREAD

**Issue by adelevie** [truetandem/e-QIP-prototype#200]
**What did you do?**

Locally, on latest `master` (`df1c005f0abdbf0fc79751032fcb65a258dd2fc9`), on fresh `docker-compose build` and `up`:

Use either of the test accounts (`admin`, `test01`)

Delete and re-add eqip to Google Authenticator

Get the following error:

Failed to load resource: the server responded with a status of 401 (Unauthorized)

**What did you expect to see?**

I expected to be logged in.

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

 - What browser and version are you using?

Chrome.

 - What operating system?

OS X

**Comment by bmallred** [comment]
@adelevie are you still experiencing this?
