### ISSUE TITLE
Applicant's Country of Birth

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2004]
**What did you do?**
Entering applicant's country of birth
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
South Sudan
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
South Sudan not available country. but it is available in current e-QIP (see attachment)
**What did you see instead?**

*Include a high-level description of the feature or error here*
Received an error message when attempting to enter South Sudan as the applicants country of birth

![country of birth](https://user-images.githubusercontent.com/31284016/31089195-38158bb6-a771-11e7-84c6-cc8eaeaac5ab.PNG)

![south sudan](https://user-images.githubusercontent.com/31284016/31089205-3f21feee-a771-11e7-809f-85f177ee2d20.PNG)

 - What browser and version are you using?
 - What operating system?

**Comment by Jay-Neighbours-I72** [comment]
lgtm

![screen shot 2017-12-19 at 4 16 10 pm](https://user-images.githubusercontent.com/19935974/34179185-f060381c-e4d7-11e7-8b72-eb1de6ae531d.jpg)
