### ISSUE TITLE
Marital/relationships status - other explanation margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2007]
- [x] Close gap between other block and provide explanation input
- [x] Make sure there is a margin between the provide explanation input and the next headline

<img width="1178" alt="screen shot 2017-10-02 at 3 52 16 pm" src="https://user-images.githubusercontent.com/19935974/31096367-cd4c0c06-a789-11e7-8e15-6606bfabddc4.png">

**Comment by lauraponce** [comment]
LGTM!
