### ISSUE TITLE
Marital/relationships status - Foreign born branch - document expiration date

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2008]
We have an "I don't know" button on the "Provide document expiration date, if applicable" question.
The PDF form doesn't have this button. Was it added after a product owner request?

<img width="1000" alt="screen shot 2017-10-02 at 3 57 43 pm" src="https://user-images.githubusercontent.com/19935974/31096639-a39fc2ca-a78a-11e7-884e-fa2e5919370d.png">

![screen shot 2017-10-02 at 3 57 58 pm](https://user-images.githubusercontent.com/19935974/31096642-a4badd3e-a78a-11e7-8670-1e80cce92978.png)

**Comment by bmallred** [comment]
So it looks to be first introduced in PR https://github.com/truetandem/e-QIP-prototype/pull/999. I don't see any associated items specifically about it, but I'm gathering it was applied since the language had *"..., if applicable"*

@floresj any recollection on this?

**Comment by floresj** [comment]
Nothing specific comes to mind. Was probably one of those "Oh this makes sense" and just went with it.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 if we remove the IDK button I think the verbiage of the field title should be changed to drop the ***if applicable***. What do you think?

**Comment by Jay-Neighbours-I72** [comment]
Good point @bmallred, I think we should leave this open with the Question tag on here and run by Sheldon/Drew

**Comment by bmallred** [comment]
Make the button say *Not applicable*

**Comment by Jay-Neighbours-I72** [comment]
lgtm
