### ISSUE TITLE
Citizenship - Foreign passport - final question margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2012]
- [ ] Add margin between accordion and final question

<img width="1275" alt="screen shot 2017-10-03 at 10 54 58 am" src="https://user-images.githubusercontent.com/19935974/31132076-da6a1ab8-a829-11e7-81d6-02faff7c6f90.png">

**Comment by lauraponce** [comment]
LGTM!
