### ISSUE TITLE
Free Wi-Fi access warning

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2017]
In the existing eQIP form their is a warning that notifies users upon access to the system that they should not use free Wi-Fi access points when filling out the form due to the sensitive nature of the data being transmitted.  Attached is a screen capture of this warning.   

Should we prompt with the same information?

![freewifiwarning](https://user-images.githubusercontent.com/12962390/31138018-08a5d71c-a83b-11e7-82bd-316da065f6bb.png)

**Comment by pjsumm** [comment]
per emails received on 3 Oct 2017: Sheldon and Drew agree the message should be included.

**Comment by bmallred** [comment]
We skipped adding the image at the moment.
