### ISSUE TITLE
Marital Status - Birthdate

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2018]
- [x] Change "Birthdate" to "Provide the date of birth" to match the PDF. On both branches.

<img width="1380" alt="screen shot 2017-10-03 at 3 17 03 pm" src="https://user-images.githubusercontent.com/19935974/31144264-38c31c6c-a84e-11e7-8efa-2dddceac604a.png">

![screen shot 2017-10-03 at 3 18 07 pm](https://user-images.githubusercontent.com/19935974/31144265-38da3db6-a84e-11e7-9e9e-4246ea5061e8.png)

**Comment by lauraponce** [comment]
LGTM!
