### ISSUE TITLE
Marital status - Location input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2020]
- [x] In the Widowed, Divorced/Dissolved, or Annulled branch - Change "Provide location" to "Provide the location" to match PDF.

<img width="1245" alt="screen shot 2017-10-03 at 3 27 15 pm" src="https://user-images.githubusercontent.com/19935974/31144715-859a2746-a84f-11e7-993b-d1ea742c40b6.png">

![screen shot 2017-10-03 at 3 27 21 pm](https://user-images.githubusercontent.com/19935974/31144714-8599bd24-a84f-11e7-861e-123a97faf4be.png)

**Comment by lauraponce** [comment]
LGTM!
