### ISSUE TITLE
Marital - Cohabitant - Foreign born branch

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2030]
- [ ] Fix margins on "Provide document number" and "Provide document expiration date..."

<img width="1327" alt="screen shot 2017-10-04 at 10 04 39 am" src="https://user-images.githubusercontent.com/19935974/31180587-043e9256-a8ed-11e7-9919-480b71065107.png">

**Comment by floresj** [comment]
Margins looked to have been resolved
![selection_713](https://user-images.githubusercontent.com/5938731/36034298-9b974244-0d81-11e8-81ab-3b27560d06ba.png)
