### ISSUE TITLE
Information about you - Place of Birth - Not getting green circle

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2033]
- [x] Place of birth inputs are complete but green circle is not being applied in nav

<img width="2011" alt="screen shot 2017-10-04 at 11 07 26 am" src="https://user-images.githubusercontent.com/19935974/31183324-397ea558-a8f4-11e7-8842-bba95e41cac1.png">

**Comment by lauraponce** [comment]
LGTM!
