### ISSUE TITLE
Form wide - multi line inputs - max character error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2046]
Looks like the max character error message is missing

<img width="849" alt="screen shot 2017-10-05 at 4 34 30 pm" src="https://user-images.githubusercontent.com/19935974/31251213-350b1a5e-a9eb-11e7-9d5d-228cbf227661.png">
<img width="1210" alt="screen shot 2017-10-05 at 4 35 02 pm" src="https://user-images.githubusercontent.com/19935974/31251214-351b838a-a9eb-11e7-9342-632069d80d11.png">

Error text:
(heading)This response is too long
(p) Please keep your response to xx characters or less.

**Comment by bmallred** [comment]
Ah, good catch. Should we not allow them to put more text in or just allow it and then show the error?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 unable to reproduce in FF or Chrome. Are you still seeing this?

**Comment by Jay-Neighbours-I72** [comment]
Looks good now, capped at the max length
