### ISSUE TITLE
Instructions - top margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2047]
- [ ] Add top margin back in for instructions modul

Current:
<img width="1451" alt="screen shot 2017-10-06 at 2 09 27 pm" src="https://user-images.githubusercontent.com/19935974/31292125-37139d3e-aaa0-11e7-906e-4a7837e51de7.png">

Desired:
<img width="1448" alt="screen shot 2017-10-06 at 2 10 35 pm" src="https://user-images.githubusercontent.com/19935974/31292130-3abc6e8e-aaa0-11e7-9bce-9cf2f8f8d1fe.png">

**Comment by bmallred** [comment]
Going to have to spend some time to try and reproduce. Currently I am seeing this:

![image](https://user-images.githubusercontent.com/697855/31295603-29af926c-aaad-11e7-82b9-054443a2c7fc.png)

**Comment by bmallred** [comment]
Looks to be fixed on staging now (verified by @Jay-Neighbours-I72)
