### ISSUE TITLE
Multi line input - resizing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2048]
- [x] When resizing a multi line input the accordion/form shifts around.
- [x] Can we disable horizontal resizing and only allow up and down?

<img width="1291" alt="screen shot 2017-10-06 at 3 23 24 pm" src="https://user-images.githubusercontent.com/19935974/31294850-7a8db3ec-aaaa-11e7-9869-7c358c4bd5c9.png">

**Comment by lauraponce** [comment]
LGTM!
