### ISSUE TITLE
Date blocks - 00 error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2049]
- [x] Typing 00 throws a missing error

<img width="1366" alt="screen shot 2017-10-06 at 3 38 02 pm" src="https://user-images.githubusercontent.com/19935974/31295385-738bd220-aaac-11e7-916a-bfe99a27c8b0.png">

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/31297138-e4b45b7e-aab2-11e7-8f2b-fa3588137134.png)

**Comment by bmallred** [comment]
## Daterange

![image](https://user-images.githubusercontent.com/697855/31297245-54d18562-aab3-11e7-8a1a-ee5e71ace7fc.png)

**Comment by lauraponce** [comment]
This issue is resolved, but thoughts on reformatting the error text to say: 

"The month should be between 01 (January) and 12 (December)."

This matches the number format of 2 digits and also adds a space in there between the number and parenthesis.

@bmallred @Jay-Neighbours-I72

**Comment by billy22g** [comment]
+1 to @lauraponce's request.

**Comment by Jay-Neighbours-I72** [comment]
Good call @lauraponce ! Sorry I missed this earlier.

Put it in here ##2154
