### ISSUE TITLE
Substance use - Illegal - ordered to seek... - review screen

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2051]
Full accordion is filled out but incomplete error is showing

<img width="1188" alt="screen shot 2017-10-06 at 4 18 17 pm" src="https://user-images.githubusercontent.com/19935974/31296985-526cafb4-aab2-11e7-8290-caea7e7d2e78.png">

**Comment by bmallred** [comment]
Appears to only happen when selecting **Yes** to _Did you take action to receive counseling or treatment?_

**Comment by floresj** [comment]
I think it's something with the phone validation and the number type. That field doesn't appear on that screen but the phone validator is still checking for it.

**Comment by bmallred** [comment]
Old code:

```js
validActionTaken () {
    switch (this.actionTaken) {
      case 'Yes':
        return validGenericTextfield(this.treatmentProvider) &&
          new LocationValidator(this.treatmentProviderAddress).isValid() &&
          validPhoneNumber(this.treatmentProviderTelephone) &&
          new DateRangeValidator(this.treatmentDates).isValid() &&
          this.validTreatmentCompleted()
      case 'No':
        return validGenericTextfield(this.noActionTakenExplanation)
      default:
        return false
    }
  }
```

The validators are not calling `.isValid()`

**Comment by bmallred** [comment]
@floresj  and you are right as well about the `noNumberType` throwing an issue.

**Comment by billy22g** [comment]
I think this is good now, but I'll let @Jay-Neighbours-I72 give the final ok.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
