### ISSUE TITLE
Telephone Numbers

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2070]
**What did you do?**
Clicked on Contact Information
*Including steps for recreating it, if applicable.*
Entered email address, then scrolled down to enter telephone number 
**What did you expect to see?**
The time of day to contact applicant at the provided telephone number should not be chosen for the applicant. The check mark was defaulted to "Both"
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
The answer for the time of day to be contacted should not be defaulted to "Both"; the answer should be the applicant's choice.  
**What did you see instead?**
a check mark defaulted in the "Both" block. 

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/31546810-ec8a2abe-aff2-11e7-8996-7bdf7beb6418.png)

 - What browser and version are you using? Google Chrome
 - What operating system? Windows 7

**Comment by Jay-Neighbours-I72** [comment]
Will regroup in meeting with Sheldon/Drew

**Comment by Jay-Neighbours-I72** [comment]
Keeping this defaulted to both per Sheldon. Will save the user time.

**Comment by bmallred** [comment]
From review: leaving as default to **both**
