### ISSUE TITLE
Telephone Number Extension

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2071]
**What did you do?**
Entered and invalid extension
*Including steps for recreating it, if applicable.*
Entered 0 and ' 
**What did you expect to see?**
an error message letting the user know to use numbers between 0 and 9 only. 
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
 Extensions should be between 0 and 10

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/31558492-0beffe4c-b01b-11e7-8992-eb7835b49ac4.png)

 - What browser and version are you using? 
Google Chrome
 - What operating system?
Windows 7

**Comment by bmallred** [comment]
This appears to be fixed.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
