### ISSUE TITLE
Citizenship - Naturalized branch - address block not validating

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2074]
Not validating against USPS here

![screen shot 2017-10-13 at 2 55 15 pm](https://user-images.githubusercontent.com/19935974/31561724-c981a7c0-b026-11e7-9f3e-b9cb5cba1b49.png)

**Comment by floresj** [comment]
This appears to be working locally. Wondering if the api key isn't being set on staging.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
