### ISSUE TITLE
Foreign passport - Travel Date range

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2078]
If user selects "Present" on To date then enters a from date the To date is shown as "NA" in the accordion header.  
![screen shot 2017-10-13 at 3 24 58 pm](https://user-images.githubusercontent.com/19935974/31562814-ce6a3a14-b02a-11e7-8abe-6991e6794b3f.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I'm not seeing this happen anymore. Can you verify this?

**Comment by Jay-Neighbours-I72** [comment]
Looks like this has been fixed

**Comment by billy22g** [comment]
LGTM too
