### ISSUE TITLE
Info about you - phone numbers

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2079]
- [ ] Mark second phone number as "Optional"
- [x] Allow the one phone number to be removed (currently if you remove one of them it appears again)

**Comment by Jay-Neighbours-I72** [comment]
Note: Think through how optional looks.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this one may already be completed by PR #2166... was there something else needing to be addressed?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred Nope, this one is older and we talked through removing the asterisks on the optional number.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
