### ISSUE TITLE
Foreign passports - Passport number

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2080]
Passport number field - currently allows all characters

Should we cap at passport digit length? and/or only allow numbers and letters?

![screen shot 2017-10-13 at 3 36 19 pm](https://user-images.githubusercontent.com/19935974/31563294-6b4b93e0-b02c-11e7-93f8-b40a9554e52b.png)

**Comment by Sheldon1013** [comment]
No let it allow all characters and don't cap the length
