### ISSUE TITLE
Country not on list error text tweak

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2084]
Propose simplifying the error text:

Current
<img width="919" alt="screen shot 2017-10-16 at 2 50 23 pm" src="https://user-images.githubusercontent.com/19935974/31630228-09839e32-b284-11e7-9fdf-0805af801ec3.png">

Proposed change
<img width="933" alt="screen shot 2017-10-16 at 3 10 23 pm" src="https://user-images.githubusercontent.com/19935974/31630280-26e55056-b284-11e7-9b33-6529ef0158a5.png">

Thoughts @lauraponce @billy22g @pjsumm

**Comment by Jay-Neighbours-I72** [comment]
duplicate of #1666

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 okay to move this to **Current Sprint Completed** or **Closed**?
