### ISSUE TITLE
Residence - Residence type - Other - Provide explanation margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2085]
Tighten up the margin above the "Provide and explanation"

Current:
<img width="1011" alt="screen shot 2017-10-16 at 3 27 18 pm" src="https://user-images.githubusercontent.com/19935974/31631132-b6ef36f6-b286-11e7-8c11-a22552ab334f.png">

Desired:
<img width="1204" alt="screen shot 2017-10-16 at 3 28 36 pm" src="https://user-images.githubusercontent.com/19935974/31631138-bbeaf834-b286-11e7-8e64-4fc80d351160.png">

**Comment by bmallred** [comment]
Resolved in bb4ab32f

![image](https://user-images.githubusercontent.com/697855/37299157-e43e7c3a-25f8-11e8-9833-7a06d6b60b77.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
