### ISSUE TITLE
Previously used address block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2086]
When using an address from the previously used address book -

After address is input it doesn't get the green verified style and check marks

<img width="898" alt="screen shot 2017-10-16 at 3 25 44 pm" src="https://user-images.githubusercontent.com/19935974/31631179-e354155e-b286-11e7-9601-6a6c5ec40900.png">

**Comment by bmallred** [comment]
Note to self: Placing the following code in `Generic.jsx` makes this all work

```jsx
      if (updates.value !== undefined) {
        console.log(`triggering validation on receiving props for ${this.props.name}`)
        this.handleValidation()
      }
```

However, it is causing infinite loops elsewhere. Need to move to higher priority bugs but wanted to track this change.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
