### ISSUE TITLE
Information about you - name error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2089]
Middle name required error is missing on review screen

<img width="947" alt="screen shot 2017-10-18 at 11 46 12 am" src="https://user-images.githubusercontent.com/19935974/31728383-2dd8d460-b3fa-11e7-8be3-0640d8f61ccd.png">

**Comment by bmallred** [comment]
Appears to have been resolved:

![image](https://user-images.githubusercontent.com/697855/37298626-3054e714-25f7-11e8-8305-b3a24caf8d94.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
