### ISSUE TITLE
Your history - accordion captions

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2092]
Can we hide the second accordion caption on the individual sections? (Where you lived, worked, went to school)

They are repetitive on those sections.

Can we have them only show on the review screen?

On review screen can we change the text color to 5b606b to match the progress bars and add 1rem of space to the right of the icons (to space out the text)
![2017-10-19](https://user-images.githubusercontent.com/19935974/31785959-d9d731d2-b4d4-11e7-9e98-a17bf69fc7d4.jpg)

**Comment by bmallred** [comment]
Work already completed in #2251

**Comment by pjsumm** [comment]
work already reviewed in #2251
