### ISSUE TITLE
Second email address

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2096]
**What did you do?**
Provided only one email address
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
To be able to proceed with only one email address because I only have one. I provided my personal email because I'm unemployed and don't have a work email. 
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
Remove the requirement to provide more than one email address. 
**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

 Screenshot will not load. 

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
Sent email to Sheldon, Drew, and Donna raising this question.

**Comment by Jay-Neighbours-I72** [comment]
Per email we can change the second email to be optional

Changing this to a bug with the change being:
- [ ] Allow users to remove the second email
- [ ] Only require one email

**Comment by bmallred** [comment]
For the additional potential change

> Allow users to remove the second email

The email(s) may be removed but due to the requirement to display a minimum of 2 emails it is recreated. This can be confusing but before removing/adjusting the minimum we are going to test this in usability.
