### ISSUE TITLE
Confirm Social Security Number

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2097]
**What did you do?**
Entered a valid SSN
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
To proceed to next sub-section "Your identifying information"

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
Was asked to confirm my SSN. This is redundant because the SSN is validated against the agency side. The applicant is not able to log into the applicant side if their SSN does not match their profile on the agency side. 
*Include a high-level description of the feature or error here*

**Additional Information**

![image](https://user-images.githubusercontent.com/31284016/31820273-9972aa14-b56e-11e7-927a-5803a4ace230.png)

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
The verification was a request from product owner:

https://github.com/truetandem/e-QIP-prototype/pull/268
