### ISSUE TITLE
Applicant Under the Age of 16

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2103]
**What did you do?**
Enter a DOB that would make an applicant under the age of 16
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
A warning message to confirm the DOB is correct
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
An error message that states Applicants must be older than 16 years of age.
*Include a high-level description of the feature or error here*
The current e-QIP allows for applicant under the age of 16.  
**Additional Information**
![image](https://user-images.githubusercontent.com/31284016/31898512-5c2b5c52-b7e7-11e7-8c54-edd511894d50.png)

Current e-QIP
![image](https://user-images.githubusercontent.com/31284016/31898649-900f2526-b7e7-11e7-937a-a4eb941e01f4.png)

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
Added question label to confirm with Sheldon

**Comment by Jay-Neighbours-I72** [comment]
Per Sheldon, we will use the confirm message and button.
