### ISSUE TITLE
Review screen - Remove top Back/Next buttons

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2104]
Thinking about removing the top Back/Next buttons on the review screen for these reasons:

- [ ] Some users stumbled on this slightly then realized it was the review screen and/or questioned why they were there.
- [ ] Less chance of users skipping review 
- [ ] Would push the review content higher on the screen so people would see it quicker

Thoughts @billy22g @bmallred @pjsumm @floresj @lauraponce 

Current:
<img width="1861" alt="screen shot 2017-10-23 at 11 50 30 am" src="https://user-images.githubusercontent.com/19935974/31899734-6bba9586-b7ea-11e7-84cd-e4dd8b6861e6.png">

Suggested:
<img width="1868" alt="screen shot 2017-10-23 at 10 08 58 am" src="https://user-images.githubusercontent.com/19935974/31899741-70cea4ea-b7ea-11e7-91ed-cbbde9285fd4.png">

**Comment by lauraponce** [comment]
Jay and I have talked through this, but I wanted to share some thoughts here for visibility. By removing the buttons from the top, we are able to steer users into the direction we want them to go (through the review). Even if they didn't miss any of the fields, having them scroll through the review to get to the back/next is still an important step and the best way for them to catch potential errors. 

Also, the back/next buttons are at the bottom of the page under the content for the other sections so it would already be where they are used to looking.

**Comment by billy22g** [comment]
I agree with this pattern, and thanks for sharing the rationale. Planning to run it by Sheldon prior to implementation?

**Comment by Jay-Neighbours-I72** [comment]
This issue came up in usability testing round 13. Will be covered in the results during sprint review.

**Comment by bmallred** [comment]
This was completed in sprint 27
