### ISSUE TITLE
Add A Comment

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2117]
**What did you do?**
Entered 3,999 characters (includes spaces) into the field. 
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
No validation errors. All comment fields in the current e-QIP application holds no more than 4K characters
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
The comment field with a red outline, no explanation of the issue. 
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

![image](https://user-images.githubusercontent.com/31284016/32002392-68984886-b96a-11e7-9b00-0035a275de24.png)

What browser and version are you using?
Google Chrome: 
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
- [ ] Set max to 4k characters

- [ ] Fix error being thrown above

**Comment by billy22g** [comment]
LGTM
