### ISSUE TITLE
Cohabitant Info Block

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2118]
**What did you do?**
Clicked on the question mark to open the Info Block
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
An explanation/help answering the cohab question
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
The question asks "Do you presently reside...", but the Info Block shows "Need help deciding whether or not you _have had_...'. Also, the question asks Do you presently reside with a person...with whom you share bonds of affection, obligation, or other commitment. The Info Block tells the applicant to answer "No" if they do share any type of bonds.  
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

![image](https://user-images.githubusercontent.com/31284016/32006000-a5c4c9a6-b973-11e7-8886-57faeaa87eb4.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
Good catch!

Fixed here: #2130
