### ISSUE TITLE
Mark required fields

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2123]
As an eApp applicant I want to see a marker on fields that are required so that I can determine at the time I am entering data on the field whether the field is required or not. 

Acceptance Criteria
- [x] There is a visual cue on fields that are required
- [x] Optional fields do not have the visual cue

**Comment by Jay-Neighbours-I72** [comment]
Style for visual cue:
<img width="1300" alt="screen shot 2017-10-26 at 9 15 01 am" src="https://user-images.githubusercontent.com/19935974/32055679-79fb9936-ba30-11e7-8aba-58eadd7b0acc.png">

**Comment by billy22g** [comment]
Phone number is not marked required in any way. Thoughts on doing this elegantly @Jay-Neighbours-I72? 

<img width="746" alt="screen shot 2017-11-02 at 7 36 14 am" src="https://user-images.githubusercontent.com/5091167/32328739-86209ade-bfa0-11e7-8c59-be361cc7ae0b.png">

**Comment by Jay-Neighbours-I72** [comment]
Good catch.

I'm thinking we drop the * right after the phone number label (United States telephone number, DSN telephone number, International telephone number)

This way we are clear that only one phone number is required and it is clear an extension isn't required.

We should only be marking one email address as required too.
Bug here #2162

**Comment by bmallred** [comment]
On nearly every usage of the `Telephone` component there is a heading which is where these required asterisks are applied. This page is notorious for not being standard so whatever gets applied here will more than likely be a one off or we could give them headings.

Before the PR is was posed to possibly put the required marking(s) on the headings above the collection (i.e. _Your phone numbers_ and _Your email addresses_).

The two email requirement conflicts with https://github.com/truetandem/e-QIP-prototype/issues/998#issuecomment-295277085

**Comment by billy22g** [comment]
LGTM
