### ISSUE TITLE
Remove default day value

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2124]
As an eApp applicant I want to enter each value into the date field so that there are no default values added on my behalf. 

Acceptance Criteria
- [x] Remove the default day of "15"
- [x] Update error/info messages to reflect

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 should the message about estimation be presented only on the **required** error message or be standalone? Also, presented immediately or only on review?

![image](https://user-images.githubusercontent.com/697855/32395295-e6962098-c0b6-11e7-8dfc-a7b917abfe2a.png)

**Comment by billy22g** [comment]
LGTM
