### ISSUE TITLE
Usability testing round 13 - starting state

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2134]
- [x] Information about you section empty
- [x] Relationship section complete except:
- Relatives - Mother - Countries of citizenship empty
- Person who knows you well - Email address for one person empty

- [x] All other sections complete

Browser will be reloaded after each session and return to the starting state listed above.

**Comment by bmallred** [comment]
Just need to go through and validate all sections (i.e. show the green/red indicators once data is loaded)
