### ISSUE TITLE
All sections - accordions

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2138]
- [x] When coming back to a section all accordions with more than one item should load closed

(seen in Relatives section)

**Comment by bmallred** [comment]
Duplicate of #1933, #1321, #1976

**Comment by Jay-Neighbours-I72** [comment]
Direction:
- [ ] User comes back to a section with a single accordion item = Accordion item is open
- [ ] User comes back to a section with multiple accordion items = Accordion items are closed

**Comment by Jay-Neighbours-I72** [comment]
lgtm
