### ISSUE TITLE
Employment record - previously used address

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2139]
1. Add a previously used address button above supervisor's address.

![screen shot 2017-10-31 at 2 11 48 pm](https://user-images.githubusercontent.com/19935974/32241072-8eb3d7f8-be45-11e7-970a-584e8085009f.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 what would this be linked to? Just other supervisor addresses or something else as well?

**Comment by Jay-Neighbours-I72** [comment]
Thinking it would share within the accordion item, users input "Address of employment" before this one. This could be the same address.

![screen shot 2017-11-03 at 11 32 36 am](https://user-images.githubusercontent.com/19935974/32382123-d47eac12-c08a-11e7-8dd5-0b334862bf6f.jpg)

**Comment by bmallred** [comment]
![image](https://user-images.githubusercontent.com/697855/33034956-782e6f68-cdf7-11e7-9b3a-6403d6bf33c0.png)

**Comment by Jay-Neighbours-I72** [comment]
I'm not seeing this one up on dev.

![screen shot 2017-11-20 at 3 00 20 pm](https://user-images.githubusercontent.com/19935974/33038699-8c226d38-ce03-11e7-812d-d25d818664b3.jpg)

**Comment by bmallred** [comment]
Moving to **in progress** until the update is applied.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
