### ISSUE TITLE
Your History - Review error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2140]
Your history section is showing an error in navigation when all fields are complete and there are no errors.

![screen shot 2017-10-31 at 2 14 39 pm](https://user-images.githubusercontent.com/19935974/32241310-2d262ba2-be46-11e7-9a40-903f81fc8a2a.jpg)
![screen shot 2017-10-31 at 2 17 15 pm](https://user-images.githubusercontent.com/19935974/32241322-355116a2-be46-11e7-9ab8-fcb8ac1de299.jpg)

**Comment by bmallred** [comment]
This was an issue in two parts:

 - When telephone is IDK
 - When supervisor email is IDK

Pushed up in https://github.com/truetandem/e-QIP-prototype/commit/ef6b3126b3a4789cae0c2402c38ebf09da1d3b92 but need to bring over to master

**Comment by bmallred** [comment]
Merged in with https://github.com/truetandem/e-QIP-prototype/pull/2143
