### ISSUE TITLE
Foreign activities - section complete

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2141]
- [x] Foreign activities section is complete but navigation isn't showing complete.

![screen shot 2017-10-31 at 2 18 37 pm](https://user-images.githubusercontent.com/19935974/32241450-8429c2c4-be46-11e7-921e-ac591c08d013.jpg)
![screen shot 2017-10-31 at 2 19 40 pm](https://user-images.githubusercontent.com/19935974/32241459-8c04c35e-be46-11e7-9810-36b5069f19f1.jpg)

**Comment by bmallred** [comment]
Fixed on **develop** with https://github.com/truetandem/e-QIP-prototype/pull/2145 but needs to be brought over

**Comment by bmallred** [comment]
Brought over with https://github.com/truetandem/e-QIP-prototype/pull/2152
