### ISSUE TITLE
Main content shifted - nav rework

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2148]
- [x] After the nav rework the main content is shifting to the right at screen below 1420px (on content that is shorter than the navigation)

![screen shot 2017-11-01 at 4 07 10 pm](https://user-images.githubusercontent.com/19935974/32295206-f24c81dc-bf1e-11e7-8098-b8119275049c.jpg)
![screen shot 2017-11-01 at 4 07 17 pm](https://user-images.githubusercontent.com/19935974/32295207-f2559998-bf1e-11e7-8397-6179c7b247e3.jpg)

**Comment by bmallred** [comment]
Also related: #2161
