### ISSUE TITLE
School counter not working

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2160]
- [x] Added a school and counter didn't update

![screen shot 2017-11-03 at 9 58 08 am](https://user-images.githubusercontent.com/19935974/32377307-9140142a-c07d-11e7-8dd5-75cf57a3a73b.jpg)

**Comment by floresj** [comment]
Counting completed degrees within 10 years.

![screen shot 2017-11-06 at 12 48 54 pm](https://user-images.githubusercontent.com/5938731/32463185-e5e76fa8-c2f0-11e7-96d4-86edee1321a8.png)
