### ISSUE TITLE
Diagnoses main content pushed to the right when content is fixed to the top

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#2161]
To reproduce go to `/form/psychological/diagnoses` and select **No** on the initial branch question. Then scroll down so the main content goes sticky with the class `.sidebar-top-fixed`.

## Example

![image](https://user-images.githubusercontent.com/697855/32379357-b7704588-c083-11e7-9b45-caa3fd07fb0b.png)

**Comment by bmallred** [comment]
Re-opening this because I think there is still some work to be done (pushing pixels)

**Comment by bmallred** [comment]
TODO
 - [ ] Remove debug function once this is issue is finished.

**Comment by pjsumm** [comment]
looks good
