### ISSUE TITLE
Your contact information - required fields

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2162]
- [x] Mark only one email as required

- [x] Mark one phone number as required
Drop the * right after the phone number label (United States telephone number, DSN telephone number, International telephone number)

**Comment by bmallred** [comment]
Partial duplicate of #2096

**Comment by bmallred** [comment]
@floresj just FYI I want to get a hard confirmation that only one email is required prior to changing this again. It makes sense, but we changed it to require two in https://github.com/truetandem/e-QIP-prototype/issues/998#issuecomment-295277085 and I can't remember if there was conversation as to why

**Comment by bmallred** [comment]
Discussed with @Jay-Neighbours-I72. The move to **1 required email** was discussed on a separate email chain.
