### ISSUE TITLE
Submit - Credit release

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2171]
- [x] Clicking the "Next release" button on the Release of info & HIPPA release takes user to the bottom of the Credit release instead of the top.

**Comment by Jay-Neighbours-I72** [comment]
I'm not seeing the "Next release" buttons

![screen shot 2017-11-27 at 12 47 49 pm](https://user-images.githubusercontent.com/19935974/33280775-32e4ed7c-d371-11e7-9294-5e1e934dd870.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 there is no next button because the signature is **invalid**. You need to enter the applicant name in the **identification** section first so the signature can be applied!

**Comment by Jay-Neighbours-I72** [comment]
lgtm
