### ISSUE TITLE
Required field message not going away for international phone numbers

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#2175]

**Comment by bmallred** [comment]
Resolved with another fix from issue #2176

**Comment by billy22g** [comment]
This is somewhat related.

<img width="689" alt="screen shot 2017-12-27 at 12 49 24 pm" src="https://user-images.githubusercontent.com/5091167/34391658-6c94464e-eb04-11e7-9fdf-e1f2808386be.png">

**Comment by bmallred** [comment]
Interesting. I don't see that one but I see something very similar to it whenever switching the type of telephone number.

**Comment by billy22g** [comment]
LGTM
