### ISSUE TITLE
Half Screens

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2179]
**What did you do?**
Clicked on the "Next" tab to get to the next screen
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
The user to be at the top of the page on the next screen

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
The user was automatically navigated to the bottom half of the page on the next screen. I had to take the scroll bar to the bottom in order for the top of the page to be available. 

*Include a high-level description of the feature or error here*
Below are 2 examples of the prototype automatically navigating the user to the bottom of the screen 
**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/32501616-73f0a1c4-c3a6-11e7-96fc-4109e9fc0e21.png)

![image](https://user-images.githubusercontent.com/31284016/32501657-90b0ca6e-c3a6-11e7-847d-833a56aea027.png)

 - What browser and version are you using?
Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
We saw this in the last round of usability testing too. Bug has been fixed.

**Comment by Jay-Neighbours-I72** [comment]
Duplicate bug opened:
https://github.com/truetandem/e-QIP-prototype/issues/2309
