### ISSUE TITLE
Remove unnecessary "required tokens" on submission form(s)

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#2180]

**Comment by bmallred** [comment]
@billy22g we had those **required asterisks (*)** on the majority of the headers/text in the submission section and this was to turn remove them. I'll update the description text (thinking this was brought up in a meeting and done by the time the meeting was done)

**Comment by billy22g** [comment]
Ah, perfect @bmallred. Thanks!
