### ISSUE TITLE
Cannot login using Internet Explorer. Missing username+password elements

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#2184]

**Comment by lauraponce** [comment]
I don't have a VM in order to look at this one, does someone else have IE and can load the login page to upload a gif or screenshot?

**Comment by bmallred** [comment]
@lauraponce sure can. We'll ping you when we attach them here!

**Comment by pjsumm** [comment]
**IE 11**
![ie11-2018-01-03](https://user-images.githubusercontent.com/12962390/34524782-c2308520-f06a-11e7-8f36-e80b868bcfce.png)

**Edge**
![edge](https://user-images.githubusercontent.com/12962390/34524784-c45bb90a-f06a-11e7-8288-de8fd868d63f.png)

**Comment by billy22g** [comment]
LGTM
