### ISSUE TITLE
Evaluate eQIP Web Service

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2186]
As an eApp developer I need to review the eQIP web service documentation so that I can create a design for how best to take SF-86 form data from eApp and push it into eQIP.

Acceptance Criteria
- Review web service documentation
- Create basic design for leveraging the web service to submit SF-86 data to eQIP
- Review design with 18f PMO

**Comment by bmallred** [comment]
**Note**: Keeping this open until the test connection has been established and verified.

**Comment by pjsumm** [comment]
test connection completed, moving on to submitting data
