### ISSUE TITLE
People who know you well - email not showing required error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2188]
- [ ] On review screen - the email address is not getting the red outline style and the "this input is required" error message when blank

- [ ] Same with Rank/title

![screen shot 2017-11-10 at 2 39 23 pm](https://user-images.githubusercontent.com/19935974/32675472-04088a76-c625-11e7-8e0f-d89e22582f1d.jpg)

![screen shot 2017-11-10 at 2 41 37 pm](https://user-images.githubusercontent.com/19935974/32675572-4da991e8-c625-11e7-8aa4-ca2771746803.jpg)

**Comment by bmallred** [comment]
Looks to have been resolved

![image](https://user-images.githubusercontent.com/697855/33034854-30a75b46-cdf7-11e7-9159-66f387119248.png)

![image](https://user-images.githubusercontent.com/697855/33034880-46b0894e-cdf7-11e7-84da-19e41f1f59e6.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
