### ISSUE TITLE
Place of birth & other shortened address blocks - asterisks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2203]
Put asterisks on individual input field on all address blocks.

Example Place of Birth (want asterisks on City, State, & County)
![screen shot 2017-11-17 at 10 20 44 am](https://user-images.githubusercontent.com/19935974/32954484-3d06d3a8-cb81-11e7-89c7-f6df7de96941.jpg)

like in the full address block:
![screen shot 2017-11-17 at 10 21 18 am](https://user-images.githubusercontent.com/19935974/32954497-44929b3e-cb81-11e7-914f-6dd8e78bcf31.jpg)

**Comment by bmallred** [comment]
These are two different layouts since the address field has quite a few. In each of these cases would we remove the asterisk on the field title (**Provide your place of birth**) as well?

**Comment by bmallred** [comment]
This is covered in more detail and a broader scope in issue #2361
