### ISSUE TITLE
Where you have lived - Is/was this residence - other margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2208]
- [x] reduce margin above other input

current:
![screen shot 2017-11-17 at 11 27 28 am](https://user-images.githubusercontent.com/19935974/32957675-6b339faa-cb8a-11e7-8e6d-04c871fbbd92.jpg)

desired:
![screen shot 2017-11-17 at 11 28 58 am](https://user-images.githubusercontent.com/19935974/32957713-8658df48-cb8a-11e7-9fd2-c3db7782205d.jpg)

**Comment by bmallred** [comment]
## Preview

![image](https://user-images.githubusercontent.com/697855/33101475-67eeb096-cee6-11e7-8359-3e663d52d97c.png)

**Comment by lauraponce** [comment]
LGTM!
