### ISSUE TITLE
Your history - phone number blocks - Can't deselect "I don't know"

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2210]
Can't uncheck "I don't know" buttons

![screen shot 2017-11-17 at 11 53 22 am](https://user-images.githubusercontent.com/19935974/32959031-4550d9de-cb8e-11e7-9d3b-7079e5d74080.jpg)

**Comment by lauraponce** [comment]
LGTM!
