### ISSUE TITLE
Your history - school - Add another degree

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2213]
- [x] Can't change add another degree question back to "No".
Warning comes up, click ok, answer stays "Yes"

![screen shot 2017-11-17 at 3 32 41 pm](https://user-images.githubusercontent.com/19935974/32967741-affc2aea-cbac-11e7-85aa-4a8027c4c0e8.jpg)

![screen shot 2017-11-17 at 3 32 46 pm](https://user-images.githubusercontent.com/19935974/32967742-b018463a-cbac-11e7-9457-a88360a0efff.jpg)

**Comment by bmallred** [comment]
This appears to be working now. Will synchronize development environment.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
