### ISSUE TITLE
People who know you well - accordion items on review

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2220]
- [x] Accordion items are showing errors when all fields are complete

![screen shot 2017-11-20 at 3 08 08 pm](https://user-images.githubusercontent.com/19935974/33039582-6aaab216-ce06-11e7-9229-0dd0c2a6785b.jpg)

**Comment by bmallred** [comment]
Should be resolved with #2173

**Comment by Jay-Neighbours-I72** [comment]
lgtm
