### ISSUE TITLE
Section nav - green dots

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2221]
Sections that are not getting green dots when complete:

- [x] Date of birth
- [x] Place of birth
- [x] People who know you well

![screen shot 2017-11-20 at 3 09 47 pm](https://user-images.githubusercontent.com/19935974/33039644-a6f44d5e-ce06-11e7-861d-adcd1ae2e423.jpg)
![screen shot 2017-11-20 at 3 22 53 pm](https://user-images.githubusercontent.com/19935974/33039674-bcbe02ec-ce06-11e7-813e-41ebeba62842.jpg)

**Comment by bmallred** [comment]
Looks to have been fixed. There is another issue concerning the counters.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
