### ISSUE TITLE
People who know you well - phone number "I don't know"

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2222]
- [ ] Phone number type should be greyed out when "I don't know is selected"

![screen shot 2017-11-20 at 3 23 55 pm](https://user-images.githubusercontent.com/19935974/33039707-dc1e6910-ce06-11e7-964d-c14674bed222.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this looks like it is already fixed. Can you verify this?

**Comment by Jay-Neighbours-I72** [comment]
lgtm

![screen shot 2017-12-22 at 10 07 51 am](https://user-images.githubusercontent.com/19935974/34302684-fe049510-e6ff-11e7-883a-ffc334a0fc60.jpg)
