### ISSUE TITLE
Police record > Domestic violence

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2234]
- [ ] Move asterisks up to question about having another order

![screen shot 2017-11-22 at 12 45 33 pm](https://user-images.githubusercontent.com/19935974/33142075-389d92f6-cf83-11e7-8f03-04a2a4d75e91.png)

**Comment by bmallred** [comment]
This is no longer valid since the section has been converted to an accordion.

**Comment by bpdesigns** [comment]
A noted above, style has been updated, but the issue of the asterisk has been resolved. Looks good. 

<img width="850" alt="screen shot 2018-03-29 at 5 50 27 pm" src="https://user-images.githubusercontent.com/15329140/38115399-e8eb576a-3379-11e8-9966-5927760c8346.png">

**Comment by bmallred** [comment]
Also, issue #2361 (when implemented) should cover all the other issues w/ asterisks elsewhere
