### ISSUE TITLE
Convert JSON to eQIP XML

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2248]
As an eApp developer I want to convert eApp form data in JSON format into the XML format used by the eQIP SOAP-based web service API so that I can submit the eApp form data via web service to the legacy eQIP database.

Acceptance
- data from eApp JSON structure is converted to XML schema used by eQIP web service
- data can be transmitted via eQIP SOAP web service and saved in eQIP database

**Comment by bmallred** [comment]
@pjsumm should this be closed?

**Comment by pjsumm** [comment]
@bmallred yes, since we broke it up and those pieces are all finished,  we can close this down too.  thanks for the heads up.
