### ISSUE TITLE
Applicant resubmit design

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2257]
As an eApp designer I want to design the user interaction required when a submitted application has been returned to an applicant for correction so that my design can be reviewed and approved for prototype implementation

Acceptance Criteria
- [x] Create a design comp illustrating the flow of returning a submitted application to the applicant to correct
- [x] Review design concept with stakeholders

**Comment by Jay-Neighbours-I72** [comment]
Goal is to reuse the final review screen style and functionality but use content related to the form rejection and user's next steps.

![e-app-comp-return-user-error](https://user-images.githubusercontent.com/19935974/33450553-293cb9ba-d5da-11e7-8ab0-e8c9a15a5606.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Current eQIP rejection flow:
![current-rejection-flow-01](https://user-images.githubusercontent.com/19935974/33782311-35bd0864-dc26-11e7-99e8-7e3b2ac56e1c.jpg)

Pilot rejection flow:
![pilot-rejection-flow-01](https://user-images.githubusercontent.com/19935974/33782329-41a15d38-dc26-11e7-9799-418f124d7a43.jpg)

**Comment by Jay-Neighbours-I72** [comment]
@Jay-Neighbours-I72 to include specific issue error messaging for "desired" flow.

**Comment by Jay-Neighbours-I72** [comment]
@billy22g @lauraponce This all look ok to you?

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 I'm not sure it's as explicit or clear as I would like to see. For example, the end of the process for eApp looks the same as e-QIP above it. It needs to specify that the user is logging back into **eApp**, not into e-QIP to fix their errors. We should also likely explicitly specify Greg's proposed idea that the "fixed" form data would just overwrite the initial form data so we don't have to deal with conflicts. I think being as explicit as possible in this would be best at each step. Like the "locking" and "unlocking" parts to me are actual steps in the flow. Even in the "Remedy flags errors and creates a draft rejection email," is that still going to be the case? Isn't it going to be a more manual process? I can't remember from Friday's call.

**Comment by Jay-Neighbours-I72** [comment]
@billy22g The majority of that makes sense to me, seems like there are a few pieces where we have different interpretations from last Friday's call. 

Do you @pjsumm have some time chat and get on the same page?

**Comment by Jay-Neighbours-I72** [comment]
Updated Current flow:
![current-rejection-flow-01](https://user-images.githubusercontent.com/19935974/33998509-b19755b4-e0b5-11e7-93da-e6e430095287.jpg)


Updated Pilot flow:
![pilot-rejection-flow-01](https://user-images.githubusercontent.com/19935974/33998527-bba0d512-e0b5-11e7-852d-e5fd7d02271f.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Updated with success paths 
![current-rejection-flow-01](https://user-images.githubusercontent.com/19935974/34174991-dcc7c306-e4c8-11e7-9044-0e8e10f54f53.jpg)

![pilot-rejection-flow-01](https://user-images.githubusercontent.com/19935974/34174993-df24a97a-e4c8-11e7-8a47-047ab27a8257.jpg)

**Comment by billy22g** [comment]
LGTM

**Comment by Jay-Neighbours-I72** [comment]
Updated per Greg's feedback on call
![pilot-rejection-flow-01](https://user-images.githubusercontent.com/19935974/34725664-9eeec1b2-f51f-11e7-8b54-a155e9039e93.jpg)
