### ISSUE TITLE
Phone number blocks - changing time of day answer

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2261]
Scenario 
User selects day only or night only.
User selects type of phone number.
Time of day input is changed to both.

- [ ] Don't auto change the time of day checkbo

![screen shot 2017-11-30 at 3 13 13 pm](https://user-images.githubusercontent.com/19935974/33452751-3c252646-d5e1-11e7-90d7-3466ed03c395.jpg)
![screen shot 2017-11-30 at 3 13 23 pm](https://user-images.githubusercontent.com/19935974/33452752-3d2766da-d5e1-11e7-92cc-406c425e12f2.jpg)

**Comment by bmallred** [comment]
Fixed in #2329 along with similar bug #2304

**Comment by Jay-Neighbours-I72** [comment]
I am still seeing this happen. I can show over a hangout.

**Comment by bmallred** [comment]
I'm seeing this again as well. One of the PRs might have squashed the update. Will check it out when I get back

**Comment by Jay-Neighbours-I72** [comment]
lgtm now
