### ISSUE TITLE
Relationships>Marital - Missing button

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2262]
Currently in a civil marriage branch:
Missing the "Use my current address" button below "Provide this person's current address, if different than your current address" address block

- [x] Add or text and "Use my current address" button

![screen shot 2017-11-30 at 3 31 45 pm](https://user-images.githubusercontent.com/19935974/33453560-10658f2a-d5e4-11e7-9fd3-cc7ddca3ab6b.jpg)
![screen shot 2017-11-30 at 3 33 04 pm](https://user-images.githubusercontent.com/19935974/33453561-12932bb8-d5e4-11e7-867f-9d7a53e1497f.jpg)

**Comment by bmallred** [comment]
Do you think just having a "previous address" functionality would suffice?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred not in this case because they haven't entered their current address yet

This one is a bit more complex:

The current form has this section coming after "Where you have lived"

In that scenerio the "Use my current address" button works. We have this relationships section coming first.

Would it make sense to add context to the button? "Use my current address (You will enter your current address later). Then later the form would have to pull that current address back here.

Thoughts Brian, @billy22g @lauraponce ?

**Comment by billy22g** [comment]
That's so interesting. I don't think I ever thought about implications of putting people you know prior to your own basic history. I almost think we should reverse the order and make "Your History" the second section. I think it would make more sense conceptually, and we'd be able to use this as intended.

The progression would be: super basic info, more detailed info about yourself, then more detailed info about your relatives/family, then citizenship, military, etc. Thoughts?

**Comment by lauraponce** [comment]
That makes sense to me @billy22g. It would be a progression of info about yourself, then it moves onto other things. Thinking about it more, this might be better for users because it eases them into the difficulty of the questions for things they would know more off the top of their head (e.g. their own addresses) vs things they would have to ask someone about and might need more time to find out (e.g. their relatives' addresses, DOBs, etc)

**Comment by Jay-Neighbours-I72** [comment]
@billy22g @lauraponce I am on board with switching those 2 sections.

New order would be
1. Information about you
2. Your History
3. Relationships
...

**Comment by Jay-Neighbours-I72** [comment]
@bmallred and I talked through this and thought a tweak on the headline and when we show the "Use current" button made sense.

Here is the description from the content tracking doc:
![screen shot 2018-03-15 at 11 05 46 am](https://user-images.githubusercontent.com/19935974/37471734-de219518-2840-11e8-9f50-7c16629944ae.jpg)

**Comment by floresj** [comment]
Looks nice.

**Comment by billy22g** [comment]
Fancy. Agreed with John, looks good. Let's make sure we get it in front of people ASAP and let Sheldon and Chris know what we did (a standup will be fine for that).

**Comment by pjsumm** [comment]
Checked in staging.  Navigation order is correct (Info about you, Your History, Relationships).  Tried without a current address and verified the text label, then tried with a current address and verified both the label and the "use my current address" label was there.  All looks good.
