### ISSUE TITLE
Information about you JSON to eQIP XML

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2263]
As an eApp developer I want to convert eApp **Information About You** form data in JSON format into the XML format used by the eQIP SOAP-based web service API so that I can submit the eApp form data via web service to the legacy eQIP database.

Acceptance Criteria
- [ ] data from eApp **Information About You** section JSON structure is converted to XML schema used by eQIP web service
- [ ] data can be transmitted via eQIP SOAP web service and saved in eQIP database

**Comment by billy22g** [comment]
LGTM
