### ISSUE TITLE
Phone blocks - false validation after deselecting i don't know

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2273]
- [ ] User fills in all or part of a number
- [ ] User then selects "I don't know"
- [ ] User deselects "I don't know" and number is wiped to all 0s but showing green valid style

![screen shot 2017-12-04 at 1 36 50 pm](https://user-images.githubusercontent.com/19935974/33569634-46f68b72-d8f8-11e7-87a2-b6019faea1f1.jpg)
![screen shot 2017-12-04 at 1 36 54 pm](https://user-images.githubusercontent.com/19935974/33569637-49598144-d8f8-11e7-95d6-8bb8404f78d0.jpg)
![screen shot 2017-12-04 at 1 36 57 pm](https://user-images.githubusercontent.com/19935974/33569643-4b79de06-d8f8-11e7-9d4c-25505dd5e0eb.jpg)

**Comment by bmallred** [comment]
May have been resolved from another update but not seeing this anymore.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
