### ISSUE TITLE
Submit screen - Releases - Instruction relocate 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2285]
- [x] Move the instructions out of the certification and sit below the "Please sign the releases below..." headline.

Prototype:
![screen shot 2017-12-06 at 11 06 08 am](https://user-images.githubusercontent.com/19935974/33671641-2af82d84-da76-11e7-8777-102e7bb7ef23.jpg)

-
Desired
![35345008-7ee5c30a-00fc-11e8-93f0-fa889744dfeb](https://user-images.githubusercontent.com/19935974/35350257-644d76c8-010b-11e8-9e7a-54bf86384243.jpg)

**Comment by lauraponce** [comment]
Here it is on dev: ![screen shot 2018-02-01 at 11 00 04 am](https://user-images.githubusercontent.com/21222704/35688400-169eed28-073f-11e8-90c8-b5edbb8cb5a6.png)

@bmallred can you add a little more padding above the certification box to separate those elements and be closer to what @Jay-Neighbours-I72 shared?

**Comment by Jay-Neighbours-I72** [comment]
lgtm
