### ISSUE TITLE
Where you have lived - Address blocks - not validating and deleting inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2291]
On all address blocks (except the first accordion):

- [x] Address fields are not getting green valid style when entering
- [x] Address doesn't validate when complete
- [ ] After a few seconds or clicking around all address inputs are deleted and green valid style shows

Entering address
![screen shot 2017-12-07 at 10 33 09 am](https://user-images.githubusercontent.com/19935974/33723358-7f30f70e-db3a-11e7-8c19-5b4b90b33f40.jpg)

After a few seconds
![Uploading Screen Shot 2017-12-07 at 10.33.25 AM.jpg…]()

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 when you have a few moments can you verify if this is happening still?

**Comment by Jay-Neighbours-I72** [comment]
I am not seeing this anymore, all looks good
