### ISSUE TITLE
Employment record - Reason for leaving - Second question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2296]
- [x] Change the "Yes" to a "No" isn't working (it stays on "Yes")

Note: same issue with the branch directly below Reason for leaving.

Edit - looks like only clicking "No" on the first question within the branch removes the second+ items.

![screen shot 2017-12-07 at 3 08 04 pm](https://user-images.githubusercontent.com/19935974/33736639-5edf77ec-db61-11e7-8840-f9d1c303dec3.jpg)
![screen shot 2017-12-07 at 3 08 14 pm](https://user-images.githubusercontent.com/19935974/33736641-60145772-db61-11e7-90a0-c0703286d2c9.jpg)

**Comment by Jay-Neighbours-I72** [comment]
This removed now but the confirm message is asked twice:

![screen shot 2017-12-21 at 1 23 48 pm](https://user-images.githubusercontent.com/19935974/34269426-3b6089e0-e652-11e7-8841-00ce27095ed0.jpg)

**Comment by bmallred** [comment]
Shouldn't it ask once each time you change it to "No"?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred yeah it should only ask once each time you change a yes branch to a no.

Form wide it looks like the confirm message is showing twice:
Click "No"
Error message 1 - Click "Ok"
Error message shows again immediately 

![screen shot 2018-01-17 at 8 54 53 am](https://user-images.githubusercontent.com/19935974/35046243-6777ce22-fb64-11e7-9456-bcbb663d9e01.png)

**Comment by Jay-Neighbours-I72** [comment]
Duplicate of #2373

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 you okay closing this since #2373 is a different issue? This one fixed what it was originally set to do but there was another bug introduced in a different update which is what the other issue tracks.

**Comment by Jay-Neighbours-I72** [comment]
Yeah, #2373 will cover this.
