### ISSUE TITLE
Employment record - National Guard branch - Last question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2299]
- [x] Last question in Employment record - when user click "Yes" new accordion item is made but starts closed. It should start open like other second/last questions.

![screen shot 2017-12-08 at 11 02 46 am](https://user-images.githubusercontent.com/19935974/33773882-6c744652-dc07-11e7-8b5f-e4e154488eb8.png)
![screen shot 2017-12-08 at 11 02 52 am](https://user-images.githubusercontent.com/19935974/33773883-6dba9d9a-dc07-11e7-9c00-8fb3fbe27139.png)

**Comment by bmallred** [comment]
That is so weird... taking a look at it!

**Comment by Jay-Neighbours-I72** [comment]
lgtm
