### ISSUE TITLE
Info about you -> your contact info: Selecting phone type changes checkbox input

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#2304]
**What did you do?**
Entered a phone number. Then selected "Night" in the checkbox below it. Then clicked "Cell" in the boxes below that.

**What did you expect to see?**
The "Night" checkbox to stay where I had it.

**What did you see instead?**
The "Night" checkbox deselected, and the "Both" checkbox became selected automatically.

<img width="537" alt="screen shot 2017-12-11 at 9 08 05 am" src="https://user-images.githubusercontent.com/5091167/33840806-3705fe0e-de53-11e7-9c6b-3895335eae81.png">

**Comment by billy22g** [comment]
This same behavior is still happening for me.

**Comment by billy22g** [comment]
Related, when my cursor is in one of the number fields for the phone number, and I click one of the checkboxes (e.g. "Night only"), the checkbox is highlighted in gray around it, but **not** selected. When someone clicks in the checkbox, regardless of where their cursor currently is, the checkbox that they click should be selected.

**Comment by bmallred** [comment]
Related to #2261. I need to take a look at why this was undone.

**Comment by billy22g** [comment]
LGTM
