### ISSUE TITLE
Form cropped on laptop screens

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2309]
Seen in usability testing and confirmed
Screen width 1077px

- [ ] When going through form using next buttons content is being cropped (hidden below header) and user can't scroll up to it.

![screen shot 2017-12-13 at 10 48 00 am](https://user-images.githubusercontent.com/19935974/33948244-6a154154-dff4-11e7-9c20-2a1c5bc2f330.jpg)
![screen shot 2017-12-13 at 10 55 36 am](https://user-images.githubusercontent.com/19935974/33948246-6b725438-dff4-11e7-8004-e45643513e9f.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Also seeing this on around 1250px width:
![screen shot 2018-01-05 at 3 25 32 pm](https://user-images.githubusercontent.com/19935974/34626989-dafae302-f22c-11e7-838d-75b99e32aeda.jpg)
![screen shot 2018-01-05 at 3 25 38 pm](https://user-images.githubusercontent.com/19935974/34626990-db1d2e76-f22c-11e7-9f07-d66a560c8940.jpg)

**Comment by Jay-Neighbours-I72** [comment]
I think this issue might need a higher priority. It can keep users from filling out the form and is a big stumbling block for people. In this round of usertesting.com videos a user saw this and it caused confusion and slowed them down:

![screen shot 2018-01-09 at 4 05 08 pm](https://user-images.githubusercontent.com/19935974/34743417-a1b1bf2a-f557-11e7-8448-e357c958d507.jpg)

https://drive.google.com/drive/u/0/folders/1-q8Kl-v1Y85mkw30zK3pk09Bp8cXV4fr
video #4914 
time stamp 12:26

Thoughts @billy22g @bmallred @lauraponce

**Comment by billy22g** [comment]
Agreed. Maybe just bring up with Sheldon in standup tomorrow or via email? I think he'll agree.

**Comment by lauraponce** [comment]
Agreed that this should be a higher priority. It breaks the experience for people who are on this screen size.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
