### ISSUE TITLE
Your history - Review - Phone block error message

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2315]
- [x] When phone number type is selected then "I don't know" is selected a missing error message is thrown

![screen shot 2017-12-13 at 2 13 02 pm](https://user-images.githubusercontent.com/19935974/33957513-d2d5af06-e00f-11e7-868f-afb50cdd4052.jpg)

![screen shot 2017-12-13 at 2 13 06 pm](https://user-images.githubusercontent.com/19935974/33957516-d4afc56e-e00f-11e7-82f4-2ad4f9203780.jpg)

**Comment by Jay-Neighbours-I72** [comment]
still seeing this on dev:

![screen shot 2018-01-11 at 3 48 31 pm](https://user-images.githubusercontent.com/19935974/34846673-e5db9fd2-f6e6-11e7-9ad4-aacd437ef906.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Also seeing this in other sections:

![screen shot 2018-01-15 at 11 10 23 am](https://user-images.githubusercontent.com/19935974/34951613-dcb0f8c0-f9e4-11e7-8691-6f908c036963.jpg)
![screen shot 2018-01-15 at 11 10 51 am](https://user-images.githubusercontent.com/19935974/34951614-dcba5280-f9e4-11e7-85be-478a69bf1fde.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I'm not seeing this. Can you give it another go or get @floresj or myself on a screenshare?

**Comment by floresj** [comment]
@Jay-Neighbours-I72  Ok, I see the behavior. I did:
- empty on review screen
- then select type
- then select IDK
What's funny is when you click I don't know and then click again anywhere in the page, the error goes away.

**Comment by Jay-Neighbours-I72** [comment]
I'm stilling seeing this on dev

![screen shot 2018-02-21 at 2 34 20 pm](https://user-images.githubusercontent.com/19935974/36501157-5c38f2ea-1714-11e8-932b-f93dc42989d5.jpg)

**Comment by bmallred** [comment]
Might need a screen share on this
