### ISSUE TITLE
Where you lived - (and all accordion items) truncate length

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2316]
- [x] Truncate long addresses to avoid date dropping onto another line

![screen shot 2017-12-13 at 3 25 05 pm](https://user-images.githubusercontent.com/19935974/33960834-fb9b7128-e019-11e7-8248-9d9a3f59a29e.jpg)

**Comment by bmallred** [comment]
no comment :smile:

**Comment by bpdesigns** [comment]
looks good
