### ISSUE TITLE
Individual asterisks on date blocks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2327]
- [ ] Put individual asterisks on date blocks (month, day, year)

![screen shot 2017-12-18 at 2 45 58 pm](https://user-images.githubusercontent.com/19935974/34124813-4c6fb9a6-e402-11e7-8983-c36f45f75b39.jpg)

**Comment by bmallred** [comment]
This is covered in more detail and a broader scope in issue #2361
