### ISSUE TITLE
Relatives - current employment address block - rework

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2332]
Need to account for Outside US addresses

- [x] Use the full address block (without APO/FPO . - Per Donna)

![screen shot 2017-12-19 at 11 11 27 am](https://user-images.githubusercontent.com/19935974/34166706-9a075b8c-e4ad-11e7-8abc-58a59ff5c5c1.jpg)

**Comment by bmallred** [comment]
What if their work address is outside the US but an APO/FPO/DPO?

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Just clarifying,  so for this, we want a full US Address and International address blocks right?

**Comment by Jay-Neighbours-I72** [comment]
@floresj Yeah. Everything but APO/FPO

**Comment by Jay-Neighbours-I72** [comment]
lgtm
