### ISSUE TITLE
Relationships JSON to eQIP XML

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2335]
As an eApp developer I want to convert eApp relationships section form data in JSON format into the XML format used by the eQIP SOAP-based web service API so that I can submit the eApp form data via web service to the legacy eQIP database.

Acceptance Criteria
- [ ] Data from eApp the relationships section JSON structure is converted to XML schema used by eQIP web service
- [ ] Data can be transmitted via eQIP SOAP web service and saved in eQIP database

**Comment by billy22g** [comment]
LGTM
