### ISSUE TITLE
Applicant successful submission workflow

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2337]
As an eApp designer I want to capture the user interaction workflow when an applicant successfully submits their SF-86 application to the Army PSI CoE and the application has been reviewed and accepted  so that the team understands the steps needed to schedule an investigation and become part of the PIPS pipeline.

Acceptance Criteria
- [x] Create a workflow diagram showing an accepted application from eApp funneling into PIPS and an investigation starting.
- [x] Review workflow diagram with stakeholders

**Comment by Jay-Neighbours-I72** [comment]
First pass:

![screen shot 2018-01-08 at 2 01 14 pm](https://user-images.githubusercontent.com/19935974/34689247-d6768252-f482-11e7-8b5f-559363d5e0a2.png)

**Comment by billy22g** [comment]
LGTM
