### ISSUE TITLE
Error list comp

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2346]
As an eApp designer II want to create a design comp to represent a list of errors at the top of a section review form so that users can see the errors that exist in the review form that follows.

Acceptance Criteria
- [x] create a design comp representing the user experience for list errors at the top of a section review
- [x] Review design comp with 18f team and key stakeholders

**Comment by Jay-Neighbours-I72** [comment]
![e-app-review-issue-list](https://user-images.githubusercontent.com/19935974/34742588-ad431954-f554-11e7-82df-af6c5de4dd1a.jpg)

**Comment by billy22g** [comment]
LGTM
