### ISSUE TITLE
Addendum question for other names

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#2350]
Reference: https://github.com/truetandem/e-QIP-prototype/pull/2344#pullrequestreview-84852122

**Comment by bmallred** [comment]
> [ @bmallred ] This is something we should probably clarify with @Jay-Neighbours-I72 if there should be a yes/no at the end of other names.
> [ @bmallred ] If the answer is to not have that then possibly hard code this to be "No"?
> [ @floresj ] Good call. Sir @Jay-Neighbours-I72, thoughts on if we should add the Yes/No confirmation branch question at the end of the OtherNames accordion within the information about you section?

![image](https://user-images.githubusercontent.com/5938731/34225818-8f337838-e57c-11e7-9599-24eb7a52c8a2.png)

**Comment by Jay-Neighbours-I72** [comment]
@bmallred @floresj 
Good catch, yes we need to add the yes/no question and remove the "Add another name" button.

Per content guide the text is:
Do you have additional names to enter?

![screen shot 2017-12-22 at 8 45 30 am](https://user-images.githubusercontent.com/19935974/34300114-99d9b40e-e6f4-11e7-898c-7b727656a97d.jpg)

**Comment by bmallred** [comment]
Completed in PR #2439

**Comment by lauraponce** [comment]
This was resolved in #2426
