### ISSUE TITLE
Employment record - remove "reason for leaving" question when job is to "Present"

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2354]
Remove the question "Provide the reason for leaving the employment activity" when the job's to date is "Present"

![screen shot 2018-01-02 at 2 25 49 pm](https://user-images.githubusercontent.com/19935974/34496929-7b002c7e-efc9-11e7-87b5-03247034016e.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 is it still valid if they have **additional periods of activity with this employer**?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred yeah, Additional periods and Reason for leaving are 2 separate branches in the PDF guide

**Comment by billy22g** [comment]
Maybe, but you can be requested an elevated clearance while staying at your present job.

**Comment by bmallred** [comment]
- [ ] @Jay-Neighbours-I72 send email to @Sheldon1013 for release to Donna
 - [ ] Check with OPM on intent of the question

**Comment by Jay-Neighbours-I72** [comment]
From Donna:

I'm thinking this is probably something that was never considered in regards to how automation could support the collection.  With that thought, I agree that when information is collected for the current employer, and employment dates support the fact (meaning, an end date is not provided; not sure if there is an option to indicate present or current ), there is not a need to present the question regarding reason for leaving the employment.

Sounds like we are good to hide this question when the job is current.

To @bmallred 's point I think we should show it when additional periods of activity are given for a job.

**Comment by Jay-Neighbours-I72** [comment]
lgtm on staging
