### ISSUE TITLE
Log in screen - password input

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2368]
Password input not getting green valid style

![screen shot 2018-01-09 at 11 02 09 am](https://user-images.githubusercontent.com/19935974/34730164-9eada5e4-f52c-11e7-9b35-89f684c722f5.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I thought we had removed this because it could be misinterpreted as having a valid password?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred good point, if we aren't validating it here then yeah we prob shouldn't show either.

Let's run with no green style on either.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
