### ISSUE TITLE
Section intro - wrong nav section open

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2375]
When using the next button to navigate through the form the left navigation doesn't update and open the current section.

Goal is to have only the section with the active page expanded.

![screen shot 2018-01-10 at 11 40 56 am](https://user-images.githubusercontent.com/19935974/34784114-5e7ec834-f5fb-11e7-957a-7d1b2fe7e81b.jpg)
![screen shot 2018-01-10 at 11 41 12 am](https://user-images.githubusercontent.com/19935974/34784116-5e8ac710-f5fb-11e7-9eb0-8bef7c0ff592.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I'm not seeing this. Usually with something like this there is a javascript error thrown. May need to get w/ you to extract that from the devtools!

**Comment by Jay-Neighbours-I72** [comment]
lgtm
