### ISSUE TITLE
People who know you well - incomplete error not showing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2378]
- [x] Accordion item incomplete error not showing on review screen

![screen shot 2018-01-10 at 2 25 10 pm](https://user-images.githubusercontent.com/19935974/34791184-2f071edc-f612-11e7-837a-fdd50761f65c.jpg)

If an item is opened then closed the errors will show:
![screen shot 2018-01-10 at 2 25 20 pm](https://user-images.githubusercontent.com/19935974/34791219-4f7ee9d8-f612-11e7-81d2-850e174fc9f6.jpg)

**Comment by bmallred** [comment]
This appears to be happening on all accordions.

**Comment by floresj** [comment]
This looks like it was resolved in another PR.

![selection_780](https://user-images.githubusercontent.com/5938731/36681088-9cfa9746-1ae5-11e8-9a94-e47e9db5b478.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
