### ISSUE TITLE
People who know you well - errors not showing in navigation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2379]
- [x] Errors in the section are not showing in navigation:
![screen shot 2018-01-10 at 2 28 05 pm](https://user-images.githubusercontent.com/19935974/34791298-942090be-f612-11e7-9baf-caebd4d96ca8.jpg)

**Comment by floresj** [comment]
This looks like it was resolved in another validation PR.

![selection_779](https://user-images.githubusercontent.com/5938731/36680296-5c0bb320-1ae3-11e8-8de9-5a731e8e6db6.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
