### ISSUE TITLE
Unlocking eApp form

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2381]
As an eApp administrator I want to unlock an applicant's locked eApp application so that if errors or omissions are found during agency review the applicant can access their eApp application, make the necessary updates, and resubmit their completed edits.

Acceptance Criteria
- [x] after the form is unlocked, user is able to edit their eApp application data

**Comment by bmallred** [comment]
Due to possible sensitive configuration and infrastructure data the standard operating procedures have been captured in a document on the teams internal library.
