### ISSUE TITLE
Firefox - Where you lived counter

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2405]
- [ ] Full accordion item complete with no errors but counter not updating

![screen shot 2018-01-15 at 11 23 05 am](https://user-images.githubusercontent.com/19935974/34952093-8382a954-f9e6-11e7-9b6c-4f2d8fe1eb24.jpg)
![screen shot 2018-01-15 at 11 23 12 am](https://user-images.githubusercontent.com/19935974/34952094-838d30ae-f9e6-11e7-8dfa-e87372b6d9ba.jpg)
![screen shot 2018-01-15 at 11 24 19 am](https://user-images.githubusercontent.com/19935974/34952115-a4d5b8e4-f9e6-11e7-9a1e-42664a1a913f.jpg)

**Comment by bmallred** [comment]
Missing the day in the date range

**Comment by Jay-Neighbours-I72** [comment]
good catch! closing
