### ISSUE TITLE
Employment - accept offer - close margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2410]
- [ ] Close margin below Accept offer yes/no and the explanation box

![screen shot 2018-01-15 at 3 20 24 pm](https://user-images.githubusercontent.com/19935974/34960167-b76fe2ce-fa07-11e7-8d33-a9a56ea69e62.jpg)

**Comment by bmallred** [comment]
Closing because this appears to have been resolved (ba3b30e8 and 92f1c0b8)

![image](https://user-images.githubusercontent.com/697855/37298965-50a59756-25f8-11e8-90f6-17ea5dbd6872.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
