### ISSUE TITLE
Financial - Non-payment consequence validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2413]
Both of these dates should not be allowed before DOB

![screen shot 2018-01-15 at 3 30 21 pm](https://user-images.githubusercontent.com/19935974/34960500-1883a0ae-fa09-11e7-9b92-20e609db6a88.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this is what I am seeing with a DOB of 1/1/1982:

![image](https://user-images.githubusercontent.com/697855/34991624-4bc9474a-fa98-11e7-8c77-073852fe0ca4.png)

**Comment by Jay-Neighbours-I72** [comment]
My mistake here too @bmallred . Closing now.
