### ISSUE TITLE
Substance use - dates validation

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2414]
All of these dates should not be allowed before DOB

- [x] Security clearance position
![screen shot 2018-01-15 at 3 39 20 pm](https://user-images.githubusercontent.com/19935974/34960763-4c3d70a4-fa0a-11e7-9b6a-f3932348a241.jpg)
_

- [x] Additional instances
![screen shot 2018-01-15 at 3 48 59 pm](https://user-images.githubusercontent.com/19935974/34961082-a8e98ef4-fa0b-11e7-853f-a68f9876b7bd.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 you may want to check you have a DOB entered. They all worked with the exception of the following:

 - [ ] Substance abuse > Use of alcohol > Additional instances > Provide the date counseling or treatment ended
![image](https://user-images.githubusercontent.com/697855/34991859-282d1e64-fa99-11e7-8a5d-deec8ccb7c4c.png)

 - [ ] Substance use > Illegal use of drugs and drug activity >
Security clearance position > Provide the dates of involvement/use
![image](https://user-images.githubusercontent.com/697855/34991903-48dae164-fa99-11e7-918f-29c4f754e3a4.png)

**Comment by Jay-Neighbours-I72** [comment]
Weird, I'll check again today. I was in Firefox so I'll check in a few other browsers too.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred You were right! I must have cleared DOB at some point yesterday. I removed all but the 2 with issues form the list.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 cool thanks for double checking!
