### ISSUE TITLE
Data persistence - Info about you

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2417]
Areas where data is not saving:

- [x] Other names used
- [x] Your Phone number (contact info)
- [x] DOB
- [x] Section comment

**Comment by bmallred** [comment]
@floresj reopened this since **section comments** haven't been handled yet.

**Comment by Jay-Neighbours-I72** [comment]
Lgtm

**Comment by bmallred** [comment]
That was after a browser refresh too, I don't think this has been implemented but definitely will be put on the top of the stack

**Comment by Jay-Neighbours-I72** [comment]
lgtm

![screen shot 2018-03-15 at 9 34 50 am](https://user-images.githubusercontent.com/19935974/37466441-20f6e3f0-2834-11e8-9309-3f4ff1944093.jpg)
