### ISSUE TITLE
Capitalization of suffix in signature blocks

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#2419]
Suffixes should be capitalized. At present in the signature, the second letter of the suffixes are not capitalized.

<img width="609" alt="screen shot 2018-01-16 at 10 20 32 am" src="https://user-images.githubusercontent.com/5091167/35002488-0d0a2664-faa7-11e7-9d09-baf47301764b.png">

**Comment by lauraponce** [comment]
LGTM!
