### ISSUE TITLE
Police record - type of charge buttons - can't select

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2420]
- [x] Can't select the type of charge buttons

![screen shot 2018-01-16 at 2 15 08 pm](https://user-images.githubusercontent.com/19935974/35007468-d1ab87cc-fac7-11e7-9fb2-624a1e09597a.jpg)

**Comment by lauraponce** [comment]
LGTM!

**Comment by Jay-Neighbours-I72** [comment]
I'm still seeing this on staging and dev @bmallred @floresj
