### ISSUE TITLE
Police record - domestic violence - accordion

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2422]
- [x] Looks like the Domestic violence question should be in an accordion

![screen shot 2018-01-16 at 2 23 12 pm](https://user-images.githubusercontent.com/19935974/35007896-dee53cc0-fac8-11e7-96bb-5c998de8e87e.jpg)

**Comment by Jay-Neighbours-I72** [comment]
In my opinion is it worth it (not before the pilot obviously, but eventually). Without an accordion I think people would get lost in this section if adding more than 1 instance. 

Curious what others think, adding question tag.

**Comment by bmallred** [comment]
I'm inline with what you said

**Comment by bmallred** [comment]
From meeting: go ahead with the change.

**Comment by floresj** [comment]
Looks like it was resolved in PR #2724.

**Comment by bpdesigns** [comment]
Looks good.

<img width="706" alt="screen shot 2018-03-29 at 6 03 12 pm" src="https://user-images.githubusercontent.com/15329140/38115820-7f005394-337b-11e8-9dbb-4a4f597a24b9.png">
