### ISSUE TITLE
Other names used - second question

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2426]
- [x] Remove "Add another name"
- [x] Add "Do you have additional names to enter?" and Yes/No button below accordion to match PDF form content and other accordions on new form

![screen shot 2018-01-17 at 9 25 52 am](https://user-images.githubusercontent.com/19935974/35047766-eaa3deae-fb68-11e7-992a-90cb77c790e1.png)
![screen shot 2018-01-17 at 9 29 36 am](https://user-images.githubusercontent.com/19935974/35047772-f3b3984a-fb68-11e7-82de-0917b28df1c1.png)

**Comment by lauraponce** [comment]
LGTM!
