### ISSUE TITLE
Save button breakpoint 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2427]
Some users from usability testing have been frustrated with the save button overlapping content.

To avoid this overlap we can put the save button below the Next/Prev button sooner at 1325px

Overlap:
![screen shot 2018-01-17 at 9 46 52 am](https://user-images.githubusercontent.com/19935974/35048534-5f38d7ae-fb6b-11e7-87e1-7e8d402c8a3c.png)

Thoughts @lauraponce ?

**Comment by lauraponce** [comment]
That sounds good to me @Jay-Neighbours-I72. We definitely don't want it to cover up the content for people, so moving it down seems like the best alternative!

**Comment by bmallred** [comment]
Breakpoint set to `1412px` to sync with othe **tablet** view behavior.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
