### ISSUE TITLE
Review and Submit - Remove section number

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2430]
- [x] Remove the number 11 from the review and submit section

This isn't a full numbered section and conflicts with the sections complete counter
![screen shot 2018-01-17 at 10 26 42 am](https://user-images.githubusercontent.com/19935974/35050537-11ee703e-fb71-11e7-886b-facf6e581c19.png)

**Comment by lauraponce** [comment]
LGTM!
