### ISSUE TITLE
Firefox - js error - investigative & criminal history review

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2433]
- [x] js error when trying to go to the review screen

![screen shot 2018-01-17 at 1 50 18 pm](https://user-images.githubusercontent.com/19935974/35061016-f1864c50-fb8d-11e7-9057-b424ba3ccdec.png)
![screen shot 2018-01-17 at 1 53 28 pm](https://user-images.githubusercontent.com/19935974/35061004-e7dd4ee2-fb8d-11e7-9adb-f0dab241461b.png)

**Comment by floresj** [comment]
This may have been resolved by previous updates that fixed issues where we were pointing to wrong variable names.

**Comment by Jay-Neighbours-I72** [comment]
No JS error anymore but the review screen drops me halfway down the screen rather than at the top. (firefox)

![screen shot 2018-02-21 at 4 02 44 pm](https://user-images.githubusercontent.com/19935974/36505198-bc8e6268-1720-11e8-9634-aaa17989e8cf.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72  I'm okay reopening this... But this is an unrelated issue and if you see more of this mind referencing them back to here?

**Comment by Jay-Neighbours-I72** [comment]
Good point, just tested again and i'm not seeing the review screen issue anymore.
