### ISSUE TITLE
Mental health - missing next button text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2437]
- [x] Missing Next button text

![screen shot 2018-01-17 at 2 11 11 pm](https://user-images.githubusercontent.com/19935974/35061859-76ac0670-fb90-11e7-8960-2f931a45d6f1.png)

**Comment by Jay-Neighbours-I72** [comment]
This button is in now but is linking to a blank page

![screen shot 2018-02-21 at 2 31 31 pm](https://user-images.githubusercontent.com/19935974/36501025-f8bf969c-1713-11e8-8254-7f15db18a71b.jpg)

**Comment by bmallred** [comment]
Lol, this happened because at the time there was an intro page... Sometimes waiting for QA items pays off :-)

**Comment by Jay-Neighbours-I72** [comment]
looks good on staging, not up on dev yet
