### ISSUE TITLE
Marital - non citizen document type - other button

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2448]
- [x] Other button is too wide

![screen shot 2018-01-18 at 1 51 02 pm](https://user-images.githubusercontent.com/19935974/35115579-b7251b6c-fc56-11e7-8b33-82ef9f272f93.jpg)

**Comment by Jay-Neighbours-I72** [comment]
@bpdesigns @bmallred This looks really strange, like the text is all 3 times too small but the other elements are the same size.

This is what I see in chrome
![screen shot 2018-03-30 at 9 49 48 am](https://user-images.githubusercontent.com/19935974/38139957-b290c9c6-33ff-11e8-9f58-89eb72c92f6e.jpg)

**Comment by bpdesigns** [comment]
that screenshot was with (i think) 67% size type. this is what I see at 100%

<img width="1186" alt="screen shot 2018-03-30 at 9 53 40 am" src="https://user-images.githubusercontent.com/15329140/38140081-4357e728-3400-11e8-8116-2b70fa3aea56.png">

**Comment by bpdesigns** [comment]
I'm viewing on Chrome. Sorry for the confusion with the type size. Its the same as what you see

**Comment by Jay-Neighbours-I72** [comment]
lgtm
