### ISSUE TITLE
IE11 - Estimated checkbox not aligned or missing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2466]
- [x] Estimated checkbox not aligned
- [x] Check boxes can't be selected
- [x] Some parts of the form the checkboxes are missing

![screen shot 2018-01-22 at 2 49 12 pm](https://user-images.githubusercontent.com/19935974/35241133-7ab33242-ff83-11e7-9841-b693401999a4.jpg)

![screen shot 2018-01-30 at 11 15 43 am](https://user-images.githubusercontent.com/19935974/35577189-ec877a64-05ae-11e8-8e71-01bf5ab0639d.jpg)

![screen shot 2018-01-30 at 11 41 02 am](https://user-images.githubusercontent.com/19935974/35578602-8d5c4430-05b2-11e8-8c2c-a942a598614f.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Most of this looks great.

- [ ] When estimate is selected though the "Estimated" text disappears 
![2018-02-28](https://user-images.githubusercontent.com/19935974/36811779-fd5b6b16-1c9c-11e8-86a2-5973618218f2.png)

**Comment by floresj** [comment]
Woaaa that's crazy. Checking it out.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
