### ISSUE TITLE
Dates for Other Names Used

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2473]
**What did you do?**
On the Other Names Used screen I entered a From date **before** my DOB; the error message tells me my From date should be **after** my DOB. However, the application allowed me to enter a From date the **same**  as my DOB. 
*Including steps for recreating it, if applicable.*
Repeated same step as I did when creating the issue
**What did you expect to see?**
An error message stating the **From** date should be **after** your DOB
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
accepted data
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35333912-818feb1c-00de-11e8-8b41-8b8b3aa6af99.png)

![image](https://user-images.githubusercontent.com/31284016/35333953-a930425c-00de-11e8-9acf-3d5604562f27.png)
![image](https://user-images.githubusercontent.com/31284016/35333982-c89b1fd6-00de-11e8-9ab5-29e973072dd7.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
This looks to be fixed for me (DOB is 8/8/1980 in this example)

![screen shot 2018-02-15 at 11 34 00 am](https://user-images.githubusercontent.com/19935974/36268765-620cca8a-1245-11e8-8399-983fed76cc33.jpg)
![screen shot 2018-02-15 at 11 42 56 am](https://user-images.githubusercontent.com/19935974/36268766-6218b304-1245-11e8-9129-5ed05a194fa1.jpg)
