### ISSUE TITLE
POB Screen

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2482]
**What did you do?**
Left the County or Province field blank
*Including steps for recreating it, if applicable.*
Same steps as initial finding
**What did you expect to see?**
Did not expect to see the County as a required field when applicant provided the City and State
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35345555-f30ed34c-00fd-11e8-8155-025a2d17d053.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
We have heard this a lot in usability testing too.

Solution is to put individual asterisks on required inputs to be clear they are required.
open issue #2361
