### ISSUE TITLE
SSN Confirmation

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2483]
**What did you do?**
No validation to ensure required field is populated
*Including steps for recreating it, if applicable.*
Same steps as initial finding (left the confirmation field blank)
**What did you expect to see?**
Error message stating confirmation of SSN is required. 
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
application accepted blank fields that are required
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35346125-61118bf4-00ff-11e8-9948-f78b5395d8c9.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
Good catch, I'm also seeing this.

- [ ] Flag SSN empty field with error message on review screen


![screen shot 2018-02-15 at 11 34 00 am](https://user-images.githubusercontent.com/19935974/36268333-2defe288-1244-11e8-873c-b924a06260c7.jpg)
