### ISSUE TITLE
Saving Data and Logging Out

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2485]
**What did you do?**
In the Review section I fixed an error by providing data in a field I left blank. After satisfying the error I logged out. When I logged back in my data was not saved; the field went back to a blank field. 
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
My data to be there when I logged back in
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
No data in a required field (with no error message that field is required). 
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35347294-bb8b2600-0102-11e8-85d4-debc9c89d565.png)

![image](https://user-images.githubusercontent.com/31284016/35347307-c4a209f2-0102-11e8-9d33-d8b871025e5b.png)
![image](https://user-images.githubusercontent.com/31284016/35347315-cf3f32f4-0102-11e8-85d8-6140fc22ecba.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
@bmallred is the save button functional currently or still waiting to be hooked in?

**Comment by Jay-Neighbours-I72** [comment]
lgtm
