### ISSUE TITLE
Logging in with CAC

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2486]
**What did you do?**
Attempted to log in as applicant
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
Log in with CAC, Log in with PIV, and Log in with Username and Password
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
Logging in with PIV is missing
*Include a high-level description of the feature or error here*
Not all agencies have CAC cards
**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35347676-d0d5a39a-0103-11e8-9d72-5961dcd5b3e3.png)

 - What browser and version are you using?
 - What operating system?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 maybe we should have this say "CAC/PIV" instead? It is the same button but may help with some confusion.

**Comment by pjsumm** [comment]
looks good
