### ISSUE TITLE
Adding Phone Number in Review Section

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2487]
**What did you do?**
Opened the screen to reveal the error in the Review section. The error was for selecting a phone number **type**, but I didn't include a phone number.  
*Including steps for recreating it, if applicable.*
Leaving phone number blank in order to correct my error in the Review section. 
**What did you expect to see?**
A place to add a phone number
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
A section to choose a phone number type. 
*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35348197-5966d58e-0105-11e8-94a4-b08d07b1246a.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by Jay-Neighbours-I72** [comment]
I am not seeing this on dev in chrome

![screen shot 2018-02-15 at 10 52 15 am](https://user-images.githubusercontent.com/19935974/36265944-5981f734-123e-11e8-8990-7e3a824418d2.jpg)
