### ISSUE TITLE
Category II STIG Review Controls 159 - 237

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2491]
As an eApp developer I want to review STIG Category II controls so that I can write a response for each control, and derive a list of action items to address.

CCI-001878 - CCI-003289

Acceptance Criteria
- [x] Write responses for each item in the list
- [x] Utilize DISA STIG viewer and put written results in a checklist file

**Comment by bmallred** [comment]
Status | #  
---------|----
Open | **13**
Not a Finding | **36**
Not Applicable | **30**

Items remaining (open and still under review):

 - [ ] CCI-001878
 - [ ] CCI-001879
 - [ ] CCI-001880
 - [ ] CCI-001881
 - [ ] CCI-001882
 - [ ] CCI-001919
 - [ ] CCI-001942

**Comment by bmallred** [comment]
## Current status

Status | #  
---------|----
Open | **8**
Not a Finding | **36**
Not Applicable | **35**

Assigned items have been reviewed with some remaining for discussion with team:

 - [ ] CCI-003256 (open)
 - [ ] CCI-003124 (open)
 - [ ] CCI-002450
 - [ ] CCI-002386 (open)
 - [ ] CCI-002264
 - [ ] CCI-002263
 - [ ] CCI-002262 (open)
 - [ ] CCI-002238 (open)
 - [ ] CCI-002052
 - [ ] CCI-001942 (open)
 - [ ] CCI-001919 (open)

**Comment by pjsumm** [comment]
checklist has been submitted to DISA
