### ISSUE TITLE
People Who Know You Well Count

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2504]
**What did you do?**
Added 4 people to the People That Know You Well section. 
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
The count should be 4/3
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
The count shows 2/3
*Include a high-level description of the feature or error here*
The count is missing 2 people (there are no errors in this section) 
**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35402938-09417696-01cc-11e8-96f6-33fa38e27725.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by bmallred** [comment]
I will need to check this. Currently it only counts people who pass validation. So

 1. if some of the items are invalid there is a bug display the error message on the item
 2. if all items are valid there is a bug in the counter

**Comment by Jay-Neighbours-I72** [comment]
Correct that we are only counting complete/valid accordion items. We decided on that because a user wouldn't be able to submit with an incomplete or invalid entry (with an error).

This screenshot might have some incomplete inputs that will be flagged on the review screen.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred @floresj 

I believe we decided to count everyone added to the accordion here. So this one should read 4/3:


![screen shot 2018-03-05 at 11 17 11 am](https://user-images.githubusercontent.com/19935974/36986183-3fe75f1c-2067-11e8-864b-d8e4ffc31998.jpg)

**Comment by bmallred** [comment]
Still only counts when valid correct?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred Ignore my comment, we talked through this on standup today and are going to leave the counter as is. Stopping at 3/3 People added

**Comment by Jay-Neighbours-I72** [comment]
lgtm
