### ISSUE TITLE
Mother's DOB

### ISSUE THREAD

**Issue by gshannon00** [truetandem/e-QIP-prototype#2506]
**What did you do?**
Entered a DOB for Mother same as applicant's
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
Error message stating DOB must be prior to your DOB
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
Application accepted the same DOB for mother
*Include a high-level description of the feature or error here*
Mother should not be able to have the same DOB as applicant. 
**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35406030-d1153eba-01d5-11e8-994c-c788171207c4.png)
![image](https://user-images.githubusercontent.com/31284016/35406038-d7a5556c-01d5-11e8-97fd-549e5e5785fc.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by bmallred** [comment]
Ah, this makes sense. @Jay-Neighbours-I72 was this part of the validation matrix? If it wasn't maybe it should be and we need to track it?

**Comment by Jay-Neighbours-I72** [comment]
Looks like it is part of the validation matrix @bmallred 

![screen shot 2018-01-26 at 9 52 35 am](https://user-images.githubusercontent.com/19935974/35445171-c25d714a-027e-11e8-867a-aa9d0b9f5880.jpg)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
![screen shot 2018-02-21 at 11 34 17 am](https://user-images.githubusercontent.com/19935974/36492450-2b8da384-16fb-11e8-978b-49ec5d5c494b.jpg)
