### ISSUE TITLE
Contact info - email and phone error messages

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2511]
- [x] "Required input" error message is missing from email and phone on review screen

![screen shot 2018-01-25 at 3 31 50 pm](https://user-images.githubusercontent.com/19935974/35410922-e008cb58-01e4-11e8-961c-6163f33f8250.jpg)

**Comment by bmallred** [comment]
This is happening on several accordions and has been reported in other issues

**Comment by floresj** [comment]
This looks like it was resolved in another PR.

![selection_774](https://user-images.githubusercontent.com/5938731/36679874-521ced44-1ae2-11e8-9e18-bfc8d47a8f54.png)

![selection_775](https://user-images.githubusercontent.com/5938731/36679858-49769e2e-1ae2-11e8-8aff-c6230ea05fae.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
