### ISSUE TITLE
Contact info - remove bottom "close" links

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2512]
- [x] Remove both bottom "close" links

These were removed a while ago on all other accordions and relocated to the top.

![screen shot 2018-01-25 at 3 51 47 pm](https://user-images.githubusercontent.com/19935974/35411761-e75f5644-01e7-11e8-80da-d19fdb2da077.jpg)
![screen shot 2018-01-25 at 3 52 06 pm](https://user-images.githubusercontent.com/19935974/35411762-e76f8d16-01e7-11e8-98ad-3498de15b9eb.jpg)

**Comment by bmallred** [comment]
Resolved in #2778

**Comment by Jay-Neighbours-I72** [comment]
lgtm
