### ISSUE TITLE
IE 11 - buttons across form - too much margin below

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2523]
- [x] Buttons with margin issues

![screen shot 2018-01-26 at 4 04 11 pm](https://user-images.githubusercontent.com/19935974/35460594-990a2ba6-02b2-11e8-8c02-c87d2fb3588a.jpg)

**Comment by pjsumm** [comment]
verified on IE 11, button margins look good.
