### ISSUE TITLE
Citizenship - Review - Error showing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2524]
- [x] Error showing in citizenship review screen when all fields are complete

![screen shot 2018-01-29 at 9 12 38 am](https://user-images.githubusercontent.com/19935974/35514620-c9682540-04d4-11e8-8bd0-369d2b49edf7.png)

**Comment by floresj** [comment]
We made some updates to the validation that would affect this. This looks ok now.

![selection_720](https://user-images.githubusercontent.com/5938731/36168942-c393d43e-10c8-11e8-8d30-8c538a469bd2.png)

**Comment by Jay-Neighbours-I72** [comment]
looked good in review vid too
