### ISSUE TITLE
Nav not showing complete sections 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2525]
Sections that are not getting green complete circle when logging back in (until they are selected) and/or not showing on first pass:

Your History:
- [x] Where you have lived
- [x] Employment record
- [x] Where you went to school
- [x] Former Federal service
- [x] ~~Review screen~~

Citizenship:
- [x] Citizenship status
- [x] Dual/multiple citizenships

Foreign activities:
- [x] Foreign contacts
- [x] Direct control
- [x] Real estate purchase
- [x] Foreign benefits

**Comment by bmallred** [comment]
Resolving #2641 will knock out the foreign activities section

**Comment by Jay-Neighbours-I72** [comment]
looked good to me in sprint review video
