### ISSUE TITLE
Military history - Foreign military service date error message missing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2529]
- [x] Error message missing

![screen shot 2018-01-29 at 10 00 26 am](https://user-images.githubusercontent.com/19935974/35517033-55eb2af2-04db-11e8-8802-37baa2f4eae5.png)

**Comment by bmallred** [comment]
This appears to have been resolved in another commit

![image](https://user-images.githubusercontent.com/697855/36169522-709ba49e-10ca-11e8-9d8a-ebf7a834acf7.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
