### ISSUE TITLE
Military history - Review section nav error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2530]
- [ ] Nav showing error when all fields are complete

![screen shot 2018-01-29 at 10 06 16 am](https://user-images.githubusercontent.com/19935974/35517339-280ce8ea-04dc-11e8-8167-7aff0e372f5c.png)

**Comment by floresj** [comment]
This should be resolved now.

![selection_723](https://user-images.githubusercontent.com/5938731/36169680-efd50944-10ca-11e8-91c0-3114ee3f8dec.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
