### ISSUE TITLE
Foreign activities - Foreign Business - Explanation blocks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2540]
- [x] Employment -  Reduce margin above the provide explanation label and box and change text to "Provide explanation"

![screen shot 2018-01-30 at 10 35 59 am](https://user-images.githubusercontent.com/19935974/35575076-7e66f9ba-05a9-11e8-880e-2a7d2e174670.jpg)

-
- [x] Event participation- Reduce margin above the provide explanation label and box
![screen shot 2018-01-30 at 10 40 38 am](https://user-images.githubusercontent.com/19935974/35575406-4e77dd86-05aa-11e8-84b7-17ac1cdfce58.jpg)

**Comment by lauraponce** [comment]
LGTM!
