### ISSUE TITLE
Foreign countries visited - data persistence

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2543]
- [x] Full section was not saved

![screen shot 2018-01-30 at 10 57 30 am](https://user-images.githubusercontent.com/19935974/35576226-79275802-05ac-11e8-9276-8fe442ce876c.jpg)

**Comment by floresj** [comment]
@Jay-Neighbours-I72 Are you still seeing this? This appears to be persisting fine on my end.

**Comment by Jay-Neighbours-I72** [comment]
Nope, looks good to me now
