### ISSUE TITLE
Foreign activities - js error - review screen

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2544]
- [x] Can't get to review screen - infinite loop on console...

![screen shot 2018-01-30 at 10 58 39 am](https://user-images.githubusercontent.com/19935974/35576301-a4a997b0-05ac-11e8-80e2-eda0bfe7fe67.jpg)
![screen shot 2018-01-31 at 10 50 07 am](https://user-images.githubusercontent.com/19935974/35632388-85847f80-0674-11e8-9b36-ae619c69cd51.jpg)

**Comment by floresj** [comment]
This was fixed in PR #2594 for issue #2406.
