### ISSUE TITLE
IE11 - Delinquent payments - missing blocks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2547]
Selection boxes are missing for financial issue type:

![screen shot 2018-01-30 at 1 12 36 pm](https://user-images.githubusercontent.com/19935974/35583300-7f967ade-05bf-11e8-8595-f39eba7dc8b3.jpg)

Same for Non payment consequence:
![screen shot 2018-01-30 at 1 52 26 pm](https://user-images.githubusercontent.com/19935974/35585060-e0f348b6-05c4-11e8-8f81-885707b5b551.jpg)

**Comment by bmallred** [comment]
Note: This may have been resolved but need to take another look at it.

**Comment by floresj** [comment]
@bmallred 👍 Looks already resolved.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
