### ISSUE TITLE
Substance use - review - use - error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2559]
- [ ] Type of drug error not resolving after it has been fixed

![screen shot 2018-02-01 at 10 36 18 am](https://user-images.githubusercontent.com/19935974/35687156-fa43179c-073b-11e8-92b9-26ca185c2f96.jpg)

**Comment by floresj** [comment]
Looks like it was indirectly resolved:
![selection_704](https://user-images.githubusercontent.com/5938731/36030436-3303b1f6-0d75-11e8-8165-a7d1a706b0fd.png)
![selection_705](https://user-images.githubusercontent.com/5938731/36030439-360e9aa0-0d75-11e8-8fe9-696e74e8fd63.png)

**Comment by bmallred** [comment]
Yeah I had resolved this in another PR I believe.
