### ISSUE TITLE
Use of alcohol - Mandatory use next/prev buttons

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2560]
- [ ] Next/prev buttons on Mandatory use screen are wrong

![screen shot 2018-02-01 at 11 20 06 am](https://user-images.githubusercontent.com/19935974/35689575-df5cf636-0741-11e8-9f75-36a8129fcc01.jpg)

**Comment by floresj** [comment]
Looks resolved.
![selection_710](https://user-images.githubusercontent.com/5938731/36031594-4197ec88-0d79-11e8-8072-c9bc4880b3a4.png)
