### ISSUE TITLE
Help text refinement - 10 - Psychological and emotional health

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2577]
Refining help text, shifting critical information to the headline, simplifying and making more clear.

- [x] Competence
- [x] Consultations
- [x] Hospitalizations
- [x] Diagnoses

**Comment by Jay-Neighbours-I72** [comment]
Forgot to drag this one over, changes made here:
#2676
#2691

**Comment by bpdesigns** [comment]
@Jay-Neighbours-I72 likewise for this issue
