### ISSUE TITLE
Remove save button on Print screen

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2587]
- [x] Remove or hide save button on Print screen (since form is already submitted)

![screen shot 2018-02-07 at 11 44 50 am](https://user-images.githubusercontent.com/19935974/35928910-51994a60-0bfc-11e8-8502-d00910d1d4b1.png)

**Comment by Jay-Neighbours-I72** [comment]
Looks like the save button was removed on the Review and Submit screen too.

We only wanted to remove it on the Print screen
![screen shot 2018-02-26 at 11 09 41 am](https://user-images.githubusercontent.com/19935974/36681123-bb3d55c2-1ae5-11e8-82b5-24a5a4bacca1.jpg)
![screen shot 2018-02-26 at 11 09 49 am](https://user-images.githubusercontent.com/19935974/36681124-bb562d86-1ae5-11e8-9822-e3dd95499d8f.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 but there is nothing to be saved on any of the screens found under **Review and submit**?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred The thinking here was someone might get to the review screen and see they have error then not feel like fixing yet. They would want to save and come back later.

Similar to the submit screen, anything could come up and they might have to stop, save and come back later. Even with there being nothing to save on Review and Submit it adds a level of comfort to the user, knowing it is still saving and they can still save when they want.

That is why this issue was to only hide it on the Print screen.

Thoughts?

**Comment by floresj** [comment]
When a user leaves a section, we save the contents automatically. So if a use were to click the review link, the contents of the page they just left would be saved.

**Comment by Jay-Neighbours-I72** [comment]
Yep, I love that functionality and think we should keep doing it. Originally we thought that would be enough for people but from usability testing we found people really wanted that added level of comfort in a physical save button. 

The feedback we heard that caused this request was asking why the save button was still there on the print screen only, they didn't say that on the submit and review screens.

Do you guys see any negatives of keeping the save button on review and submit screens?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 besides it not actually doing anything on those screens? Guess not.

**Comment by Jay-Neighbours-I72** [comment]
Still seeing this linger for a little bit on the print screen then it disappears. 

@bmallred can it be hidden as soon at user is on the print screen?

![screen shot 2018-03-01 at 10 43 40 am](https://user-images.githubusercontent.com/19935974/36853853-85c77710-1d3d-11e8-970b-fec9e43baebe.jpg)

**Comment by bmallred** [comment]
If we do that its going to be delayed popping up everywhere else I believe

**Comment by Jay-Neighbours-I72** [comment]
Got it, that would be worse.
