### ISSUE TITLE
Initial only check box wording

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2588]
- [ ] Change wording to "Single letter name"

Current:
![screen shot 2018-02-07 at 11 50 23 am](https://user-images.githubusercontent.com/19935974/35929288-297d3324-0bfd-11e8-85be-c5abec3c301b.png)

Desired:
![screen shot 2018-02-07 at 11 50 41 am](https://user-images.githubusercontent.com/19935974/35929298-2e4ddd54-0bfd-11e8-9406-3e75749c5f44.png)

@billy22g @lauraponce Would you prefer to clear this with Donna before me make the change or after?

**Comment by billy22g** [comment]
I thought I heard from Donna last time that we couldn’t change the label either, but I could be misremembering. Let’s ask Sheldon first.

________________________________

**Comment by Jay-Neighbours-I72** [comment]
I could be optimistically misremembering too! We can bring it up to Sheldon tomorrow at standup.

**Comment by Jay-Neighbours-I72** [comment]
Per Sheldon Billy was right on this, we can't change the wording.
