### ISSUE TITLE
Post submission text notification

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2591]
As an eApp designer I want to create a design concept for the text to display once an eApp form has been submitted so that when users submit their SF-86 application they receive basic guidance on what to expect next. 

Acceptance Criteria
- [x] create design concept
- [ ] customer stakeholder approval

**Comment by bmallred** [comment]
Closed with #2605. Comp'd in browser.

**Comment by pjsumm** [comment]
verified, looks good.
