### ISSUE TITLE
Create mock database tables

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#26]
Create a mock database schema to test persistence of data through the application.

Considerations:

 - [ ] Do not use or emulate current schema due to possible security concerns
 - [ ] Only encompass enough to facilitate proper testing of the front end
 - [ ] Allow schema and sample data to be loaded from compose
     - [x] Basic user auth tables

Other Notes
- Should we have a dev docker-compose? I noticed that without the ports:, I can't expose the db to my host machine. However, adding the ports config option then does not allow travis ci to build

**Comment by floresj** [comment]
Going to close since we'll need to evaluate how we'll handle the database CM process.
