### ISSUE TITLE
Screen reader is not reading the agreement before the log in screen

### ISSUE THREAD

**Issue by lauraponce** [truetandem/e-QIP-prototype#2619]
<img width="1030" alt="screen shot 2018-02-15 at 9 45 26 am" src="https://user-images.githubusercontent.com/21222704/36262330-2004dc00-1235-11e8-9553-78f56dde4566.png">

**Comment by Jay-Neighbours-I72** [comment]
This has been fixed, users read the agreement before agreeing.
