### ISSUE TITLE
Storyboard Your History Section

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#262]
As an eApp designer I want to create a storyboard showing the style and navigational flow of the Your History form section containing places lived, school history, employment history, former federal service information so that we have a clear outline of how the Your History form section will look and behave.  

Acceptance Criteria
- Create a Storyboard utilizing the current design styles and standards
- Have subsections for places lived, school history, employment history (during time period), former federal service information, employment history
- Show representation of overall roll-up of Your History timeline
- Illustrate navigation between subsection details and subsection overviews
- Illustrate navigation between sections
- Review the storyboard/comp with the Product Owner
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
https://xd.adobe.com/view/df1f98fb-a487-42ac-a9c8-a92a43b1debb/screen/33c4faed-6eec-46df-9786-e930ca34a246/Artboard-1

**Comment by Jay-Neighbours-I72** [comment]
[your-history-flow.pdf](https://github.com/truetandem/e-QIP-prototype/files/727892/your-history-flow.pdf)

**Comment by Jay-Neighbours-I72** [comment]
[your-history-flow-v2.pdf](https://github.com/truetandem/e-QIP-prototype/files/735548/your-history-flow-v2.pdf)

**Comment by Jay-Neighbours-I72** [comment]
Version 3 starts here:

![e-app-comp-section-history-1](https://cloud.githubusercontent.com/assets/19935974/22470279/c5e24cda-e79c-11e6-975b-1dc963557bf8.jpg)
![e-app-comp-section-history-2](https://cloud.githubusercontent.com/assets/19935974/22470278/c5e09336-e79c-11e6-82ae-d7d08e253b11.jpg)
![e-app-comp-section-history-3](https://cloud.githubusercontent.com/assets/19935974/22470280/c5e3ee50-e79c-11e6-81d8-f1ed7280468e.jpg)
![e-app-comp-section-history-4](https://cloud.githubusercontent.com/assets/19935974/22470281/c5e715bc-e79c-11e6-9e8b-5810559d83e6.jpg)
![e-app-comp-section-history-5](https://cloud.githubusercontent.com/assets/19935974/22470283/c5e9b628-e79c-11e6-950f-5a6e7296370a.jpg)
![e-app-comp-section-history-6](https://cloud.githubusercontent.com/assets/19935974/22470284/c5f034e4-e79c-11e6-937d-a8b9b6bc7ad1.jpg)
![e-app-comp-section-history-7](https://cloud.githubusercontent.com/assets/19935974/22470282/c5e828ee-e79c-11e6-94c8-88de2ec64bb2.jpg)
![e-app-comp-section-history-8](https://cloud.githubusercontent.com/assets/19935974/22470286/c5f230f0-e79c-11e6-92aa-8df3c6603d45.jpg)
![e-app-comp-section-history-9](https://cloud.githubusercontent.com/assets/19935974/22470288/c5fc6dc2-e79c-11e6-8fa8-769da7533072.jpg)
![e-app-comp-section-history-10](https://cloud.githubusercontent.com/assets/19935974/22470287/c5f45538-e79c-11e6-8795-c5d2397a98e8.jpg)
![e-app-comp-section-history-11](https://cloud.githubusercontent.com/assets/19935974/22470285/c5f2355a-e79c-11e6-99f5-04dc21149c92.jpg)
![e-app-comp-section-history-12](https://cloud.githubusercontent.com/assets/19935974/22470290/c6021632-e79c-11e6-9abf-eb3c3aca6c22.jpg)
![e-app-comp-section-history-13](https://cloud.githubusercontent.com/assets/19935974/22470289/c5ffeca4-e79c-11e6-8200-c524ee879d83.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-APP-comp-section-history.pdf](https://github.com/truetandem/e-QIP-prototype/files/742287/e-APP-comp-section-history.pdf)

**Comment by Jay-Neighbours-I72** [comment]
Version 3 starts here:

**Comment by Jay-Neighbours-I72** [comment]
![e-app-comp-section-history-1](https://cloud.githubusercontent.com/assets/19935974/22482349/a317ac02-e7c6-11e6-9e05-255db16d1a8d.jpg)
![e-app-comp-section-history-2](https://cloud.githubusercontent.com/assets/19935974/22482351/a31a6988-e7c6-11e6-9c67-7cf062410304.jpg)
![e-app-comp-section-history-3](https://cloud.githubusercontent.com/assets/19935974/22482350/a31a6b2c-e7c6-11e6-91cc-0646000af285.jpg)
![e-app-comp-section-history-4](https://cloud.githubusercontent.com/assets/19935974/22482353/a31e3fea-e7c6-11e6-94b8-a58d1ffc4d27.jpg)
![e-app-comp-section-history-5](https://cloud.githubusercontent.com/assets/19935974/22482352/a31ac91e-e7c6-11e6-926e-2fd8e125ec54.jpg)
![e-app-comp-section-history-6](https://cloud.githubusercontent.com/assets/19935974/22482354/a32043e4-e7c6-11e6-88c5-491e35dfd3b8.jpg)
![e-app-comp-section-history-7](https://cloud.githubusercontent.com/assets/19935974/22482356/a323a0ac-e7c6-11e6-9721-f66c66e96972.jpg)
![e-app-comp-section-history-8](https://cloud.githubusercontent.com/assets/19935974/22482355/a3218c2c-e7c6-11e6-8ccb-32120c2ae9ab.jpg)
![e-app-comp-section-history-9](https://cloud.githubusercontent.com/assets/19935974/22482359/a3272dee-e7c6-11e6-8a1c-8f4ba65c1d8f.jpg)
![e-app-comp-section-history-10](https://cloud.githubusercontent.com/assets/19935974/22482357/a324881e-e7c6-11e6-8c17-65be90067bb3.jpg)
![e-app-comp-section-history-11](https://cloud.githubusercontent.com/assets/19935974/22482358/a32534da-e7c6-11e6-9d83-f715f1baf3c3.jpg)
![e-app-comp-section-history-12](https://cloud.githubusercontent.com/assets/19935974/22482360/a32a94de-e7c6-11e6-8e71-eed964009f15.jpg)
![e-app-comp-section-history-13](https://cloud.githubusercontent.com/assets/19935974/22482361/a32dd87e-e7c6-11e6-866e-1f6d6facdf93.jpg)

**Comment by pjsumm** [comment]
[e-APP-comp-section-history.pdf](https://github.com/truetandem/e-QIP-prototype/files/745155/e-APP-comp-section-history.pdf)
