### ISSUE TITLE
Screen reader is not focused on modals when open

### ISSUE THREAD

**Issue by lauraponce** [truetandem/e-QIP-prototype#2621]
When modals are open screen readers can still tab through/read content behind them.

- [x] When modals are open make only the modal content interactive (disable everything behind them)

List of modals:

- Wi-fi access points page
- Agreement before log in screen
- Instructions modal
- Address verification

Note from Nick:
"Modals/Popups - When the screen is covered by the terms and conditions, focus should not be given behind that. So you should only be able to tab to the buttons on that page."

Details for wi-fi page:
-
Tabbing through the wi-fi access points page is selecting the log in screen behind it and you can continue to log in while bypassing clicking the consent button altogether
<img width="950" alt="screen shot 2018-02-15 at 9 45 51 am" src="https://user-images.githubusercontent.com/21222704/36262603-f2cf6a74-1235-11e8-8ba3-035fe42305f4.png">

**Comment by bmallred** [comment]
This is interesting because it is a modal laying over the content of the main page. Will have to look into whether this is possible to disable tabbing on content present in a dynamic way.

**Comment by Jay-Neighbours-I72** [comment]
lgtm
