### ISSUE TITLE
Storyboard Phone block style

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#263]
As an eApp designer I want to create a storyboard showing the style and behavior of Phone number fields so that we have a consistent design representation to implement across all cases of telephone numbers.

Acceptance Criteria
- Create a Storyboard utilizing the current design styles and standards
- Have separate field for each group of numbers in the (e.g. xxx-xxx-xxxx)
- Must support standard US, International, and DSN formatted phone numbers
- Support option to have Extension
- Support adding telephone number type (home, cell, day, night, etc...)
- Support for Not Available/I don't know option if number is unknown
- Ability to add more telephone numbers
- Review the storyboard/comp with the Product Owner
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
![e-app-phone-block](https://cloud.githubusercontent.com/assets/19935974/22437414/fa571420-e6f5-11e6-8953-e9776a67b805.jpg)

**Comment by Jay-Neighbours-I72** [comment]
[e-app-phone-block.pdf](https://github.com/truetandem/e-QIP-prototype/files/743037/e-app-phone-block.pdf)
