### ISSUE TITLE
Architectural diagram

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2637]
Need to diagram the eApp architecture and execution/data flow to illustrate the flow of data through the application components.

**Comment by pjsumm** [comment]
Base architecture diagram

![eapparchitecture](https://user-images.githubusercontent.com/12962390/37501684-d17bd836-28a5-11e8-87d7-8be2c2f96ef2.png)


Diagram with data flow annotatiions

![eapparchitecturewithdataflow](https://user-images.githubusercontent.com/12962390/37501714-e799547c-28a5-11e8-9f0b-5087bb81b2f4.png)

**Comment by bmallred** [comment]
Only comment is it the database is spelled PostgreSQL

**Comment by floresj** [comment]
I think it needs:
![image](https://user-images.githubusercontent.com/5938731/37520395-30c799a4-28f3-11e8-9849-0b6914046ef3.png)

Jay would appreciate that.

**Comment by pjsumm** [comment]
Updated base diagram:

![eapparchitecture](https://user-images.githubusercontent.com/12962390/37600234-1ecdb4ba-2b5d-11e8-99b3-a07f46aef611.png)


Updated diagram with data flow:
![eapparchitecturewithdataflow](https://user-images.githubusercontent.com/12962390/37600241-246495e2-2b5d-11e8-9d1f-41e10f3fcc75.png)
