### ISSUE TITLE
Storyboard Applicant Login

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#265]
As an eApp designer I want to create a storyboard showing the style and behavior of the eApp login form and corresponding warnings and messages and 2 factor authentication so that we have a vetted design representation to implement for the login form.

Acceptance Criteria
- Create a Storyboard utilizing the current design styles and standards
- Show legal and wifi warning messages (as needed, 18f to verify which are legally necessary)
- Have option for users without an id to register
- Review the storyboard/comp with the Product Owner
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
Approved style:

![e-qip-log-in-option-2-1](https://cloud.githubusercontent.com/assets/19935974/23765853/a546e6c4-04d0-11e7-8e12-c598fafe7aeb.jpg)
![e-qip-log-in-option-2-2](https://cloud.githubusercontent.com/assets/19935974/23765852/a54686e8-04d0-11e7-9d86-dc86f12c8cc1.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 and @pjsumm... this has been closed for a while and still in the **Product Backlog**. Just curious if it should be moved to closed?

**Comment by pjsumm** [comment]
thanks @bmallred I think this was just an oversight.  it's been moved to closed.
