### ISSUE TITLE
Phone numbers - DSN/Outside US links

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2667]
- [ ] Phone number switching links should say "Switch to DSN, Switch to..." for screen readers

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 is this a duplicate of https://github.com/truetandem/e-QIP-prototype/issues/2739

**Comment by Jay-Neighbours-I72** [comment]
lgtm
