### ISSUE TITLE
Error message missing text when there is an issue with the state

### ISSUE THREAD

**Issue by lauraponce** [truetandem/e-QIP-prototype#2693]
When an invalid state is entered, the address validator is missing the error message
<img width="682" alt="screen shot 2018-03-02 at 2 59 20 pm" src="https://user-images.githubusercontent.com/21222704/36919366-faef8e4a-1e2a-11e8-8bd7-9fb69ea8d1d4.png">

**Comment by Jay-Neighbours-I72** [comment]
this looks to be fixed by not running usps verification when there is an error in state
