### ISSUE TITLE
Instruction modal is not displayed on smaller view sizes

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#2701]
If the view size width was under 1000px the instructions modal is not displayed.

**Comment by bpdesigns** [comment]
This issue seems to popped up again. @bmallred I would move this back to in progress. 
<img width="681" alt="screen shot 2018-03-30 at 4 13 39 pm" src="https://user-images.githubusercontent.com/15329140/38152355-632e5822-3435-11e8-9cbc-b655c5cf9234.png">

**Comment by Jay-Neighbours-I72** [comment]
This is working correctly for me.

When you drag the browser width in do the instructions disappear?

**Comment by bpdesigns** [comment]
Yes, but they show up under the hamburger menu. Is that the intention or should the instructions remain in the top bar?

**Comment by bmallred** [comment]
The issue was with the **modal** not the hyperlink. The **hyperlink** does move in to the navigation drawer when the navigation is no longer always visible.

The **modal** instructions previously were not visible on tablet and smaller devices but would appear when in a larger view size and the navigation on the left was visible.

**Comment by bpdesigns** [comment]
Got it. Thanks
