### ISSUE TITLE
Info about you - Full name - inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2703]
- [ ] Inputs have a white border overlapping them in the lower right corner

![screen shot 2018-03-06 at 1 40 19 pm](https://user-images.githubusercontent.com/19935974/37051309-16eb02b6-2144-11e8-9b0b-084feb86f753.jpg)

**Comment by bmallred** [comment]
Resolved earlier today in referenced PR

**Comment by pjsumm** [comment]
verified in dev and staging.
