### ISSUE TITLE
Submit form data to test web service connection

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#2705]
As an eApp developer I want to perform a test submission using the OPM web services API to the legacy eQIP database so that I can test the conversion of eApp data to the eQIP system.

Acceptance Criteria

 - [ ] Fill in form data from the eApp system and submit the data to the eQIP
 - [x] Get response signifying that the data has been submitted

**Comment by pjsumm** [comment]
Completing this task and opening a new task to track testing submission to Army PSI CoE eApp test Agency ID.  Opened #2753
