### ISSUE TITLE
Save button text - screen readers

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2737]
Can we change the readable text on the save button for screen readers?

1. Change to "Saved xx minutes ago. Save now?" (currently it is only saying "Saved xx minutes ago"

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 would this just be what is read by the screen reader or something we want visually as well?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred It wasn't read on JAWS with the user we had run through. It only read "Saved xx minutes ago"

**Comment by Jay-Neighbours-I72** [comment]
lgtm
