### ISSUE TITLE
Accordion items accessibility updates

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2747]
- [x] Need a solution to call out accordion content to screen readers

Suggested solutions for accordion:
- [x] Accordion items should add a number when then are read. Ex. Phone number 1, Phone number 2
- [x] "Close" button should read "Phone number 1 close" (accordion item title)
- [x] Remove button should try to reference item and number or say "Remove this item"

**Comment by bpdesigns** [comment]
@Jay-Neighbours-I72 can you confirm this on JAWS? 

for item 2 in the checklist, I do not get the item referenced. see below. 
<img width="1280" alt="screen shot 2018-04-13 at 9 58 23 am" src="https://user-images.githubusercontent.com/15329140/38738914-576e4778-3f01-11e8-8179-0be0a85a4ae3.png">

**Comment by Jay-Neighbours-I72** [comment]
@bpdesigns These are working for me in JAWS on Edge and IE11. They read "Phone number 2"

There is an issue in the Your history section though which is tracked here:
https://github.com/truetandem/e-QIP-prototype/issues/2889
