### ISSUE TITLE
Section numbers off

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2769]
With nav re-order section numbers need to be updated

![screen shot 2018-03-23 at 4 30 29 pm](https://user-images.githubusercontent.com/19935974/37852071-981b3ff6-2eb7-11e8-970a-2946d7ee2f8a.jpg)
![screen shot 2018-03-23 at 4 30 34 pm](https://user-images.githubusercontent.com/19935974/37852072-9828e25a-2eb7-11e8-926a-1c3f065eecbf.jpg)

**Comment by bmallred** [comment]
Ah this is from the reordering most likely

**Comment by bpdesigns** [comment]
looks good 

<img width="907" alt="screen shot 2018-03-29 at 4 53 47 pm" src="https://user-images.githubusercontent.com/15329140/38113039-cc82e230-3371-11e8-9f22-840fd216ab51.png">
<img width="859" alt="screen shot 2018-03-29 at 4 53 37 pm" src="https://user-images.githubusercontent.com/15329140/38113040-ccb2d88c-3371-11e8-9450-acf0b2b1bd02.png">
