### ISSUE TITLE
SSN invalid error - still showing confirm

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2770]
Confirm SSN is showing with an invalid SSN

![screen shot 2018-03-23 at 4 32 46 pm](https://user-images.githubusercontent.com/19935974/37852154-ed5f8904-2eb7-11e8-9d16-781b9970615b.jpg)

**Comment by bpdesigns** [comment]
looks good

<img width="645" alt="screen shot 2018-03-29 at 5 19 53 pm" src="https://user-images.githubusercontent.com/15329140/38114185-6fd69de8-3375-11e8-8fe9-0a85324eaab2.png">
