### ISSUE TITLE
Middle name checkbox error

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2776]
- [x] Error is being thrown on middle name when "No middle name" checkbox is selected - across full form

![screen shot 2018-03-26 at 2 20 24 pm](https://user-images.githubusercontent.com/19935974/37924833-00d3ad3a-3101-11e8-8fd3-e70ee12e8d35.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 may need to get with you on this b/c we just closed an issue involving something like this and it wasn't happening.

**Comment by bpdesigns** [comment]
Not sure if this belongs here or is a new issue @bmallred but now no error shows if you do not add anything to middle name field. see below.

<img width="1112" alt="screen shot 2018-03-30 at 4 18 45 pm" src="https://user-images.githubusercontent.com/15329140/38152549-680c0e6a-3436-11e8-9a82-a340264ad48c.png">

**Comment by bmallred** [comment]
Messages for **required** fields only show up on the review sections. This was to avoid the pain of seeing a lot of error messages for each field on larger sections.

**Comment by bpdesigns** [comment]
right, but isn't the middle name required? or at least checking a button that there is no middle? there is an asterisk next to it.

**Comment by bmallred** [comment]
It is required but error messages for required items only are displayed on the review section.

The screen shot shows it is currently in the "Full name" section and not the "Review" section of "Information about you"

**Comment by Jay-Neighbours-I72** [comment]
lgtm on staging
