### ISSUE TITLE
SSN - not applicable button

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2783]
- [x] Can't submit form when "Not applicable" is checked for SSN

![screen shot 2018-03-27 at 11 33 38 am](https://user-images.githubusercontent.com/19935974/37977971-ebfe0902-31b2-11e8-8bb8-1b2b2c2d6c6f.jpg)
![screen shot 2018-03-27 at 11 33 51 am](https://user-images.githubusercontent.com/19935974/37977974-ecf50108-31b2-11e8-9990-18a34b7bc95e.jpg)

**Comment by Jay-Neighbours-I72** [comment]
Related: when you toggle not applicable on and off you get this error message:
![screen shot 2018-03-27 at 11 41 25 am](https://user-images.githubusercontent.com/19935974/37978349-da941bce-31b3-11e8-9e5d-edbab533db59.jpg)

**Comment by floresj** [comment]
![selection_826](https://user-images.githubusercontent.com/5938731/38031715-e7f8e964-3269-11e8-98db-1f3789c80ce7.png)

![selection_825](https://user-images.githubusercontent.com/5938731/38031716-e814e0f6-3269-11e8-95d8-eff561f4823f.png)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
