### ISSUE TITLE
Middle name allowing numbers

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2792]
- [x] Error should be thrown when numbers are entered

![screen shot 2018-03-27 at 3 07 35 pm](https://user-images.githubusercontent.com/19935974/37989212-d1936cec-31d0-11e8-8a1a-3fef38599090.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 going to check through the history on this one b/c I could've sworn this was intentional.

**Comment by bmallred** [comment]
Couldn't find it nor anything mentioning what is allowed. will go ahead and update this.
