### ISSUE TITLE
Foreign activities - indirect control - name not throwing errors

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2800]
- [x] Name inputs are not throwing errors for character that shouldn't be allowed

![screen shot 2018-03-28 at 2 22 35 pm](https://user-images.githubusercontent.com/19935974/38048514-9525b7c4-3293-11e8-918e-d72fc9212dad.jpg)

**Comment by bmallred** [comment]
Ah, that is not a typical `<Name/>` but instead are multiple `<Text/>` components. We just need to add the patterns on these types of usages.

**Comment by Jay-Neighbours-I72** [comment]
lgtm on staging
