### ISSUE TITLE
Relatives - address block not hitting USPS

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2805]
Relatives - U.S. Citizenship Documentation branch:

Court address is not validating against USPS

![screen shot 2018-03-29 at 2 00 21 pm](https://user-images.githubusercontent.com/19935974/38105400-f0219f6e-3359-11e8-83c5-9d640dd9b215.png)

**Comment by bmallred** [comment]
Looks like this one doesn't validate because it is not part of the `<Address/>` component, but instead just renders fields similar to it. May take a bit of rework to get this one in there.

**Comment by Jay-Neighbours-I72** [comment]
lgtm on staging
