### ISSUE TITLE
User number symbol for placeholders

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#2829]
As an eApp application I want to see a non-numeric value in the text hints of numeric fields so that I am not confused by the presence of a number (0) when I have not yet entered anything. 

Acceptance Criteria
- [x] replace the '0' text hint used in numeric fields with generic '#' 
  - [x] date fields
  - [x] SSN fields
  - [x] height/weight
  - [x] monetary/values

**Comment by bpdesigns** [comment]
Doesn't look updated

**Comment by bmallred** [comment]
![image](https://user-images.githubusercontent.com/697855/38741535-1ec9145a-3f08-11e8-9efc-01ffe17a9d4f.png)

@bpdesigns looks updated to me. this is on `staging` which is what we go off of for these since `dev` is updated manually.

**Comment by bpdesigns** [comment]
@bmallred got it. probably the same for the new updates to hair and eye color too.
