### ISSUE TITLE
Hair color reorder 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2842]
New order:

Black
Brown
Red or Auburn
Blond or Strawberry
Sandy
Gray or partially gray
White
Bald
Blue
Green
Orange
Pink
Purple
Unspecified or unknown

**Comment by Jay-Neighbours-I72** [comment]
@bpdesigns forgot to tag you in this, does this order look good to you?

**Comment by bpdesigns** [comment]
sounds good

**Comment by Jay-Neighbours-I72** [comment]
Updated bald icon
![screen_shot_2018-04-05_at_4 37 38_pm](https://user-images.githubusercontent.com/19935974/38424954-99343b3a-3980-11e8-9eac-c44c8c6c6c72.jpg)

@bmallred svg is in the drive folder

**Comment by bpdesigns** [comment]
Doesn't look updated

**Comment by bmallred** [comment]
![image](https://user-images.githubusercontent.com/697855/38741707-86fe4f9a-3f08-11e8-897d-58c253922468.png)

@bpdesigns looks good to me on `staging`
