### ISSUE TITLE
Eye color reorder

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#2843]
New order:
Brown
Hazel
Blue
Green
Gray
Maroon
Black
Multicolored
Pink

cc @bpdesigns

**Comment by bpdesigns** [comment]
looks good

**Comment by bpdesigns** [comment]
Doesn't look updated

**Comment by bmallred** [comment]
![image](https://user-images.githubusercontent.com/697855/38741676-6fc72fb8-3f08-11e8-94f8-cfb186b27fe8.png)

@bpdesigns looks good to me on `staging`
