### ISSUE TITLE
saml.go:SamlCallbackHandler should not pass JWT token via request param

### ISSUE THREAD

**Issue by ryanhofdotgov** [truetandem/e-QIP-prototype#2859]
Because request URLs are frequently logged in multiple places (access logs, proxy logs, etc.) it is recommend that security tokens not be passed to the browser via a URL request parameter.

A cookie or a POST instead of redirect might be alternative ways to convey to client.

**Comment by bmallred** [comment]
Tokens are valid only for a short period of time and are renewed immediately in this one use case.

Cookies were something we originally tried to avoid doing due to concerns about them early on. I'm not opposed to them BTW.

POST to static frontend isn't possible AFAIK.

**Comment by ryanhofdotgov** [comment]
Gotcha.... the situation is similar to this application STIG line item:
https://www.stigviewer.com/stig/application_security_and_development/2017-01-09/finding/V-70213

**Comment by bmallred** [comment]
Will have to test if cookies will work across potentially different subdomains
