### ISSUE TITLE
Apply bankruptcy details to appropriate section/collection

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#289]
Form Fields (all fields required unless specified otherwise)

- [x] Select the applicable bankruptcy petition type
  - Select list
  - Options: Chapter 7, Chapter 11, Chapter 12, Chapter 13
  -  If Chapter 13 is selected, must provide additional information
      - Provide the name of the trustee for this bankruptcy. Free-Text
      - Provide the address of the trustee for this bankruptcy. Address (With Country Option)
        - Must provide Street and City
        - State and Zip - or - Country are required
- [x] Provide the bankruptcy court docket/account number.	
  - Free-text		
- [x] Provide the date bankruptcy was filed	
  - Date type: M/Y Est
  - Month and Year and specify if the date is an Estimate	
- [x] Provide the date bankruptcy was filed
  - Date type: M/Y Est
  - Month and Year and specify if the date is an Estimate
  - "Not Applicable" - Checkbox if No, date is not required
- [x] Provide the total amount (in U.S. dollars) involved in the bankruptcy.	
  - Amount		
  - "Estimated" - Checkbox to designate if the value is an estimate		
- [x] Provide the name debt is recorded under.
  - Name Block (standared name block fields: First, Middle (i/o or no), Last(i/o), Suffix)
- [x] Provide the name of the court involved.
  - Free-text
- [x] Provide the address of the court involved.
  - Address - With Country Option
  - Provide Street and City
  - State and Zip - or - Country are required		
- [x] Add Optional Comment
  - Optional - show only if needed
  - Help - "Note: If you need to provide any additional comments about this information, enter them below."
  - Multiline free-text
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
Example of legacy page

![selection_224](https://cloud.githubusercontent.com/assets/5938731/22291193/01b45402-e2d3-11e6-9f90-ff5268176983.png)
