### ISSUE TITLE
Apply Yes/No component to bankruptcy

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#290]
Form Fields

- [x] In the last seven (7) years have you filed a petition under any chapter of the bankruptcy code?
  - Required
  - Yes\No Option	
  - [x] Yes: When selected goes to backrupty to enter bankruptcy information
  - ~~[ ] No: Move on to next financial form section~~
  - [x] Add Optional Comment
  - [ ]Optional - show only if needed
  - [x] Help - "Note: If you need to provide any additional comments about this information, enter them below."
  - Multiline free-text
- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
Crossed out since we will require users to click next to move on

> No: Move on to next financial form section

**Comment by floresj** [comment]
Sample of current screen:

![selection_223](https://cloud.githubusercontent.com/assets/5938731/22290904/7e8febaa-e2d1-11e6-8ac5-5aed5da32434.png)
