### ISSUE TITLE
Usability action and punch list items

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#294]
Items carried over from [eApp - SF86 - Prototype punch list](https://docs.google.com/a/ignition72.com/spreadsheets/d/1VS2DD-c2Ta9RK-x_j7WSyvRGvX4mI8GVrLTcUc4Pm8k/edit?usp=sharing):

- [x] Piece or full section choice should only be there when going back to a section. Should also include either error message or no errors message
- [x] Progress bar functionality
- [ ] ~~Bold text looks too heavy, re-evaluate weights?~~ (@jay will re-evaluate)
- [x] Info/help circles wrong color and not aligned. Pull color/hover color from comp. Should be closer to the input
- [x] Saved indicator missing
- [x] DOB - Can we keep height of buttons the same?
- [x] Other names - Date range - missing arrow (@joeignition)
- [x] Other names - headline hierarcy, margins, missing headlines, add another name
- [x] Identifying info - headline sizes (@joeignition)
- [x] Hair color - use correct icon, add animation, white hair icon needs stroke from comp (@joeignition)
- [x] Error box missing from ssn section. Only icon shows when error
- [x] No dropdowns - replace drop downs with either typeahead, block, or visual answers. Consult comp for style (sections that have been stroyboarded) Regroup on new sections (not storyboarded)
- [x] Check box hover style - use same hover style from input
- [x] Suffix - "None" Should not be a selection
- [x] Other names used - Dates - clicking present should put present date in inputs
- [x] Other names used - validation for "Reason for change" is not showing
- [x] Physical attributes - Height error message is misaligned (@joeignition)
- [x] Nav column validation - Correct (green) style should be Green number and green check only. No green vertical line, no green text.
- [ ] SSN verification style/functionanlity - Can this be a yes/no instead of re-typing their number?

From the **Usability testing**:

 - [x] Change Date and other number fields to be input “text”, input type “number” adds arrows that are of little use to users. (includes weight, height)
- [x] Prevent Weight field from receiving an initial value of 0.
- [x] Remove validation from Date fields until input loses focus to prevent false positive error messaging.
- [x] Navigation Validation display issues
- [x] Do not clear previous validated state when user enters section. Only if new error introduced,
- [x] Ensure Prev/Next triggers validation *before* changing screens to prevent incorrect validation state.
- [ ] When going back to fix one thing, user had to click through rest of section to return successful section state.
- [ ] ~~Middle Name validation - if single character entered does user need “initial only” checked for successful validation?~~ (It is possible for a person to have a 1 letter name. This would  distinguish those cases)
- [x] Login messaging should match internal error messaging display.
- [x] Login errors should not continue display on 2 factor authentication screen.
- [x] Replace State dropdown with autocomplete with full State text / abbreviation.
- [x] Place of Birth - if non-U.S. chosen, do not display county or relabel to be more accurate.
- [x] Add messaging to top of review screen to provide user context.
- [ ] Add "Back to top" anchor link to bottom of screens.
- [x] Change “Add Another Name” control style to be more in-line with form button styles, less like navigation style.  (@joeignition)
- [x] Determine method to place more advanced content in Help / Error content. (inline link, or list of links)
- [x] Choose different “Help” icon to more accurately convey purpose.  (@joeignition)
- [x] When user engages “Help” scroll screen to show Help content, prior to showing the help box.
- [x] Add a focus style to checkbox / radio inputs to convey focus for tabbing users.
- [x] Change icon for bald from “do not enter”.  (@joeignition)
- [ ] Prevent accidental clicking of “estimated” checkbox on leaving date fields. (@joeignition)
- [ ] Prompt user to print / save as PDF before final submission.
- [x] Create more official-feeling header treatment, and welcome screen once logged in.  (@joeignition)
- [x] Correct spacing issues on Review screen. (@joeignition)
- [ ] Develop printable CSS. (@joeignition)
- [ ] How do we handle validation / translation of accented characters
- [ ] Design selection screen switching between one at a time vs all at once before starting sections.

**Comment by floresj** [comment]
@Jay-Neighbours-I72 @joeignition @bmallred 

"SSN verification style/functionality - Can this be a yes/no instead of re-typing their number?"

Have we decided if we're keeping the re-typing?

**Comment by bmallred** [comment]
@floresj can you capture a screenshot of what it looks like now with the double entry and then mock up and capture a screenshot of what it may look like w/ a yes/no? doesn't have to be anything more than Chrome devtool manipulation but this is something we can put forth to everyone at least.

**Comment by bmallred** [comment]
@joeignition for the item

> Determine method to place more advanced content in Help / Error content. (inline link, or list of links)

1. Does this mean we want to potentially handle messages with complex structures?
2. Will something like Markdown suffice?

**Comment by floresj** [comment]
@joeignition @Jay-Neighbours-I72 

> Middle Name validation - if single character entered does user need “initial only” checked for successful validation?

Some users could potentially have single letter names so having initial only will distinguish between cases. Is this something we should get confirmation from Sheldon?
