### ISSUE TITLE
Update Prototype behavior and styles

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#303]
As an eApp designer and developer I want to update the HTML structure and CSS for the eApp SF86 form prototype so that it reflects the styles and behaviors of the approved Storyboards. 

Acceptance Criteria
- Styles and behaviors in the Prototype match the corresponding Storyboards
- Prototype changes have been reviewed and approved by the Product Owner and 18f PMO

**Comment by bmallred** [comment]
This was closed and any items left created new individual issues placed in the icebox.
