### ISSUE TITLE
Create mock entities for use within the back end

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#31]
After further discussion, this issue deals with creating a generic solution to handling the persistence of form data.

See comments below for on-going analysis

**Comment by bmallred** [comment]
What would we do for form storage?

```go
type Form struct {
    /* a bunch of fields */
}
```

or more generic

```go
type FormEntry struct {
     ID int64
     Section string
     Name string
     Value string
}
```

**Comment by floresj** [comment]
Ok, so I've analyzed a couple of approaches. I'm just going to do a brain dump and we'll see where this takes us. I have code for this but I'm going to post snippets here to depict the general idea. For the purposes of this discussion, when I mention `component`, I'm referring to some golang `type`. This can be  a `struct` or a primitive `type` like `string` or `int64` that has been enhanced. 

**Concept 1**
Create composite components much like the client side. We can create new structs and new types that "extend" existing` primitive types like `string` or `int64` to add behavior that is specific to a form element or component.  

We can create a `Validator` or `Field` interface that simply could contain one method

```go
type Validator interface {
    Valid() (bool, error)
}
```
Each component implements a `Valid()` method to determine if the information it has is valid. This can build a validation tree where every component, whether it's a basic component to one that is composed of many sub-components, knows exactly how to validate itself. 

For instance, basic components could provide very generic validation rules.  Here's a list of some basic components that could potentially be used

- TextField
  - ```go
     type TextField string
     func (t TextField) Valid() (bool, error) {
         if (t == "") {
            return false, fmt.Errorf("Empty")
         }
         return true, nil
     }
- EmailField
  - ```go
     type EmailField string
     func (t EmailField) Valid() (bool, error) {
         // Add logic to ensure this is formatted properly, etc
         return true, nil
     }
- DateField
   - ```go
      type DateField struct {
           Month int64
           Day int64
           Year int64
      }
     func (t DateField) Valid() (bool, error) {
         // Add logic to ensure this is formatted properly, etc
         return true, nil
     }
- PhoneNumberField
- UrlField
- NumberField


From these basic components, we create higher-level components (just like the client-side) that are made up of many sub-components.
- Address
   - ```go
      type Address struct {
         Address1 TextField
         Address2 TextField
         City TextField
         // etc etc
       }

     func (a Address) Valid() (bool, error) {
         // This can check if each one is valid or something along those lines
         return true, nil
     }
- Person
   - ```go
      type Person struct {
         Firstname TextField
         Lastname  TextField
      }
      func (p Person) Valid() (bool, error) {
         // This can check if each one is valid or something along those lines
         return true, nil
      }

From these basic building blocks, we can then create `sections`.

```go
type IdentifyingInfo struct {
    Name  Person
    PlaceOfBirth Address
    DateOfBirth  DateField
}
func (i IdentifyingInfo) Valid() (bool, error)
    // This can check the validity of the entire section 
    ok, err := i.Name.Valid()
    ok, err := i.PlaceOfBirth.Address1.Valid()
    return true, nil
 }
```

To handle errors, we can create custom Err types for each component that store error specific information that can be returned to the client.

For instance, we could have a custom error for invalid dates that contains which parts of the field are invalid. Since it implements the `error` interface, we can return it as an error and be able to send back as json to expose the exported fields that the client can use to determine what went wrong.

```go
type ErrInvalidDateField struct {
  MonthInvalid bool
  DayInvalid bool  
  YearInvalid bool
}

func (e ErrInvalidDateField) Error() string {
 return fmt.Sprintf("Month: %v  Day %v  Year %v", e.MonthInvalid, e.DayInvalid, e.YearInvalid)
}
```
If we go back to our `DateField`, we can do something like this (this is obviously not correct but just showing how it can be used)

```go
      type DateField struct {
           Month int64
           Day int64
           Year int64
      }
     func (t DateField) Valid() (bool, error) {
         err := ErrInvalidDateField {}
         // Add logic to ensure this is formatted properly, etc
         if t.Month == 0 {
             err.MonthInvalid = true
         }
         return false, err
     }
```

Sorry for the novel.

**Comment by floresj** [comment]
To handle errors, here's one approach. For every custom `field type`, provide an associated struct that implements the `error` interface. For every field in a section struct, include that field with an `error` type. For instance, let's say the `IdentifyingInfoSection` struct
```go
type IdentifyingInfoSection struct {
	Firstname    TextField `v:"minLength=3,maxLength=100"`
	Lastname     TextField `v:"minLength=5,maxLength=100"`
	Middle       TextField
	DateOfBirth  DateField
	PlaceOfBirth AddressField
	SSN          SSN
	Suffix       Suffix
}
```

The associated error struct would be

```go
type ErrIdentifyingInfoSection struct {
	Firstname    error
	Lastname     error
	Middle       error
	DateOfBirth  error
	PlaceOfBirth error
	SSN          error
	Suffix       error
}
```

Now, within the `valid()` method inside of `IdentifyingInfoSection`, you can populate this error and return it if the section contains errors. This can be applied to any component, including basic and complex types. So every component has an error hierarchy to present "stuff" that has gone wrong.

```go
func (f IdentifyingInfoSection) Valid () (bool, error) {
   err := ErrIdentifyingInfoSection {}

   if ok, e := f.PlaceOfBirth.Valid(); !ok {
       err.PlaceOfBirth = e
    }
    // Do for each

   return err.HasErrors(), err
}
```

Here's an example of a FieldRequired error. It includes an exportable `Text` property so that it marshals properly with the json encoder.
```go
type ErrFieldRequired struct {
    Text string
}

func (e ErrFieldRequired) Error() string {
    return e.Text
}
```

From a json perspective, here's what the client could receive for a `POST` request. Imagine 

```json
{
   "Section" : {},
   "Errors" : {}
}
```

```json
{
  "Section": {
    "Firstname": {
      "Name": "",
      "InitialOnly": false
    },
    "Lastname": "Flores",
    "PlaceOfBirth": {
      "City": "",
      "State": "",
      "County": "Some county",
      "Country": "United States"
    },
    "Suffix": ""
  },
  "Errors": {
    "Firstname": {
      "Text": "Firstname is required"
    },
    "PlaceOfBirth": {
      "City": {
        "Text": "City is required"
      },
      "State": {
        "Text": "State is required"
      },
      "County": null,
      "Country": null
    }
  }
}
```

**Comment by bmallred** [comment]
So a twist...

```go
type ValidationError struct {
	Name  string
	Error error
}

type ErrorStack []ValidationError

func (stack ErrorStack) HasErrors() bool {
	return len(stack) > 0
}

func (stack *ErrorStack) Append(name string, err error) {
	stack = append(stack, ValidationError{name, e})
}
```

then for a validation function...

```go
func (f IdentifyingInfoSection) Valid() (bool, ErrorStack) {
	var stack ErrorStack

	// Do for each field of the struct
	if ok, e := f.PlaceOfBirth.Valid(); !ok {
		stack.Append(stack, ValidationError{"PlaceOfBirth", e})
	}

	return stack.HasErrors(), stack
}
```

then in the handler...

```go
func Encode(w http.ResponseWriter, v Validator) error {
	w.Header().Set("Content-Type", "application/json")

	err, stack := v.Valid()
	if err != nil {
		return err
	}

	return json.NewEncoder(w).Encode(stack)
}

func ValidateIdentifyingInfo(w http.ResponsWriter, r *http.Request) {
	Encode(IdentifyingInfoSection {
		/* assign values */
	})
}
```

returning a response of

```json
{
  "Errors": [
    {
      "Name": "PlaceOfBirth",
      "Error": "&quot;We demand rigidly defined areas of doubt and uncertainty!&quot; is not a valid place of birth"
    }
  ]
}
```

fodder for discussion on Monday :)

**Comment by floresj** [comment]
The `ErrorStack` approach is **awesome!**. I incorporated that and the error tree is quite wonderful. 

```json
  "Errors": [
    {
      "Name": "Person",
      "Error": [
        {
          "Name": "Firstname",
          "Error": {
            "Message": "Firstname is required"
          }
        },
        {
          "Name": "Lastname",
          "Error": {
            "Message": "TextField is required"
          }
        },
        {
          "Name": "Middlename",
          "Error": [
            {
              "Name": "Name",
              "Error": {
                "Message": "Middlename is required"
              }
            },
            {
              "Name": "Type",
              "Error": {
                "Message": " is not a valid Middlename Type"
              }
            }
          ]
        }
      ]
    },
    {
      "Name": "DateOfBirth",
      "Error": [
        {
          "Name": "Month",
          "Error": {
            "Message": "`0` is an invalid month"
          }
        },
        {
          "Name": "Day",
          "Error": {
            "Message": "`0` is an invalid day"
          }
        },
        {
          "Name": "Year",
          "Error": {
            "Message": "`0` is an invalid year"
          }
        }
      ]
    },
    {
      "Name": "PlaceOfBirth",
      "Error": [
        {
          "Name": "City",
          "Error": {
            "Message": "Field is required"
          }
        },
        {
          "Name": "State",
          "Error": {
            "Message": "State is required"
          }
        },
        {
          "Name": "Country",
          "Error": {
            "Message": "Invalid Country",
            "Suggestions": [
              "United States",
              "United Kingdom"
            ]
          }
        }
      ]
    },
    {
      "Name": "SSN",
      "Error": [
        {
          "Name": "First",
          "Error": {
            "Message": "First is a required field"
          }
        },
        {
          "Name": "Middle",
          "Error": {
            "Message": "Middle is a required field"
          }
        },
        {
          "Name": "Last",
          "Error": {
            "Message": "Last is a required field"
          }
        }
      ]
    }
  ]
```
