### ISSUE TITLE
Storyboard Use Existing Name

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#314]
As an eApp designer I want to create a storyboard that illustrates the design and flow for how users might be able to reuse a name that they have already entered elsewhere on the SF86 form so that in areas like Passport name the user can access the name they entered earlier in the form and use that instead of entering the same name again.

Acceptance Criteria

**Comment by bmallred** [comment]
- Do the address example first and then move forward (or not) with this
 - or, possibly leave out entirely
 - or, possibly use as a suggestions use-case when something is typo'd

**Comment by pjsumm** [comment]
not necessary since entering names is straight forward
