### ISSUE TITLE
Prototype - Financial Record Punch List

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#317]
Punch list for Financial Record. Will continue to review and add new items as they are seen.

- [x] Flow of adding a debt. Follow the flow from the "Where you have lived" comps. User clicks yes, form is loaded (no summary at this point), user fills out form, if user selects "add another" then summary is created and page scroll back up to condensed summary and new form loaded.

- [x] Active state is being applied to yes/no buttons
![screen shot 2017-01-24 at 11 49 02 am](https://cloud.githubusercontent.com/assets/19935974/22257146/2839ae72-e22b-11e6-8086-93941cc8dfa8.png)

- [x] Margins on date entry. Match margins of date range to comp.
![screen shot 2017-01-24 at 11 50 00 am](https://cloud.githubusercontent.com/assets/19935974/22257233/68faa222-e22b-11e6-822b-de74170e21c8.png)

- [x] Add headline on debt entry. Add headline above "Provide the date range of your financial..." Headline should be "Enter your gambling debt". Follow this structure/hierarchy...
![screen shot 2017-01-24 at 11 50 00 am](https://cloud.githubusercontent.com/assets/19935974/22257393/f17125ae-e22b-11e6-8f2c-8cc1f2478fc1.png)

- [x] Align help circle to "From date" (align like amount, description)
![screen shot 2017-01-24 at 11 55 26 am](https://cloud.githubusercontent.com/assets/19935974/22257500/4561a030-e22c-11e6-8733-0b9b0694b766.png)

- [x] Hit box on "Estimated" and all check boxes should not be visible.
![screen shot 2017-01-24 at 11 57 55 am](https://cloud.githubusercontent.com/assets/19935974/22257544/69cade64-e22c-11e6-9af7-bbfe8bdb74a3.png)

- [x] Add comment below explanation is adding comment to full section. The style used here is for a specific element only. If we need full section comments a different style will have to be comped up.

- [x] All inputs should have a label. For example "Provide a description of your financial problems due to gambling" input label should be "Description".  Style example...
![screen shot 2017-01-24 at 12 01 30 pm](https://cloud.githubusercontent.com/assets/19935974/22257775/0ace4a94-e22d-11e6-8c9d-751ce763a3ef.png)
 
Partial review 1/24.

**Comment by bmallred** [comment]
![gambling debt](https://cloud.githubusercontent.com/assets/697855/22261788/47691b64-e23c-11e6-8e50-8496d2a68b25.png)

After the revisions. The only thing this screenshot doesn't capture is that the *gutters* are only applied when a summary is present. Otherwise it has no padding applied on left and right.

Also, I went ahead and got the DateRange arrow closer, but I think @joeignition is taking a look at this as well on a separate issue!
