### ISSUE TITLE
Navigation buttons are sizes vary based on length of content

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#366]
The navigation buttons should be similar in height and width.

![nav-button-resizing](https://cloud.githubusercontent.com/assets/697855/22506345/f3b2219c-e84d-11e6-89bc-94c2f61ab204.png)

**Comment by joeignition** [comment]
![screen shot 2017-02-03 at 12 03 57 am](https://cloud.githubusercontent.com/assets/1541473/22580546/526548ea-e9a7-11e6-8630-1a23e73e7711.png)

New look.

**Comment by floresj** [comment]
Joe resolved.
![selection_255](https://cloud.githubusercontent.com/assets/5938731/22593668/b754b5ec-e9ed-11e6-9722-932883e73462.png)
