### ISSUE TITLE
When going to a different section scroll the view up

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#369]
Currently when navigating to a new section (from the left navigation or from the previous/next buttons) the content updates but the user is left at the same position on the screen.

Instead the view should scroll to the very top **or** towards the progress bar (so it is still visible).

**Comment by floresj** [comment]
Just an idea, could possibly add additional parameter in `push(path, scrollToTop)` or `push(path, toToXCoordinate)` that specifies the scrolling so we can just handle it in the history redux middleware

**Comment by bmallred** [comment]
I think this is a splendid idea :)

**Comment by bmallred** [comment]
Scrolling to the top of the progress bar if visible.

![2017-02-03_154012_230885981](https://cloud.githubusercontent.com/assets/697855/22607890/e7b3c5cc-ea27-11e6-9ac0-e79e7714e75a.png)
