### ISSUE TITLE
Apply components to places lived

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#386]
Epic #327: As an eApp applicant I want to enter the address of a place I've lived along with the dates I lived there and whether I owned, rented, was there for military, or other reason so that I can complete the places I've lived.

Design comps at #262 

## Fields

Provide dates of residence. (date range with Present)
  - [x] Date Range - Est/Present
  - [x] Validation - For an Address within the last 3 years 
  - [x]  **Branch** to add someone who knows you at that location
    - Is/was this residence: 
      - [x] Selection: "Owned by you", "Rented or leased by you", "Military housing", "Other (Provide explanation)"
      - [x] Explanation - Free-Text

Provide the street address.
  - [x] Address - With Country Option
  - [x] Provide Street and City
  - [x] State and Zip - or - Country are required
  - [x] Validation - For an APO/FPO Address 
    - [x] If State = AA, AE, or AP Then City must be = APO or FPO 
    - [x] **Branch** to APO/FPO Location Details

Add Optional Comment
  - [x] Optional - show only if needed
  - [x] Help - "Note: If you need to provide any additional comments about this information, enter them below."
  - [x] Multiline free-text

### For places I've lived in the last 3 years

From Epic #329: As an eApp applicant **for places I've lived in the last 3 years** I want to enter the name and contact information for someone who knows I lived at that location so that my investigator can reach out to this people for verification and character reference. 

Provide the name of a neighbor, landlord (if rental), or other person who knows you at this address.
  - [x] Provide the full name - Name block

Provide date of last contact:
  - [x] Date - Est

Provide your relationship to this person (check all that apply)
  - [x] Select: "Neighbor", "Friend", "Landlord", "Business associate", "Other (Provide explanation)" 
  - [x] Explanation: Multiline Free Text

Provide the following contact information for this person :
  - [x] Telephone block - evening, daytime, cell/mobile 

Provide e-mail address for this person:
  - [x] Email (Free Text) I don’t know 

Provide street address for this person (including apartment number).
  - [x]  Address - With Country Option
     - [x] Provide Street and City
     - [x] State and Zip - or - Country are required
  - [x] Validation - For an APO/FPO Address
    - [x] If State = AA, AE, or AP Then City must be = APO or FPO
    - [x] **Branch** to APO/FPO Location Details

Add Optional Comment
  - [x] Optional - show only if needed
  - [x] Help - "Note: If you need to provide any additional comments about this information, enter them below."
  - [x] Multiline free-text

## Feedback

- [x] Validation rules are enforced on the client side as the user leaves the field
- [x] Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by floresj** [comment]
Legacy
![selection_246](https://cloud.githubusercontent.com/assets/5938731/22552210/f5159b80-e925-11e6-8c3d-352e1f21cf7b.png)

**Comment by bmallred** [comment]
Items left:

 - [ ] Ensure validations are working
 - [ ] Make sure completed flags are passed
 - [ ] Make sure errors are passed
 - [ ] Refactor the `referenc()` function in to another component for re-use in other sections
