### ISSUE TITLE
Apply components to employment history

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#390]
Epic #341

Fill out the requirements once the epic has been spec'd out

- [x] Select your employment activity
- [x] Provided dates of employment
- [x] Provide the name of your employer
- [x] Select the employment status for this position
- [x] Provide most recent position title
- [x] Provide the address of employer
- [x] Provide telephone number
- Additional periods of activity with this employer
  - [x] Do you have any additional periods of activity to add (Yes/No)

**Comment by floresj** [comment]
![selection_254](https://cloud.githubusercontent.com/assets/5938731/22588313/3f329166-e9d3-11e6-8e25-dc04724dd3e2.png)
