### ISSUE TITLE
Physical attributes - margins and spacing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#398]
The margins and spacing look a bit off on the visual answer sections.

Prototype:
![prototype](https://cloud.githubusercontent.com/assets/19935974/22559221/7642f3ac-e93e-11e6-9843-ebf686dc5638.png)

vs

Comp:
![comp](https://cloud.githubusercontent.com/assets/19935974/22559222/777d2594-e93e-11e6-89ea-8a5f74825c7c.png)

**Comment by joeignition** [comment]
Reviewed with Jay and ready to close. help icon positioning will be resolved in another issue: #406
