### ISSUE TITLE
"Add question about.." margins and font weight

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#399]
Margin above the "Add question is too large.

Font weight should be bold.

Prototype:
![screen shot 2017-02-02 at 1 22 22 pm](https://cloud.githubusercontent.com/assets/19935974/22562519/e118277c-e94a-11e6-97a4-4e2e511f7bf7.png)

Comp:
![screen shot 2017-02-02 at 1 22 34 pm](https://cloud.githubusercontent.com/assets/19935974/22562527/e86ea140-e94a-11e6-9234-304827e594e8.png)

**Comment by bmallred** [comment]
Duplicate #363
