### ISSUE TITLE
Date range block - margins 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#400]
Date range block element margins are too small. Need more room to breathe.

Prototype:
![screen shot 2017-02-02 at 1 26 41 pm](https://cloud.githubusercontent.com/assets/19935974/22562627/56001f68-e94b-11e6-9ae4-220bea45689e.png)

Comp:
![screen shot 2017-02-02 at 1 26 16 pm](https://cloud.githubusercontent.com/assets/19935974/22562634/5b113ec4-e94b-11e6-89ba-cb7f9892449d.png)

**Comment by bmallred** [comment]
## Preview

![daterange](https://cloud.githubusercontent.com/assets/697855/23510222/a784dc7a-ff26-11e6-9258-d76762e00eae.png)
