### ISSUE TITLE
Passport section - Passport vs passport card

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#402]
For the passport card checkbox:

Can we switch to a U.S. Passport vs Passport Card button selection?

So order would be:

1. Provide your U.S. passport number
2. [Passport (default)] [Passport card]    (this will be the box buttons, Yes/No style)
3. Input 

Current style:
![screen shot 2017-02-02 at 1 36 34 pm](https://cloud.githubusercontent.com/assets/19935974/22562942/a45be4ac-e94c-11e6-9090-70e5511becfb.png)

**Comment by bmallred** [comment]
The buttons **Passport Book** and **Passport Card** would be below the number still? Should  we make the text box equal the width of the buttons?

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 something like this?

![passport-book-card-toggle](https://cloud.githubusercontent.com/assets/697855/22605438/d93eb90c-ea1d-11e6-9535-96fa44ecdbce.png)

**Comment by bmallred** [comment]
![passport-card-book-toggle](https://cloud.githubusercontent.com/assets/697855/22666145/7ff6c3d4-ec85-11e6-9486-9dbb1cc1f6dd.png)
