### ISSUE TITLE
Add additional comment discussion

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#403]
Need to determine where and how the Add additional comments will appear.

Per section on the the form and whether it will be a full section comment or comment tied to individual section.

Discussion/decisions need to include Sheldon and likely other.

**Comment by Jay-Neighbours-I72** [comment]
@billy22g What is the best way to get an answer on this? 

@pjsumm mentioned he wanted "clarification on this so we can move forward"

**Comment by billy22g** [comment]
@Jay-Neighbours-I72 I thought we already decided that comments would be related to individual fields to limit contextual confusion?

**Comment by Jay-Neighbours-I72** [comment]
@billy22g I remember that being the preference from my end. That is excellent though, for some reason I thought it was still being decided. I think individual fields is much more clear to users.

I mentioned to Paul earlier though that the style for these comments is flexible enough that we can use on a specific field or the full section if that decision ever changes.

@pjsumm Did you have something else in mind? Is this the clarification you needed?

**Comment by billy22g** [comment]
All of that works for me.

**Comment by Jay-Neighbours-I72** [comment]
Here is the full section comment style in case we need to use it in the future:

![e-qip-comp-section-comment-style-1](https://cloud.githubusercontent.com/assets/19935974/24926186/c1afe786-1ec8-11e7-9888-64e92a8a1971.jpg)
![e-qip-comp-section-comment-style-2](https://cloud.githubusercontent.com/assets/19935974/24926185/c16e876e-1ec8-11e7-839b-2d428963fd76.jpg)

**Comment by bmallred** [comment]
:skull: **R** :skull: **I** :skull: **P** :skull: 

On the good side  we have all the internals built for focused comments.
