### ISSUE TITLE
Passport name auto population 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#404]
When user is entering passport information can we auto populate their name?

Flow would be:

1. H3 - "Is this the name that exactly matches your passport?"
2. Name inputs auto populated
3. H4 "This name exactly matches my passport"
4. Yes/No button

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 @pjsumm 

Yeah I think there was a conversation about this at the end of Sprint 4. We weren't sure if this should be comp'd out or not though.

Reference: #313 Allow subject to select previously entered name or use a new one for Passport

**Comment by bmallred** [comment]
Thinking of doing something similar to [the address verification](https://github.com/truetandem/e-QIP-prototype/issues/377#issuecomment-278745680) style. @Jay-Neighbours-I72 what do you think?

**Comment by bmallred** [comment]
Moving to [Sprint 7](https://github.com/truetandem/e-QIP-prototype/milestone/8) since design comps were not approved until end of [Sprint 6](https://github.com/truetandem/e-QIP-prototype/milestone/7)

**Comment by Jay-Neighbours-I72** [comment]
I like using that style here a lot.

**Comment by bmallred** [comment]
## Updated with modal

![alternate_names](https://cloud.githubusercontent.com/assets/697855/23676696/88a4d750-034b-11e7-983b-abb539c896ce.png)

**NOTE**: Design guidelines are present in the screenshot
