### ISSUE TITLE
Move rendering position of input's connected checkboxes.

### ISSUE THREAD

**Issue by joeignition** [truetandem/e-QIP-prototype#407]
Currently, any "initial only" or "no middle name" checkboxes render between an input's error message and help message.

These inputs should always render directly after the related input field, above both error and help messaging components.
![screen shot 2017-02-03 at 9 33 07 am](https://cloud.githubusercontent.com/assets/1541473/22595159/357efdb4-e9f4-11e6-80af-3e7148695106.png)

**Comment by bmallred** [comment]
Since these items are wrapped in the `Help` component as well maybe it should be able to handle the error messages, too. This would at least allow both types of messages to be placed in the same area.
