### ISSUE TITLE
Telephone `I don't know option` not aligned inside of Collection component

### ISSUE THREAD

**Issue by floresj** [truetandem/e-QIP-prototype#439]
Updated style to ensure the `I don't know` button renders inline to match comp.

**Currently**
![screen shot 2017-02-08 at 11 52 03 am](https://cloud.githubusercontent.com/assets/5938731/22754619/0920c3e2-edf5-11e6-9605-ea9bdea04807.png)

**Match with**
![screen shot 2017-02-08 at 11 52 38 am](https://cloud.githubusercontent.com/assets/5938731/22754649/23027350-edf5-11e6-9113-5bfb042a7844.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 how does this look?

![telephone-padding](https://cloud.githubusercontent.com/assets/697855/22804100/9003986c-eee5-11e6-9fc2-064c28e6492b.png)
