### ISSUE TITLE
When appending to the collection the new item should not be within the accordion

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#449]
Pointed out by @Jay-Neighbours-I72 that the collection/accordion is not behaving as was originally designed.

Things to note:
 - Items do not get added to the accordion until after clicking the add/append button
 - Items which are not part of the accordion need to persist throughout navigation
 - Items which are not part of the accordion still need the remove button

## What it currently is...

![collection-appending-current](https://cloud.githubusercontent.com/assets/697855/22834178/510c6f10-ef82-11e6-99a0-9b0d07d47f1a.png)

## What it should be...

![collection-appending-futur](https://cloud.githubusercontent.com/assets/697855/22834179/51e5d5f2-ef82-11e6-8481-3dfd88922065.png)

**Comment by bmallred** [comment]
Hold on making these adjustments because there are additional changes being testing in usability testing for Sprint 7.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 okay to close this since it seems we are moving away from this direction?

**Comment by Jay-Neighbours-I72** [comment]
yeah i think so. closing now
