### ISSUE TITLE
No middle name checkbox bug

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#470]
Information about you section

User selected "no middle name" then continues on through form.
When they get to the review screen "no middle name" is unchecked.

![screen shot 2017-02-15 at 1 26 31 pm](https://cloud.githubusercontent.com/assets/19935974/22989115/9af47b28-f382-11e6-982c-c62bd1b0be7f.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I think this is left over from before we went with the explicit checkbox route and had the text be optional overall.
