### ISSUE TITLE
Other names used - margin issues

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#471]
Information about you section > Other names 

- [x] Remove extra left margin on "Have you used any other names?" headline

![screen shot 2017-02-15 at 1 34 04 pm](https://cloud.githubusercontent.com/assets/19935974/22989363/98bd4b68-f383-11e6-837a-aa7c552d651d.png)

**Comment by bmallred** [comment]
## Closed

![sex-comment-add](https://cloud.githubusercontent.com/assets/697855/23067880/35675cbc-f4ef-11e6-8f7f-979afcc836a1.png)


## Opened

![sex-comment-heading](https://cloud.githubusercontent.com/assets/697855/23067889/390d9afc-f4ef-11e6-920a-75b53bdb1151.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 are you still seeing this? Curious if it was fixed by another change.

## What I see...

![othesnames](https://cloud.githubusercontent.com/assets/697855/23083607/7c55165e-f52c-11e6-98e2-685d420ec791.png)

**Comment by Jay-Neighbours-I72** [comment]
Not seeing any margin issues anymore.

Can we change "Have you used any other names back to a headline? H3.

When changed back to a H3 looks like the margin issue is still there....
![screen shot 2017-02-20 at 9 32 18 am](https://cloud.githubusercontent.com/assets/19935974/23129143/8c07b4c4-f74f-11e6-8f95-0faf2615ef8f.png)

**Comment by bmallred** [comment]
## Preview

![othernames-heading](https://cloud.githubusercontent.com/assets/697855/23260539/5098d406-f9a0-11e6-8f29-d2286fdaeb4c.png)
