### ISSUE TITLE
Enter key to select items

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#472]
During usability testing a user tried to make a selection using the enter key.

Ex. Tabbing through phone number inputs, tab to "Mobile" phone type, press enter to select

**Comment by pjsumm** [comment]
Need to review the underlying HTML form elements to see if switching from radio buttons to checkboxes is needed.

**Comment by bmallred** [comment]
This should be resolved now with #2329

**Comment by Jay-Neighbours-I72** [comment]
I am seeing this work on buttons like suffix buttons but not on check boxes like "Initial only"

![screen shot 2017-12-21 at 11 43 15 am](https://user-images.githubusercontent.com/19935974/34265569-3933541c-e644-11e7-8aee-0300670cc6a9.jpg)

**Comment by Jay-Neighbours-I72** [comment]
lgtm
