### ISSUE TITLE
DOB error bug

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#473]
Information about you > DOB

- [ ] Error indicator icons flash in left nav before user is done inputting year

![screen shot 2017-02-15 at 1 46 12 pm](https://cloud.githubusercontent.com/assets/19935974/22989855/66024000-f385-11e6-929c-2ac99afd2b07.png)

**Comment by bmallred** [comment]
This issue in general may need some brainstorming on possibly reworking how errors are passed. We have two different paths they can take with what appears to be the same goals.
