### ISSUE TITLE
Format phone number in summaries

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#475]
- [x] Insert correct dashes and parenthesis in the summary to match the input style

![screen shot 2017-02-15 at 2 06 30 pm](https://cloud.githubusercontent.com/assets/19935974/22990735/1bbfe486-f388-11e6-904e-b1739746f6b9.png)

**Comment by bmallred** [comment]
In this order:

 1. Domestic
 2. DSN
 3. International

## Preview

![formatted-phone-numbers](https://cloud.githubusercontent.com/assets/697855/23023123/ff492b1a-f421-11e6-8bd5-41823c361f0e.png)
