### ISSUE TITLE
Finalize accordion style/functionality

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#476]
Currently 2 accordion styles/functionality are on the table. Thinking a discussion/decision point is needed.

**From the comp:**
- Item is only added to the accordion after clicking "add another.." button. (may need to change this to save and add another.."
- New(blank( input sits below and separate from accordion
![screen shot 2017-02-15 at 2 12 04 pm](https://cloud.githubusercontent.com/assets/19935974/22991048/12cfe35c-f389-11e6-900a-b82a6fd10892.png)

vs.

**From the prototype:**
- Item is added to the accordion immediately when blank inputs are created
- New(blank) input is part of the accordion already 
![screen shot 2017-02-15 at 2 16 36 pm](https://cloud.githubusercontent.com/assets/19935974/22991149/64049538-f389-11e6-8ac5-9e0ce4ef3e6e.png)

**Comment by bmallred** [comment]
This is related to issue #449

**Comment by Jay-Neighbours-I72** [comment]
Joe has some thoughts about this from the Usability testing. Recommend holding off until he goes over that with us. @bmallred

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 are you okay if we close this since we have another epic #607 for storyboarding other accordion options?
