### ISSUE TITLE
Height  - 0 inches bug

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#477]
Information about you > Physical attributes > Height

If user inputs 0 for inches no validation is shown.

![screen shot 2017-02-15 at 2 19 22 pm](https://cloud.githubusercontent.com/assets/19935974/22991351/f3b3d554-f389-11e6-82a1-e893053ededa.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 I just tried to reproduce this but found satisfactory results. I tried both using keyboard navigation as well as mouse in both `chrome` and `firefox`. Any assistance in getting this to reproduce would be great!

## Screenshot

![height-validation](https://cloud.githubusercontent.com/assets/697855/23025335/98d754ec-f42b-11e6-9d44-f3aed4703dcf.png)

**Comment by Jay-Neighbours-I72** [comment]
Just tested again.

Looks like on initial input it validates

When you go to another section then come back it loses validation. Also loses on review screen.

I'm on Chrome

**Comment by bmallred** [comment]
Thanks for that info!

Turns out we have this check:

```js
if (this.state.value) { /* do validation stuff */ }
```

and typically it comes in as a string such as `'0'` but on re-entry it is an integer like `0` which evaluates as `false` in Javascript land causing it to bypass validations.
