### ISSUE TITLE
High Priority Bug

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#478]
Information about you > Other names used

User selects Yes
Leaves inputs empty and moves on
On review screen answer is changed to No

Have to make sure form never changes a user's answer like this.

![screen shot 2017-02-15 at 2 26 37 pm](https://cloud.githubusercontent.com/assets/19935974/22991654/060180ac-f38b-11e6-89dc-e793659aca97.png)

![screen shot 2017-02-15 at 2 26 49 pm](https://cloud.githubusercontent.com/assets/19935974/22991658/08db5960-f38b-11e6-92ee-0be3080cf953.png)

**Comment by bmallred** [comment]
Good news is we weren't changing their responses. Bad news is according to the logic their selection wasn't persisted on the first selection **unless** they selected "No".

This affected the following branching:
 - Other names
 - Gambling
 - Bankruptcy
