### ISSUE TITLE
Initial only checkbox - hit area width

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#479]
The hit area on the "Initial only" checkboxes spans the full width. Users were accidentally checking it.

Reduce the width to correspond with the checkbox and text only.

![screen shot 2017-02-15 at 2 32 46 pm](https://cloud.githubusercontent.com/assets/19935974/22991832/a280a5d4-f38b-11e6-9737-35bd694bc34f.png)

**Comment by bmallred** [comment]
The hit area has a dashed blue border around it

![hit-area-initial-only](https://cloud.githubusercontent.com/assets/697855/23024206/23fa87ba-f427-11e6-8cb7-ba1431722560.png)
