### ISSUE TITLE
Center Last saved text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#486]
- [x] All sections - Center the "Last saved.." text and icon in the space.

Protoype:
![screen shot 2017-02-15 at 3 13 02 pm](https://cloud.githubusercontent.com/assets/19935974/22993508/4791d700-f391-11e6-93e0-b8c75a96a161.png)

Comp:
![screen shot 2017-02-15 at 3 12 56 pm](https://cloud.githubusercontent.com/assets/19935974/22993511/4b78a038-f391-11e6-877d-6828c5169f7c.png)

**Comment by bmallred** [comment]
## Preview

![last-saved-centered](https://cloud.githubusercontent.com/assets/697855/23261009/74bf740a-f9a2-11e6-88c0-050bf3e0a7ed.png)
