### ISSUE TITLE
Add comment text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#490]
- [x] When we are adding a comment to a specific question change the headline to "Add comment about [question name]"

Prototype:
![screen shot 2017-02-15 at 3 15 40 pm](https://cloud.githubusercontent.com/assets/19935974/22993685/d71bd164-f391-11e6-9ac9-9194814c2adc.png)

Comp:
![screen shot 2017-02-15 at 3 16 13 pm](https://cloud.githubusercontent.com/assets/19935974/22993690/db20970e-f391-11e6-823f-46786245435a.png)

**Comment by bmallred** [comment]
## Closed

![sex-comment-add](https://cloud.githubusercontent.com/assets/697855/23067880/35675cbc-f4ef-11e6-8f7f-979afcc836a1.png)


## Opened

![sex-comment-heading](https://cloud.githubusercontent.com/assets/697855/23067889/390d9afc-f4ef-11e6-920a-75b53bdb1151.png)
