### ISSUE TITLE
Create reprimand component

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#495]
Epic: #419

If this is grouped in with the existing employment item then should only be asked if is within the 7 years.

## Fields
  - [x] For this employment, in the last seven (7) years have you received a written warning, been officially reprimanded, suspended, or disciplined for misconduct in the workplace, such as a violation of security policy?
  - [x] Yes/No Option
  - [ ] **Branch**
    - [ ] ~~On No - move on to next subsection/section~~ 
    - [ ] ~~On Yes - show the data entry form for job reprimand:~~

Provide the month and year you were warned, reprimanded, suspended or disciplined 
  - [x] Date Month\Year - Est

Provide the reason(s) for being warned, reprimanded, suspended or disciplined 
  - [x] Multiline free-text

## Actions

  - Action - Add another reprimand

- [x] Add question - "Do you have another instance of discipline or a warning to provide?"
    - [x] Add Yes - appends another job reprimand data entry section
  - Action - Remove reprimand
    - [x] Add No button - required to validate

**Comment by floresj** [comment]
![selection_297](https://cloud.githubusercontent.com/assets/5938731/23663181/d5794bf0-031f-11e7-9b40-6f47b52942d6.png)

![selection_298](https://cloud.githubusercontent.com/assets/5938731/23663183/d824c5e6-031f-11e7-976c-170a098ca3c6.png)
