### ISSUE TITLE
Complete help style

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#504]
Fill out the help style to include all elements.

- [x] Headline 
- [x] Regular style (already there)
- [x] Note
- [x] Close text

Comp:
![screen shot 2017-02-16 at 4 16 34 pm](https://cloud.githubusercontent.com/assets/19935974/23041605/6c6a387e-f463-11e6-9116-102dd129e35c.png)

Prototype:
![screen shot 2017-02-16 at 4 16 42 pm](https://cloud.githubusercontent.com/assets/19935974/23041613/743cacda-f463-11e6-8463-7e83c665cd24.png)

**Comment by bmallred** [comment]
## Preview

![message-structure](https://cloud.githubusercontent.com/assets/697855/23278210/b7eff9e8-f9de-11e6-9879-419c082809a7.png)
