### ISSUE TITLE
Your history - employment branching discussion

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#510]
There is branching within the add employer depending on what type of employment it is.

Dev team regroup with Jay and we can talk through where this will live in the form flow.

**Comment by bmallred** [comment]
Crosslinked with
 - Epics: #411, #412, #413, #414, #415
 - Tasks: #498, #497, #496

**Comment by bmallred** [comment]
Recap on this discussion after we work on the items above to dot our I's
