### ISSUE TITLE
Your contact information - add text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#513]
Found some text in the 2016 form version that needs to be added to the Your Contact Information section.

**Text to add under email headline:**
Email addresses may be used as a contact method, and identify subject in records.

**Text to add under phone headline:**
Provide three contact numbers. At least one telephone number is required. Additional numbers provided may assist in the completion of your background investigation.

![screen shot 2017-02-17 at 3 59 52 pm](https://cloud.githubusercontent.com/assets/19935974/23083094/32709c4a-f52a-11e6-857f-81c785886ae8.png)

**Comment by bmallred** [comment]
## Preview

![contact-new-verbiage](https://cloud.githubusercontent.com/assets/697855/23083862/bdeacc20-f52d-11e6-9acb-82533509f1f8.png)
