### ISSUE TITLE
Passport information tweaks

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#517]
- [x] Add a return (to give margin) above the text link "U.S. State Department passport help"

- [x] Change "Do you possess a U.S. passport?" to an H3. Keep current or expired as paragraph text.

![screen shot 2017-02-20 at 11 30 45 am](https://cloud.githubusercontent.com/assets/19935974/23134003/2bf0368a-f761-11e6-82da-7843c95f74df.png)

**Comment by bmallred** [comment]
## Preview

![passport-headline-tweaks](https://cloud.githubusercontent.com/assets/697855/23261152/07346854-f9a3-11e6-9a14-e19469a0e52d.png)
