### ISSUE TITLE
Financial record Headline and label updates

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#518]
Changing a few headlines and labels around to match the updated headline question style.

**Gambling Debt:**
- [x] Remove "Losses" label
- [x] Remove "Description" label
- [x] Remove "Action(s) taken or explanation label"

**Bankruptcy:**
- [x] Remove "Number" label
- [x] Remove "Amount" label
- [x] Remove "Court name" label
- [x] Remove "Trustee name" label (in the chapter 13 branch)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 should the branch questions be changed to `h3` elements as well?
