### ISSUE TITLE
Bankruptcy - Chapter 12 missing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#519]
- [x] Chapter 12 selection is missing.

![screen shot 2017-02-20 at 1 26 55 pm](https://cloud.githubusercontent.com/assets/19935974/23137513/64e1d0c0-f770-11e6-8ce3-14d9e95076ad.png)

![screen shot 2017-02-20 at 1 26 58 pm](https://cloud.githubusercontent.com/assets/19935974/23137498/58384e3a-f770-11e6-81e5-70ab4a1c0276.png)

**Comment by bmallred** [comment]
Nice catch. This slipped by even when going through the checklist on epic #253

**Comment by bmallred** [comment]
## Preview

![chapter12](https://cloud.githubusercontent.com/assets/697855/23167303/dea6bdd4-f811-11e6-98af-ff50c858ed89.png)
