### ISSUE TITLE
Bankruptcy - bakruptcy discharge

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#520]
- [x] Add "not applicable" option to Bankruptcy discharge 

![screen shot 2017-02-20 at 1 29 20 pm](https://cloud.githubusercontent.com/assets/19935974/23137683/6650d41e-f771-11e6-8ea3-36d8955d1fef.png)

**2016 Form:**
![screen shot 2017-02-20 at 1 29 23 pm](https://cloud.githubusercontent.com/assets/19935974/23137686/68f317d6-f771-11e6-9d54-bf15e155a908.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 did we want a different style for the **not applicable**? Like I think in one of the comps we had the button and then disabled the control or something along those lines.

**Comment by Jay-Neighbours-I72** [comment]
Yeah, let's use this style:

![screen shot 2017-02-22 at 11 08 09 am](https://cloud.githubusercontent.com/assets/19935974/23220229/4012562c-f8ef-11e6-8b03-4dc6a6dc9876.png)

**Comment by bmallred** [comment]
## Preview

![bankruptcy-discharge-na](https://cloud.githubusercontent.com/assets/697855/23866078/17a0e8bc-07ee-11e7-9527-7c7ada20416d.png)
