### ISSUE TITLE
Bankruptcy - total amount 

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#521]
- [x] Add "Estimated" in bankruptcy amount

![screen shot 2017-02-20 at 1 46 25 pm](https://cloud.githubusercontent.com/assets/19935974/23137973/04aa55a8-f773-11e6-8a1b-24855f799170.png)

**2016 form:**
![screen shot 2017-02-20 at 1 46 28 pm](https://cloud.githubusercontent.com/assets/19935974/23137988/0a4e633c-f773-11e6-970e-d19b3bdb7ab3.png)

**Comment by bmallred** [comment]
## Preview

![estimated-amount](https://cloud.githubusercontent.com/assets/697855/23166906/8d2bbee2-f810-11e6-88f3-a9ac013b70ac.png)
