### ISSUE TITLE
Your history - start screen text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#536]
- [x] Match paragraph text from comp

Correct text:
"List the places where you have lived and worked beginning with your present residence or employeer and working back 10 years. **Residences and employers for the entire period must be accounted for without breaks.** 

You will also list any school attended in the last 10 years and all diplomas & degrees earned at any point in your life."

Prototype:
![screen shot 2017-02-23 at 1 07 08 pm](https://cloud.githubusercontent.com/assets/19935974/23273382/cd70649a-f9cc-11e6-96a1-f3db674a3fe8.png)

Comp:
![screen shot 2017-02-23 at 1 07 30 pm](https://cloud.githubusercontent.com/assets/19935974/23273387/d27b8596-f9cc-11e6-89c8-e7333205cb71.png)

**Comment by bmallred** [comment]
I think we had matched it to the assigned Epic but I will verify.

**Comment by bmallred** [comment]
## Preview

![timeline-intro](https://cloud.githubusercontent.com/assets/697855/23305852/bca39284-fa6e-11e6-8057-541bf54a8c7f.png)
