### ISSUE TITLE
Your history - start screen styles

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#537]
Start screen style issues:

- [x] Icons look too big
- [x] Icons need more margin above
- [x] "Start with your..." text looks to small and heavy
- [x] Add button stroke looks too thin
- [x] Add button + icon looks too large
- [x] Add button text looks too large

Prototype:
![screen shot 2017-02-23 at 1 07 08 pm](https://cloud.githubusercontent.com/assets/19935974/23273435/fd7fe494-f9cc-11e6-8ca6-4c847ccd29cc.png)

Comp:
![screen shot 2017-02-23 at 1 07 30 pm](https://cloud.githubusercontent.com/assets/19935974/23273439/00d45526-f9cd-11e6-8951-2ba8684e5943.png)

**Comment by bmallred** [comment]
Stroke should be `4px`

**Comment by bmallred** [comment]
## History timeline introduction

![history-intro](https://cloud.githubusercontent.com/assets/697855/23313227/cfd2ee10-fa8a-11e6-92eb-cf87852d8827.png)
