### ISSUE TITLE
Your history - progress numbers and text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#539]
- [x] Correct color for Your history progress numbers and text is #5b606b

Prototype:
![screen shot 2017-02-23 at 3 12 19 pm](https://cloud.githubusercontent.com/assets/19935974/23277095/bb755a62-f9da-11e6-9c61-a632d6307f94.png)

Comp
![screen shot 2017-02-23 at 3 12 30 pm](https://cloud.githubusercontent.com/assets/19935974/23277101/c0350430-f9da-11e6-9d24-408f94a5b6bc.png)

**Comment by bmallred** [comment]
## Summary progress and counters

![summary-counter-progress-text](https://cloud.githubusercontent.com/assets/697855/23310240/d7290b6e-fa7f-11e6-8990-18cad5ea79a8.png)
