### ISSUE TITLE
Visual answer icon color

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#540]
- [x] Correct color for basic visual answer icons is #5b606b

Prototype:
![screen shot 2017-02-23 at 3 11 23 pm](https://cloud.githubusercontent.com/assets/19935974/23277219/0f6ac71a-f9db-11e6-96e5-11e1f17b0066.png)

Comp:
![screen shot 2017-02-23 at 3 16 50 pm](https://cloud.githubusercontent.com/assets/19935974/23277242/21f8aeba-f9db-11e6-9312-fb507a610e42.png)

**Comment by bmallred** [comment]
## Icons in radio/checkbox inputs

![svg-option-color](https://cloud.githubusercontent.com/assets/697855/23311103/dfe4ddf2-fa82-11e6-93af-27123910b48c.png)
