### ISSUE TITLE
Accordion - add hover state

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#541]
- [x] Add hover state to accordion items.

Prototype:
![screen shot 2017-02-23 at 3 20 19 pm](https://cloud.githubusercontent.com/assets/19935974/23277567/4e94ff86-f9dc-11e6-9067-c3c03f85a817.png)

Comp:
![screen shot 2017-02-23 at 3 24 46 pm](https://cloud.githubusercontent.com/assets/19935974/23277572/51af31fa-f9dc-11e6-96ed-7151457c6b12.png)

**Comment by bmallred** [comment]
So had to make some structure as well as style changes to both the `HistoryCollection` and regular `Collection`.

## Collection

![regular-collection-hover](https://cloud.githubusercontent.com/assets/697855/23309813/290bb62c-fa7e-11e6-9458-cbecfd0ec37d.png)

## HistoryCollection

![history-collection-hover](https://cloud.githubusercontent.com/assets/697855/23309808/24df3fc4-fa7e-11e6-9080-cbfddbedc4fd.png)
