### ISSUE TITLE
Your history - add employer text missing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#542]
- [x] Add missing text at top of add employer section

Missing text:
"**List where you have worked**
List all of your employment activities, including unemployment and self-employment, beginning with the present and working back 10 years. The entire period must be accounted for without breaks. If the employment activity was military duty, list separate employment activity periods to show each change of military duty station.

Do not list employment before your 18th birthday unless to provide a minimum of 2 years employment history."

Prototype:
![screen shot 2017-02-23 at 4 19 25 pm](https://cloud.githubusercontent.com/assets/19935974/23279787/9ed6c8d2-f9e4-11e6-8990-1feb4b87dc18.png)

Comp:
![screen shot 2017-02-23 at 4 19 34 pm](https://cloud.githubusercontent.com/assets/19935974/23279782/9bba78ba-f9e4-11e6-9950-0d7821f167b1.png)

**Comment by bmallred** [comment]
Moved from above to within... @Jay-Neighbours-I72 let us know if this works out with the individual section as well.

## Preview

![heading-employment](https://cloud.githubusercontent.com/assets/697855/23306116/f6048352-fa6f-11e6-87de-720f503d0105.png)
