### ISSUE TITLE
Compile a listing of legacy screenshots

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#543]
Requested by @adelevie for demonstration and comparison.

**Comment by bmallred** [comment]
Issues:

 - #152 
 - #191 
 - #195 
 - #254 
 - #255 
 - #267 
 - #276 
 - #289 
 - #325 
 - #327
 - #330 
 - #333
 - #336 
 - #341 
 - #386 
 - #390 
 - #392 
 - #496 
 - #497 
 - #498

**Comment by bmallred** [comment]
You can also search by the label [legacy-screenshot](https://github.com/truetandem/e-QIP-prototype/issues?utf8=%E2%9C%93&q=label%3Alegacy-screenshot) which will be actively maintained.

**Comment by adelevie** [comment]
Thanks so much!
