### ISSUE TITLE
Your history - 10 year coverage

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#552]
- [x] Need to track this coverage to ensure the most recent/current employer or address is added.

This example shows how currently 10 years can be covered without having a most recent/current added.

![screen shot 2017-02-27 at 9 10 46 am](https://cloud.githubusercontent.com/assets/19935974/23364893/dc6c5bac-fcce-11e6-8574-4f72e7971821.png)

**Comment by bmallred** [comment]
## Preview

![progress-bar-update](https://cloud.githubusercontent.com/assets/697855/23371575/87d4bf22-fce6-11e6-8ae0-c8fe4e2ac689.png)

**Comment by Jay-Neighbours-I72** [comment]
nice!
