### ISSUE TITLE
Your history - dividing lines and margins

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#556]
- [x] Add dividing lines where needed (shown in comps)

- [x] Give elements appropriate margins

Prototype:
![screen shot 2017-02-27 at 10 06 45 am](https://cloud.githubusercontent.com/assets/19935974/23366412/9f00f40c-fcd4-11e6-8ae6-9c9c558844e8.png)

Comp:
![screen shot 2017-02-27 at 10 05 04 am](https://cloud.githubusercontent.com/assets/19935974/23366417/a48ccf90-fcd4-11e6-910e-73dc3d2ca5c2.png)

**Comment by bmallred** [comment]
## Preview

![rulers](https://cloud.githubusercontent.com/assets/697855/23368014/5d0a3242-fcda-11e6-9d4d-b7b4fab7d52f.png)
