### ISSUE TITLE
Your history - overall headline sizes

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#558]
- [x] Headlines seem small within the inputs, can we match these closer to comps?

Prototype:
![screen shot 2017-02-27 at 10 15 45 am](https://cloud.githubusercontent.com/assets/19935974/23366736/d6a4f786-fcd5-11e6-9e3f-c415c9fc5ecd.png)

Comp:
![screen shot 2017-02-27 at 10 15 39 am](https://cloud.githubusercontent.com/assets/19935974/23366741/dc94a0ec-fcd5-11e6-83ad-59c3f774e414.png)

**Comment by bmallred** [comment]
## Preview

![header-increase](https://cloud.githubusercontent.com/assets/697855/23370600/34b6f484-fce3-11e6-8133-eb63d5940c26.png)

**Comment by Jay-Neighbours-I72** [comment]
looks good
