### ISSUE TITLE
Your history - add text block when adding school/degree

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#559]
- [x] Add text block above inputs when adding school/degree

Text:
List the places you went to school
Do not list education before your 18th birthday, unless to provide a minimum of two years education history.

Prototype:
![screen shot 2017-02-27 at 11 15 10 am](https://cloud.githubusercontent.com/assets/19935974/23369124/4b911f68-fcde-11e6-841c-2b1a1936eb35.png)

Comp:
![screen shot 2017-02-27 at 11 16 29 am](https://cloud.githubusercontent.com/assets/19935974/23369133/512aa4e4-fcde-11e6-9375-bdab1aec3364.png)

**Comment by bmallred** [comment]
You may be looking at an older version...

## What I see

![list-places-for-school](https://cloud.githubusercontent.com/assets/697855/23371684/eb2e0fec-fce6-11e6-8c3e-dea34974f682.png)

**Comment by Jay-Neighbours-I72** [comment]
Your screenshot looks good. Not what I see though.

I cleared cache and still not seeing it.

![screen shot 2017-02-27 at 3 26 04 pm](https://cloud.githubusercontent.com/assets/19935974/23378450/25c27480-fd01-11e6-9343-22f808c64216.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 isn't the highlighted area (from your post) the piece that is missing?

![highlighted-25c27480-fd01-11e6-9343-22f808c64216](https://cloud.githubusercontent.com/assets/697855/23378991/2d6aa1f6-fd03-11e6-8570-56d6ab323d9a.png)
