### ISSUE TITLE
Your history - degree/diploma add

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#560]
Change from comp:
When adding another degree or diploma let's use the yes/no style again to avoid an accordion within an accordion.

**New flow would be:**

1. User adds first degree or diploma
2. Form question below first diploma "Do you have another degree/diploma to add?" <yes/no buttons>
3. User clicks yes and type and date appear
4. User clicks no and moves on

**Comment by floresj** [comment]
I've updated this to work with the latest accordion changes. However, I'm going to wait to push up until accordion is all styled up. I don't want to break anything!
