### ISSUE TITLE
Write spec for "Former federal service"

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#586]
Write the feature specification for the subsection "Former federal service"

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/27617108-41736c72-5b82-11e7-85af-2375cf527322.gif)

**Comment by pjsumm** [comment]
![testresult](https://user-images.githubusercontent.com/12962390/27617148-7ec95b0e-5b82-11e7-9571-acfb70cc01c2.gif)
