### ISSUE TITLE
State abbreviation bug

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#623]
Manually entering abbreviation (ex. MD) then space after throws and error and doesn't switch to "Maryland"

![screen shot 2017-03-03 at 11 26 54 am](https://cloud.githubusercontent.com/assets/19935974/23559276/72c0f418-0004-11e7-8468-e97841592446.png)

**Comment by bmallred** [comment]
This should be working now... I'll check it is on staging but was part of PR #610
