### ISSUE TITLE
Relationship visual answers size and icon size

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#625]
- [x] Can we match the size of boxes and icons from comp?

Prototype:
![screen shot 2017-03-03 at 3 25 47 pm](https://cloud.githubusercontent.com/assets/19935974/23567789/012cfef6-0026-11e7-920f-8fc3665f3b0c.png)

-

Comp:
![screen shot 2017-03-03 at 3 26 11 pm](https://cloud.githubusercontent.com/assets/19935974/23567793/065245b2-0026-11e7-9b27-648bcd1c33d2.png)

**Comment by bmallred** [comment]
Sure can :)

**Comment by bmallred** [comment]
## Preview

![relationship](https://cloud.githubusercontent.com/assets/697855/23913330/fe449776-08b8-11e7-82a9-c9c9efc6d2d6.png)

@Jay-Neighbours-I72 was this suppose to allow multiple selections?
