### ISSUE TITLE
Military History - help box margin - registration number headline

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#635]
- [x] Reduce margin above help box (Note: ignore the serif headline in the comp, that is a mistake)
- [x] Change "Provide registration number to H3

Prototype:
<img width="718" alt="screen shot 2017-03-07 at 3 59 44 pm" src="https://cloud.githubusercontent.com/assets/19935974/23677766/78b5f276-034f-11e7-8f2d-c2667983c8ae.png">

-

Comp:
![screen shot 2017-03-07 at 3 59 51 pm](https://cloud.githubusercontent.com/assets/19935974/23677777/8178d3e2-034f-11e7-9614-760b5a49626e.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 how do these look?

## Registered

![sss-h3-no-margin-bottom-1](https://cloud.githubusercontent.com/assets/697855/23705198/c0806898-03d6-11e7-8f20-2a6f6b91aa11.png)

## Not registered

![sss-h3-no-margin-bottom-2](https://cloud.githubusercontent.com/assets/697855/23705196/bcae8628-03d6-11e7-8029-a51ce4cc1376.png)

**Comment by Jay-Neighbours-I72** [comment]
I'm 90% sure those look good. Hard to tell with the guides in. I say run with that and we can tweak later if need be.
