### ISSUE TITLE
Military history - Visual answers - selection hover/active style - margins

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#636]
- [x] Let's use our regular hover/selected style for visual answers
- [x] Match margins - currently not enough margin above each box

<img width="731" alt="screen shot 2017-03-07 at 4 06 39 pm" src="https://cloud.githubusercontent.com/assets/19935974/23677931/0e9f4d96-0350-11e7-9b25-f122b776cdbe.png">

-

<img width="767" alt="screen shot 2017-03-07 at 4 06 04 pm" src="https://cloud.githubusercontent.com/assets/19935974/23677934/11217940-0350-11e7-9a1f-e84bcf24d849.png">

**Comment by bmallred** [comment]
## Hover state

![service-hover-state](https://cloud.githubusercontent.com/assets/697855/23705593/9e0e78f2-03d8-11e7-88d7-bc4278a0d8ac.png)

Not the prettiest thing after the transition, but that may be due to the icons not being SVGs.

**Comment by Jay-Neighbours-I72** [comment]
Looks good to me. Agreed we will need those in svgs at some point.
