### ISSUE TITLE
Military History - Headline margins

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#637]
- [x] Too much space below headlines

Prototype:
<img width="785" alt="screen shot 2017-03-07 at 4 09 39 pm" src="https://cloud.githubusercontent.com/assets/19935974/23678092/aa1e5ba4-0350-11e7-981d-34038f0b0635.png">

-

Comp:
![screen shot 2017-03-07 at 4 09 42 pm](https://cloud.githubusercontent.com/assets/19935974/23678095/ada3ed16-0350-11e7-823a-7a466be36574.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 should the date range have the margin between the header and the component removed as well? Took a screenshot of what it looks like removed.

## Preview

![no-label-military-service](https://cloud.githubusercontent.com/assets/697855/23706066/b3e1757e-03da-11e7-9965-b99a478c6422.png)

**Comment by bmallred** [comment]
Applied the same changes throughout the rest of the **Military history** section.

**Comment by Jay-Neighbours-I72** [comment]
Yes to date range. Ideally that margin will be form wide. It keeps the element below the headline visually connected to it.
