### ISSUE TITLE
Military history - status & officer buttons

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#638]
- [x] Clicking an officer buttons clears the status selection

<img width="834" alt="screen shot 2017-03-07 at 4 42 34 pm" src="https://cloud.githubusercontent.com/assets/19935974/23679228/2f609cce-0355-11e7-94aa-f85683df06b8.png">
<img width="813" alt="screen shot 2017-03-07 at 4 42 37 pm" src="https://cloud.githubusercontent.com/assets/19935974/23679230/30a22ee0-0355-11e7-9c8b-9da61390cf84.png">

**Comment by bmallred** [comment]
## Preview

![status-officer-active](https://cloud.githubusercontent.com/assets/697855/23705819/8962198a-03d9-11e7-8566-60673addda99.png)
