### ISSUE TITLE
Military history - text answers - vertically center text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#644]
- [x] Vertically center multi line text

Prototype:
<img width="765" alt="screen shot 2017-03-08 at 2 12 00 pm" src="https://cloud.githubusercontent.com/assets/19935974/23719444/70c81af2-0409-11e7-93b2-89b28f7e4d6a.png">

-

Comp:
<img width="997" alt="screen shot 2017-03-08 at 2 12 19 pm" src="https://cloud.githubusercontent.com/assets/19935974/23719452/781184e2-0409-11e7-9e30-469d092355d5.png">

**Comment by bmallred** [comment]
Ah, and `Other (provide type)` needs a line break in there as well.

**Comment by bmallred** [comment]
The smaller text may be an interesting workaround. I tried the markdown of

```
Other<br><small>(provide type)</small>
```
as well as

```
Other<br><sub><sup>(provide type)</sup></sub>
```

Might need to have @joeignition take a look and do some magic :smile:
