### ISSUE TITLE
Foreign military - text buttons style

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#645]
- [x] Tighter line height
- [ ] Secondary text smaller (ex. after "military")

Prototype:
<img width="827" alt="screen shot 2017-03-08 at 2 23 41 pm" src="https://cloud.githubusercontent.com/assets/19935974/23719913/110eeddc-040b-11e7-8657-13cc4b3bb05c.png">

-

Comp:
<img width="969" alt="screen shot 2017-03-08 at 2 23 37 pm" src="https://cloud.githubusercontent.com/assets/19935974/23719915/15475a56-040b-11e7-83ba-13d3f3296e6a.png">

**Comment by bmallred** [comment]
The smaller text may be an interesting workaround. I tried the markdown of

```
Other<br><small>(provide type)</small>
```
as well as

```
Other<br><sub><sup>(provide type)</sup></sub>
```

Might need to have @joeignition take a look and do some magic :smile:

## Preview

![foreign-service-buttons](https://cloud.githubusercontent.com/assets/697855/23725408/6c1965e6-041e-11e7-8ed3-5bc5ba53e774.png)

**Comment by bmallred** [comment]
## Smaller byline

![smaller-byline](https://cloud.githubusercontent.com/assets/697855/23907482/af101bc8-08a7-11e7-89f0-5edbd2222bc7.png)
