### ISSUE TITLE
Confusing verbiage - "provide at least two", "one is required"

### ISSUE THREAD

**Issue by billy22g** [truetandem/e-QIP-prototype#687]
**What did you do?**
<img width="642" alt="screen shot 2017-03-13 at 9 29 54 pm" src="https://cloud.githubusercontent.com/assets/5091167/23881981/4409a4d4-0834-11e7-819d-e2e17ed6f7c4.png">

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
"Provide two phone numbers (one is required)" potentially, but I'm not 100% sure this is perfectly clear either. As it is now, it's confusing. 

cc: @Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
Agreed it is confusing now. 

If 2 are required then maybe "Provide at least 2 phone numbers..."

If 1 is required then maybe "Provide at least 1 phone number..."

To me the text in parenthesis is the most confusing part.

**Comment by Jay-Neighbours-I72** [comment]
Jay and Laura to provide multiple options on how to reword this text.

**Comment by Jay-Neighbours-I72** [comment]
Suggestion:

Provide at least _your_ phone numbers (one is required). Additional numbers provided may assist in the completion of your background investigation.

Thoughts @lauraponce

**Comment by lauraponce** [comment]
@Jay-Neighbours-I72 nicely done in not straying from the original too much, I think your version makes the requirements a little clearer. Here is another suggestion: 

Provide your phone numbers. At least one number is required, but providing additional numbers may assist in the completion of your background investigation.

**Comment by Jay-Neighbours-I72** [comment]
I like that much more. I'm going to put it in now.
