### ISSUE TITLE
Evaluate font size on smaller screens

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#695]
- [x] Evaluate font sizes on smaller screens 
- [x] Suggest changes if needed

Potentially font size shift at smaller screen sizes to reduce scrolling.

**Comment by Jay-Neighbours-I72** [comment]
Initial tweaks at screens smaller than 1100px wide (before mobile break):

- [ ] Header - reduce font size to 4rem
<img width="175" alt="screen shot 2017-03-27 at 2 21 04 pm" src="https://cloud.githubusercontent.com/assets/19935974/24371561/29f532be-12f9-11e7-81f6-a65d6b56008c.png">

- [ ] H2 - reduce font size to 3rem
<img width="222" alt="screen shot 2017-03-27 at 2 20 33 pm" src="https://cloud.githubusercontent.com/assets/19935974/24371575/36c23154-12f9-11e7-8ff0-e35dc0688f6c.png">

- [ ] Input fields - reduce bottom padding to 1.5rem

Overall goal is to tighten things up a bit on these smaller laptop/tablet sizes. Maybe a working session with dev team and Laura and Jay in the future.

**Comment by floresj** [comment]
For the reduction of the bottom padding, would this be for the `eapp-field-wrap`? I'm looking at some of the form elements and most I've seen have bottom margins < 1.5rem

**Comment by floresj** [comment]
@bmallred This one looks like it'll also be resolved with #406
