### ISSUE TITLE
Diplomatic Post Office (DPO) address validation

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#696]

**Comment by floresj** [comment]
Using DPO is just a matter of adding as an option. USPS validates it like APO/FPO.
![selection_248](https://user-images.githubusercontent.com/5938731/27545838-f18c10c0-5a5e-11e7-8f5d-ecc451605633.png)


![selection_247](https://user-images.githubusercontent.com/5938731/27545807-d2dd3bcc-5a5e-11e7-9f71-4ec056094d1b.png)

![selection_246](https://user-images.githubusercontent.com/5938731/27545788-bfe6eb3a-5a5e-11e7-8180-d55ef386761e.png)

**Comment by lauraponce** [comment]
Looks good!
