### ISSUE TITLE
Create details for police record starting from sentencing

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#714]
Epic #570

# Ensure this part is completed...

## Court information
  - [x] Provide the name of the court
    - [x] Label: Name of Court
    - [x] Free-text

## Provide the location of the court
  - [x] Full Street address with Country

## Charges Detail
  - [x] Label: **Provide all the charges brought against you for this offense**, and the outcome of each charged offense (such as found guilty, found not-guilty, charge dropped or “nolle pros,” etc). If you were found guilty of or pleaded guilty to a lesser offense, list separately both the original charge and the lesser offense.

## Type of charge
  - [x] Choice: Felony, Misdemeanor, Other

## Charge
  - [x] Free-text

## Outcome
  - [x] Free-text

## Date 
  - [x] Date: Month/Year - Est

# This information and details should be new

## Sentencing
  - [x] Were you sentenced as a result of this offense?
    - [x] Yes / No Option
    - [x] **Branch**
      - [x] If Yes show "Conviction detail" section (below)
      - [x] If No show "Trial detail" section (below)

## Conviction detail
  - [x] Provide a description of the sentence.
    - [x] Free-text
  - [x] Were you sentenced to imprisonment for a term exceeding 1 year?
    - [x] Yes / No Option
  - [x] Were you incarcerated as a result of that sentence for not less than 1 year?
    - [x] Yes / No Option
  - [x] If the conviction resulted in imprisonment, provide the dates that you actually were incarcerated. 
    - [x] Not Applicable
    - [x] Date Range - Est/Present
  - [x] If conviction resulted in probation or parole, provide the dates of probation or parole. 
    - [x] Not Applicable
    - [x] Date Range - Est/Present

## Trial detail
  - [x] Are you currently on trial, awaiting a trial, or awaiting sentencing on criminal charges for this offense?
    - [x] Yes / No Option
    - [x] Provide Explanation
      - [x] Free-text

## Do you have any other offenses where any of the following has happened to you?
  - **In the last seven (7) years** have you been issued a summons, citation, or ticket to appear in court in a criminal proceeding against you? (Do not include citations involving traffic infractions where the fine was less than $300 and did not include alcohol or drugs)
  - **In the last seven (7) years** have you been arrested by any police officer, sheriff, marshal or any other type of law enforcement official?
  - **In the last seven (7) years** have you been charged with, convicted of, or sentenced for a crime in any court? (Include all qualifying charges, convictions, or sentences in a Federal, state, local, military, or non-U.S. court even if previously listed on this form.)
  - **In the last seven (7) years** have you been or are you currently on probation or parole?
  - Are you currently on trial or awaiting a trial on criminal charges?
  - If yes use the button below to add another offense  
    - [ ] "Add another offense" button - adds another offense section - [Add Offense](https://github.com/truetandem/e-QIP-prototype/issues/569) 
  - If no select no below and continue
    - [ ] "No" button - move on to next form field

**Comment by floresj** [comment]
Added NA options
