### ISSUE TITLE
History - re-order individual entries to avoid having date first 

### ISSUE THREAD

**Issue by joeignition** [truetandem/e-QIP-prototype#720]
As an eApp user, I want to enter an identifying piece of data before entering date ranges or other information.

 - [x] For a residence, alter order to input address first, then date range, rest of fields.
 - [x] For employment, move the employer name / supervisor name, etc above date range.
 - [x] For education, ensure name of institution appears before date range.

This will be more in line with how Users remember items from their past: remember the place, then date.

**Comment by bmallred** [comment]
@joeignition this includes reordering of the **Information about you** section?

 - Full name
 - Contacts
 - Other names
 - Birth date
 - Birth place
 - Social security number
 - Physical attributes

**Comment by bmallred** [comment]
Need to get with @joeignition and @floresj about moving the supervisor pieces or breaking them apart.
