### ISSUE TITLE
Landing page - blank

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#737]
- [ ] The fist page of the prototype is blank, should start on the full name section.

<img width="2279" alt="screen shot 2017-03-23 at 9 44 42 am" src="https://cloud.githubusercontent.com/assets/19935974/24250480/70ba109c-0fad-11e7-9e70-29126346c8b1.png">

**Comment by bmallred** [comment]
We'll get rid of this all together... usually only happens if you didn't go through the entire login process again.

**Comment by floresj** [comment]
Redirects to `/form/identification/name` now. Removed Home view as well.
