### ISSUE TITLE
Information about you - review scroll

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#738]
- [ ] Clicking “Next - review” button at the end of section 1 doesn’t scroll user to the top of the screen. Takes them to the SSN on the review page

<img width="2282" alt="screen shot 2017-03-23 at 9 48 20 am" src="https://cloud.githubusercontent.com/assets/19935974/24250656/0bf31c0c-0fae-11e7-8fe3-7c4ade251ff1.png">

**Comment by bmallred** [comment]
Appears to only happen when there is information filled in within **Physical Traits**

**Comment by bmallred** [comment]
OOoooOOOOooo... it appears the repopulation of height which then triggers the validation momentarily triggers an error which error message is then scrolled in to view.
