### ISSUE TITLE
Your history - incomplete error timing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#740]
- [x] Incomplete error is being thrown immediately. Should be thrown only when after user is done with accordion item.

<img width="1164" alt="screen shot 2017-03-23 at 9 58 56 am" src="https://cloud.githubusercontent.com/assets/19935974/24251115/794913a0-0faf-11e7-950d-64328de357a1.png">

**Comment by bmallred** [comment]
Not sure how this is going to be accomplished honestly. @floresj any ideas?

**Comment by floresj** [comment]
Mmm, yea this one looks like a fun one. We'll need to decide what `done` means. Is this done as in all fields have been entered and then we check? Or done as in, they're temporarily done and decided to perform another action. For instance

**Scenario**
  - User completes half an accordion item
   **Possible actions that could trigger the red to show up**
     - User decides to add another item to collection despite first one being incomplete.
     - User leaves section and then comes back
     - User fills every field out but then modifies something that invalidates the form

**Comment by joeignition** [comment]
Maybe we hold off until user reaches the review screen? They can complete the items from the review screen, which would be an improvement from the current application's pattern of going back to previous screen.

**Comment by bmallred** [comment]
We can and that is easy because essentially that's what we do for gaps as well
