### ISSUE TITLE
Address validation positioning

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#741]
- [x] Can we center this error on the screen?

<img width="2278" alt="screen shot 2017-03-23 at 10 02 16 am" src="https://cloud.githubusercontent.com/assets/19935974/24251268/f5cce7d0-0faf-11e7-9f9c-80d9046fe732.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 you mean center horizontally **and** vertically correct?

**Comment by floresj** [comment]
And we need to look at what's going on with the z-index since some elements were showing on top of the modal.

**Comment by bmallred** [comment]
The `z-index` issue was captured in #751

**Comment by Jay-Neighbours-I72** [comment]
Correct

**Comment by bmallred** [comment]
Something like this?

![2017-03-24_130822_456023747](https://cloud.githubusercontent.com/assets/697855/24305511/97451856-1093-11e7-8d53-fc05237528ef.png)

**Comment by Jay-Neighbours-I72** [comment]
yeah that looks great.
