### ISSUE TITLE
Person who knows you - name placeholder text

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#742]
- [x] Change person who knows you name placeholder text to:

"Enter first name of the person who knows you"
"Enter middle name of the person who knows you"
"Enter last name of the person who knows you"

Currently they are specific to "you"
<img width="965" alt="screen shot 2017-03-23 at 10 04 43 am" src="https://cloud.githubusercontent.com/assets/19935974/24251458/998bde26-0fb0-11e7-9df7-7cb18ca29ce6.png">

**Comment by floresj** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/5938731/24300992/a667876a-1084-11e7-982a-23ae8cc71489.png)
