### ISSUE TITLE
Accordion Close text link

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#743]
- [ ] Make the hit area large on these text links
- [x] Use the link hand on these text links
- [x] Add margin below the text link (around 20px)

<img width="184" alt="screen shot 2017-03-23 at 10 12 10 am" src="https://cloud.githubusercontent.com/assets/19935974/24251704/73dc510a-0fb1-11e7-975d-5bddb8680c8d.png">

**Comment by bmallred** [comment]
![accordion-close-link](https://cloud.githubusercontent.com/assets/697855/24294719/14cc36fe-106e-11e7-9267-b7ef9d73fd2f.png)
