### ISSUE TITLE
Accordion add new functionality

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#744]
Placeholder issue to have a discussion on accordion open/close polishing

**Comment by Jay-Neighbours-I72** [comment]
New functionality:

By default on append:
- Collapse all previous accordion items (no animation may work)
- Scroll user up to top of accordion (on items with progress bar show progress bar)

**Comment by bmallred** [comment]
Going to close. We can reopen or make tweaks on the PR.
