### ISSUE TITLE
Auto tab on fixed character number inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#747]
Make all items with fixed character number inputs auto tab
Example" SSN, dates, etc.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 we had this before and through the conversation (#507) removed it. Is this for sure what we want?

**Comment by Jay-Neighbours-I72** [comment]
Yes, we removed it then got negative feedback on it during more usability test sessions.

**Comment by floresj** [comment]
@Jay-Neighbours-I72 @joeignition @bmallred Is this something we'll tackle next sprint after some formal discussions with 18F/Sheldon?

**Comment by bmallred** [comment]
@floresj I would say definitely next sprint. We would want to agree on the behaviors in different scenarios.

 1. Focus on an empty input that autotabs
 2. Focus on a non-empty input that autotabs that has not met the maximum characters
 3. Focus on a non-empty input that autotabs that has met the maximum characters
 4. Handling the deletion key on an autotab input
 5. Handling a typeahead selection on an autotab input

and more :smile:

**Comment by joeignition** [comment]
Yes, I think next sprint, this does need some thought prior to implementation. Some inputs are going to be weird. ZIP codes: we take 5 -OR- 9 characters. International phone numbers would be another.
