### ISSUE TITLE
Enter key to select items

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#749]
- [ ] Make it possible for users to use the Enter key to select an item. (form-wide)

<img width="857" alt="screen shot 2017-03-23 at 2 56 31 pm" src="https://cloud.githubusercontent.com/assets/19935974/24265152/e98e792e-0fd8-11e7-9c42-c7bd17c3646e.png">

**Comment by bmallred** [comment]
This was already referenced in #472. If we need to classify this as a bug even though it departs from normal form behavior then apply the label on the other item.
