### ISSUE TITLE
Date range blocks - tab skips present

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#750]
When tabbing through inputs, tab skips over the "Present" button on date range

<img width="655" alt="screen shot 2017-03-23 at 3 18 13 pm" src="https://cloud.githubusercontent.com/assets/19935974/24266071/f254623c-0fdb-11e7-9cf8-dc06a56d054c.png">

**Comment by bmallred** [comment]
Tab from the last **year** takes you to **estimated**. Tab from **estimated** takes you to **present**. Is this not the desired path? If we want to skip **estimated** then is it going to apply to all dates or just in this one use case?

@Jay-Neighbours-I72

**Comment by Jay-Neighbours-I72** [comment]
Ohhh I completely missed this, I think you are correct, the current tabbing works.
