### ISSUE TITLE
Error & Help messages - add border radius

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#752]
- [x] Add 6px border radius to all error and help blocks

<img width="1022" alt="screen shot 2017-03-23 at 4 22 00 pm" src="https://cloud.githubusercontent.com/assets/19935974/24268682/f4f5f3d0-0fe4-11e7-97aa-fe222822b328.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72  for the border radius do you want them on all information and help blocks and not just the one in the accordion summary right?

also, keep the error/help icon in the top-left corner?

**Comment by bmallred** [comment]
## General errors and information

![border-radius-error-info](https://cloud.githubusercontent.com/assets/697855/24296271/d49c3fc8-1074-11e7-94c4-20c554beaaf6.png)

## Accordion incomplete and gap messages

![error-accordion](https://cloud.githubusercontent.com/assets/697855/24296265/cea138f8-1074-11e7-9a5b-1c1e9f80fd1b.png)
