### ISSUE TITLE
Applicant Citizenship Derived

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#758]
As an eApp applicant who is a derived U.S. citizen I want to provide my alien registration information, the basis of my derived citizenship and related document numbers so that my investigator can verify my derived U.S. citizenship.

Acceptance Criteria
- Fields
  - Help: You answered that you are a derived U.S. citizen.
  - Provide your alien registration number (on Certificate of Citizenship—utilize USCIS, CIS or INS registration number).
    - [x] Free Text
  - Provide your Permanent Resident Card number (I-551)
    - [x] Free Text
  - Provide your Certificate of Citizenship number (N560 or N561)
    - [x] Free Text
  - Provide the name in which the document was issued.
    - [x] Name block
  - Provide the date the document was issued.
    - [x] Date/estimated
  - Provide the basis of derived citizenship. 
    - [x] Choice: By operation of law through my U.S. citizen parent. - Other (Provide explanation)
    - [x] Explanation
      - [x] Multi-line text

**Comment by bmallred** [comment]
Determine if there are validation rules for the **certification number** or the **permanent resident card number**.
