### ISSUE TITLE
Adding padding around text on buttons

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#760]
- [x] Add padding around button text and icons

Prototype:
<img width="657" alt="screen shot 2017-03-24 at 11 54 42 am" src="https://cloud.githubusercontent.com/assets/19935974/24302360/c08c00fe-1088-11e7-899b-d3b9d43c5a72.png">

Desired padding: (1em on text - .5em left and right of icon)
<img width="606" alt="screen shot 2017-03-24 at 11 54 34 am" src="https://cloud.githubusercontent.com/assets/19935974/24302369/c6594820-1088-11e7-8b5d-64c88542a13c.png">

**Comment by bmallred** [comment]
This may be fixed already... need to check after everything is merged.

**Comment by floresj** [comment]
![selection_005](https://cloud.githubusercontent.com/assets/5938731/24377357/25d5adee-130d-11e7-89f1-d47035ce3739.png)

![selection_006](https://cloud.githubusercontent.com/assets/5938731/24377378/30bfdbbc-130d-11e7-8335-38149bc1074e.png)
