### ISSUE TITLE
Text below accordion margin & alignment

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#761]
- [x] Increase margin below accordion
- [x] Align buttons below accordion

Prototype:
<img width="939" alt="screen shot 2017-03-24 at 11 56 22 am" src="https://cloud.githubusercontent.com/assets/19935974/24302447/0b1a3b90-1089-11e7-8f01-520e9255bc3c.png">

-
Desired
<img width="1288" alt="screen shot 2017-03-24 at 12 00 42 pm" src="https://cloud.githubusercontent.com/assets/19935974/24302599/923ee8aa-1089-11e7-8d57-e063c3f7ab01.png">

**Comment by bmallred** [comment]
This may be fixed already. Need to check after things have been merged.

**Comment by floresj** [comment]
This looks like it was already resolved. Did an inspection of other sections using this and everything is lining up.

![selection_007](https://cloud.githubusercontent.com/assets/5938731/24377714/467cadbc-130e-11e7-8781-f6a551a1517f.png)
