### ISSUE TITLE
Gambling Debt section - reduce margin above inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#763]
- [x] Reduce the margin above inputs on the gambling debt section - can these me the same form wide?

Prototype:
<img width="828" alt="screen shot 2017-03-27 at 3 44 20 pm" src="https://cloud.githubusercontent.com/assets/19935974/24375081/0ed99aae-1305-11e7-9b67-ecf46ac9add5.png">

Desired:
<img width="905" alt="screen shot 2017-03-27 at 3 50 24 pm" src="https://cloud.githubusercontent.com/assets/19935974/24375093/1bdf019e-1305-11e7-862a-4ffd8b3ef3bc.png">

**Comment by floresj** [comment]
@bmallred I have a feeling #406 will come to the rescue for this one.
