### ISSUE TITLE
History review headline

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#771]
- [x] Use correct (single headline) for review page - correct text - "Let's make sure your history is covered"

Prototype:
<img width="1191" alt="screen shot 2017-03-29 at 9 48 03 am" src="https://cloud.githubusercontent.com/assets/19935974/24457694/f1ac4240-1464-11e7-9a9d-989df81344e9.png">

Comp:
<img width="672" alt="screen shot 2017-03-29 at 9 41 41 am" src="https://cloud.githubusercontent.com/assets/19935974/24457699/f3566508-1464-11e7-9a39-ecfe80aa7279.png">

**Comment by bmallred** [comment]
I think we just have to pass the one heading into the `IntroHeader` component. Artifact of multiple revisions here.
