### ISSUE TITLE
People who know you well email issue

### ISSUE THREAD

**Issue by DBrenenborg** [truetandem/e-QIP-prototype#772]
based on the Usability testing it seemed that users wanted to have an "I Don't Know" for the for people who know you well email.  

In the Content Guide we should be following, it actually should have an "I Don't Know" for the email field. 

![image](https://cloud.githubusercontent.com/assets/23641154/24458346/aafd8726-1466-11e7-937e-9e81a0989cb9.png)

Thanks Drew

**Comment by bmallred** [comment]
Add this to the `Supervisor` and `Reference` components.
