### ISSUE TITLE
Storyboard foreign activities section

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#775]
As an eApp designer I want to create a storyboard showing the layout and navigational flow for the foreign activities section of SF-86 questions asking the applicant about foreign financial interests so that we have a clear outline of how the series of questions will look and behave in the prototype form.

Acceptance Criteria
- Create a Storyboard utilizing the current design styles and standards
- Show how the foreign activities will be presented to the user
- clearly establish how users will navigate between questions
- clearly establish how the resulting data entry will be summarized and shown to the user
- Review the storyboard/comp with the Product Owner
- Product Owner Approval of storyboard

**Comment by Jay-Neighbours-I72** [comment]
Working doc:
https://docs.google.com/document/d/1BhG8X4vCW2GujCvzIgiv9wVSlxDFHGkoQpl55-7E-QI/edit
