### ISSUE TITLE
Create Applicant Finances Credit Counseling summary

### ISSUE THREAD

**Issue by floresj** [truetandem/e-QIP-prototype#787]
Epic #306

Acceptance Criteria
- Summary of Financial Assistance
  - [x] Shown only if counseling service entry has been provided
  - [x] Listing of each credit counseling service entry the applicant has entered
  - [x] For each credit counseling service entry show the following summary fields: 
    - [x] Name of Service: Read-Only label
    - [ ] ~~Date of Service: Read-Only label~~
    - [x] Actions:
      - [x] Edit - goes to personal credit counseling information entry section
      - [x] Delete - Removes the personal credit counseling information entry
- Easily toggle between high-level summary data and detail data
- Error feedback is provided in line, and clearly state which field(s) are incorrect and why

**Comment by bmallred** [comment]
@pjsumm there is no **date** associated with the counseling. Going to strike that part of the summary.
