### ISSUE TITLE
Relatives - Mother branch - full name

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#824]
- [x] Use the full name inputs in the "Mother" branch instead of free text input

This was a mistake on my end, I had the wrong input type in the wireframe.

- [x] Add the "Same as listed" button
This would load the same name from the first time user entered it. Open to a discussion here too whether we would rather use the shared address/name style we are talking about here instead.

Protoype:
<img width="808" alt="screen shot 2017-04-04 at 1 46 07 pm" src="https://cloud.githubusercontent.com/assets/19935974/24670777/6a48ce26-193d-11e7-9bf5-d6726a97606f.png">

-

PDF form:
![screen shot 2017-04-04 at 1 46 13 pm](https://cloud.githubusercontent.com/assets/19935974/24670780/6c8bdb10-193d-11e7-863c-56b0eb747ad9.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 could another option to the `suggestion` style (similar to addresses) be just a button similar to the **Not Applicable** toggles?

**Comment by Jay-Neighbours-I72** [comment]
I think so yeah, so the button would say "Same as listed" and when clicked it would load the address? @bmallred

**Comment by Jay-Neighbours-I72** [comment]
New structure from our conversation:

H3
Provide your mother's maiden name
<Same as listed button> <Different name (will load full name block)>
