### ISSUE TITLE
Relatives - US Citizenship branch - missing

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#827]
- [ ] Looks like the full citizenship branch is missing

PDF form:
![screen shot 2017-04-04 at 2 18 38 pm](https://cloud.githubusercontent.com/assets/19935974/24672177/e68205b2-1941-11e7-8282-d048b805ceef.png)

Example:
<img width="1066" alt="screen shot 2017-04-04 at 2 45 18 pm" src="https://cloud.githubusercontent.com/assets/19935974/24673177/5e0d91ca-1945-11e7-919a-6db810817186.png">

**Comment by bmallred** [comment]
Checking on this. It **was** in there but need to check if something changed.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 in this use case the data provided has everything being a U.S. citizen with no foreign POB or current address.

**Comment by Jay-Neighbours-I72** [comment]
You are right @bmallred , I had the wrong info in there so wasn't seeing it.
