### ISSUE TITLE
Relatives - Address - Outside US block

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#828]
- [ ] Clicking outside the US on the address block loads inputs from a deeper branch (I think too early) 

Might be fixed when the first US Citizenship Documentation inputs are put in

Example:
<img width="797" alt="screen shot 2017-04-04 at 2 26 28 pm" src="https://cloud.githubusercontent.com/assets/19935974/24672500/00426c16-1943-11e7-9297-076392a1b95b.png">
<img width="967" alt="screen shot 2017-04-04 at 2 28 45 pm" src="https://cloud.githubusercontent.com/assets/19935974/24672519/093fe064-1943-11e7-933b-f0bf01bf22f0.png">
<img width="1039" alt="screen shot 2017-04-04 at 2 28 50 pm" src="https://cloud.githubusercontent.com/assets/19935974/24672521/0af491e8-1943-11e7-8d9e-80616833ff50.png">

**Comment by bmallred** [comment]
The **US Citizenship Documentation** are in. https://github.com/truetandem/e-QIP-prototype/issues/827#issuecomment-291619124

I think what we can do is not display the additional branching until a complete address is provided.

**Comment by Jay-Neighbours-I72** [comment]
Sorry @bmallred this was my mistake.

I misunderstood the PDF, what is in the prototype is correct.

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 not a problem... just went through the PDF and looks the fields are showing up as needed, too.
