### ISSUE TITLE
Emotional health - Competence - margin

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#829]
- [x] Large margin below date input (maybe cause of stray div?)

<img width="1193" alt="screen shot 2017-04-04 at 3 49 37 pm" src="https://cloud.githubusercontent.com/assets/19935974/24675892/cca5c022-194e-11e7-92c3-714bf83b3d35.png">
<img width="1046" alt="screen shot 2017-04-04 at 3 49 28 pm" src="https://cloud.githubusercontent.com/assets/19935974/24675893/cdf9d800-194e-11e7-966b-369028f87ffb.png">

**Comment by floresj** [comment]
Interesting, I don't see a checkbox in yours.

![selection_020](https://cloud.githubusercontent.com/assets/5938731/24710848/558a2c96-19ec-11e7-970f-efa95fc14653.png)

**Comment by floresj** [comment]
@bmallred You think this will most likely be resolved with all the goodness happening in #406 ?

**Comment by bmallred** [comment]
@floresj the checkboxes are definitely being displayed, and the padding between fields is consistent throughout. If there is some additional tweaking necessary we can handle it there too.

**Comment by bmallred** [comment]
Going to close this since should be resolved in #406 (coming from PR #896). If it is incorrect you can scold me!
