### ISSUE TITLE
Emotional health - all buttons

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#830]
- [x] Match button text from comp

Subsections have different button texts (some are the same)

Prototype:
<img width="851" alt="screen shot 2017-04-04 at 4 01 26 pm" src="https://cloud.githubusercontent.com/assets/19935974/24676298/6dd50b14-1950-11e7-8f5d-e5256b434ab3.png">

  - 

Comp:
<img width="1022" alt="screen shot 2017-04-04 at 4 01 38 pm" src="https://cloud.githubusercontent.com/assets/19935974/24676308/76f8e166-1950-11e7-802e-3f9e2d318955.png">
<img width="1120" alt="screen shot 2017-04-04 at 4 03 41 pm" src="https://cloud.githubusercontent.com/assets/19935974/24676310/7826ff0a-1950-11e7-8794-10de251d4e18.png">

**Comment by floresj** [comment]
Updated to reflect comp.
