### ISSUE TITLE
Emotional health - Competence - Appealed branch inputs

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#831]
- [x] Looks like the appealed branch doesn't have the correct inputs

Prototype:
<img width="898" alt="screen shot 2017-04-04 at 4 07 25 pm" src="https://cloud.githubusercontent.com/assets/19935974/24676458/0c9360ac-1951-11e7-95a5-ccc776dbd85c.png">

-

Comp:
<img width="614" alt="screen shot 2017-04-04 at 4 07 59 pm" src="https://cloud.githubusercontent.com/assets/19935974/24676462/110d462a-1951-11e7-968f-ebfc3d8fda20.png">

**Comment by floresj** [comment]
Added final disposition field
