### ISSUE TITLE
Relatives - US citizenship documentation - tighten up

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#836]
- [x] Tighten up the buttons (here and form wide) 
equal margin between buttons (left, right, top, bottom), less space below P (ex. derived)

- [x] Use mouse pointer for these buttons instead of regular cursor (for all clickable items form wide)

- [x] 1em left & right padding on text inside buttons (for readability, text is a bit too close to the edge now)

- [x] Small text doesn't look visually centered (top and bottom lines don't look center against each other)

- [x] Provide document number - help icon is shifted below input (bring back up to the right)

Prototype:
<img width="968" alt="screen shot 2017-04-05 at 9 20 04 am" src="https://cloud.githubusercontent.com/assets/19935974/24707557/0eba10a6-19e2-11e7-8e0d-e8540cd8d451.png">

-

Desired:
<img width="857" alt="screen shot 2017-04-05 at 9 23 41 am" src="https://cloud.githubusercontent.com/assets/19935974/24707564/169d11ec-19e2-11e7-91f5-43f05ba4bc48.png">

Help icon:
<img width="786" alt="screen shot 2017-04-05 at 9 30 00 am" src="https://cloud.githubusercontent.com/assets/19935974/24707692/a2bc54da-19e2-11e7-84ea-f0df4e7dd81a.png">

**Comment by bmallred** [comment]
> Use mouse pointer for these buttons instead of regular cursor (for all clickable items form wide)

@Jay-Neighbours-I72 are you still experiencing issues on your end?

**Comment by bmallred** [comment]
Also being re-worked during the refactoring on #406
