### ISSUE TITLE
Form comment preference

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#923]
Need decision on how form comments will be implemented:

- [ ] Allow comments on individual inputs only (could be many per screen)
or
- [ ] Allow comments on full sections only (would be one per screen)
or
- [ ] Allow comments on individual inputs and full sections (case by

**Comment by floresj** [comment]
We have another issue opened that appears to be relevant. #403. Also adding @bmallred

**Comment by Jay-Neighbours-I72** [comment]
Sorry, missed the other one, closing this.
