### ISSUE TITLE
Examine hover state on active/inactive buttons

### ISSUE THREAD

**Issue by bmallred** [truetandem/e-QIP-prototype#953]
Reported by @billy22g

**Comment by Jay-Neighbours-I72** [comment]
Color for button hover: #cececf
<img width="717" alt="screen shot 2017-04-12 at 2 10 14 pm" src="https://cloud.githubusercontent.com/assets/19935974/24972554/cd688404-1f89-11e7-9eaa-88ba2ef62ec6.png">

**Comment by Jay-Neighbours-I72** [comment]
Help icon active style:
Keep hover style when help is open.

Current:
<img width="826" alt="current" src="https://cloud.githubusercontent.com/assets/19935974/24972639/196b9922-1f8a-11e7-88b5-09756c2f519c.png">

Desired:
<img width="813" alt="desired" src="https://cloud.githubusercontent.com/assets/19935974/24972646/21dd8eda-1f8a-11e7-91ca-ca371f964edf.png">

**Comment by Jay-Neighbours-I72** [comment]
Add another buttons:
Change stroke to border: solid 3px #0071bc
![2017-04-12](https://cloud.githubusercontent.com/assets/19935974/24973306/448ad6e8-1f8c-11e7-929c-1a7a551c0f2b.png)

Use box shadow for hover: 0px 1px 5px 0px rgba(0,0,0,0.6)
![2017-04-12-1](https://cloud.githubusercontent.com/assets/19935974/24973312/4713918e-1f8c-11e7-995a-5ea6343220de.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 are there borders on the radio/check buttons in https://github.com/truetandem/e-QIP-prototype/issues/953#issuecomment-293661998

**Comment by Jay-Neighbours-I72** [comment]
@bmallred 
Green button (selected) doesn't have a border.
Border color stays the same on hover and inactive

**Comment by Jay-Neighbours-I72** [comment]
Logout hover:
On hover change text color to #fff
