### ISSUE TITLE
Content Change Audit

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#957]
Go through sections (based on legacy SF86) to determine places where content (field labels/help) have changed and catalog those changes if not already cataloged.

Section 1 - Full Name
Section 2 - Date of Birth
Section 3 - Place of Birth
Section 4 - SSN
Section 5 - Other Names Used
Section 6 - Identifying Information
Section 7 - Your Contact Information

**Comment by Jay-Neighbours-I72** [comment]
Audit done, issues tracking in GH or Content Update doc
