### ISSUE TITLE
Sections Complete Design

### ISSUE THREAD

**Issue by pjsumm** [truetandem/e-QIP-prototype#958]
Review the "Sections complete" box in the navigation to determine if green is the best design choice.  Provide options.

**Comment by Jay-Neighbours-I72** [comment]
Re-worked sections complete to mimic the form "progress bar/counter" style.
This new style saves vertical height which allows us to push the form navigation up a bit.

![e-app-comp-sections-complete-1](https://cloud.githubusercontent.com/assets/19935974/25007725/6cba5fd2-202f-11e7-8816-3240539ff66d.jpg)
![e-app-comp-sections-complete-2](https://cloud.githubusercontent.com/assets/19935974/25007726/6cbc0bac-202f-11e7-8b8f-dad97d914bcf.jpg)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 if there are any errors that bubble up do we need to make it red?

**Comment by Jay-Neighbours-I72** [comment]
No, we can keep the current error style within the navigation.

**Comment by Jay-Neighbours-I72** [comment]
@bmallred Let's go ahead and implement this in the prototype.

Review/tweaks can happen in browser

**Comment by bmallred** [comment]
Sounds good!
