### ISSUE TITLE
Inactive form field style

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#963]
- [x] Let's use the opacity change form wide for inactive form fields.
- [x] Reduce opacity to .35 instead of the current .5

Ex. Change this style:
<img width="810" alt="screen shot 2017-04-12 at 3 06 02 pm" src="https://cloud.githubusercontent.com/assets/19935974/24974879/b6c054b8-1f91-11e7-92f2-9bbfe13e68c1.png">

to this:
<img width="888" alt="screen_shot_2017-04-12_at_2 06 35_pm" src="https://cloud.githubusercontent.com/assets/19935974/24974886/bbb35c68-1f91-11e7-9ffe-03cb8b810cdd.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 this is at the recommended opacity... look okay?

![disabled-dither](https://cloud.githubusercontent.com/assets/697855/24975247/0b0770a0-1f93-11e7-8255-bf4b3f30fd59.png)

**Comment by Jay-Neighbours-I72** [comment]
Sorry @bmallred I worded this strangely

This is the desired style:
<img width="888" alt="screen_shot_2017-04-12_at_2 06 35_pm" src="https://cloud.githubusercontent.com/assets/19935974/24975395/7b56f524-1f93-11e7-81ac-80bc041ecc56.png">


The opacity of the full inactive block (inputs, labels, etc.) is at .5 now. That is what I'd like to reduce to 3.5

**Comment by bmallred** [comment]
Got that, but what about the middle name? Does that need a change as well?

**Comment by Jay-Neighbours-I72** [comment]
As per google hangout:
When input is disabled or read only apply opacity .35 to it and it's associated labels

**Comment by bmallred** [comment]
## Middle name

![disabled-dither](https://cloud.githubusercontent.com/assets/697855/24976371/32369f80-1f97-11e7-9f03-a5b3e9e5545c.png)

## Telephone

![dithered-telephone](https://cloud.githubusercontent.com/assets/697855/24977263/71d5596c-1f9a-11e7-8060-70c300deaa80.png)

## Date range

![dithered-daterange](https://cloud.githubusercontent.com/assets/697855/24976622/33db3656-1f98-11e7-8c23-79d4ec2f22db.png)
