### ISSUE TITLE
Help block - <br> needs space

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#978]
- [x] <br> tags need space so they break up the P

Current:
<img width="746" alt="screen shot 2017-04-14 at 9 43 09 am" src="https://cloud.githubusercontent.com/assets/19935974/25044863/1599f73a-20f7-11e7-8aaf-5c0bfda9c1a7.png">

Desired:
<img width="739" alt="screen shot 2017-04-14 at 9 45 48 am" src="https://cloud.githubusercontent.com/assets/19935974/25044876/2b98de70-20f7-11e7-9059-a692051d9c01.png">

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 wouldn't that be better if paragraphs were used? `<br>` typically isn't used to introduce that type of whitespace. This may be where we need to refactor the help message usage to allow for multiple lines to be entered...

```json
{
   title: <string>,
   message: <string or array>,
   note: <string or array>,
}
```

so you could do:

```json
{
   title: 'Need help with your middle name?',
   message: [
      'If your middle name is a single initial letter only type that initial and check the "Initial only" checkbox.',
      'If you do not have a middle name leave this field empty and check the "No middle name" checkbox.'
   ],
   note: '"Initial only" is for single letter names only, not for the initial of your full name.'
}
```

**Comment by Jay-Neighbours-I72** [comment]
Perfect, I can do that

**Comment by bmallred** [comment]
I'm switching over to work this out and will let you know when it is pushed up.
