### ISSUE TITLE
Phone number blocks - I don't know button alignment

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#988]
- [x] I don't know button is mis-aligned

<img width="1142" alt="screen shot 2017-04-17 at 1 45 22 pm" src="https://cloud.githubusercontent.com/assets/19935974/25097859/4200a24a-2374-11e7-8c13-b7b333357457.png">

**Comment by bmallred** [comment]
This may be similar to what I was seeing for the `DateRange` as well which was resolved in PR #982.
