### ISSUE TITLE
Your contact info - email

### ISSUE THREAD

**Issue by Jay-Neighbours-I72** [truetandem/e-QIP-prototype#998]
We need to ask for 2 email address at first instead of one. Found this during the content review and confirmed with Sheldon and Drew.

Load 2 open email accordion items instead of one.

![unnamed](https://cloud.githubusercontent.com/assets/19935974/25151124/5c83ac50-2452-11e7-884b-3bbd8f9ed8d2.png)

**Comment by bmallred** [comment]
@Jay-Neighbours-I72 and still 2 telephone numbers as well correct?

**Comment by bmallred** [comment]
Also, @Jay-Neighbours-I72, do you know if two are **required** or if we just need to initially ask for more?

**Comment by Jay-Neighbours-I72** [comment]
@bmallred 
Yes still 2 phone numbers.
Technically only 1 phone number is required but the form strongly suggests at least 2 (thus the loading of 2)

2 email address will be required
